### PR TITLE
Fix Mesh.increaseVertices not working with updatable buffers

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/updatable-mesh-and-increasevertices/18037/2

### CODE REVIEW

**Review by RaananW — COMMENTED** [review]
Will that not fail on IE11? I remember adding Array.from once and the one issue it had was browser support. Is there a different way of doing this?

**Comment by Popov72** [comment]
Ah, IE11...

I don't know if we should put [the polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#polyfill) in the `ArrayTools` class?

**Comment by RaananW** [comment]
So much code to support the best browser in the world...

If there is no other way, maybe we should I just think - we increase the codebase just for a single browser that is probably used in less than 1% of the experiences. My suggestion would be - to keep the old implementation for IE11 only. Meaning - check if Array.from exists, and if not - simply continue without it, as it was until now. This way we support this function in other browsers, while slowly removing advance-functionality support for IE11. 
@deltakosh - is that acceptable?

**Comment by deltakosh** [comment]
I agree with @RaananW idea. We will not increase our size for ie11 anymore.

**Comment by Popov72** [comment]
Ok, done!

**Review by deltakosh — APPROVED** [review]

**Pull request merged**
