### PR TITLE
Add viewer alpha tooling for code coverage and used bytes flame chart

### PR DESCRIPTION
**Pull request by ryantrem**
This PR adds the last piece of planned local dev tooling for package size analysis for the new alpha viewer (building on top of the previous PR: https://github.com/BabylonJS/Babylon.js/pull/15319).

The primary change is the introduction of nyc/istanbul (nyc is the command line interface for the istanbul code coverage library) for code coverage so you can easily see what code is actually executed when the viewer runs. This is done by:
1. Running `npm run start:coverage`, which launches a test app (will add more functionality later exercises more Babylon code for expected scenarios) that looks like this:
image
1. Clicking the "Collect Coverage" button, which collects the istanbul coverage data and generates and opens two reports that look like this:
image
The left report is the standard nyc html report. The right flame chart is a variation of the file/folder size flame chart where it specifically shows the approximate unused bytes per file/folder (e.g. `(1-coverage)*size`).
The goal is to make it easy to see where there might be opportunity to reduce the package size.

To make this work, the following is what happens under the hood:
1. The code is tree shaken but not bundled into a single file, nor is it minified (to make line number status useful)
1. The resulting code is then instrumented with the `nyc` command line
1. The vite local server is started and the test web page is launched
1. The vite local server uses middleware to expose an api that the page can send coverage information to
1. The vite middleware saves the coverage data locally and invokes a report generation script
1. The report generation script reads the coverage data and uses `nyc` to generate the html coverage report as well as a json summary, then uses the file/folder size flame chart generation script plus the json coverage summary to create a flame chart of unused bytes

Another change in this PR makes it easier to find import chains by just running an npm command like: `npm run import-chains -- standardmaterial`

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15334/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15334/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15334/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15334/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15334/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15334/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15334/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15334/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15334/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15334/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
