### PR TITLE
adt.useInvalidateRectOptimization using scale incorrectly when toggling visibility and redrawing invalidated parts of canvas

### LINKED ISSUE #13622: adt.useInvalidateRectOptimization using scale incorrectly when toggling visibility and redrawing invalidated parts of canvas
When using adt.useInvalidateRectOptimization in conjunction with container.renderToIntermediateTexture where the container uses scaleX/scaleY will redraw the container incorrectly. It is applying the scale of the container to the area to redraw instead of redrawing the entire container.

**Repro**
- Bug repro on [playground](https://playground.babylonjs.com)](https://playground.babylonjs.com/#XCPP9Y#17836)
- Roll down the GUI hierarchy until you find the "no name" rectangle container that is a sibling to the button.
- Toggle the visibility on the "no name" rectangle container and note how the screen redraws.
- Expected result: When the rectangle visibility flag is set to false, the screen will redraw the entire rectangle render area of the canvas
- Current result: The rectangle is referencing the scaleX/ScaleY property of the container and only redrawing a scaled portion of the canvas, so the result is an area in the center of the control that redraws in reaction to the change in visibility and the rest of the container remains drawn to the canvas.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by RaananW**
Fixes #13622
Current measure already has the right measure. when applying the transform again it applies scale twice.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — APPROVED** [review]
interesting the transformMatrix is not required ? I wonder why it was added ?

**Comment by RaananW** [comment]
Explaining what is happening here:

When a parent has a scale, the child gets this scale added to ist transformation matrix. During drawing, the canvas' state is updated with the parent's transformation, going down the hierarchy. 
But the invalidate rectangle is in global space and doesn't change when propagated down the hierarchy tree. 

What I am doing here is applying the inversed transformation matrix of the current component to the measures passed to the clearRect, to negate the state of the canvas without using restore (as this will have other side effects).

**Comment by RaananW** [comment]
https://playground.babylonjs.com/?snapshot=refs/pull/13627/merge#XCPP9Y#17907
to test

**Review by sebavan — APPROVED** [review]
I will fully trust you on the maths :-)

**Review by PatrickRyanMS — APPROVED** [review]
Works great!

**Pull request merged**
