### PR TITLE
Revert the missing fix and add some logs

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Review by ryantrem — APPROVED** [review]

**Comment by deltakosh** [comment]
Cc @sebavan as it seems the iridescence tests are failing

**Comment by sebavan** [comment]
> Cc @sebavan as it seems the iridescence tests are failing

Can you try to merge master in ? I do not understand why master is not failing :-(

**Comment by sebavan** [comment]
I updated it to see, still no explanations so far...

**Review by sebavan — APPROVED** [review]

**Comment by sebavan** [comment]
@RaananW would be great if you could have a look, I wonder why the config was from master but none of the iridescence code was available ? but at least it is all in :-)

**Comment by RaananW** [comment]
@sebavan - I will look into that. The config is taken from the branch it's in, nothing should be taken from master.

**Pull request merged**
