### PR TITLE
Add getMeshUnderPointerIndex for getting mesh under XR controller by index

### PR DESCRIPTION
**Pull request by vtange**
…non-string param. Add getMeshUnderPointerIndex for getting controllers via numerical index instead of string id

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13981/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13981/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13981/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13981/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13981/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13981/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13981/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13981/merge#BCU1XR#0

**Review by RaananW — COMMENTED** [review]
I have no problem adding this function, but you do know that it is not guaranteed to always be the same? 

For example - you have two hands registered. 0 is left, 1 is right. Now left leaves and comes back again - a new controller is added with a new ID. now right is 0m and left is 1.

**Comment by vtange** [comment]
> I have no problem adding this function, but you do know that it is not guaranteed to always be the same?
> 
> For example - you have two hands registered. 0 is left, 1 is right. Now left leaves and comes back again - a new controller is added with a new ID. now right is 0m and left is 1.

Yeah I know it's not guaranteed to be the same controller since they're not necessarily even in the same order - left can be index 0 on first load too. I don't think there's a way to guarantee left/right controllers since as mentioned in the forum WebXR abstracts controllers so we can have more than 2, and they're not necessarily named all the same way.

It's mostly for sanity checking - it would be easier to know you're using the method that requires string id wrong if using this one with index 0 works

**Comment by RaananW** [comment]
> > I have no problem adding this function, but you do know that it is not guaranteed to always be the same?
> > For example - you have two hands registered. 0 is left, 1 is right. Now left leaves and comes back again - a new controller is added with a new ID. now right is 0m and left is 1.
> 
> Yeah I know it's not guaranteed to be the same controller since they're not necessarily even in the same order - left can be index 0 on first load too. I don't think there's a way to guarantee left/right controllers since as mentioned in the forum WebXR abstracts controllers so we can have more than 2, and they're not necessarily named all the same way.
> 
> It's mostly for sanity checking - it would be easier to know you're using the method that requires string id wrong if using this one with index 0 works

The more I think about it, the more I find it hard to understand the use-case here...

So sorry, I don't mean to be hard on this one. There was a reasoning for deciding the getter architecture.

**Comment by vtange** [comment]
No problem! it's just a suggestion since we were already discussing changing the code in the forum.

**Pull request closed without merging**
