### PR TITLE
front/back/double side feature

### PR DESCRIPTION
**Pull request by jbousquie**
Modified 5 files to add the front/back/double side features : 

	modifié:         ../../Babylon/Mesh/babylon.geometry.ts
	modifié:         ../../Babylon/Mesh/babylon.mesh.ts
	modifié:         ../../Babylon/Mesh/babylon.mesh.vertexData.ts
	modifié:         ../../Babylon/PostProcess/babylon.volumetricLightScatteringPostProcess.ts
	modifié:         ../../Babylon/Rendering/babylon.boundingBoxRenderer.ts

Don't get why all other built JS files come with again :-(
I just can't prevent them to follow when having my command line : _git push origin feature.doubleside_

Each basic shape creation method has got now a new expected parameter : _sideOrientation_
This parameter is usually ordered at the last position before the _scene_ paramater in the parameter list for each shape, except for the cylinder where it is the next to last because an existing optional parameter.

Possible values are : 
* BABYLON.Mesh.FrontSide,
* BABYLON.Mesh.BackSide,
* BABYLON.Mesh.DoubleSide,
* BABYLON.Mesh.DefaultSide (which is the same value as FrontSide)

If called with a _null_ value, the DefaultSide is then applied.

If a mesh is set a material, its _backFaceCulling_ can be disabled so the opposite face to the selected side will be opaque as usal. 
So _BackFaceCulling_ shouldn't be disabled for _DoubleSide_ value.

So far, the following shapes have been updated (and tested with and without material, with and without light reflection, with and without texture) : 
* box,
* cylinder,
* torus,
* torus knot,
* sphere, 
* plane, 
* ribbon

I didn't modify all _ground_ shapes because I didn't think it was pertinent to add them back sides. Don't know ...

Btw, the _Cylinder_ class in geometries wasn't asked to be modified by the compiler, so I didn't do anything for it.
For now, I just added the _side_ property in each impacted shape  class only. Maybe is it better to declare it at _Primitive_ class level ?

As it is a quite impacting change in each shape constructor signature call, it will probably break down many working examples in the playground unless each existing example is bound to its own BJS engine version.

### CODE REVIEW

**Comment by deltakosh** [comment]
Hey Jerome, you cannot change public signatures else users code will be broken. You have to add your new parameter as the last parameter with a default value so that we can keep backward compatibility

**Comment by jbousquie** [comment]
ok
I will learn how to do this. I'll set DefaultSide as default value
What about the CreateCylinder which has already an optional parameter with a default value ? Is this the same : can I just add the sideOrientation parameter after it ?

Anyway this is just a little change to do as it concerns only mesh.ts file  _CreateXXX()_  public methods afaik. 
I'll do it next monday (files at office... as usual)

**Comment by deltakosh** [comment]
Absolutely, just add your parameter at the end. But I can do that for you as well if you prefer. You decide :)

**Comment by jbousquie** [comment]
ok, please do it :-) if it's not too long for you.
So then I will review your code to understand how you did it. 
And I still fight with this git command line, I'm not sure to be able to re-push it rightly , pfff

**Comment by deltakosh** [comment]
Ok, I did some changes but before all the DoubleSide will not work if you do not take in account other kinds (colors, weights, etc...) I suggest duplicating everything else than normals actually

**Comment by deltakosh** [comment]
And then you'll need to update my beloved docs :D

**Comment by jbousquie** [comment]
ok, I will update the docs (I know how to do this :-) )
Are you updating all the rest in the code ? 
I don't know what is really this _"everything else than normals"_ when you talk about colors, weight, etc because I only had to deal with positions/normals/indices when coding my new mesh types (ribbon, tube) and it just worked.

**Comment by raananw** [comment]
Hi Jerome, 
A mesh can have many data types other than positions normals indices and uvs. there is also color, uv2 and more - you can see all kinds and their definition in the VertexBuffer class.
They should be taken into account in the function where you inverse the normals. You can check if the mesh has this kind, and if it does duplicate them (since they will probably stay the same).

**Comment by deltakosh** [comment]
No worries:) I'll update your code so you will be able to see my changes:)

**Comment by jbousquie** [comment]
Thank you both for your explanations.
I understand well that a mesh can have many other data types, of course.
But as the _ComputeSides()_ is to be called just after the positions/indices/normals/uvs population and before the vertexData creation, I thought the mesh didn't exist yet at this moment : vertexData not returned yet by the _createXXX()_ function.
This is why I thought it wasn't necessary to replicate other things than vertices/indices/normals just in case of _doubleSide_ wanted.

Thank you again :-)

**Comment by deltakosh** [comment]
Actually you're totally right. I will just set the computeSide function private and we're good. Push incoming

**Comment by jbousquie** [comment]
:-D

Thank you guys !

**Comment by deltakosh** [comment]
Done!

**Comment by jbousquie** [comment]
Chaaaampagne !

**Pull request closed without merging**
