### PR TITLE
add reminders for cdn usage

### PR DESCRIPTION
**Pull request by carolhmj**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by thomlucc** [comment]
@carolhmj - Maybe on the main CDN page (content/setup/frameworkPackages/CDN.md), you could add a more detailed message inspired by Jason communication: 

"The Babylon CDN is not recommended to be used in production applications. The purpose of our CDN is to serve Babylon packages to developers:
- for learning how to use the platform
- for the development phase of projects 
- for for small experiments

Once you've built an application and are ready to share it with the world, you should serve all packages from your own CDN."

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14415/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14415/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14415/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14415/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14415/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14415/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14415/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14415/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Pull request merged**
