### PR TITLE
Adding Input to Sliders in Inspector

### PR DESCRIPTION
**Pull request by msDestiny14**
slider

### CODE REVIEW

**Comment by deltakosh** [comment]
I feel like we are missing some margin on the left of x,y and z

**Comment by msDestiny14** [comment]
> I feel like we are missing some margin on the left of x,y and z

I would agree but that affects all the labels using slider. Those are all currently aligned. Should I make a special flag?

slider

off

**Comment by deltakosh** [comment]
yes probably ;)

**Comment by msDestiny14** [comment]
Added the margins!

**Comment by PatrickRyanMS** [comment]
Am I mistaken or would having the sliders still there run into the same issue we saw before when converting between quaternion and euler? If so, we should probably remove the sliders as the UX is fairly broken using the sliders and we should encourage the use of the rotation gizmo instead.

**Comment by msDestiny14** [comment]
> Am I mistaken or would having the sliders still there run into the same issue we saw before when converting between quaternion and euler? If so, we should probably remove the sliders as the UX is fairly broken using the sliders and we should encourage the use of the rotation gizmo instead.

That is up to you! Note this PR may not be the final solution to that specific issue (I did not link it for that reason). This was to be consistent with NME, which got input added to sliders last week in another PR.

**Comment by deltakosh** [comment]
Well I still use the slider a lot. so maybe we can do this:
only display the slider when we do NOT have a rotationQuaternion?

**Comment by PatrickRyanMS** [comment]
That could be a solution though I worry a bit about the UX changing without the user understanding why. We should take a look at it and see how it feels.

**Comment by RaananW** [comment]
I have commented on the issue connected to this (this - https://github.com/BabylonJS/Babylon.js/issues/9206#issuecomment-713436564), maybe this would be an acceptable solution?

**Comment by deltakosh** [comment]
>> That could be a solution though I worry a bit about the UX changing without the user understanding why. We should take a look at it and see how it feels.

This could be associated with an info indicating (like a label) that the current rotation is using a quaternion instead of euler

**Comment by msDestiny14** [comment]
Close for the moment since I noticed a weird glitch that happens on float inputs with values sliders between 0-1. Will investigate,

**Comment by msDestiny14** [comment]
Also including fix for https://github.com/BabylonJS/Babylon.js/issues/9206

rotation

**Pull request merged**
