### PR TITLE
Sprite2D.scaleToSize(size)

### PR DESCRIPTION
**Pull request by albertbuchard**
Sets the scale of the sprite using a BABYLON.Size(w,h).
Keeps proportion by taking the maximum of the two scale for x and y.

It waits until the size is set or texture is ready to scale.

### CODE REVIEW

**Comment by albertbuchard** [comment]
sorry.. my first pull request.. I dont know how to set just one file...

**Comment by nockawa** [comment]
hi, you have to update your repo with the "main babylon.js" one.
take a look at this tutorial: http://pixelcodr.com/tutos/contribute/contribute.html
you need to create the "upstream" to the official repo, then a "git merge upstream/master"
good luck, I've been there (well still am), git is...special.

**Comment by nockawa** [comment]
one more thing you should only commit the .ts files! not the .js! never commit the .js file, that's your mistake in this case

**Comment by albertbuchard** [comment]
Ok I re-did it - I think this time it worked :)

**Pull request closed without merging**
