### PR TITLE
Fix to styling of NME and NGE

### LINKED ISSUE #14347: UI colors for NGE leaking to NME
The UI accent color in NME is blue and in NGE is green. However, when there is a PG with both node geometry and node material components, the accent color is the green used by NGE for both editors. There is something leaking between the editors in style. 

This [playground repro](https://playground.babylonjs.com/#6I2RMN#133) has both a node material and a node geometry, and opening both editors will display green as the accent color.

### LINKED ISSUE #14348: Possible to drop a category to NME/NGE
If a category button is dragged and dropped into NME/NGE, it becomes this invalid node:
drag-drop-nme

### PR DESCRIPTION
**Pull request by carolhmj**
Trying to separate the class names more so one doesn't contaminate the other
Fix #14347
Fix #14348

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14349/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14349/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14349/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14349/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14349/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14349/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14349/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14349/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14349/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14349/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14349/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Review by sebavan — APPROVED** [review]

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
