### PR TITLE
Inspector pane resize doesn't stick after mouse up

### LINKED ISSUE #15548: Inspector pane resize doesn't stick after mouse up
Repro:
1. Open sandbox to any model (e.g., [this](https://sandbox.babylonjs.com/?assetUrl=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DragonDispersion/glTF/DragonDispersion.gltf))
2. Open the inspector with the UI
3. Try to resize any of the panes.
- Expected result: The panes to resize
- Current result: The panes reset to original size after mouse up
msedge_2024-09-06_09-43-40

### PR DESCRIPTION
**Pull request by RaananW**
Fixes #15548

To check - https://sandbox.babylonjs.com/?assetUrl=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DragonDispersion/glTF/DragonDispersion.gltf&snapshot=refs/pull/15549/merge

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15549/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15549/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15549/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15549/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15549/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15549/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15549/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15549/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15549/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15549/merge/testResults/webgl2playwright/index.html

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
