### PR TITLE
Refactoring stereoscopic cameras system

### PR DESCRIPTION
**Pull request by vousk**
- Renamed everything related to stereo according to the regular names
- Renamed some function for better clarity
- Throwed away SUB_CAMERAID_A and SUB_CAMERAID_B constants. I found them irrelevant , particularly if we let rigs open for any kind of setups we don't know in advance. We have the sub cameras array and that should be enough for devs to use and extend class for more complex rigs, it's up to the user to define its cameras and IDs.
- Put a generic rig parameters instead of every single VR and stereo params inside the global camera class (to provide better flexibility for later)
- Inverted cameras (depth was calculated inside out)
- Put babylon.anaglyphCamera.js in babylon.stereoscopicCamera.js (renamed babylon.stereoscopicCameras.js) because an anaglyh camera is a stereoscopic camera, it's just the final output which is different, there is no reason to treat them differently (quite the contrary, it would be disturbing for users to separate them)
- Added STEREOSCOPY_CONVERGENCE_MODE and STEREOSCOPY_PARALLEL_MODE constants for _cameraRigParams.stereoMode flag to let JCPalmer implement parallel mode alongside convergence mode (if we decide to implement both to let user choose which one better suits its need).

### CODE REVIEW

**Comment by deltakosh** [comment]
Hello. Everything seems perfect except one question: why defining STEREOSCOPY_CONVERGENCE_MODE and STEREOSCOPY_PARALLEL_MODE.

They seem not used in the code

**Comment by vousk** [comment]
You're right for now they're not used. I think it may be good if we provide the two stereoscopic modes (that's not necessary but that would be really pro), and JCP did a first try at parallel stereo two days ago, so I put those vars yet to let him register the two modes in code.
But I'm not sure for the names, I have a little difficulty defining them because it's an inner mode of stereoscopy but not a value camera rig mode can receive (we can't name it RIG_MODE_STEREOSCOPY_CONVERGENCE_MODE because it's not a value we assign to cameraRigMode). What do you think ?

**Comment by deltakosh** [comment]
So far I won't keep them. We will be able to add this parameter when code will be in the framework. Name wise I find it great

**Comment by Palmer-JC** [comment]
On the assumption that the tester still runs, I am ok with this.  I did not know anything about 3D 2 weeks ago.   Getting the names right was not a priority.  No one was going to care, if I did not get to run.  Would like this committed, to check it still runs.  Am a computer generalist, guess they are calling it, full stack developer today.  If you have enough experience, you do not really have to know what you are doing.

As far as my thinking on this effort is:  was feeling I needed to step back & widen my scope, right after I did the parallel way experiment.  Was low on gas, so took the weekend off, but woke up today with a much wider approach.  I was stumbling over, why if I removed the subcameras & the pass shader, did I improve so little?

- Was it a canvas+ related? (post rendering a weakest of this platform)
- Was it OS related?  (Firefox profiler shows virtually no change when switching subcameras on)
- Was it hardware?  (Have both an Apple A8, and Qualcomm snapdragon)  Do not need iPad to actually have miracast to test this part.

The fact that I started to test out Intel's XDK Friday is NOT an accident.  The app I am running through is the 3D tester.  Can directly compare Canvas+ to XDK, I think.

So now I have all these combinations to test.  That is the way I like it.  And one more thing.  The TV has a simulated 3D mode (I assume other brands do as well).  It is really hit or miss as far as usability.  It must be being implemented with parallel. Even at it's best, it was not even close to the stuff from that roku channel.  This leads me to 2 conclusions:
1 - I will concentrate on convergence.  Parallel seems to have an upper limit, that the TV can do without us.
2 - This is just another dimension of testing for me.  I will not let that go to waste.

**Comment by vousk** [comment]
TV (or any device) that create 3D on the fly by converting 2D image used an totaly different approach: (will try to explain in english...) pixels shifts between identical group of pixels on successive images towards other groups of identical pixel are analysed and used to guess that this element is above that other one (guessing that this shift is due to depth difference, defining that this group of pixel will be draw a little more to the left or right of the second eye view, to create fake depth based on relative movement between objets at different depth in the movie (roughly, the real process is much more complex). But this is just awful, the stereoscopy produced is a mess, turning upside down all the time on little parts on the image, resulting in a bad experience and real strain for the viewers, it's that kind of process that perpetually kill the stereoscopic experience every 5 years (there are very few people who really does good stereo, work, and this is a real problem

**Comment by vousk** [comment]
DK, do you want me to update commit in PR with those 2 vars removed ?

**Comment by deltakosh** [comment]
I'll do it :) I'm working on finish 2.1 and your pull will make it into this release :)

**Comment by vousk** [comment]
I would have some other little PRs to do for 2.1 final. I'll try to send them this evening or tomorrow (not easy, I have to do all that stuff from my phone because I'm on the road)

**Comment by RaananW** [comment]
2.1 was just finalized a few mins ago. 2.2 is waiting for your PRs :-)

**Comment by vousk** [comment]
And after a good think, I also find that AnaglyphCameras shouldn't be there, that make no sense, I suggest only StereoscopicCameras but with a better constructor params.
I'll also PR that if you're ok.

**Comment by vousk** [comment]
Ah, damn, too late :)

**Comment by deltakosh** [comment]
Send it. I'll update 2.1

**Pull request merged**
