### PR TITLE
Add reflectionMatrix support for more coordinatesMode's

### PR DESCRIPTION
**Pull request by ddervisis**
Since I ran into the problem where my reflection matrix could not be rotated in `SPHERICAL_MODE`, I searched the forums and found [this](https://forum.babylonjs.com/t/reflection-on-texture-with-equirectangular-mode/288) post where it was mentioned, that the reflection matrix is not used on modes other than `PLANAR_MODE`, `CUBIC_MODE` and `PROJECTION_MODE`.

So I took the liberty to add support for not just the `SPHERICAL_MODE`, but also `EQUIRECTANGULAR_MODE`, ~`FIXED_EQUIRECTANGULAR_MODE`~, ~`FIXED_EQUIRECTANGULAR_MIRRORED_MODE`~ and `SKYBOX_MODE`.

I based the refactoring on the implementation of the `CUBIC_MODE` where the coordinates are just a multiplication between the `reflectionMatrix` and a Vector4 from the previous `coords` and a 0 (in `PLANAR_MODE` it is a 1):
```shader
coords = vec3(reflectionMatrix * vec4(coords, 0));
```

An example for the `SKYBOX_MODE`:
(0, 0, 0)

(3.141593, 0, 0)
x180
(0, 3.141593, 0)
y180
(0, 0, 3.141593)
z180

Suggestions are welcome.

### CODE REVIEW

**Comment by ddervisis** [comment]
While testing some more, I noticed that the reflection for the `SPHERICAL_MODE` rotates until 180 degrees and instead of rotating further in the same direction it rotates backwards again (to 0, instead of 360). So the refactoring I made there does not work correctly.

In contrast the `SKYBOX_MODE` version works as intended. I'm going to test the other modes some more as well.

**Comment by deltakosh** [comment]
One test is failing

**Comment by ddervisis** [comment]
I'm not quite sure, if the failing tests correlate with my changes, so I'm reverting my shader changes to rerun the pipeline again and see if they fail again or succeed.

Failing pipeline tests:
<details>
  <summary>Click to expand</summary>

```bash

2019-04-05T09:57:44.3518573Z Firefox 65.0.0 (Ubuntu 0.0.0): Executed 34 of 116 SUCCESS (0 secs / 3 mins 35.935 secs)
2019-04-05T09:57:47.3190969Z [1A[2KFirefox 65.0.0 (Ubuntu 0.0.0) Validation Tests Fresnel FAILED
2019-04-05T09:57:47.3192166Z 	expected false to be true
2019-04-05T09:57:47.3192671Z 	AssertionError@node_modules/chai/chai.js:9449:13
2019-04-05T09:57:47.3193087Z 	[3]</module.exports/Assertion.prototype.assert@node_modules/chai/chai.js:239:13
2019-04-05T09:57:47.3193474Z 	[5]</module.exports/<@node_modules/chai/chai.js:1021:5
2019-04-05T09:57:47.3193890Z 	propertyGetter@node_modules/chai/chai.js:7899:22
2019-04-05T09:57:47.3194228Z 	proxyGetter@node_modules/chai/chai.js:9247:14
2019-04-05T09:57:47.3194629Z 	@tests/validation/integration.js:58:33
2019-04-05T09:57:47.3195007Z 	evaluate@http://localhost:3000/tests/validation/validation.js:139:5
2019-04-05T09:57:47.3195419Z 	processCurrentScene/</<@http://localhost:3000/tests/validation/validation.js:157:21
2019-04-05T09:57:47.3195809Z 	./Engines/engine.ts/Engine</Engine.prototype._renderLoop@http://localhost:3000/dist/preview%20release/babylon.max.js:31521:21
2019-04-05T09:57:47.3215814Z

...

2019-04-05T09:58:10.8494719Z [1A[2KFirefox 65.0.0 (Ubuntu 0.0.0) Validation Tests Lens FAILED
2019-04-05T09:58:10.8496185Z 	expected false to be true
2019-04-05T09:58:10.8496416Z 	AssertionError@node_modules/chai/chai.js:9449:13
2019-04-05T09:58:10.8496583Z 	[3]</module.exports/Assertion.prototype.assert@node_modules/chai/chai.js:239:13
2019-04-05T09:58:10.8496785Z 	[5]</module.exports/<@node_modules/chai/chai.js:1021:5
2019-04-05T09:58:10.8496922Z 	propertyGetter@node_modules/chai/chai.js:7899:22
2019-04-05T09:58:10.8497247Z 	proxyGetter@node_modules/chai/chai.js:9247:14
2019-04-05T09:58:10.8497493Z 	@tests/validation/integration.js:58:33
2019-04-05T09:58:10.8497690Z 	evaluate@http://localhost:3000/tests/validation/validation.js:139:5
2019-04-05T09:58:10.8497794Z 	processCurrentScene/</<@http://localhost:3000/tests/validation/validation.js:157:21
2019-04-05T09:58:10.8498008Z 	./Engines/engine.ts/Engine</Engine.prototype._renderLoop@http://localhost:3000/dist/preview%20release/babylon.max.js:31521:21
2019-04-05T09:58:10.8498662Z 	

...

2019-04-05T09:58:33.3448376Z [1A[2KFirefox 65.0.0 (Ubuntu 0.0.0) Validation Tests Displacement map FAILED
2019-04-05T09:58:33.3450845Z 	expected false to be true
2019-04-05T09:58:33.3451328Z 	AssertionError@node_modules/chai/chai.js:9449:13
2019-04-05T09:58:33.3451778Z 	[3]</module.exports/Assertion.prototype.assert@node_modules/chai/chai.js:239:13
2019-04-05T09:58:33.3452173Z 	[5]</module.exports/<@node_modules/chai/chai.js:1021:5
2019-04-05T09:58:33.3452582Z 	propertyGetter@node_modules/chai/chai.js:7899:22
2019-04-05T09:58:33.3452960Z 	proxyGetter@node_modules/chai/chai.js:9247:14
2019-04-05T09:58:33.3454235Z 	@tests/validation/integration.js:58:33
2019-04-05T09:58:33.3454976Z 	evaluate@http://localhost:3000/tests/validation/validation.js:139:5
2019-04-05T09:58:33.3455537Z 	processCurrentScene/</<@http://localhost:3000/tests/validation/validation.js:157:21
2019-04-05T09:58:33.3455912Z 	./Engines/engine.ts/Engine</Engine.prototype._renderLoop@http://localhost:3000/dist/preview%20release/babylon.max.js:31521:21
2019-04-05T09:58:33.3457082Z 	

...

2019-04-05T09:58:42.9192823Z [1A[2KFirefox 65.0.0 (Ubuntu 0.0.0) Validation Tests Custom render target FAILED
2019-04-05T09:58:42.9194485Z 	expected false to be true
2019-04-05T09:58:42.9195037Z 	AssertionError@node_modules/chai/chai.js:9449:13
2019-04-05T09:58:42.9195427Z 	[3]</module.exports/Assertion.prototype.assert@node_modules/chai/chai.js:239:13
2019-04-05T09:58:42.9195884Z 	[5]</module.exports/<@node_modules/chai/chai.js:1021:5
2019-04-05T09:58:42.9196138Z 	propertyGetter@node_modules/chai/chai.js:7899:22
2019-04-05T09:58:42.9196713Z 	proxyGetter@node_modules/chai/chai.js:9247:14
2019-04-05T09:58:42.9197054Z 	@tests/validation/integration.js:58:33
2019-04-05T09:58:42.9197337Z 	evaluate@http://localhost:3000/tests/validation/validation.js:139:5
2019-04-05T09:58:42.9197593Z 	processCurrentScene/</<@http://localhost:3000/tests/validation/validation.js:157:21
2019-04-05T09:58:42.9197885Z 	./Engines/engine.ts/Engine</Engine.prototype._renderLoop@http://localhost:3000/dist/preview%20release/babylon.max.js:31521:21
2019-04-05T09:58:42.9198158Z 	

...

2019-04-05T10:05:01.6570340Z [1A[2KFirefox 65.0.0 (Ubuntu 0.0.0) Validation Tests Local cubemaps FAILED
2019-04-05T10:05:01.6572075Z 	expected false to be true
2019-04-05T10:05:01.6572366Z 	AssertionError@node_modules/chai/chai.js:9449:13
2019-04-05T10:05:01.6572724Z 	[3]</module.exports/Assertion.prototype.assert@node_modules/chai/chai.js:239:13
2019-04-05T10:05:01.6573096Z 	[5]</module.exports/<@node_modules/chai/chai.js:1021:5
2019-04-05T10:05:01.6573284Z 	propertyGetter@node_modules/chai/chai.js:7899:22
2019-04-05T10:05:01.6573475Z 	proxyGetter@node_modules/chai/chai.js:9247:14
2019-04-05T10:05:01.6573641Z 	@tests/validation/integration.js:58:33
2019-04-05T10:05:01.6573832Z 	evaluate@http://localhost:3000/tests/validation/validation.js:139:5
2019-04-05T10:05:01.6574011Z 	processCurrentScene/</<@http://localhost:3000/tests/validation/validation.js:157:21
2019-04-05T10:05:01.6574220Z 	./Engines/engine.ts/Engine</Engine.prototype._renderLoop@http://localhost:3000/dist/preview%20release/babylon.max.js:31521:21
2019-04-05T10:05:01.6574419Z 	

...

2019-04-05T10:05:09.2036182Z [1A[2KFirefox 65.0.0 (Ubuntu 0.0.0) Validation Tests DDS FAILED
2019-04-05T10:05:09.2038807Z 	expected false to be true
2019-04-05T10:05:09.2039534Z 	AssertionError@node_modules/chai/chai.js:9449:13
2019-04-05T10:05:09.2040085Z 	[3]</module.exports/Assertion.prototype.assert@node_modules/chai/chai.js:239:13
2019-04-05T10:05:09.2041008Z 	[5]</module.exports/<@node_modules/chai/chai.js:1021:5
2019-04-05T10:05:09.2041687Z 	propertyGetter@node_modules/chai/chai.js:7899:22
2019-04-05T10:05:09.2042186Z 	proxyGetter@node_modules/chai/chai.js:9247:14
2019-04-05T10:05:09.2042662Z 	@tests/validation/integration.js:58:33
2019-04-05T10:05:09.2043318Z 	evaluate@http://localhost:3000/tests/validation/validation.js:139:5
2019-04-05T10:05:09.2043922Z 	processCurrentScene/</<@http://localhost:3000/tests/validation/validation.js:157:21
2019-04-05T10:05:09.2044614Z 	./Engines/engine.ts/Engine</Engine.prototype._renderLoop@http://localhost:3000/dist/preview%20release/babylon.max.js:31521:21
2019-04-05T10:05:09.2045109Z 	

----------

2019-04-05T10:05:35.0970445Z TOTAL: 6 FAILED, 110 SUCCESS
2019-04-05T10:05:35.4148096Z [10:05:35] 'tests-validation-virtualscreenWebGL1' errored after 12 min
2019-04-05T10:05:35.4237292Z [10:05:35] Error: 1
2019-04-05T10:05:35.4242019Z     at formatError (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:20:10)
2019-04-05T10:05:35.4242659Z     at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:31:15)
2019-04-05T10:05:35.4242936Z     at Gulp.emit (events.js:194:15)
2019-04-05T10:05:35.4243255Z     at Gulp.EventEmitter.emit (domain.js:441:20)
2019-04-05T10:05:35.4243444Z     at Object.error (/home/vsts/work/1/s/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
2019-04-05T10:05:35.4243829Z     at handler (/home/vsts/work/1/s/node_modules/now-and-later/lib/map.js:46:14)
2019-04-05T10:05:35.4244046Z     at f (/home/vsts/work/1/s/node_modules/once/once.js:25:25)
2019-04-05T10:05:35.4244200Z     at f (/home/vsts/work/1/s/node_modules/once/once.js:25:25)
2019-04-05T10:05:35.4244755Z     at tryCatch (/home/vsts/work/1/s/node_modules/async-done/index.js:24:15)
2019-04-05T10:05:35.4245163Z     at done (/home/vsts/work/1/s/node_modules/async-done/index.js:40:12)
2019-04-05T10:05:35.4245376Z     at removeAllListeners (/home/vsts/work/1/s/node_modules/karma/lib/server.js:354:9)
2019-04-05T10:05:35.4245535Z     at webServer.close (/home/vsts/work/1/s/node_modules/karma/lib/server.js:365:13)
2019-04-05T10:05:35.4246443Z     at Server.close (net.js:1556:9)
2019-04-05T10:05:35.4246704Z     at Object.onceWrapper (events.js:277:13)
2019-04-05T10:05:35.4246894Z     at Server.emit (events.js:194:15)
2019-04-05T10:05:35.4247089Z     at Server.EventEmitter.emit (domain.js:459:23)
2019-04-05T10:05:35.4460500Z ##[error]Bash exited with code '1'.
2019-04-05T10:05:35.4472380Z ##[section]Finishing: Visual Tests

```
</details>

**Comment by ddervisis** [comment]
Ok since, the pipeline succeeded, the problem lies within my changes. Some tests probably have to be refactored.

I'm open for hints and suggestions, since it's gonna take a while for me to read through the tests and understand the problem and what changes need to be done.

**Comment by deltakosh** [comment]
Let's concentrate on one scene first: https://www.babylonjs-playground.com/#RNASML#4

Does this code work locally for you? If not then a potential idea is that the reflectionmatrix is not identiy as we may have thought initially

**Comment by deltakosh** [comment]
Do you want me to have a look? I can help if you want

**Comment by ddervisis** [comment]
Sorry for the delay, I tried the PG example locally and it does indeed not work.

**Comment by deltakosh** [comment]
I'll check what could be wrong as I would like to close this PR before publishing beta 5

**Comment by deltakosh** [comment]
OK I have it fixed. I'll close this PR but merge your code anyway :) (And do the required fix)

**Pull request closed without merging**
