### PR TITLE
Disable gizmo rotation when in billboard mode

### PR DESCRIPTION
**Pull request by CedricGuillemet**
follow up on this thread https://forum.babylonjs.com/t/problem-with-gizmos-and-billboard-modes/14547

### CODE REVIEW

**Review by RaananW — APPROVED** [review]

**Comment by Popov72** [comment]
Shouldn't we simply document that the rotation gizmo should not be used with billboard mode instead of blocking it by code? If one displays the rotation gizmo in this case, they may wonder why dragging the circles do nothing. Whereas if it does something (wrong), they may ask in the forum or read the doc that will explain it is expected.

**Comment by RaananW** [comment]
> Shouldn't we simply document that the rotation gizmo should not be used with billboard mode instead of blocking it by code? If one displays the rotation gizmo in this case, they may wonder why dragging the circles do nothing. Whereas if it does something (wrong), they may ask in the forum or read the doc that will explain it is expected.

I agree with both - document it is not working in billboard mode, and limit that in code to stay defensive, as not so many developers read the docs in full. 

Will wait before merging for some more voices

**Comment by CedricGuillemet** [comment]
I can log in console with trying to attach a billboarded transform to a rotationGizmo.

**Comment by julien-moreau** [comment]
+1 for the log. But as @RaananW says, developers don't necessary read the full doc and they also don't necessary take care of the logs ahah

**Comment by deltakosh** [comment]
Yes let's log it but I like the defensive stance as well in the code

**Review by deltakosh — APPROVED** [review]

**Comment by RaananW** [comment]
Linting failed. Will merge right after it's fixed

**Pull request merged**
