### PR TITLE
Update sphereBuilder.ts

### PR DESCRIPTION
**Pull request by aWeirdo**
Fix sphereBuilder adding 6 indices to the top and bottom segments of sphere (even there's only 1 triangle)

Image; White parts have been removed from the sphere, wireframe still shows indices on center area of image (top of sphere)
sphereBug

### CODE REVIEW

**Comment by deltakosh** [comment]
We have a linting issue :)

**Comment by aWeirdo** [comment]
that should fix it i think😄

**Comment by aWeirdo** [comment]
Hmm, it ran lint on the first commit again? 
says whitespace missing x 2, but i added both lol

**Comment by deltakosh** [comment]
just run npm run build and it will lint your code for you (but do not push the dist folder changes :)

**Comment by aWeirdo** [comment]
Sorry, I don't have it locally, just threw the change in the github editor :)

**Comment by deltakosh** [comment]
I'll fix it for you ;)

**Pull request merged**
