### PR TITLE
Fix.create xxx.optionable

### PR DESCRIPTION
**Pull request by jbousquie**
updated for _options_ parameter : 
* CreatePlane
* CreateGround
* CreateSphere
* CreateTorus
* CreateTorusKnot
* CreateBox

### CODE REVIEW

**Comment by deltakosh** [comment]
This:
https://github.com/BabylonJS/Babylon.js/pull/716/files#diff-275ef6355aab4f0ea954727a7a424f72L1260

seems REALLY suspicious :)

**Comment by jbousquie** [comment]
As we decided, I just deleted all the old VertexData.CreateXXX(param1, 
param2, param3, etc) and put instead VertexData.CreateXXX(options)

So all modified VertexData.CreateXXX() calls now use the object "options"

What do you think is suspicious ?
I tested both, old and new, signatures on each modified mesh type, even 
with optional properties when using the object "options". Everything was OK.

**Comment by deltakosh** [comment]
The "var" looks strange. (var closeArray = options.closeArray; in line 1260 in mesh.ts)

**Comment by jbousquie** [comment]
well 
the closeArray variable may be used in the mesh.ts code when the CreateRibbon is told to manage an existing instance instead of creating a new ribbon.
In this very case, no call to VertexData.CreateRibbon() is done, only the existing geometry is recomputed on the fly and a call to updateVerticesData is then done. The value of closeArray is needed in the geometry recomputation.
But closeArray is not valued as an incoming parameter, there's no parameter named closeArray in the overloaded signature... it's closeArrayOrScene or options.closeArray

**Comment by jbousquie** [comment]
Well after review... it's not needed for now, but it will be (like closePath), when I will implement the smooth seam on closeArray as I just did for closePath

line 1344 : (<any>ribbon)._closePath = closePath;
it will be soon the same with closeArray

**Comment by jbousquie** [comment]
actually this line can be commented for now

**Comment by deltakosh** [comment]
Sounds good then!

**Pull request merged**
