### PR TITLE
Update scene.ts

### PR DESCRIPTION
**Pull request by aWeirdo**
I'm in need of getting a texture by it's uniqueId, hope it's okay to add.
Didn't want to bloat by adding the other functions, id, name, etc. not sure it's missed. (thoughts?)

Added scene.getTextureByUniqueID( ... );

### CODE REVIEW

**Comment by aWeirdo** [comment]
Will check errors soon, not sure what's up, i just lazy copy/pasted the getMaterialByUniqueId function 😄

**Comment by aWeirdo** [comment]
Remaining errors seems to be due to 
"TS2740: Type 'BaseTexture' is missing the following properties from type 'Texture': url, uOffset, vOffset, uScale, and 37 more."

shouldn't have any effect.

**Comment by deltakosh** [comment]
Hey! I cannot merge while this error is blocking the CI unfortunately

**Comment by aWeirdo** [comment]
Hey, np. should be fixed now

**Comment by deltakosh** [comment]
Thanks!

**Pull request merged**
