### PR TITLE
Add setCurrentPoseAsRest

### PR DESCRIPTION
**Pull request by Pryme8**
Just waiting to see if the build is successful.

### CODE REVIEW

**Comment by deltakosh** [comment]
Failures are my bad
please sync with master and it should be fine

**Comment by Pryme8** [comment]
Ok cool, I was trying to figure that out!

Also it seems like there is something up with bone.getLocalMatrix() it seems to be modifying the matrix?

Is this related?

**Comment by deltakosh** [comment]
Nope not related. I did not change that

**Comment by Popov72** [comment]
> Also it seems like there is something up with bone.getLocalMatrix() it seems to be modifying the matrix?

`getLocalMatrix` is modifying the matrix if there were some pending changes not integrated in the matrix yet so that you get an up to date matrix.

**Comment by Pryme8** [comment]
Should we add this?
https://forum.babylonjs.com/t/bones-freeze-transformations/14036/22?u=pryme8

**Comment by Popov72** [comment]
Waiting for inputs from @deltakosh or @bghgary, but if doing it I think you can add it as an option (true by default), in case we miss a use case where the user wouldn't want us to modify the textures...

**Pull request merged**
