### PR TITLE
NME: Add missing extra indice and weight matrices blocks

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/morph-target-and-bones-with-animation-issue-using-nme/38765

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13600/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13600/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13600/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13600/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13600/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13600/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13600/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13600/merge#BCU1XR#0

**Review by sebavan — CHANGES_REQUESTED** [review]
Are those the ones waiting for Patrick s review ?

Flagging as Change requested to prevent merge

**Comment by Popov72** [comment]
I have increased the size of all the input blocks to make room for "mesh.matricesIndicesExtra".

image

**Review by sebavan — APPROVED** [review]

**Pull request merged**
