### PR TITLE
PBR: Fix bugs when specific combinations of parameters are used

### PR DESCRIPTION
**Pull request by Popov72**
Specular workflow + sheen "linkSheenWithAlbedo=true": https://playground.babylonjs.com/#QVPPIE

Clear coat + reflection "linearSpecularLOD=true": https://playground.babylonjs.com/#EWFYQ1

### CODE REVIEW

**Comment by Popov72** [comment]
May update the what's new file and keep only the latest entry "Fix bug in PBR when specific combinations of parameters are used" and remove all others?

**Comment by Popov72** [comment]
Reflection texture "isRGBD=true" + irradiance texture: https://playground.babylonjs.com/#5W9Q4W
Translucency enabled + Reflection texture "isRGBD=true" + irradiance texture: https://playground.babylonjs.com/#L9I4FZ

**Comment by sebavan** [comment]
So glad you are checking them all, let me know when to merge :-)

Maybe adding a dedicated validation test would help ?

**Comment by Popov72** [comment]
You can merge those, I shouldn't add new ones now.

I will add the validation test once all fixes are deployed, else the new test will make the validation process fail!

**Comment by sebavan** [comment]
Oh no worry they only use the local code after building it locally :-)

**Pull request merged**
