### PR TITLE
ComputeEffect: Implement onError callback

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/computeshader-compilation-error-callback/48508

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by stefnotch — COMMENTED** [review]
Would it be possible to also provide the offset and length fields of the compile error messages?

Also, I just realised that if Babylon.js modifies the WGSL code, then the line number would be something unexpected that I couldn't easily map back.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14952/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14952/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14952/merge/testResults/webgl2playwright/index.html

**Review by RaananW — APPROVED** [review]

**Comment by Popov72** [comment]
@stefnotch See https://github.com/BabylonJS/Babylon.js/pull/14955

**Pull request merged**
