### PR TITLE
Update TypeScript

### PR DESCRIPTION
**Pull request by ryantrem**
One of my other [PR](https://github.com/BabylonJS/Babylon.js/pull/15823)s is failing in the build because the older version of TS we are using (5.1.6) is missing the `states` property from the `ElementInternals` WebAPI type (the `states` property and the its type `CustomStateSet` are sort of new but supported in all the major browsers). TypeScript 5.5+ has this property and type, so I started trying to update our TypeScript version. However I ran into some problems with deprecated TypeScript APIs used for the path transformation stuff in the build. I tried to fix it (based on some input from the TypeScript team!), but I definitely broke it. So I'm creating a draft PR as a starting point for getting TypeScript updated.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15826/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15826/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15826/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15826/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15826/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15826/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15826/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15826/merge#BCU1XR#0

**Comment by sebavan** [comment]
Is ElementInternals support wide enough considering where the viewer might be used ?

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15826/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15826/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
Wer usually fix these first by adding them manually to the mixins file and then removing them when not needed. Using an API that only exists in a certain typescript version will also force our users to use this version. Otherwise, type check will fail. 
I have no problem with updating the version (after making sure everything works as existed), but we have to support older versions as well.

**Comment by ryantrem** [comment]
> Is ElementInternals support wide enough considering where the viewer might be used ? 

Yes I think it is ok.
ElementInternals is baseline 2023: https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals
CustomStateSet is baseline 2024: https://developer.mozilla.org/en-US/docs/Web/API/CustomStateSet

If they are missing in a browser, it will just mean annotation elements don't get a reduced opacity when not facing the camera.

**Comment by ryantrem** [comment]
> Wer usually fix these first by adding them manually to the mixins file and then removing them when not needed. Using an API that only exists in a certain typescript version will also force our users to use this version. Otherwise, type check will fail. I have no problem with updating the version (after making sure everything works as existed), but we have to support older versions as well.

I remembered this from one of our previous conversations :) In this case, it is only used as an implementation detail, it is not surfaced through the API at all, so it doesn't show up in the d.ts files. I believe that means it cannot impact consumers of the package.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Review by RaananW — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15826/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
