### PR TITLE
assets npm package, repacking viewer

### PR DESCRIPTION
**Pull request by RaananW**
Last task of https://github.com/BabylonJS/Babylon.js/issues/4339

* Viewer's npm package is now the compiled js files with their corresponding ts declaration files.
* new npm package for the babylon viewer assets.

### CODE REVIEW

**Comment by RaananW** [comment]
babylon tests file for some reason?

**Comment by deltakosh** [comment]
No worry you can merge

**Comment by RaananW** [comment]
I just want to run a few test locally. Will merge afterwards

**Comment by RaananW** [comment]
the viewer package will include both a bundled umd version (main) and compiled commonjs sources.

**Pull request merged**
