### PR TITLE
pointerDragBahavior: use AbstractMesh instead of Mesh

### PR DESCRIPTION
**Pull request by Poolminer**
To allow manually attaching the behavior to an AbstractMesh such as an InstancedMesh, without the type checker saying it's an error.

### CODE REVIEW

**Comment by deltakosh** [comment]
Some checks are failing

**Comment by Poolminer** [comment]
> 
> 
> Some checks are failing

I would have to add a note to the "what's new" it seems

**Comment by TrevorDev** [comment]
@Poolminer Whats new is this file https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/what's%20new.md which is used to document the changes for the next release

**Comment by Poolminer** [comment]
I've added a note to the "what's new" file, so it should be OK now, but unfortunately _deploy/netlify_ got timed out; is there a way to retry?

**Comment by deltakosh** [comment]
This is fine thanks!

**Pull request merged**
