### PR TITLE
WebXR mesh detection 

### PR DESCRIPTION
**Pull request by RaananW**
This PR augments the current implementation of the WebXR mesh detection to support the webxr specs - https://immersive-web.github.io/real-world-meshing/

A new option was added - generate mesh based on the geometry provided. The mesh will be updated if the vertex data is updated by the underlying system.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by RaananW** [comment]
This was converted to draft as I could not test it on any of my devices (hololens, android, quest pro). I will create a playground that should work and ask for feedback from quest 3 owners.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14543/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14543/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14543/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14543/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14543/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14543/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14543/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14543/merge#BCU1XR#0

**Comment by RaananW** [comment]
A test playground - https://playground.babylonjs.com/?snapshot=refs/pull/14543/merge#CB9E35

**Pull request merged**
