### PR TITLE
Preparation for playground snapshots and testing

### PR DESCRIPTION
**Pull request by RaananW**
This PG does the following:

1. restructure the playwright configuration and test detection. From now on any test file throughout the repository matched by the specific playwright project matcher will be included in the tests of this specific project.
2. Added playground test project as a preparation for playground user interaction testing
3. Prepare the playground to a full snapshot deployment and testing.

The next steps (after this is merged) are:

1. Build the playground as part of the standard CI
2. Deploy this to a snapshot directory so we can test the actual playground (and not only the default playground with CDN snapshots)
3. Run the playground tests as part of this CI step. Fail if the playground doesn't work correctly.

Note that I opted-out of snapshot testing for the actual website. Mainly because of different rendering cross OSes AND the fact that we have a constant version changing, which will require either not rendering this part or ignoring a lot of pixel changes, which will render snapshot testing useless.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15889/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15889/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15889/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15889/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15889/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15889/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgl2playwright/index.html

**Comment by RaananW** [comment]
> not sure the webgpu.json file should be removed

AFAIK this file has been merged with config.json and has not been used in a long time, at least not in the CI. I can of course revert it, if it is still being used.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by sebavan** [comment]
> > not sure the webgpu.json file should be removed
> 
> AFAIK this file has been merged with config.json and has not been used in a long time, at least not in the CI. I can of course revert it, if it is still being used.

Also I am not sure to understand how the webgl2 and webgpu tests are now able to run (it is clearly Monday :-) ) ?

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by RaananW** [comment]
> Also I am not sure to understand how the webgl2 and webgpu tests are now able to run (it is clearly Monday :-) ) ?

Just as they were running until now! Playwright only. We don't use jest anymore. there are many different ways starting them. The issue with the CI was actually browserstack (which is only enabled on the CI).

To start the tests you can:

1. use the vscode extension
2. Use `npm run test:visualization`
3. Open the UI using `npm run test:visualization:ui`
4. run the tests directly using playwright `npx playwright test --project-webgl2`

Jest and puppeteer as visualization testing was deprecated a long time ago. we don't use on the CI (except fro webgl1) and i don't recommend using it locally as well. Playwright is better.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Comment by RaananW** [comment]
I'll fix the build. This is a permission issue.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15889/merge/testResults/webgl2playwright/index.html

**Pull request merged**
