### PR TITLE
Add public version of AbstractMesh's _getPositionData function

### PR DESCRIPTION
**Pull request by BlakeOne**
PR to add a public version of the _getPositionData function to the AbstractMesh class to allow users to get positions data with skeleton and/or morph applied.
https://forum.babylonjs.com/t/how-do-i-extract-mesh-vertex-data-properly/27381/9

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]
Thanks :)

**Comment by deltakosh** [comment]
Some tests are failing :(

**Comment by BlakeOne** [comment]
I'm going to trace through the called functions and see if I can find the problem, it seems like it should work thou

**Comment by BlakeOne** [comment]
Okay I rearranged the order of the different parts to match the original exactly and it’s validating locally now. :)

And I ended up adding an optional parameter to the function so that the positions data can optionally be passed in. That seems to be the most straightforward way to match the original behavior exactly, at least that I can find.

**Comment by deltakosh** [comment]
Seems great like that!

**Comment by BlakeOne** [comment]
It looks like the checks got cancelled... The only error is that it was cancelled thou, so hopefully the checks just needs to be restarted.
`##[error]The build was canceled by Babylon 4Ever.`

**Comment by BlakeOne** [comment]
Hmm now that it cancelled and restarted the checks a few times they finally finished but there’s another failed visual check, “Chibi Rex FAILED”. It’s too late now to get into it tonight but tomorrow I can give it another try.

**Pull request closed without merging**
