### PR TITLE
Fix breaking issue with ScriptBaseUrl

### PR DESCRIPTION
**Pull request by RaananW**
The general idea here is this - change the ScriptBaseUrl functionality. If it is provided AND the URL is an absolute URL that starts with cdn.babylonjs.com, change this portion of the URL with the data provided in ScriptBaseURL

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14472/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14472/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14472/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14472/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14472/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14472/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14472/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14472/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]
Just wonder if the urls should be constructed from the constant _DefaultCdnUrl to prevent typos ?

**Review by Popov72 — APPROVED** [review]

**Comment by RaananW** [comment]
> Just wonder if the urls should be constructed from the constant _DefaultCdnUrl to prevent typos ?

That was the initial thought and this is why it is public, but that would force a dependency on tools right on load. 
I guess most depend on tools anyhow, but it can be an optional dependency, whereas this forces it to be a required dependency.
I can make the change, as clean-code wise, it does make sense

**Comment by sebavan** [comment]
It could also be in its own module but I guessed all the one with a url are automatically depending on tools in order to use it so I am not sure it would change anything.

**Review by carolhmj — APPROVED** [review]

**Pull request merged**
