### PR TITLE
Add support for Draco compression to glTF loader

### PR DESCRIPTION
**Pull request by bghgary**
First pass at Draco compression support. Only decoding is supported in core for now.

### CODE REVIEW

**Comment by deltakosh** [comment]
Would you mind updating what's new and also reference supported extensions here:
http://doc.babylonjs.com/how_to/gltf

Thanks!

**Comment by bghgary** [comment]
I did update what's new locally but forgot to include it in the change. I'll update both.

**Comment by bghgary** [comment]
> http://doc.babylonjs.com/how_to/glTF

I have a few updates to make for this. I'll make them together.

**Comment by bghgary** [comment]
Please don't merge yet. I found a bug.

**Comment by deltakosh** [comment]
Can you also add a validation tests? Thanks:)

**Comment by bghgary** [comment]
> Can you also add a validation tests?

I was thinking about this. Where do you suggest I add the draco library for the validation tests? I already added the script for the sandbox. Should I duplicate the script everywhere?

**Comment by bghgary** [comment]
@deltakosh Please merge when ready. I will add the validation test afterwards since it requires these changes to go in first.

**Comment by deltakosh** [comment]
Would you mind also referencing supported extensions here:
http://doc.babylonjs.com/how_to/gltf

**Comment by bghgary** [comment]
Yup, will do that together with my other changes already in progress.

**Pull request merged**
