### PR TITLE
Unity Toolkit Workaround

### PR DESCRIPTION
**Pull request by MackeyK24**
Workaround to temp disable the Unity Toolkit scripts loading from playground loadScriptAsync. But load from BABYLON.Tools.LoadScriptAsync while debugging the issue

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14754/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14754/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14754/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14754/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14754/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14754/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14754/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14754/merge#BCU1XR#0

**Comment by MackeyK24** [comment]
What missing docs ?
Are you talking some sort of doc for the commit or are you talking docs in general for the whole toolkit ?

**Comment by RaananW** [comment]
Just check the files, the error is there. You are missing code doc of one variable

**Comment by MackeyK24** [comment]
I see now, sorry... Fixed missing param doc

**Pull request merged**
