### PR TITLE
Thank you apple

### PR DESCRIPTION
**Pull request by RaananW**
For introducing ua agent sniffing into our framework :+1:

### CODE REVIEW

**Comment by deltakosh** [comment]
Best PR ever

**Comment by deltakosh** [comment]
Just a reminder for all of us: we need to remove this hack as soon as iOS will be fixed

**Comment by nockawa** [comment]
I'm laughing reading the PR, but I still feel the pain of @RaananW going on for hours of bug hunting!

**Comment by flashgoblin** [comment]
Love your choice of variable names, Raanan!! LOL

**Comment by jbousquie** [comment]
flushOS ?  ;-)

**Pull request merged**
