### PR TITLE
Disable Physics Sync for static/kinematic bodies

### LINKED ISSUE #14820: Improve physics performance with many static bodies
There is a performance issue when there are lots of physics bodies within a scene.

https://forum.babylonjs.com/t/physics-performance-with-many-static-bodies/48402

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes #14820 
follow up https://forum.babylonjs.com/t/physics-performance-with-many-static-bodies/48402

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by Popov72 — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14880/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14880/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14880/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14880/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14880/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14880/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14880/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14880/merge#BCU1XR#0

**Review by RaananW — APPROVED** [review]

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14880/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14880/merge/testResults/webgpuplaywright/index.html

**Comment by FlorentMasson** [comment]
`this.disableSync = motionType != PhysicsMotionType.DYNAMIC;` should be also added to PhysicsBody.setMotionType()

**Comment by CedricGuillemet** [comment]
> `this.disableSync = motionType != PhysicsMotionType.DYNAMIC;` should be also added to PhysicsBody.setMotionType()

I'm not sure: it makes sense to set disableSync at creation. Then user might change disableSync and change motionType independently. As disableSync is public, I don't want to force it to a new value.
This is edge case for 0.01% of users, I guess :)

**Comment by FlorentMasson** [comment]
Thanks I see, yes it's probably edge case. I was not considering disableSync being public. I can only foresee one use case: disabling sync for dynamic bodies that are not shown on screen.
I can guess changing motion type as being used not so rarely though, for instance pulling a lever makes a rock fall (change from STATIC to DYNAMIC). In that case, the user also needs to change disableSync and that should at least be documented in setMotionType().

**Comment by CedricGuillemet** [comment]
@FlorentMasson I've changed my mind. I think it's indeed better to update the flag when setting motionType. I'll do a PR shortly.

**Pull request merged**
