### PR TITLE
ReflectiveShadowMap: Fix typo in the "no ubo support" path

### PR DESCRIPTION
**Pull request by Popov72**

### CODE REVIEW

**Review by bghgary — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14925/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14925/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14925/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14925/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14925/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14925/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14925/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14925/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14925/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14925/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14925/merge/testResults/webgl2playwright/index.html

**Pull request merged**
