### PR TITLE
SCSS - run an update of dependencies, move to modern API

### PR DESCRIPTION
**Pull request by RaananW**
This will remove the annoying warnings when building some of the tools.

Note that the large amount of files changed is due to the updated dependency that doesn't support default import. Named exports are now being used, so this had to be changed for the entire framework. It's mostly changing everything from `import styles from...` to `import * as styles from...`

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15867/merge/testResults/webgpuplaywright/index.html

**Review by Popov72 — APPROVED** [review]

**Comment by RaananW** [comment]
Moved to draft to test something, will reopen after I am done :-)

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Pull request merged**
