### PR TITLE
Snapshot rendering helper: add support for gaussian splatting meshes

### PR DESCRIPTION
**Pull request by Popov72**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by CedricGuillemet** [comment]
This doesn't look like a maintenable fix. Thin instances update would need such hack (and any object inheriting from thin instances). Is it because of the vertex buffer update or another limitation?

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15906/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15906/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15906/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15906/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15906/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15906/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15906/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15906/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15906/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15906/merge/testResults/webgl2playwright/index.html

**Comment by Popov72** [comment]
I'm not sure why this isn't maintainable? `Mesh.render` isn't called when snapshot rendering is enabled, so the solution is to have the helper make the call itself. Can you think of another way of doing this? Note that the fix is not linked to thin instances, it simply does “manually” what is no longer done automatically.

**Review by CedricGuillemet — APPROVED** [review]
Discussed offline with @Popov72 . All good!

**Review by sebavan — APPROVED** [review]

**Pull request merged**
