### PR TITLE
FilesInput: call _startingProcessingFilesCallback only if files…

### PR DESCRIPTION
**Pull request by julien-moreau**
FilesInput: call "_startingProcessingFilesCallback" only if files have been dropped
Mesh.serialize: if "doNotSerialize", do not serialize

### CODE REVIEW

**Comment by julien-moreau** [comment]
Thanks!

**Comment by julien-moreau** [comment]
Can you let me know once deployed on NPM ?
It fixes an issue in the babylonjs editor :)

**Comment by deltakosh** [comment]
Sure..probably Friday unless this is a big issue for you?

**Comment by julien-moreau** [comment]
No problems, it fixes https://github.com/BabylonJS/Editor/issues/103
You mean friday today ? Or friday next week ?

**Comment by deltakosh** [comment]
oh yeah I meant today :)

**Pull request merged**
