### PR TITLE
Fix reentrancy issue with glTF loader extensions

### PR DESCRIPTION
**Pull request by bghgary**
If a loader extension does some async work before calling back into the parent function, the loader will do the wrong thing. This fixes the problem. Thanks to @eoineoineoin for finding the issue.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14069/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14069/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14069/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14069/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14069/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14069/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14069/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14069/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14069/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14069/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14069/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14069/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Review by Popov72 — APPROVED** [review]

**Comment by bghgary** [comment]
This fix is actually not right. I don't really have a solution. Will discuss offline.

**Comment by bghgary** [comment]
Closing for now. Will reopen if we come up with a clean solution.

**Pull request closed without merging**
