### PR TITLE
Add flags to control glTF loading capabilities

### LINKED ISSUE #15338: Add option to disable animation types in GLTF loader
In some situations users might want to not import specific animation types when loading a GLTF. Right now we can disable specific GLTF extensions but it would be great to also allow for disabling specific features such as node animation, skeleton animation and morph animation.

### PR DESCRIPTION
**Pull request by bghgary**
Fixes #15338

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15346/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15346/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15346/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15346/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15346/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15346/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15346/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15346/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15346/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15346/merge/testResults/webgpuplaywright/index.html

**Review by ryantrem — APPROVED** [review]

**Review by SergioRZMasson — APPROVED** [review]
LGTM

**Review by sebavan — APPROVED** [review]

**Pull request merged**
