### PR TITLE
Material: Adds a property to define the relative order in which decals and detailed maps are rendered

### LINKED ISSUE #14024: Decal map: Add an option to apply it before or after the detail map
See the discussion here:

https://forum.babylonjs.com/t/how-to-render-decal-map-on-top-of-detail-map-or-control-the-render-order-on-a-material-and-its-various-map-properties/42165/6

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/how-to-render-decal-map-on-top-of-detail-map-or-control-the-render-order-on-a-material-and-its-various-map-properties/42165

Fixes #14024

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14025/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14025/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14025/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14025/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14025/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14025/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14025/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14025/merge#BCU1XR#0

**Comment by Popov72** [comment]
See the discussion in the thread, it seems it could be beneficial in some cases, and because it was not difficult to support both and to keep backward compatibility, I added a new property for it.

**Comment by sebavan** [comment]
Let s keep both then and if we need to mention the property too often in the forum lets change the default behavior as it seems pretty far fetch for the current one :-)

**Review by sebavan — APPROVED** [review]

**Pull request merged**
