### PR TITLE
add InstancedLinesMesh

### PR DESCRIPTION
**Pull request by barroij**
add a dedicated `InstancedLinesMesh` to handle instances of LinesMesh.

This is needed as different instances of a LinesMesh might have different `intersectionThreshold` value depending on their world transform.

### CODE REVIEW

**Comment by barroij** [comment]
@deltakosh one more :)

**Comment by barroij** [comment]
@deltakosh hold on, some test are failing, I'll check if it's me.

**Comment by barroij** [comment]
@deltakosh I've got also failing tests when I run them locally on master

**Comment by barroij** [comment]
And now the tests are sucessful... looks like something not determinist in the build 🌪

**Comment by deltakosh** [comment]
Which tests where failing?

**Comment by barroij** [comment]
localy, the Running Sliders (on master branch too)
image


I have the same kind of difference in "Advanced Shadow", but it does not cause the test to fail 👍 
image

**Comment by deltakosh** [comment]
Sliders are for visual validation only so we're good!

**Pull request merged**
