### PR TITLE
OBJLoader

### PR DESCRIPTION
**Pull request by Jaskar**
Correct the loading, taking into account the UVs.
Set a new parameter to specify to take it into account or not.
Update the readme

Asked by @Temechon , following this topic http://www.html5gamedevs.com/topic/18006-babylonjs-very-slow/

### CODE REVIEW

**Comment by Temechon** [comment]
And fix the texture bug here : http://www.html5gamedevs.com/topic/17186-incorrect-obj-loader/?hl=loader

**Comment by RaananW** [comment]
Looking good! How much does it impact the performance, when the flag is true?

**Comment by Jaskar** [comment]
With an object like the desk on this topic : http://www.html5gamedevs.com/topic/18006-babylonjs-very-slow/ , 5000ms without, 14000ms with. It's the reason why I add a flag.
With this one : http://i.imgur.com/IkGNZA9.png
300ms without, 400ms with.

**Comment by RaananW** [comment]
na na na na Batman! :-)
Cool. Thanks for the fix!

**Comment by Temechon** [comment]
Go Batman ! :+1:

**Pull request merged**
