### PR TITLE
Device Orientation Cameras

### PR DESCRIPTION
**Pull request by RaananW**
Fixing the device-orientation cameras (both VR and non-VR one).
Up-Vector is now recalculated using the quaternion.

Target camera now has a quaternion that acts the same as a mesh's rotationQuaternion - if it is defined it will be used, and if not the Vector3 rotation will be used.

With great thanks to Neo-Pangea.

### CODE REVIEW

**Comment by deltakosh** [comment]
Why deleting Autodesk dll :) ?

**Comment by RaananW** [comment]
Now that is interesting :)
It came from the merge, Let me look into that.

**Comment by RaananW** [comment]
The DLL is being ignored for some reason, had to force-add it. I can't find the gitignore line that does it, but it should be fine now.

**Comment by Temechon** [comment]
Super mega cool :)

**Comment by NeoHoffa** [comment]
You guys are pretty swell!!!

**Pull request merged**
