### PR TITLE
Fix webgpu SSR, reflectionmap shader compliation error

### PR DESCRIPTION
**Pull request by noname0310**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15453/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15453/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15453/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15453/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15453/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15453/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15453/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15453/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15453/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15453/merge/testResults/webgl2playwright/index.html

**Comment by noname0310** [comment]
I think it's working now,

how did it pass the test when this PG was in the visualization test. The error is still there in the console.
[#PIZ1GK#1500](https://playground.babylonjs.com/#PIZ1GK#1500)

**Comment by deltakosh** [comment]
Good question that I need to investigate

**Review by deltakosh — APPROVED** [review]

**Pull request merged**
