### PR TITLE
[Native] Warning for non supported fill modes

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes https://github.com/BabylonJS/BabylonNative/issues/1216

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15300/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15300/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15300/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15300/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15300/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15300/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15300/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15300/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15300/merge/testResults/webgpuplaywright/index.html

**Review by RaananW — APPROVED** [review]

**Comment by sebavan** [comment]
You sure you want to log everyframe ?

**Comment by CedricGuillemet** [comment]
> You sure you want to log everyframe ?

I don't think the code does that

**Comment by sebavan** [comment]
would it not log the warning every time draw is called so potentially every frame ?

**Comment by sebavan** [comment]
stupid me lol I did not see this, I had a pavlov reflex of log in draw...

**Pull request merged**
