### PR TITLE
Add IsEnabled Property To Control

### PR DESCRIPTION
**Pull request by barteq100**
I have got a task today to make some inputs not focusable and not editable. As I skimmed through the properties I couldn't find any way to do it what really surprised me so I did it myself, I think it might be usefull for others. Blocking input isn't uncommon.

### CODE REVIEW

**Comment by sebavan** [comment]
Hello,

Could we call the property isEnabled to be consistent with the BabylonJS Node class ?

**Comment by barteq100** [comment]
Sure. I will make changes asap

**Comment by sebavan** [comment]
@barteq100 I am wondering if this should also be added to other controls for consistency ?

Also, it would be really cool if you could drop a line in the dist/preview release/whatsnew.md file for the nice addition.

**Comment by barteq100** [comment]
@sebavan sure I can do it for csistency but I need this change asap and changing all controls will take a moment.

**Comment by sebavan** [comment]
@barteq100  Sure, no problem I can integrate this one first and then you ll have more time for the other controls.

Could you just add the line in the whats new file so that I can merge ?

**Comment by barteq100** [comment]
@sebavan 
Done

**Comment by sebavan** [comment]
I ll test and merge in the afternoon, thanks again for the contribution.

**Pull request merged**
