### PR TITLE
Improve handling of AR in webXRDefaultExperience

### PR DESCRIPTION
**Pull request by AdamMitchell-ms**
- Add support for passing through session mode.
- In immersive-ar mode, hide any background elements

### CODE REVIEW

**Comment by AdamMitchell-ms** [comment]
@RaananW and @bghgary, can y'all take a look?

**Comment by AdamMitchell-ms** [comment]
To test, enable WebXR and the AR module in Chrome Android.  Then you can use this script in the playground.  I copied one of the ones from how_to/webxr and modified it slightly.


```
var createScene = async function() {
    // Create scene
	var scene = new BABYLON.Scene(engine);

    // Create simple sphere
    var sphere = BABYLON.Mesh.CreateIcoSphere("sphere", {radius:0.2, flat:true, subdivisions: 1}, this.scene);
    sphere.position.y = 1;
    sphere.material = new BABYLON.StandardMaterial("sphere material",scene)

    // Lights and camera
    var light = new BABYLON.DirectionalLight("light", new BABYLON.Vector3(0, -0.5, 1.0), scene);
    light.position = new BABYLON.Vector3(0, 5, -2);
    var camera = new BABYLON.ArcRotateCamera("camera", -Math.PI / 2, Math.PI / 4, 3, new BABYLON.Vector3(0, 1, 0), scene);
    camera.attachControl(canvas, true);
    scene.activeCamera.beta += 0.8;

    // Default Environment
    var environment = scene.createDefaultEnvironment({ enableGroundShadow: true });
    environment.setMainColor(BABYLON.Color3.FromHexString("#74b9ff"))
    environment.ground.parent.position.y = 0;
    environment.ground.position.y = 0
    
    // Shadows
    var shadowGenerator = new BABYLON.ShadowGenerator(1024, light);
    shadowGenerator.useBlurExponentialShadowMap = true;
    shadowGenerator.blurKernel = 32;
    shadowGenerator.addShadowCaster(sphere, true);

    let xrSessionMode = "immersive-ar";

    // Enable XR
    var xr = await scene.createDefaultXRExperienceAsync({sessionMode: xrSessionMode, floorMeshes: [environment.ground], backgroundMeshes: [environment.ground, environment.skybox]})
    xr.baseExperience.onStateChangedObservable.add((state)=>{
        if(state === BABYLON.WebXRState.IN_XR){
            // When entering webXR, position the user's feet at 0,0,-1
            xr.baseExperience.setPositionOfCameraUsingContainer(new BABYLON.Vector3(0,xr.baseExperience.camera.position.y,-1))
        }
})

    // Runs every frame to rotate the sphere
    scene.onBeforeRenderObservable.add(()=>{
        sphere.rotation.y += 0.0001*scene.getEngine().getDeltaTime();
        sphere.rotation.x += 0.0001*scene.getEngine().getDeltaTime();
    })

    // GUI
    var plane = BABYLON.Mesh.CreatePlane("plane", 1);
    plane.position = new BABYLON.Vector3(0.4, 1.5, 0.4)
    var advancedTexture = BABYLON.GUI.AdvancedDynamicTexture.CreateForMesh(plane);
    var panel = new BABYLON.GUI.StackPanel();    
    advancedTexture.addControl(panel);  
    var header = new BABYLON.GUI.TextBlock();
    header.text = "Color GUI";
    header.height = "100px";
    header.color = "white";
    header.textHorizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
    header.fontSize = "120"
    panel.addControl(header); 
    var picker = new BABYLON.GUI.ColorPicker();
    picker.value = sphere.material.diffuseColor;
    picker.horizontalAlignment = BABYLON.GUI.Control.HORIZONTAL_ALIGNMENT_CENTER;
    picker.height = "350px";
    picker.width = "350px";
    picker.onValueChangedObservable.add(function(value) {
        sphere.material.diffuseColor.copyFrom(value);
    });
    panel.addControl(picker);
    
	return scene;
};

var colors = {
        seaFoam: BABYLON.Color3.FromHexString("#16a085"),
        green: BABYLON.Color3.FromHexString("#27ae60"),
        blue: BABYLON.Color3.FromHexString("#2980b9"),
        purple: BABYLON.Color3.FromHexString("#8e44ad"),
        navy: BABYLON.Color3.FromHexString("#2c3e50"),
        yellow: BABYLON.Color3.FromHexString("#f39c12"),
        orange: BABYLON.Color3.FromHexString("#d35400"),
        red: BABYLON.Color3.FromHexString("#c0392b"),
        white: BABYLON.Color3.FromHexString("#bdc3c7"),
        gray: BABYLON.Color3.FromHexString("#7f8c8d")
    }
```

**Comment by RaananW** [comment]
Hi, I am already working parallel on this, just didn't commit the changes yet. there will be an entire AS module to support all of AR's wonderful features.

**Comment by RaananW** [comment]
I'll review this tomorrow, i just don't want to overload the default experience class too much (a lesson from the VR Experience helper).
The sessionMode is almost exactly what I did, I will see about the rest.

**Comment by AdamMitchell-ms** [comment]
Hey @RaananW, it sounds like you may already be implementing what I was about to start on next.  Let's discuss.  I've sent you an email to the address listed in your account.

**Comment by deltakosh** [comment]
What is the status of this PR?

**Comment by RaananW** [comment]
I have discussed this with @AdamMitchell-ms . I will create a new AR-Ticket soon and we will follow this ticket for new features for AR.

Closing for now. Thanks Adam :-)

**Pull request closed without merging**
