### PR TITLE
Add undo / redo support to NME

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15546/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15546/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15546/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15546/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15546/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15546/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15546/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15546/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15546/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15546/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15546/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15546/merge/testResults/webgl2playwright/index.html

**Review by RaananW — APPROVED** [review]
~~My honest opinion - this is only partly the solution. But it does solve a pain point!~~

Ignore that :-)

**Comment by deltakosh** [comment]
> ~My honest opinion - this is only partly the solution. But it does solve a pain point!~
> 
> Ignore that :-)

Discussed offline and we are all good!

**Comment by Popov72** [comment]
I'm afraid that the undo stack list will take up a significant amount of memory if a material has several textures embedded... I've seen .json files that weighed several tens of megabytes. Perhaps we should only store two diffs for each entry (one for undo and one for redo) + the complete json for the current entry in the stack? We'd need a quick way to diff two json, though (I suppose applying a diff to a json should be quick)...

**Comment by deltakosh** [comment]
That's why I limited to 64 for now. That being said I like the idea of the diff for an upcoming version

**Pull request merged**
