### PR TITLE
Blender exporter 3.0

### PR DESCRIPTION
**Pull request by Palmer-JC**

### CODE REVIEW

**Comment by deltakosh** [comment]
Please add yourself to the what's new:)

**Comment by Palmer-JC** [comment]
Ok, not today though.

**Comment by deltakosh** [comment]
Sure. I just want you to get the credits you deserve

**Comment by bhouston** [comment]
Having an exporter generate source code is a tightly coupled design, no?  I can foresee versioning issues with it as changes in the source of the project will require re-exports to say in sync.

I actually though the .babylon and especially the delayed load system was quite nice.

If one wanted source code instead I'd just write a translator that takes a .babylon file and created *.js/.ts code form it -- such an approach would have worked with all exporters as well.  Thus it would just be an optimizer that is easy to run from the command line rather than re-exporting all files from their source representation.

Base64 is less efficient than straight binary as well.  The approach taking by the glTF loader with one or more binary files that are referenced in a manner that supports deduplication seemed like a really nice way to go.

Actually, I could actually see it useful to the project to adopt glTF as one of the recommended native formats, it is fairly well designed, efficient and decoupled.

It is of course your project...

**Comment by deltakosh** [comment]
I think there is a misunderstanding here. The exporter still generates a.Babylon file. But there is also an extension project called POV which generates code..
The problem is that exporter links to pov doc that's why I asked JCPalmer to update exporter doc as well

**Comment by deltakosh** [comment]
Oh and we support pure binary as well:)
https://github.com/BabylonJS/Babylon.js/tree/master/Tools/ConvertToBinary

**Comment by deltakosh** [comment]
And for glTF, this is not public yet but we have a working loader in progress:)

**Pull request merged**
