### PR TITLE
P8 Nine Patch clear fix

### PR DESCRIPTION
**Pull request by Pryme8**
I still need to test this, but here is the draft PR.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by sebavan** [comment]
This will introduce back the bug showing overlap lines that your previous change fixed i believe.

**Comment by Pryme8** [comment]
Possibly, Id have to see it again.  I should be able to fix this up.

I'm fighting with my local playground to get spun up so I can test, but was just getting the ball rolling on this.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14434/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14434/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14434/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14434/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14434/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14434/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14434/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14434/merge#BCU1XR#0

**Comment by Pryme8** [comment]
image
You are right it does, ill have to take a look at this after work today.  But Ill get a fix in asap!

**Comment by Pryme8** [comment]
image
Got it... that was a dumb over sight on my part...

**Comment by sebavan** [comment]
Thanks a lot, @Pryme8 can you explain where the +1 and -2 come from ?

**Comment by Pryme8** [comment]
Its just moving the draw methods away from overlapping.

**Pull request merged**
