### PR TITLE
Update interface to match changes in Havok 1.3.0 plugin

### PR DESCRIPTION
**Pull request by eoineoineoin**
Discussed with @RaananW - just updates raycast to match interface changes in the Havok 1.3.0 WASM with reasonable defaults (don't hit triggers, don't exclude any particular body.) Will expose new functionality to users in a future PR.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by RaananW** [comment]
Does this require replacing the wasm on the cdn as well?

**Comment by eoineoineoin** [comment]
Yes, it needs the 1.3.0 version of @babylonjs/havok

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14517/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14517/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14517/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14517/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14517/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14517/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14517/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14517/merge#BCU1XR#0

**Pull request merged**
