### PR TITLE
Changed eval to Function in Validation

### PR DESCRIPTION
**Pull request by kcoley**
- minor change: `eval` to `Function`

### CODE REVIEW

**Comment by sebavan** [comment]
@kcoley Is it fixing the tests or just making them red ?

**Comment by kcoley** [comment]
This doesn't fix the tests, but I will redo this PR with some test handling logic to have the tests fail if the code itself fails.

**Comment by sebavan** [comment]
Np, I am on it :-)

**Comment by sebavan** [comment]
All Fixed.

**Comment by kcoley** [comment]
sweet :)

**Pull request closed without merging**
