### PR TITLE
Replaced voronoi noise code

### PR DESCRIPTION
**Pull request by lockphase**
Pls see forum [post](https://forum.babylonjs.com/t/voronoi-node-noise-artifact/50465/9) on voronoi noise node artifact in nme.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15117/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15117/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15117/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15117/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15117/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15117/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15117/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15117/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15117/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15117/merge/testResults/webgpuplaywright/index.html

**Comment by Popov72** [comment]
I'm ok with the changes, the only thing is that it's a breaking change for people who use the existing function and weren't bothered by the bug...

What do you think @sebavan?

**Review by deltakosh — APPROVED** [review]

**Comment by deltakosh** [comment]
I believe it is ok. We usually fix bugs even if the previous behavior was acceptable for some users

**Pull request merged**
