### PR TITLE
Viewer annotation custom element

### PR DESCRIPTION
**Pull request by ryantrem**
This change adds a simple custom element to add HTML screen space annotations that track hotspots. For example:

```html
<babylon-viewer
    source="https://raw.githubusercontent.com/BabylonJS/Assets/master/meshes/ufo.glb"
    hotspots='{
        "antenna": {
            "type": "surface",
            "meshIndex": 1,
            "pointIndex": [94, 93, 76],
            "barycentric": [0.391, 0.387, 0.223],
            "cameraOrbit": [1.270, 1.424, 0.514]
        }
    }'
>
    <babylon-viewer-annotation hotspot="antenna">
        <div>
            <svg style="width: 20px; height: 20px; transform: translate(-50%, -50%)">
                <ellipse cx="10" cy="10" rx="8" ry="8" fill="red" stroke="white" stroke-width="3" />
            </svg>
        </div>
    </babylon-viewer-annotation>
</babylon-viewer>
```

Annotation elements have a custom state for when the associated hotspot is facing away from the camera, which can be used in CSS styling. The default is to decrease the opacity when the hotspot is not facing the camera.

https://github.com/user-attachments/assets/8c0c6c40-b81f-45fd-8d8e-6226c64e0438

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15823/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15823/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15823/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15823/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15823/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15823/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15823/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15823/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15823/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15823/merge/testResults/webgpuplaywright/index.html

**Review by RaananW — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Pull request merged**
