### PR TITLE
Create option to Render Screenshot

### PR DESCRIPTION
**Pull request by 13djwright**
As discussed [here](https://forum.babylonjs.com/t/screenshot-in-high-resolution-sandbox/5319/5), this is a simple addition to the inspector to include a way to render a screenshot and allows for the ability to change the precision, width, or height.

I wasn't sure the best way to do the settings, so feel free to advise me if they should be changed.

### CODE REVIEW

**Comment by deltakosh** [comment]
The CI is failing: https://github.com/BabylonJS/Babylon.js/pull/6822/checks

**Comment by deltakosh** [comment]
up :)

**Comment by 13djwright** [comment]
I've got to find some time to get this to build. I haven't forgot about it though.

**Comment by deltakosh** [comment]
Hey!

1. Can you add a checkbox to turn the width and height definition on/off? And in that case fill it with a 512 defaut value
2. Just credit yourself here: https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/what's%20new.md

**Comment by 13djwright** [comment]
Here is a gif of what it looks like.

**Comment by deltakosh** [comment]
Thanks a lot!

**Pull request merged**
