### PR TITLE
glTFSerializer: Add texture transform support

### PR DESCRIPTION
**Pull request by kcoley**
This was originally going to be support for the KHR_texture_transform extension, but I ran into a bunch of edge cases in terms of implementing the fallback behavior.  So for now, if texture transform properties are applied to a texture, the texture file will be modified.  Should resolve https://github.com/BabylonJS/Babylon.js/issues/4974

### CODE REVIEW

**Comment by deltakosh** [comment]
This looks good so far:
- Can you update the what's new file?
- Can you provide one visual test where we serialize a scene and load it again to make sure we have a validation?
- Would like to get @bghgary approval as well

**Comment by kcoley** [comment]
Yeah sure thing

**Comment by sebavan** [comment]
LGTM as well but completely agree on the validation test :-)

**Comment by kcoley** [comment]
@sebavan @deltakosh does the validator visual test support promises?  It seems to exit before the serializer is able to execute since it waits for the scene to finish rendering.

**Comment by deltakosh** [comment]
Yes but you have to turn on the polyfill: BABYLON.PromisePolyfill.Apply(true);

**Comment by deltakosh** [comment]
Let's see how the CI feels about that :)

**Comment by deltakosh** [comment]
Let's see how the CI feels about that :) (and you have a conflict)

**Pull request merged**
