### PR TITLE
Remove side effects on more method parameters

### PR DESCRIPTION
**Pull request by hcschuetz**
This is a follow-up to PR #15381.

While identifying that bug I detected three more similar issues,
two of which should be fixed here.

See also https://forum.babylonjs.com/t/unexpected-side-effect-of-quaternion-rotationaxis/52622

Notice that
- I just detected the issues fixed here by looking for issues similar to
  the one fixed in my earlier PR.
- I have no test case for the affected functions.
- There seem to be no unit tests for the affected functions either.

So you might want to review this change particularly thoroughly.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — APPROVED** [review]

**Review by deltakosh — APPROVED** [review]
Help appreciated

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15402/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15402/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15402/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15402/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15402/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15402/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15402/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15402/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15402/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15402/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15402/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15402/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
