### PR TITLE
First beta version of Babylon.js inspector

### PR DESCRIPTION
**Pull request by Temechon**
New folder added : inspector, with its own dependencies and gruntfile.
Class Tools updated to load a script by calling a specific URL

Class DebugLayer entirely removed and replaced by this code in the 'show' method : 
* Check if namespace inspector exist.
  * If not, load the script set at http://www.babylonjs.com/inspector.js
* Create a new inspector with the current scene

### CODE REVIEW

**Comment by Temechon** [comment]
Yes it's being implemented !

**Comment by deltakosh** [comment]
Can you check with @sevan to use gulp and merge it into the main gulpfile(same for distribution folder as we merged all in /dist

**Comment by deltakosh** [comment]
Could we change namespace to Babylon.inspector?

**Comment by deltakosh** [comment]
Beside that I love everything

**Comment by Temechon** [comment]
I can change the namespace, no problem.
And we can use [gulp-grunt](https://www.npmjs.com/package/gulp-grunt) to run the inspector grutn task from the gulp file. I'll check with Seb.

**Comment by deltakosh** [comment]
any news on this guys?

**Pull request merged**
