### PR TITLE
Feature.bezier curve

### PR DESCRIPTION
**Pull request by jbousquie**
Added a new class in the math.ts file : _Curve3_.
This object is to embbed math 3D curve computations and to provide pre-implemented complex equations to users (bezier, splines, etc).
For now, the _construtor_ method and _getPoints()_ method, returning an array of the successive _Vector3_ of the curve, are available.

Two first static methods are also defined for Bezier curves :  
```javascript
var bezier2 = BABYLON.Curve3.QuadraticBezier(origin, control, destination, nb_of_points);
```
and
```
var bezier3 = BABYLON.Curve3.CubicBezier(origin, control1, control2, destination, nb_of_points)
```
Both returning an instantiated _Curve3_ object.
Then users can access the Bezier curves points with 
```javascript
var points = bezier3.getPoints();
```

PR : only the maths.ts file is modified and then tested with _CreateLines()_
The rest is again the bunch of compiled js files coming with :-(

### CODE REVIEW

**Comment by raananw** [comment]
Hi Jerome, 

there are a few conflicts that needs to be resolved before this is merged, and I think you once again committed all of the javascript files :-)

**Comment by jbousquie** [comment]
I know the js files are commited :-(

What am I doing ?
```bash
$ git checkout master
M	Babylon/Audio/babylon.sound.js
M	Babylon/Audio/babylon.soundtrack.js
M	Babylon/Debug/babylon.debugLayer.js
M	Babylon/Lights/Shadows/babylon.shadowGenerator.js
M	Babylon/Lights/babylon.directionalLight.js
M	Babylon/Lights/babylon.spotLight.js
M	Babylon/Loading/Plugins/babylon.babylonFileLoader.js
M	Babylon/Materials/Textures/babylon.cubeTexture.js
M	Babylon/Materials/Textures/babylon.renderTargetTexture.js
M	Babylon/Materials/babylon.standardMaterial.js
M	Babylon/Math/babylon.math.js
M	Babylon/Mesh/babylon.geometry.js
M	Babylon/Mesh/babylon.meshSimplification.js
M	Babylon/PostProcess/babylon.postProcess.js
M	Babylon/PostProcess/babylon.postProcessManager.js
M	Babylon/Tools/babylon.filesInput.js
M	Babylon/Tools/babylon.tools.js
Basculement sur la branche 'master'
Votre branche est en avance sur 'origin/master' de 25 commits.
  (utilisez "git push" pour publier vos commits locaux)

$ git fetch upstream
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 10), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Depuis https://github.com/BabylonJS/Babylon.js
   fa47717..69549e3  master     -> upstream/master

$ git merge upstream/master
error: Your local changes to the following files would be overwritten by merge:
	Babylon/Debug/babylon.debugLayer.js
	Babylon/Loading/Plugins/babylon.babylonFileLoader.js
Please, commit your changes or stash them before you can merge.
Aborting
```
Sometimes, there are far more files listed in the last error message. Especially after local compilations.
**It prevents me to go on merging before I commit.**
So I usually just run : 
```bash
$ git commit
$ git merge upstream/master
```
This allow then me to go on with the last BJS version. If I don't do it, I haven't got the last version.
I can then create a new local branch, checkout it, code in the last BJS files, compile and test, commit my changes, push them to my github repo, then PR.
When I compile, I generate different local JS files of course, different from the ones imported from the BJS github repo.
Maybe this mandatory commit has something to do with these JS file differences ?

Elseway do you know a way to avoid this mandatory initial commit ? 
When I use the GUI client SmartGit, it is just the same behavior than with git command line :-(

**Comment by raananw** [comment]
The main problem is the different compilers that are being used to generate the js files.
After you use gulp typescript (or typescript-to-js), new JS files are being compiled. those are your conflicts. But you don't have to commit them, and you can actually revert most if not all of them before commiting. 
Try this - 
(starting a new branch, just like you do - fetch, merge, create branch).
After making your changes run gulp typescript, this will generate a new babylon.js that you can use to test.
Test everything, and then revert all of the JS changes, except for the js changes corresponding to your ts changes.
Then the only files you commit will be the files you actually changed.

**Comment by jbousquie** [comment]
Ok I understand.

To be more clear : 
So far, I just commited _only_ the TS files I modified, only one or two files on the new created branch. Nothing else.
I explicitly commit each modified TS file one by one. 
I don't commit any JS file, you know.

Except the initial commit asked by the **merge** command, just after the **fetch** on the master branch.
This merge aborts if I don't commit !  :-( 
And I then don't have the latest BJS files.
So I don't know how to do then :-( 

Where and when can I revert in this  vicious circle your opinion ?

**Comment by raananw** [comment]
A few pointers, I hope it can help :smile:
* The commit titled "mandatory update before merge upstream/master : modified js files only" is the one with all of the js files. I assume this commit was "forced" upon you, since those git error messages can be rather intimidating. "You have to commit,  otherwise all changes are lost" or something like that...
* Don't fetch and merge the upstream after creating a new branch. finish what you started and create a pull request from there.
* After modifying the js files, simply revert them. You got what you are looking for - a new babylon.js file to test with.
* After fetching and merging the upstream to the master, sync the master with github.com, and only then create a new branch (I guess you are already doing that). The branch will then have the newest state and won't have any problems with conflicts and such.

You are doing a wonderful thing with those function you add, it will be great seeing them merged into the framework!

**Comment by jbousquie** [comment]
> * The commit titled "mandatory update before merge upstream/master : modified js files only" is the one with all of the js files. I assume this commit was "forced" upon you, since those git error messages can be rather intimidating. "You have to commit, otherwise all changes are lost" or something like that...

It's right this ! 
And if I ignore this, the merge isn't done, and I don't' get the latest BJS files.

> * Don't fetch and merge the upstream after creating a new branch. finish what you started and create a pull request from there.

 I guess here is my error. 
I fetch/merge initially, then create a new branch, then start working on it : code, compilation, etc.
The next day, as my work isn't finished yet, I checkout on master, then re-fetch/re-merge (+ forced commit), then checkout my new working branch.
Thank you Raanan :-) I think this is the place where my process is wrong !

> * After modifying the js files, simply revert them. You got what you are looking for - a new babylon.js file to test with.

How can I _revert_ them ? one by one manually in each BJS folder ? (aaargg)

> You are doing a wonderful thing with those function you add, it will be great seeing them merged into the framework!

Thank you... what am I supposed to do with with PR now ? 
Re-PR it another way ?
Or let DK do the job with all those conflicts and ... apologize for this extra work ?

**Comment by raananw** [comment]
If it is something simple that you can copy and recreate, I would simply close this one and create a new branch and commit it. Should be less work for everyone.

BTW - When I said don't fetch etc', I meant in the branch. You can do whatever you want with the master. This of course has the disadvantage that if someone changes exactly the same position as you at the same file and at the same time, a conflict will have to be resolved. Then you will have to resolve the conflicts locally (rather easy with UI tools, a bit harder with CLI) and commit. 

About reverting - using the CLI I believe the checkout function is the right one to use:

    git checkout ???

Revert is also a very "svn" term. some will call it discard, as revert is actually used on commits and not local changes. UI tolls (I personally use tortoiseGit and github for windows) have this function as well.

**Comment by jbousquie** [comment]
Ok, thank you again.
I'll try all this... and still don't know how to deal with this initial forced commit :-P

**Comment by raananw** [comment]
There will be no need if you use the freshest branch and commit only the changed files

**Comment by jbousquie** [comment]
ok
I'll do this... and hope.

I'll delete this branch once it will be merged  ... if it will ;-)

**Comment by raananw** [comment]
:) Practice makes perfect. It will soon be very simple for you. You'll see :wink:

**Comment by jbousquie** [comment]
Maybe is it simplier to copy/past the only last 40 lines of maths.ts ( class  Curve3 : https://github.com/jbousquie/Babylon.js/commit/ee98a44c55986394b9a965efb98e9a8f327d1c17 ) rather than trying to merge all that *$%&€@ stuff ?

**Comment by deltakosh** [comment]
I'll do that for you

**Comment by jbousquie** [comment]
thank you DK
and sorry again for all the bunch coming with... I try each time to avoid it : sometimes it works, sometimes I face those mandatory initial commit before merging :-( 
Dont't know why... maybe because of the TS compiler differences ? no idea.

Maybe is it simplier for everyone that a fully delete my github BJS repo and then re-clone again when I need to contribute..?

**Comment by latop2604** [comment]
hard reset + force push will do the same.
```
git reset upstream/master --mixed    (or --hard if you want to erase you changes)
... clean files
... commit
git push -f
```

If you have few commit on a branch, you can use git rebase instead of a classic merge.

Some docs 
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request
http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

**Comment by deltakosh** [comment]
Done my friend! Let me know it fhis is ok for you and then...doc :D

**Comment by jbousquie** [comment]
Thank you guys
and thank you Rémy for the git advices :-)

**Comment by jbousquie** [comment]
@DK : tested in new build, ok for me.
Documented too. ;-)

**Comment by dk** [comment]
hmm what? i'm not involved in this :)

**Comment by deltakosh** [comment]
Hey Jerome..can you add some playground samples on your doc? This will be helpful for beginners:)

**Comment by deltakosh** [comment]
Oh and this one needs...some text :)
http://doc.babylonjs.com/page.php?p=25088

**Comment by jbousquie** [comment]
Mouuaaarfff..
Yes, I just created the ribbon tutorial with empty parts to remember what should be written. Not started yet. Soon :-)

I will add a PG example to Curve3, OK.

Could you change please the function names to _ComputeCubicBezier()_ and _ComputeQuadraticBezier()_ in the code directly ou do ou prefer I try a PR ?
I'm changing the names in the docs accordingly right now.

**Pull request closed without merging**
