### PR TITLE
Texture: Set type and format at load time

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/update-just-one-channel-of-texture/44163/4

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14314/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14314/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14314/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14314/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14314/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14314/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14314/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14314/merge#BCU1XR#0

**Review by carolhmj — APPROVED** [review]

**Comment by RaananW** [comment]
Just making sure - can this be a breaking change?

**Comment by Popov72** [comment]
It could be (but I don't think it will have a big impact), but it's really a bug.

**Pull request merged**
