### PR TITLE
Create screenshot: Fix resources not recreated with the right sizes

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/babylonjs-5-0-5-5-5-ios-15-4-safari-15-4-issues/30195/27

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by Popov72** [comment]
It is the basis loader test which is failing, so likely not coming from my PR.

**Comment by deltakosh** [comment]
cc @RaananW

**Comment by bghgary** [comment]
We just merged https://github.com/BabylonJS/Babylon.js/pull/12662 which is likely the reason. But the CI was fine for that PR?

**Comment by bghgary** [comment]
Oh, I know why. You have to make sure to merge latest after that change goes in because the config needs to point to the correct Basis files.

**Comment by bghgary** [comment]
Actually, never mind. It should still work since we kept the old Basis files at the same location. The visualization test for the basis loader still works on the playground: https://playground.babylonjs.com/#4RN0VF#102.

**Pull request merged**
