### PR TITLE
 Replace examples pane in the playground - issue #4376

### PR DESCRIPTION
**Pull request by Jaskar**
https://github.com/BabylonJS/Babylon.js/issues/4376

### CODE REVIEW

**Comment by deltakosh** [comment]
Can you link to doc website for the content?

**Comment by deltakosh** [comment]
I would like to avoid duplicating Json and images

**Comment by Jaskar** [comment]
I'll link the doc website for the icons, but I can't for the list.json.
The documentation website is built, so the list.json is not in the public website.

**Comment by deltakosh** [comment]
We can move it as part of doc build process

**Comment by Jaskar** [comment]
Other question : Categories / examples are sorted by alphabetical order, except "Misc." category on doc website, is it the expected result ?

**Comment by deltakosh** [comment]
Nope:)

**Pull request merged**
