### PR TITLE
Making data Nullable for RawTexture3D and RawTexture2DArray

### PR DESCRIPTION
**Pull request by christianphalv**
This change will make creating RawTexture3D and RawTexture2DArray storage textures less tedious when setting the data in a compute shader. This also brings it more in line with the RawTexture constructor.
https://doc.babylonjs.com/typedoc/classes/BABYLON.RawTexture#constructor

Related to this change that allows RawTexture3D and RawTexture2DArray to be flagged as storage textures.
https://github.com/BabylonJS/Babylon.js/pull/14070

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14072/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14072/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14072/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14072/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14072/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14072/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14072/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14072/merge#BCU1XR#0

**Review by sebavan — COMMENTED** [review]
I am not too sure we should add the 2 static functions here as they are only shortcuts for functions which are not currently used a lot.

@RaananW what do you think ?

**Comment by RaananW** [comment]
> I am not too sure we should add the 2 static functions here as they are only shortcuts for functions which are not currently used a lot.
> 
> @RaananW what do you think ?

Not sure how much these functions are needed, especially since they are just a proxy to the constructor, passing the variables you are passing anyhow. Why won't the dev use the constructor directly?

**Comment by christianphalv** [comment]
I added the static functions because I am currently using their analog in RawTexture. They aren't necessary, though. I can remove them.

**Pull request merged**
