### PR TITLE
Move to TypeScript 4.9.5

### PR DESCRIPTION
**Pull request by RaananW**
There are small improvements (mainly to type safety).
This PR is öpen for discussions", as this is not 100% needed. We will move to TS 5.X when it's out. This is just another small step towards that goal.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Review by Popov72 — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13512/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13512/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13512/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13512/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13512/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13512/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13512/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13512/merge#BCU1XR#0

**Pull request merged**
