### PR TITLE
Adding warning for matching versions

### PR DESCRIPTION
**Pull request by litlatte**
Adding a note to make sure users install matching versions of babylonjs and babylonjs-loaders

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13544/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13544/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13544/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13544/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13544/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13544/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13544/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13544/merge#BCU1XR#0

**Review by RaananW — COMMENTED** [review]
Since 5.22.0 it is possible to have different versions, if it fits the peer dependency definition. We recommend using the same version. It's the case with all of our other packages. Did you experience something else?

**Comment by RaananW** [comment]
Closing for now, please reopen if needed

**Pull request closed without merging**
