### PR TITLE
Added some @since 5.0.0 tags

### PR DESCRIPTION
**Pull request by Popov72**
I have reviewed the what's new file and added some `@since` 5.0.0 tags wherever I could.

I have also fixed some glTF extension comments for extensions that are now merged into the Khronos repo.

### CODE REVIEW

**Comment by RaananW** [comment]
tsdoc doesn't support the @since tag...

https://tsdoc.org/

**Comment by RaananW** [comment]
Following up on this - we had this discussion (where i had the same answer) https://forum.babylonjs.com/t/since-tag-versioning/14393

I wonder why it passed back then. I'll have to investigate that.

**Comment by Popov72** [comment]
That's strange because it works for this class WebXRDomOverlay: https://doc.babylonjs.com/typedoc/classes/babylon.webxrdomoverlay

**Comment by Popov72** [comment]
Ah, I think I know: it's supported only for methods and classes, and it fails for properties.

**Review by RaananW — APPROVED** [review]
LGTM :-)

**Pull request merged**
