### PR TITLE
docs: readme

### PR DESCRIPTION
**Pull request by Lubov66**
Replaced shields and added a link to Discord

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by deltakosh** [comment]
Nice try but this is not the correct Babylon discord;)

**Comment by sebavan** [comment]
We should not change it

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15762/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request closed without merging**
