### PR TITLE
Better architecture of the UMD test project

### PR DESCRIPTION
**Pull request by RaananW**
The test project tests the declaration generated for core, gui, loaders, materials and serializers. 
This takes the declaration generated directly, without the nees to deal with npm dependencies. It is set to no-emit, so it only checks compilation and nothing else.

It will not be able to report which reference is incorrect, just the package that failed and the reason (line in a long declaration file)

### CODE REVIEW

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14870/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14870/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14870/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14870/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14870/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14870/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14870/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14870/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14870/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14870/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Review by Popov72 — APPROVED** [review]
I noticed that the path is `packages/public/umd/babylonjs-testporject` and not `packages/public/umd/babylonjs-testproject`. I don't know if it can be safely corrected?

**Comment by RaananW** [comment]
> I noticed that the path is `packages/public/umd/babylonjs-testporject` and not `packages/public/umd/babylonjs-testproject`. I don't know if it can be safely corrected?

fixing this right now. Thanks!

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14870/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
