### PR TITLE
Fix EquiRectangularCubeTexture error handling and EquiRect./HDRCubeTexture caching problem

### PR DESCRIPTION
**Pull request by ddervisis**
While working with the `EquiRectangularCubeTextureAssetTask` I ran into a problem where textures would not load in some cases (very hard to reproduce, I will try to create a PG example) which affects both, `EquiRectangularCubeTexture`'s and `HDRCubeTexture`'s. 

Another problem was the error handling in the `EquiRectangularCubeTexture`, when an image cannot be loaded (wrong path or io problems), so I created an Error eventlistener for such cases, which essentially just bubbles up on the onError callback chain.

Playground example: tbd

Suggestions are welcome

### CODE REVIEW

**Comment by deltakosh** [comment]
Checks are failing
https://github.com/BabylonJS/Babylon.js/pull/6105/checks

**Comment by deltakosh** [comment]
up?

**Comment by ddervisis** [comment]
The errors should be fixed now, but there are some linting errors regarding a package:

```bash
[09:35:15] Starting 'core-tsLint'...
/home/vsts/work/1/s/src/Meshes/transformNode.ts:94:6
ERROR: 94:6   semicolon  Unnecessary semicolon
ERROR: 103:6  semicolon  Unnecessary semicolon
ERROR: 943:6  semicolon  Unnecessary semicolon

[09:35:22] 'core-tsLint' errored after 7 s
[09:35:22] ‌Error‌ in plugin &quot;‌gulp-tslint‌&quot;‌
Message:
    Failed to lint: /home/vsts/work/1/s/src/Meshes/transformNode.ts [94, 6]: Unnecessary semicolon, /home/vsts/work/1/s/src/Meshes/transformNode.ts [103, 6]: Unnecessary semicolon, /home/vsts/work/1/s/src/Meshes/transformNode.ts [943, 6]: Unnecessary semicolon.
Details:
    domain: [object Object]
    domainThrown: true
```

**Comment by deltakosh** [comment]
Ok I'll take care of the linting

**Pull request merged**
