### PR TITLE
Fix gui declaration

### LINKED ISSUE #13502: Latest build 5.45.0 gives gui declaration file error
The latest build 5.45.0 give typescript error with Babylon guy declaration file:

```
Assets/[Babylon]/Template/Typings/babylon.gui.d.ts(594,96): error TS2792: Cannot find module 'core/Engines/ICanvas'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
```

### PR DESCRIPTION
**Pull request by RaananW**
Fixes #13502

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13503/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13503/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13503/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13503/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13503/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13503/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13503/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13503/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13503/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13503/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13503/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13503/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
