### PR TITLE
U3D - BabylonJS Toolkit Loader API

### PR DESCRIPTION
**Pull request by MackeyK24**
Loader API For The U3D - BabylonJS Toolkit

### CODE REVIEW

**Comment by deltakosh** [comment]
Seems like you do it twice?
Which one do you want to keep? (Other is #1518)

**Comment by MackeyK24** [comment]
the #1518 had the some 'tab indent' issues... So I reformatted the .cs files in the 1519 with windows and visual studio.

**Comment by MackeyK24** [comment]
Hey Delta.... Please cancel both 1518 and 1519... I and working on a cleanup for individual mesh.onDispose...  BTW... How come there is no camera.onDispose and light.onDispose ???

**Comment by deltakosh** [comment]
Ok no problem. 
Regarding onDispose, I'll add them for you in a couple of minutes ;)

**Pull request closed without merging**
