### PR TITLE
Added JSON-based procedural code generator to the Playground

### PR DESCRIPTION
**Pull request by Tricotou**
This PR is following the [same topic on the forum](https://forum.babylonjs.com/t/what-about-a-code-generator-for-the-playground/50396/7)

- source code is the same than CTRL+SPACE menu (`tools/playground/public/templates.json`)
- any new code block from this code generator is now as well available from the CTRL+SPACE menu :heavy_check_mark: 
- added a structure json in `tools/playground/public/procedural.json` which is used to build the drop down menu :heavy_check_mark: 
- the `fetch("templates.json").then()` has been move to the monaco constuctor since now it's used from different places.
- `NB:` the code generator is not "100%" based on the JSON (for now...?) since some conditions have been included outside, such as for example a `shadowGenerator` check (cannot be enabled on hemi light), etc.
- `NB:` In the monaco editor I added a `if (model.isDisposed())` check (see line 720 & 727), but I could not find exactly when the error `Model is disposed!` is triggered. Seems to be a bit random :thinking: 
___
Demo : https://github.com/BabylonJS/Babylon.js/assets/167624418/6b95747b-8f10-42ca-955a-46dc873e0f96

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15243/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15243/merge/testResults/webgpuplaywright/index.html

**Comment by sebavan** [comment]
Lets  see if @PatrickRyanMS can tests the code to validate the UI/UX? and if @RaananW can check the code :-)

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15243/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15243/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
Sorry fro taking the time here, was preoccupied with other tasks. I will review this PR today

**Comment by RaananW** [comment]
Code-wise I am perfectly fine with it. I'll wait for @PatrickRyanMS to try this out and give some feedback, when he has the time.
To test it you need to pull the branch and test it locally, as the playground and sandbox are the one thing that doesn't get pushed to the snapshot

**Comment by PatrickRyanMS** [comment]
I am out of the office for the US holiday. I will be back on Monday and able to take a look.

**Review by deltakosh — APPROVED** [review]
Looks AWESOME!
Love it

**Comment by deltakosh** [comment]
I merged to have it used by people and we can do a new PR if we want improved UX

**Comment by Tricotou** [comment]
`we can do a new PR if we want improved UX`
Absolutely ! @PatrickRyanMS don't hesitate to give a feedback about design :)

**Pull request merged**
