### PR TITLE
Fix CCW 2D GUI Ellipse Arcing.

### PR DESCRIPTION
**Pull request by aWeirdo**
Fix counter-clockwise arcing. (negative arc value)

See top right ellipse stack.
Before;
https://playground.babylonjs.com/?snapshot=refs/pull/15207/merge#IC5LC6#3

After;
https://playground.babylonjs.com/?snapshot=refs/pull/15207/merge#IC5LC6#4

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15210/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15210/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15210/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15210/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15210/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15210/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15210/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15210/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15210/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15210/merge/testResults/webgpuplaywright/index.html

**Review by RaananW — APPROVED** [review]

**Pull request merged**
