### PR TITLE
Explicit dispose for Canvas and Context

### PR DESCRIPTION
**Pull request by CedricGuillemet**
see https://github.com/BabylonJS/BabylonNative/issues/810

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — CHANGES_REQUESTED** [review]
I am wondering if this does not create an issue when ppl are passing their own canvas/context in dynamicTexture via the options ?

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14064/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14064/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14064/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14064/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14064/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14064/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14064/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14064/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14064/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14064/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by sebavan** [comment]
Yup but not sure the API should allow breaking it ?

**Comment by carolhmj** [comment]
> Yup but not sure the API should allow breaking it ?

Maybe this can be controlled as a parameter of the DynamicTexture? Something like `cleanupContextUponDisposal`

**Comment by CedricGuillemet** [comment]
I'm hoping for a better approach. May reopen if I don't find any better solution.

**Comment by sebavan** [comment]
yup nw

**Pull request closed without merging**
