### PR TITLE
TAA: Fix when using an orthographic camera

### PR DESCRIPTION
**Pull request by Popov72**
PG: https://playground.babylonjs.com/#539X0P#42

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14783/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14783/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14783/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14783/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14783/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14783/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14783/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14783/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14783/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14783/merge/testResults/webgl2playwright/index.html

**Review by RaananW — APPROVED** [review]

**Pull request merged**
