### PR TITLE
Lint config fixes

### PR DESCRIPTION
**Pull request by ryantrem**
Two small changes:
1. Put quotes around the file pattern in the eslint command. Without this, the command does not work on Mac. With it, it works on both Mac and Windows.
2. Update the prettier config to allow LF or CRLF line endings. Right now we have a mix (e.g. some files are LF and some are CRLF). When I run the linter, I get like 15K warnings because of LF line endings. I would think everyone else would be hitting this as well.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15341/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15341/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15341/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15341/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15341/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15341/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15341/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15341/merge#BCU1XR#0

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15341/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15341/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
