### PR TITLE
AbstractMesh 'metadata' object added

### PR DESCRIPTION
**Pull request by MackeyK24**
Added ‘metadata’ to abstract mesh class to support adding ‘any’ meta
data to the mesh. This is very useful when using the 'Exporters'.

Example: My Unity Exporter now exports 'custom properties' from the editor components.

### CODE REVIEW

**Comment by deltakosh** [comment]
We already support Tags for that:)
http://doc.babylonjs.com/tutorials/How_to_use_the_Tags_System

**Comment by MackeyK24** [comment]
Well i was hoping to use metaData to 'attach' unity specific properties to 'GameObjects' using the BabylonJs exporter... Example Snippet from custom exporter:

`
public class UnityMetaData
	{
		public string type;
		public string tagName;
		public int layerIndex;
		public string layerName;
		public string shadowCasting;
		public BabylonGameComponent[] gameComponents;

		public UnityMetaData()
		{
			type = "Unity3D";
			tagName = "";
			layerIndex = 0;
			layerName = "";
			shadowCasting = "Off";
			gameComponents = null;
		}
	}

       [DataContract]
	public abstract class BabylonGameComponent : MonoBehaviour
	{
		[DataMember]
		public string className;
	}
        public void ConvertFromUnity()
        {
            ExporterWindow.ReportProgress(0, "Starting Babylon.js exportation process...");
            ...
// Unity metadata
				UnityMetaData metaData = new UnityMetaData();
				metaData.tagName = gameObject.tag;
				metaData.layerIndex = gameObject.layer;
				metaData.layerName = LayerMask.LayerToName(gameObject.layer);
				metaData.gameComponents = gameObject.GetComponents<BabylonGameComponent>();
				var meshRender = gameObject.GetComponent<MeshRenderer>();
				if (meshRender != null) {
					metaData.shadowCasting = meshRender.shadowCastingMode.ToString();
				}

				// Static meshes
				var meshFilter = gameObject.GetComponent<MeshFilter>();
                if (meshFilter != null)
                {                    
					ConvertUnityMeshToBabylon(meshFilter.sharedMesh, meshFilter.transform, gameObject, progress, metaData);
                    continue;
                }
}
`

Having a 'metaData' object that goes thru 'Parse' routines makes it real easy to more 'closely' use unity editor to build my scenes.

**Comment by MackeyK24** [comment]
Well i was hoping to use metaData to 'attach' unity specific properties to 'GameObjects' using the BabylonJs exporter... Example Snippet from custom exporter:

public class UnityMetaData
	{
		public string type;
		public string tagName;
		public int layerIndex;
		public string layerName;
		public string shadowCasting;
		public BabylonGameComponent[] gameComponents;

		public UnityMetaData()
		{
			type = "Unity3D";
			tagName = "";
			layerIndex = 0;
			layerName = "";
			shadowCasting = "Off";
			gameComponents = null;
		}
	}

       [DataContract]
	public abstract class BabylonGameComponent : MonoBehaviour
	{
		[DataMember]
		public string className;
	}
        public void ConvertFromUnity()
        {
            ExporterWindow.ReportProgress(0, "Starting Babylon.js exportation process...");
            ...
// Unity metadata
				UnityMetaData metaData = new UnityMetaData();
				metaData.tagName = gameObject.tag;
				metaData.layerIndex = gameObject.layer;
				metaData.layerName = LayerMask.LayerToName(gameObject.layer);
				metaData.gameComponents = gameObject.GetComponents<BabylonGameComponent>();
				var meshRender = gameObject.GetComponent<MeshRenderer>();
				if (meshRender != null) {
					metaData.shadowCasting = meshRender.shadowCastingMode.ToString();
				}

				// Static meshes
				var meshFilter = gameObject.GetComponent<MeshFilter>();
                if (meshFilter != null)
                {                    
					ConvertUnityMeshToBabylon(meshFilter.sharedMesh, meshFilter.transform, gameObject, progress, metaData);
                    continue;
                }
}

Having a 'metaData' object that goes thru 'Parse' routines makes it real easy to more 'closely' use unity editor to build my scenes.

**Comment by deltakosh** [comment]
You can do the same using tags :) just create a tag named unityExporter and save a json serialized version of your metadata (using json.net for instance)

**Comment by MackeyK24** [comment]
How would i put my metaData in the .babylon scene file that is created from the unity exporter... basically
can i edit the .babylon scene file and add something like:

"metaData" : {
				"type" : "Mesh",
				"parentId" : "3fc9a478-1f80-4094-b0fa-5e39e0c83096",
				"tagName" : "Player",
				"layerIndex" : 1,
				"layerName" : "TransparentFX",
				"shadowCasting" : "On",
				"gameComponents" : [
					{
						"className" : "My.Custom.Component",
						"propertyBag" : {
							"testPositionData" : {
								"x" : 1,
								"y" : 2,
								"z" : 3
							},
							"testNumberData" : 24,
							"testFloatData" : 24.24,
							"testBooleanData" : true,
							"testStringData" : "some more data",
							"testStringList" : [
								"test 1",
								"test 2"
							],
							"testPositionList" : [
								{
									"x" : 1,
									"y" : 2,
									"z" : 3
								},
								{
									"x" : 4,
									"y" : 5,
									"z" : 6
								},
								{
									"x" : 7,
									"y" : 8,
									"z" : 9
								}
							]
						}
					}
				]
			}


Then... how would i pull that metaData using the babylon api in javascript...

I dont wanna have to create a separate json file for my metaData

**Comment by MackeyK24** [comment]
The tags are for strings... That will not work for what I'm doing. Let me try to explain my Html Game Development Pipeline.

1... I have modified the Unity Exporter to support 'metaData' to meshes, cameras and lights. Look at this .babylon scene file snippet:

	"cameras" : [
		{
			"name" : "Main Camera",
			"id" : "2c767860-d0a4-4972-9ca6-a83a508f0e6b",
			"parentId" : null,
			"lockedTargetId" : null,
			"type" : null,
			"position" : [
				0,
				1,
				-10
			],
			"rotation" : [
				0,
				0,
				0
			],
			"target" : [
				0,
				1,
				-9
			],
			"fov" : 1.04719758,
			"minZ" : 0.3,
			"maxZ" : 1000,
			"speed" : 1,
			"inertia" : 0.9,
			"checkCollisions" : true,
			"applyGravity" : true,
			"ellipsoid" : [
				0.5,
				1,
				0.5
			],
			"autoAnimate" : false,
			"autoAnimateFrom" : 0,
			"autoAnimateTo" : 0,
			"autoAnimateLoop" : false,
			"animations" : null,
			"metaData" : {
				"type" : "Camera",
				"parentId" : "2c767860-d0a4-4972-9ca6-a83a508f0e6b",
				"tagName" : "MainCamera",
				"layerIndex" : 0,
				"layerName" : "Default",
				"shadowCasting" : null,
				"gameComponents" : null
			}
		}

by creating the 'metaData' as a fully serializable class (NOT JUST A STRING TAG) , i can closely attach 'unity' logic to the game objects (meshes, cameras and lights... the three main items created by the unity exporter)

2... On the client html side after scene load, i can run my UnityMetaData.Parse(scene) routine that
iterates over the scene.meshes, cameras and lights. I can then do what i want with the metaData. In my case i, i instantiate a custom babylon class passing the mesh, camera or light object. I also support a special unity script sub classed from 'BabylonGameComponent'... It has a babylon class name and property bag (contains all the simple public fields on the unity script with the [BabylonProperty] attribute).

This whole thing lets me attach Babylon Game components to my unity game objects in my scene... I can then use unity editor properties on the unity script component. it works really wells.

The client side unitymetadata parsing automatically manage metaData components, calling the game object 'Init, Tick, Destroy' life cycle methods without manually coding the components by having to do a bunch scene.getMesh functions attach functionality to my scene game objects...

It is more UNITY LIKE DESIGN EXPERIENCE.

None of this works with just BABYLON.Tags string based tags.

**Comment by deltakosh** [comment]
I think there is a misunderstanding here.
Everything that you mentioned before is already doable with a tag. Tags are string exactly like your metadata. You can set a a tag and save your json (as a string) in it.
Once loaded in Babylon.js you can query any tag anduse JSON.Parse to get your structure

**Comment by deltakosh** [comment]
At the very least, I could be ok if you add a metadata untyped item at node level.
(For simplicity sake, but once again this is clearly doable with tags)

**Comment by sebavanmicrosoft** [comment]
Could we not add Serialization and Deserialization Hook instead ?

You could them rely on them to inject your custom part and reading them on the other side. 

Everybody is having different needs concerning storage and I guess the more open it is, the easiest. Without making the objects grow all the time or relying on type any.

**Comment by MackeyK24** [comment]
I get what saying about the tag system. I just don't like that, seems kinda 'cheesy' for a piece of code that will be the MAIN INTERFACE between my design time editor experience (Unity) and my runtime BABYLON code.

The code changes i submitted should NO negative impact on the framework itself. As a matter a fact it "natively" opens the framework for extensibility by "TAGGING" the three main things that you export, Meshes, Cameras and Lights.

I simply add three lines of code to BABYLON.AbstractMesh, BABYLON.Camera and BABYLON.Light:
1... Declare the general purpose field 'metaData: any = null' in typescript files (1 line of code)
2... In Mesh.Parse, Camera.Parse and Light.Parse functions 'if (parsedMesh.metaData !== undefined) mesh.metaData = parsedMesh.metaData'

SO SIMPLE (if you will allow it)... No performance impact... The metaData it 'natively' exposed to the javascript 'mymesh.metaData' without SOME EXTRA CRAP to load the metaData... Its already a 'dance' going on with loading the .babylon file which in turns loads the .manifest file... I don't want put EXTRA crap on the end of that... And most of all i don't want have to make a second server trip. 

The BABYLON.Tag system doesn't quite work for me (yes i know i can serialize my metaData as a separate string that ultimately gets store back in the babylon file... But that is not as clean as my suggested code changes... REAL SMALL, GENERAL PURPOSE, NON NEGATIVE IMPACT CODE CHANGES)

P.S. Sorry for the capitals... But I'm practically 'begging' you to accept them... My workflow i developed using Unity and my UnityExporter (Which supports adding Design Time script components to Meshes, Cameras And Lights) is sweet... I get "MOST" of the power of unity editor and asset management (Especially The Assets Store) and all the native HTML/JS/CSS/WEBGL/CANVAS and for me DuoCode (I write all my babylon code using C# which is transpired to javascript, just like typescript or copfescript) from the MOST AWESOME JS GAME FRAMEWORK... BABYLON... I love it :)

**Comment by nockawa** [comment]
@MackeyK24 hello, sorry, we know it takes time and it's mainly due to the fact that your request initiated an internal discussion that we couldn't finish yet.

I'm advocating for the solution you proposed but at the Node class level, I don't see the point to implem 3 times the same code for a feature that could live without much consequence in the very base class.

DK will be soon online and we try to give you an answer asap.

Thanks

**Comment by nockawa** [comment]
@MackeyK24 please revise your PR with the implem in the Node class, because it's the one that is most likely to get merged. 

Thanks

**Comment by deltakosh** [comment]
Agree with @nockawa. And please stop calling things crap:)

**Comment by deltakosh** [comment]
So here is the idea: 
just add a proeprty on node= public metadata: any;

and flag it with @serialize() it should be enough :)

**Comment by MackeyK24** [comment]
Will Do... (Node Stuff)

NOTE: i was never calling anything to do babylon js CRAP... I was calling any EXTRA code that i would have to write to implement metaData... That would be CRAP code compared to the David's 'Node' suggestion.

JUST TO CLARIFY :)

**Pull request closed without merging**
