### PR TITLE
Return animation groups when calling SceneLoader.ImportMesh 

### LINKED ISSUE #3971: Expose animation groups in loader callback

### LINKED ISSUE #3999: Playground/scenes/Alien doesn't play its morph targets
- Bug repro on [sandbox](http://sandbox.babylonjs.com/):
Using [Alien](https://github.com/BabylonJS/Babylon.js/blob/master/Playground/scenes/Alien/Alien.gltf)
- Expected result:
Morph target and skeletal animation channels play.
- Current result:
Only skeletal animation channels play.

### PR DESCRIPTION
**Pull request by bghgary**
* Fixes #3971 
* Fixes #3999

Other changes
* Replace onAnimationGroupLoaded with returned animationGroups in glTFLoader.
* Add AnimationMultiTarget to optimize animations that target multiple targets.
* Update unit tests to check for morph targets, animations, and animation groups.
* Add animation groups and textures to asset container.

### CODE REVIEW

**Comment by bghgary** [comment]
There seems to be a build order issue. I think the issue is that the viewer module depends on the loader module and they are currently building at the same time.

**Comment by deltakosh** [comment]
There is a build error unfortunately

**Comment by bghgary** [comment]
Yes, I'm not sure how to fix. See my previous comment.

**Comment by deltakosh** [comment]
Pinging @raananw for ideas;)
I guess making sure viewer is built after loaders and bjs should make it

**Comment by deltakosh** [comment]
I found a way to fix it. I'll merge tomorrow and do the fix:)

Thanks

**Pull request merged**
