### PR TITLE
Updating Viewer readme

### PR DESCRIPTION
**Pull request by ryantrem**
This change is mostly updating the new viewer's readme.md with a bit more high level info about how to use and customize the viewer. My hope is that the readme.md will basically be the top level doc page for the viewer, and then we'll have more detailed doc pages plus the API documentation. This will be easier to setup after @RaananW merges the docs repo into the main BJS monorepo. For now I'm just updating the top level readme.md.

This change also adds photoStudio.env to an assets folder of the viewer package.

Lastly, this change removes the `"sideEffects": false` from the package.json. I found in various integrations that with this set, the custom element registration does not work since it in fact depends on side effects (effectively a module level call to `customElements.define`, which is the standard pattern for custom elements). I will talk with @RaananW more about this specific change.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15635/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15635/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15635/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15635/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15635/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15635/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15635/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15635/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15635/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15635/merge/testResults/webgl2playwright/index.html

**Review by RaananW — APPROVED** [review]

**Pull request merged**
