### PR TITLE
WebGPU: synchronize with Spec / multiple improvements and fixes

### LINKED ISSUE #13564: Foreset WebGPU sample doesn't work due to Wgsl spec change
In babylonjs webgpu sample,  the wgsl shader below
```
==============
// Example WGSL shader code:

var<private> position : vec3<f32>;

struct main_out {
  @builtin(position) gl_Position : vec4<f32>,
}

@vertex
fn main() -> main_out {
  position = vec3<f32>(0.0f);
  return main_out(vec4<f32>(0.5f));
}
```
is not correct anymore due to the new Wgsl spec changes(https://github.com/gpuweb/gpuweb/pull/3859). Now the module-scope variable `position` will shadow the built-in value name.

The suggested fix for this is rename the `var<private> position: vec3<f32>` to others.

### LINKED ISSUE #13633: WebGPU Update (uniform analysis, GLSL update, spec update)

### PR DESCRIPTION
**Pull request by Popov72**
In this PR:
* Synchronization with the latest specifications
* Added labels to textures for debugging purposes. This helps a lot when debugging with WebGPU as all error messages in Canary refer to the faulty object(s) via their label, if any. 
* Changed vertex/fragment input/output handling to fix #13564. The user must now prefix all inputs/outputs with the correct object (`vertexInputs`/`vertexOutputs`/`fragmentInputs`/`fragmentOutputs`). This is a breaking change but it's the only way to make it work with WebGPU, and WebGPU isn't out yet so it doesn't matter much.
* Updated caps based on actual limits retrieved from the device.
* Uniformity analysis (UA) fixed. I did not disable uniformity analysis as a whole (`WebGPUTintWASM.DisableUniformityAnalysis = false`), let's see if we get any feedback from users because of the failure of uniformity analysis (all visual tests are successful).
* there are still two visualization tests that fail ("Shadows CSM and LODs" and "Multi shadow generators per light") because of https://bugs.chromium.org/p/tint/issues/detail?id=1886
* several fixes (wrong depth/stencil texture format in MultiRenderTarget in some cases, memory leaks, etc.)

Fixes #13633, #13564

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13691/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13691/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13691/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13691/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13691/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13691/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13691/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13691/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Pull request merged**
