### PR TITLE
Add viewer alpha tooling for tree shaking analysis

### PR DESCRIPTION
**Pull request by ryantrem**
This PR adds two things:
1. Uses `rollup-plugin-visualizer` to generate a stats json file that has a lot of raw data, including references between all modules.
1. A script that takes a module path substring and the status json file and prints out all reference paths so you can immediately identify why a module was not tree shaken.

So with the [initial size analysis tooling](https://github.com/BabylonJS/Babylon.js/pull/15298) changes you can find what is contributing to the size, and with this tooling you can figure out why that thing contributing to the size wasn't tree shaken.

For example, with the size analysis tooling I could see that `nodeMaterial.js` was included, which clearly is unnecessary. With the tooling in this PR, I was able to run the `npm run analyze` command followed by the script `node ../../../scripts/queryRollupStats.js nodeMaterial.js ./dist/analyze/stats.json` and see this output:

image

This made it immediately obvious that `sceneHelpers.js` is pulling in a lot of other stuff. Having identified this, I factored out the one thing we were using from it (`scene.createDefaultSkybox`) and removed the reference to `sceneHelpers` (this will be coming in a separate PR). This alone brought the package size down from ~2.3mb to ~1.8mb. In a separate PR yet, I will be adding a bit more tooling to diff two flame charts so you can also easily understand why removing `sceneHelpers` has such a dramatic impact on package size.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15319/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15319/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15319/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15319/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15319/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15319/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15319/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15319/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15319/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15319/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
