### PR TITLE
Mark native engine as supporting MSAA

### PR DESCRIPTION
**Pull request by bghgary**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14292/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14292/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14292/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14292/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14292/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14292/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14292/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14292/merge#BCU1XR#0

**Review by Popov72 — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Comment by sebavan** [comment]
Does it not need to be on a min version of Native to not break @bghgary ???

**Comment by bghgary** [comment]
> Does it not need to be on a min version of Native to not break @bghgary ???

No, this doesn't do anything if the native side isn't updated. I ran the visual tests locally and passed with just this change.

**Pull request merged**
