### PR TITLE
Adds VAT, Texture Bone capabilities to the VolumetricLightScatteringPostProcess and DepthRenderer

### PR DESCRIPTION
**Pull request by noname0310**
Added morphtarget, skeleton and VAT support to VolumetricLightScatteringPostProcess.

Added VAT and CPU Skinning fallback support to DepthRenderer.

Other minor refactoring included.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15468/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15468/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15468/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15468/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15468/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15468/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15468/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15468/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15468/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15468/merge/testResults/webgl2playwright/index.html

**Review by sebavan — COMMENTED** [review]
Looks Great !!!

Would you be able to add a visual test for them ?

**Comment by sebavan** [comment]
And by the way @noname0310 , thanks a lot for all the contribs recently :-)

**Comment by noname0310** [comment]
I add the test, and while working on it, I found the issue in other rendering code by accident, so I'll PR it separately.

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15468/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15468/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15468/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by noname0310** [comment]
On my local machine, the WebGL1 test works fine. I have no clue what the problem is.

**Review by sebavan — APPROVED** [review]

**Comment by noname0310** [comment]
I don't think there's a problem now

**Comment by sebavan** [comment]
@noname0310 can you try merging back master in your branch ?

**Pull request merged**
