### PR TITLE
Extend size and position should be in local space for the physics engin(s)

### PR DESCRIPTION
**Pull request by RaananW**
Closing #7407 

I checked other physics demos and they dont seem to be influenced by this change, however it needs to be monitored

### CODE REVIEW

**Comment by RaananW** [comment]
Please wait with merging

**Comment by deltakosh** [comment]
good?

**Comment by RaananW** [comment]
Still fighting Oimo, I hope to be done very soon

**Comment by RaananW** [comment]
After this commit oimo compounds work. I had to disable the bidirectional transformation transfer between oimo and babylon when using compound meshes. So, this will work:

https://www.babylonjs-playground.com/#492ZK0#32

Setting the position AFTER creating the impostors will not work (!). To update the position use the physics body's position parameter:

`impostor.physicsBody.position.y = 10`:

https://www.babylonjs-playground.com/#492ZK0#33

(Note that the demos will only work after merging those changes to babylon!!)

@deltakosh - good to go now.

**Pull request merged**
