### PR TITLE
Allow alpha in shadow color

### LINKED ISSUE #15540: Color picker for shadow color in GUI editor does not respect alpha value in Hex color
Controlling alpha in drop shadows in GUI is done through the hex value of the assigned color and can be controlled in the inspector or through code. In the GUI editor, however, the alpha component of the hex value seems to be ignored. This should work the same as the inspector where the alpha component of the hex value sets the alpha for the drop shadow. The shadow is taking an alpha value from the fill color of the control, but should also have its own alpha value. The alpha of the fill color of the control should multiply with the alpha from the shadow as happens normally in GUI.

**Repro**
- [Open this snippet](https://gui.babylonjs.com/#X86NF7)
- select the rectangle with the red drop shadow and navigate to the appearance section
image
- Click on the shadow color button and change the alpha component of the hex value to anything other than `ff`

**Expected**
The shadow should not be fully opaque with any value other than `ff` in the alpha component of the hex value. What happens right now is that the value entered will stay until the color picker is closed and then upon opening it again, the default value of `ff` for alpha has returned implying that the update to the color is not passing the alpha value. This works correctly on both the fill color and stroke color in the appearance section. This appears to be isolated only to the shadow color input.

### PR DESCRIPTION
**Pull request by RaananW**
Fixes #15540

### CODE REVIEW

**Review by Popov72 — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15541/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15541/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15541/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15541/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15541/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15541/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15541/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15541/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15541/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15541/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
