### PR TITLE
#5673 Cleaned gradient material + disable lighting as emissive

### PR DESCRIPTION
**Pull request by julien-moreau**
- Cleaned gradient material by removing useless uniforms and defines
- As @sebavan suggested, disabling lighting makes the material workins as emissive

### CODE REVIEW

**Comment by sebavan** [comment]
Nice one :-) I ll male a nightly ASAP

**Comment by julien-moreau** [comment]
Hopefully my last commit about the what's new was merged while you pushed the button "merge" ahahah

**Comment by sebavan** [comment]
Yup it is in, it is why I merged, I was adding a comment when it popped :-)

**Comment by julien-moreau** [comment]
Ahah excellent synchronization

**Comment by julien-moreau** [comment]
Thanks !!! :)

**Pull request merged**
