### PR TITLE
Playwright visualization tests

### PR DESCRIPTION
**Pull request by RaananW**
This PR adds a new script to run playwright visualization tests.

To test playwright:

1. run `npm install` 
2. run `npx playwright install` (this will install the missing browsers)
3. run `npm start` (or start the babylon-server any other way)
4. run `npm run test:playwright -w @tools/tests -- --project=webgl2 --ui` to start webgl2 tests in UI mode

This will start playwright in UI mode. You can run tests individually and see the results or run all of them:

image

other projects - webgl1 and webgpu

For automated tests run

`npm run test:playwright -w @tools/tests -- --project=webgl2` . This will run headless with no UI. If something fails playwright will open its HTML reporter to show you exactly what happened.

Alternative to 3 (to test against public CDN), set the CDN_BASE_URL environment variable to "https://cdn.babylonjs.com".

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14308/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14308/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14308/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
