### PR TITLE
Update meshopt_decoder.js to 0.18

### PR DESCRIPTION
**Pull request by zeux**
This brings us up to the latest decoder module for meshopt contents which includes Wasm binary updates and the removal of experimental console.log message that is no longer relevant.

The update makes decoding a little faster (~5%), and the module itself a little bigger (~5%) due to the use of new LLVM toolchain.

The extra download size, however, is just 287 bytes (gzip delta).

Raw numbers (Ryzen 5900X, node.js 18.12, Linux):

before:
- decodeVertex 3.54 GB/s
- decodeIndex 2.05 GB/s
- raw size 21781 bytes
- gzip size 5868 bytes

after:
- decodeVertex 3.77 GB/s
- decodeIndex 2.16 GB/s
- raw size 23379 bytes
- gzip size 6155 bytes

The file is copied verbatim from https://github.com/zeux/meshoptimizer/blob/v0.18/js/meshopt_decoder.js

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — APPROVED** [review]
LGTM, Adding @bghgary for another pair of eyes :-)

Thanks a lot @zeux

**Review by bghgary — APPROVED** [review]
Good for me. Do we have any tests for meshopt models? If not, maybe we can add some using the [new ones](https://github.com/KhronosGroup/glTF-Sample-Models/pull/363) that @zeux just added.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13407/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13407/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13407/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13407/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13407/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13407/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13407/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13407/merge#BCU1XR#0

**Comment by sebavan** [comment]
> Good for me. Do we have any tests for meshopt models? If not, maybe we can add some using the [new ones](https://github.com/KhronosGroup/glTF-Sample-Models/pull/363) that @zeux just added.

Let s add them in a separate PR ???

**Comment by bghgary** [comment]
> Let s add them in a separate PR ???

Okay with me.

**Pull request merged**
