### PR TITLE
Updated dynamic texture clip test

### PR DESCRIPTION
**Pull request by SergioRZMasson**
Updated dynamic texture clipping test to make it no longer pass in Babylon Native when texture is not rendered correctly.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15087/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15087/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15087/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15087/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15087/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15087/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15087/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15087/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15087/merge/testResults/webgpuplaywright/index.html

**Comment by bghgary** [comment]
Just for additional context, without this change, even if the dynamic texture failed to render, the number of pixels that are different is not enough to trigger the default 2.5% error ratio. The new PG will make more pixels different when the test fails.

**Review by bghgary — APPROVED** [review]

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
