### PR TITLE
Make AbstractMesh a real abstract class

### PR DESCRIPTION
**Pull request by bghgary**
Note that some calls to `new AbstractMesh` were converted to `new Mesh` instead of `new TransformNode` because various helper functions still take an `AbstractMesh` when it could in theory take `TransformNode`.

### CODE REVIEW

**Comment by bghgary** [comment]
Let's discuss to make sure we are okay with the changes. It is semi-breaking as we will no longer be able to create AbstractMesh objects, which arguably should not be allowed.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15160/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15160/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15160/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15160/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15160/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15160/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15160/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15160/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15160/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15160/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
