### PR TITLE
add texture/materials to assetContainer

### PR DESCRIPTION
**Pull request by TrevorDev**
https://github.com/BabylonJS/Babylon.js/issues/6051

TestPG: #Q96J2D

### CODE REVIEW

**Comment by nbduke** [comment]
One thing I'm curious about with the `LoadAssetContainer` methods: should *any* assets be put into the scene before calling `addAllToScene` on the returned container? Or is that impossible to guarantee?

**Comment by TrevorDev** [comment]
@nbduke  Are you asking if LoadAssetContainer should have any side effects before calling addAllToScene? It should not, so if you are aware of cases where this happens, let me know. Loading an assetContainer should only populate the assetContainer and adding and removing that asset container assets to the scene should only effect the assets in the assetcontainer.

**Comment by nbduke** [comment]
Yeah, you can actually see that happening if you make a slight tweak to the playground I put in the bug. Check this out: https://www.babylonjs-playground.com/#FHHM51#6

**Comment by TrevorDev** [comment]
@nbduke, after double checking this, this PR should make things better for this case eg. mesh materials/textures should not be be in the scene but I still do see skeleton textures populated on the scene after calling LoadAssetContainer. I could add special logic to remove these but this texture is internal to skeleton so if a user wants to add only skeletons back to the scene for some reason I'm afraid of breaking something for them so I think I'm going to leave those alone unless you have an issue with this. Those skeleton textures will be removed if the container is disposed like in your example.

**Comment by nbduke** [comment]
Ok, thanks. Ideally loading assets into a container would have no side effects, but I agree that the highest priority is that AssetContainer cleans up after itself, which your PR will fix.

**Pull request merged**
