### PR TITLE
Materials: Improve management of frozen materials

### LINKED ISSUE #13776: Materials: improve management of frozen materials
See https://forum.babylonjs.com/t/how-to-unfreeze-and-freeze-in-6-0/40242

Also:
* [x] https://playground.babylonjs.com/#ITQR47#7
=> this one does work because we call `ground.resetDrawCache();`, but calling `ground.material.markDirty(true);` instead should make it work (which is not the case) => https://playground.babylonjs.com/#ITQR47#8
* [x] https://playground.babylonjs.com/#7PPJ1M#9
=> this one doesn't work even with `resetDrawCache` + `markDirty(true)` - comment `mat.freeze()` to see it working => https://playground.babylonjs.com/#7PPJ1M#11
* [x] https://forum.babylonjs.com/t/what-cant-be-safely-changed-when-freezing-materials/41103
=> same than above, the `texture.vScale=-1` is not applied correctly
* [x] https://playground.babylonjs.com/#7MXSEV#5
=> a single sphere turns red (the first one) because after the color is updated for it, `effect._forceRebindOnNextCall` is set to `false`, so the other spheres won't execute the uniform buffer update code (because all the spheres use the same effect)
* [x] https://forum.babylonjs.com/t/cross-browser-performance-priority-material-bug/42792/3
=> it is using the `Intermediate` performance mode

The problem is that `_wasPreviouslyReady`, `_wasPreviouslyUsingInstances` and `_forceRebindOnNextCall` which are currently stored on the effect should be stored on the `DrawWrapper` instead (that's because an effect can be shared by multiple submeshes).

Also, the doc should be updated:
* https://doc.babylonjs.com/features/featuresDeepDive/scene/optimize_your_scene#performance-priority-modes

Instead of unfreezing when something needs to be changed on the material, one should probably call `markDirty(true)` instead.

### PR DESCRIPTION
**Pull request by Popov72**
Closes #13776 

Basically, I did what I explained in #13376:
> The problem is that _wasPreviouslyReady, _wasPreviouslyUsingInstances and _forceRebindOnNextCall which are currently stored on the effect should be stored on the DrawWrapper instead (that's because an effect can be shared by multiple submeshes).

I will also update the docs shortly.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by sebavan** [comment]
Would be great to check how is this impacting perfs ?

**Comment by Popov72** [comment]
I don't think it impacts perfs, before there's actually no new code. It's only that some properties have been moved from `Effect` to `DrawWrapper`, and so instead of doing something like `subMesh.effect.XXX`, we now do `drawWrapper.XXX`.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14741/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14741/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14741/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14741/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14741/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14741/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14741/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14741/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14741/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
