### PR TITLE
Sprite: Fix picking when angle is not zero

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/should-sprite-picking-work-with-rotation-angle/40768

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13860/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13860/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13860/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13860/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13860/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13860/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13860/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13860/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13860/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13860/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Review by sebavan — COMMENTED** [review]
I trust you on the Maths, just validating the code :-)

**Comment by Popov72** [comment]
> I trust you on the Maths, just validating the code :-)

:)

The ray was already rotated, so we didn't need to rotate it again in `_checkTextureAlpha`.

However, the ray was rotated with the wrong angle, so we need to take `-angle` to transform the ray into the correct coordinate system (this is the same as transforming a ray with the inverse world transformation when we want to test a ray-mesh intersection in the local coordinate system of the mesh).

**Review by RaananW — APPROVED** [review]

**Pull request merged**
