### PR TITLE
Preparations For GPU Testing

### PR DESCRIPTION
**Pull request by RaananW**
This PR is a (hopefully) final preparation for webgpu testing.

This adds further configuration flags that can be adjusted using the CI. On top of that, prepass tests (and 2 other unrelated tests) were excluded from webgpu testing.

Some tests fail on WebGPU/Ubuntu. The reason is unclear (As they don't fail on windows) and will be investigated in the future.

Until then it should be possible to run the webgpu tests on a remote chrome using this config file.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14015/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14015/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14015/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14015/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14015/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14015/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14015/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14015/merge#BCU1XR#0

**Review by carolhmj — APPROVED** [review]

**Comment by Popov72** [comment]
The problem with this PR is that those tests won't run anymore, even locally, whereas they do work... Maybe we should have different exclusions, for local and production?

**Comment by RaananW** [comment]
> The problem with this PR is that those tests won't run anymore, even locally, whereas they do work... Maybe we should have different exclusions, for local and production?

I have a solution for this, integrated in this PR already. I'll fix it on Monday and make sure they are skipped only in the CI

**Pull request merged**
