### PR TITLE
SceneOptimizer improvements. Fix #2995

### LINKED ISSUE #2995: Add option to automatically adapt the scaling level based on performances
We are currently choosing statically the hardware scaling level. It would be nice to have an option to automatically scale up/down the scaling level based on the FPS o better benefits form the hardware capabilities of the target device/experience.

### PR DESCRIPTION
**Pull request by deltakosh**
Example:
```
        // Options (target 70fps (which is not possible) with a check every 500ms)
        var options = new BABYLON.SceneOptimizerOptions(70, 500);
        options.addOptimization(new BABYLON.HardwareScalingOptimization(0, 1));
        options.addCustomOptimization(function () {
            environment.groundMaterial.reflectionTexture = null;
            return true;
        }, function () {
            return "Turning mirror off";
        });
        options.addOptimization(new BABYLON.HardwareScalingOptimization(0, 1.5));
        options.addCustomOptimization(function () {
            environment.ground.setEnabled(false);
            return true;
        }, function () {
            return "Turning ground off";
        });

        // Optimizer
        var optimizer = new BABYLON.SceneOptimizer(scene, options);
        optimizer.start();
```

### CODE REVIEW

**Comment by deltakosh** [comment]
Documentation update in progress. Need to mention:
- New SceneOptimizer instance
- stop, start, reset
- autoGeneratePriorities
- custom optimization with callbacks
- dispose
- observables
- Improvement for HardwareScalingLevelOptimization

**Comment by deltakosh** [comment]
New doc: http://doc.babylonjs.com/how_to/how_to_use_sceneoptimizer

**Comment by dad72** [comment]
Hi,
I was watching the demo on the documentation of this PR and the GUI is not displaying:
https://www.babylonjs-playground.com/index.html#3Q8PCL

**Comment by deltakosh** [comment]
Because the code is not merged yet:)

**Comment by dad72** [comment]
oops, ok. I was too curious ...

**Comment by deltakosh** [comment]
Not a problem at all;)

**Pull request merged**
