### PR TITLE
3D GUI Near Menu computes the cell size incorrectly

### LINKED ISSUE #15550: 3D GUI Near Menu computes the cell size incorrectly
See https://forum.babylonjs.com/t/issue-with-gui3dmanager-menus-random-appearance-difficult-to-click-buttons-and-misalignment/53208?u=raananw

### PR DESCRIPTION
**Pull request by RaananW**
Fixes #15550

The extend size was computed incorrectly (if the menu is transformed in any way). The reason it was not found so far is that it will only appear if the menu is manipulated after rotating the camera.

Playground to test with - #Z6M4WM#4 . If testing the "before" state, rotate the camera 90 degrees and press one of the buttons.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15551/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15551/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15551/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15551/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15551/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15551/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15551/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15551/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15551/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15551/merge/testResults/webgl2playwright/index.html

**Review by deltakosh — APPROVED** [review]

**Pull request merged**
