### PR TITLE
Removing Tools from Math completely 

### PR DESCRIPTION
**Pull request by RaananW**
Math has now no more Tools references.
We should consider throwing errors instead of Tools.Error (but then exceptions will have to be handeled)

### CODE REVIEW

**Comment by RaananW** [comment]
Found some other references, wait with that for a minute.

**Comment by deltakosh** [comment]
oups!

**Comment by RaananW** [comment]
it's ok,
nothing is broken.

**Comment by RaananW** [comment]
Will create another PR after making the final changes.

**Pull request merged**
