### PR TITLE
Improve viewer camera framing (and other small fixes)

### PR DESCRIPTION
**Pull request by ryantrem**
The main change here is to improve camera framing via:
1. Using the new `computeMaxExtents` helper from @bghgary to take into account animation. This significantly improves the framing for models with significant translation in animations. Note this also includes a small bug fix in `computeMaxExtents` where it did not handle the case of a mesh with no verts.
2. When models have animations, set the selected `AnimationGroup` to frame 0. This ensures it is within the camera framing computed for the model + animation.
3. Change the camera to looking down at a slight angle to the object.
4. Reduce the framing scalar from 1.2 to 1.1 to fit a bit better.

There are a couple other Viewer fixes included in this PR as well:
1. Remove the redundant `beginFrame` and `endFrame` calls. They are already called in `_renderLoop` and they mess up frame time calculations and break some behavior (like animating the camera back to its initial pose upon double click).
2. If an async operation (like loading an environment or model) was correctly started while the viewer was not disposed, but then the viewer is disposed while the async operation is still running, the async operation should be aborted and throw and abort error rather than a disposed error. A disposed error is indicative of a programming error, which this is not. We need this to be accurate for consumers who need to be able to tell the difference between an unexpected error and an expected error.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15618/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15618/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15618/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15618/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15618/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15618/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15618/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15618/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15618/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15618/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
