### PR TITLE
WebGPU: Sync with specification

### PR DESCRIPTION
**Pull request by Popov72**

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by RaananW** [comment]
Failed UMD build - https://dev.azure.com/babylonjs/ContinousIntegration/_build/results?buildId=34585&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=e553b5d8-21f0-59ad-51a3-60ad4a6f02e3

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15744/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15744/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15744/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15744/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15744/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15744/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15744/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15744/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15744/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15744/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
https://dev.azure.com/babylonjs/ContinousIntegration/_build/results?buildId=34592&view=results Done, merging

**Pull request merged**
