### PR TITLE
Make gulp task names more explicit

### PR DESCRIPTION
**Pull request by egnor**
Without this change, many "private" gulp task names (created by closure functions) had generic names like "shaders" or "importLint", even though the actual task is specific to a particular module (due to closure parameters):

```
[19:55:13] Finished 'postProcessesLibrary-importLint' after 13 ms
[19:55:13] Starting 'proceduralTexturesLibrary-importLint'...
[19:55:13] Starting 'shaders'...
[19:55:13] Finished 'shaders' after 10 ms
[19:55:13] Starting 'lint'...
[19:55:13] Finished 'lint' after 20 ms
[19:55:13] Finished 'proceduralTexturesLibrary-importLint' after 31 ms
[19:55:13] Starting 'loaders-importLint'...
[19:55:13] Starting 'shaders'...
[19:55:13] Finished 'shaders' after 2.67 ms
[19:55:13] Starting 'lint'...
[19:55:13] Finished 'lint' after 38 ms
[19:55:13] Finished 'loaders-importLint' after 41 ms
[19:55:13] Starting 'serializers-importLint'...
[19:55:13] Starting 'shaders'...
[19:55:13] Finished 'shaders' after 3.66 ms
[19:55:13] Starting 'lint'...
[19:55:13] Finished 'lint' after 15 ms
[19:55:13] Finished 'serializers-importLint' after 19 ms
[19:55:13] Starting 'gui-importLint'...
[19:55:13] Starting 'shaders'...
[19:55:13] Finished 'shaders' after 7.3 ms
[19:55:13] Starting 'lint'...
[19:55:13] Finished 'lint' after 46 ms
[19:55:13] Finished 'gui-importLint' after 54 ms
```

Probably to those very familiar with the build process it's clear what is nested within what, but I was finding it tricky when diagnosing a build failure that happened in something like "buildes6" without any elaboration. With this change, the task names are explicit:

```
[19:52:36] Starting 'postProcessesLibrary-importLint'...
[19:52:36] Starting 'postProcessesLibrary-importLint:shaders'...
[19:52:36] Finished 'postProcessesLibrary-importLint:shaders' after 4.6 ms
[19:52:36] Starting 'postProcessesLibrary-importLint:lint'...
[19:52:36] Finished 'postProcessesLibrary-importLint:lint' after 7.23 ms
[19:52:36] Finished 'postProcessesLibrary-importLint' after 13 ms
[19:52:36] Starting 'proceduralTexturesLibrary-importLint'...
[19:52:36] Starting 'proceduralTexturesLibrary-importLint:shaders'...
[19:52:36] Finished 'proceduralTexturesLibrary-importLint:shaders' after 9.1 ms
[19:52:36] Starting 'proceduralTexturesLibrary-importLint:lint'...
[19:52:36] Finished 'proceduralTexturesLibrary-importLint:lint' after 20 ms
[19:52:36] Finished 'proceduralTexturesLibrary-importLint' after 29 ms
[19:52:36] Starting 'loaders-importLint'...
[19:52:36] Starting 'loaders-importLint:shaders'...
[19:52:36] Finished 'loaders-importLint:shaders' after 2.93 ms
[19:52:36] Starting 'loaders-importLint:lint'...
[19:52:36] Finished 'loaders-importLint:lint' after 37 ms
[19:52:36] Finished 'loaders-importLint' after 40 ms
[19:52:36] Starting 'serializers-importLint'...
[19:52:36] Starting 'serializers-importLint:shaders'...
[19:52:36] Finished 'serializers-importLint:shaders' after 3.24 ms
[19:52:36] Starting 'serializers-importLint:lint'...
[19:52:36] Finished 'serializers-importLint:lint' after 15 ms
[19:52:36] Finished 'serializers-importLint' after 19 ms
[19:52:36] Starting 'gui-importLint'...
[19:52:36] Starting 'gui-importLint:shaders'...
[19:52:36] Finished 'gui-importLint:shaders' after 7.35 ms
[19:52:36] Starting 'gui-importLint:lint'...
[19:52:36] Finished 'gui-importLint:lint' after 40 ms
[19:52:36] Finished 'gui-importLint' after 47 ms
```

This made everything way more clear to me (and doesn't seem to add much complexity), but of course y'all might find it somewhat frivolous?

### CODE REVIEW

**Comment by deltakosh** [comment]
I like it but somehow it broke the compilation :)

**Comment by egnor** [comment]
Weird. Will investigate.

**Comment by egnor** [comment]
Should be fixed now, sorry about that!

**Comment by deltakosh** [comment]
Thanks a lot for your help!

**Pull request merged**
