### PR TITLE
Custom Material

### PR DESCRIPTION
**Pull request by NasimiAsl**

### CODE REVIEW

**Comment by sebavan** [comment]
looks good to me, could you remove the .js and .map from the pr, the files will be built in the dist/preview release/materialslibrary folder automatically.

**Comment by sebavan** [comment]
cool perfect, this will be up in the playground for you to play in a couple of hours.

**Comment by NasimiAsl** [comment]
this is a big changes for material  :)

**Comment by dad72** [comment]
Cool, I'm anxious to see examples of PG

**Comment by NasimiAsl** [comment]
i check PG and i don't see yet that come to PG babylon

**Comment by sebavan** [comment]
Yep that was only in the cdn, I have just added it for you in the pg

**Pull request merged**
