### PR TITLE
Fixed null callback issues

### PR DESCRIPTION
**Pull request by MackeyK24**
Fixed null callback for textures

### CODE REVIEW

**Comment by wyklion** [comment]
They'll tell you don't commit js file. :-)

**Comment by RaananW** [comment]
the elusive "they" are here!
as long as the .ts file is there, the occasional .js file is fine.

Now, a question - why is this needed? when is a null callback added?

**Comment by MackeyK24** [comment]
It is need when no callback is specified. Like when using the Unity Exporter to export a skybox. The unity export programmatically builds the skybox material and texture using C# in unity editor to create the .babylon file. When that .babylon scene file is loaded i get this error:

"TypeError: callback is not a function. (In 'callback()', 'callback' is null)"

When look at line of that is throwing the error:

texture.onLoadedCallbacks.forEach(function (callback) {
                        callback();
                    });

So simply added the checks:
                        if (callback) {
                            callback();
                        }

**Comment by sebavan** [comment]
Could you check what is happening there?

This probably highlights another issue during the export.

I would prefer a fix in the unity exporter cause it seems the issue is there.

**Comment by RaananW** [comment]
Exactly what I washed to say. This is a solution, but maybe we should find where a null callback is added and fix it

**Comment by deltakosh** [comment]
Agree with raanan and seb. This should never be null. We need to understand the root problem

**Comment by MackeyK24** [comment]
I don't know why creating the skybox in C# with unity explorer would cause that either. First there is NO CALLBACK in the context of the texture or material at the time we are programmatically creating the skybox in c# sharp. Here is the code i use to create SKYBOX in C#

        private void ConvertUnitySkyboxToBabylon(Camera camera, float progress)
        {
            // Skybox
            if ((camera.clearFlags & CameraClearFlags.Skybox) == CameraClearFlags.Skybox)
            {
                if (RenderSettings.skybox != null)
                {
					BabylonTexture skytex = null;
					if (RenderSettings.skybox.shader.name == "Skybox/Cubemap") {
						var cubeMap = RenderSettings.skybox.GetTexture("_Tex") as Cubemap;
						if (cubeMap != null) {
							skytex = new BabylonTexture();
							CopyTextureCube("sceneSkybox.hdr", cubeMap, skytex);
						}
					} else if (RenderSettings.skybox.shader.name == "Skybox/6 Sided") {
						var frontTexture = RenderSettings.skybox.GetTexture("_FrontTex") as Texture2D;
						var backTexture = RenderSettings.skybox.GetTexture("_BackTex") as Texture2D;
						var leftTexture = RenderSettings.skybox.GetTexture("_LeftTex") as Texture2D;
						var rightTexture = RenderSettings.skybox.GetTexture("_RightTex") as Texture2D;
						var upTexture = RenderSettings.skybox.GetTexture("_UpTex") as Texture2D;
						var downTexture = RenderSettings.skybox.GetTexture("_DownTex") as Texture2D;
						if (frontTexture != null && backTexture != null && leftTexture != null && rightTexture != null && upTexture != null && downTexture != null) {
							skytex = new BabylonTexture();
							skytex.isCube = true;
							skytex.name = "sceneSkybox";

							var frontTextureName = String.Format("{0}_pz.jpg", skytex.name);
							var frontTexturePath = Path.Combine(babylonScene.OutputPath, frontTextureName);
							CopyTextureCubeFace(frontTexturePath, frontTextureName, frontTexture);

							var backTextureName = String.Format("{0}_nz.jpg", skytex.name);
							var backTexturePath = Path.Combine(babylonScene.OutputPath, backTextureName);
							CopyTextureCubeFace(backTexturePath, backTextureName, backTexture);

							var leftTextureName = String.Format("{0}_px.jpg", skytex.name);
							var leftTexturePath = Path.Combine(babylonScene.OutputPath, leftTextureName);
							CopyTextureCubeFace(leftTexturePath, leftTextureName, leftTexture);

							var rightTextureName = String.Format("{0}_nx.jpg", skytex.name);
							var rightTexturePath = Path.Combine(babylonScene.OutputPath, rightTextureName);
							CopyTextureCubeFace(rightTexturePath, rightTextureName, rightTexture);

							var upTextureName = String.Format("{0}_py.jpg", skytex.name);
							var upTexturePath = Path.Combine(babylonScene.OutputPath, upTextureName);
							CopyTextureCubeFace(upTexturePath, upTextureName, upTexture);

							var downTextureName = String.Format("{0}_ny.jpg", skytex.name);
							var downTexturePath = Path.Combine(babylonScene.OutputPath, downTextureName);
							CopyTextureCubeFace(downTexturePath, downTexturePath, downTexture);
						}
					}
					if (skytex != null) {
						skytex.coordinatesMode = 5;
						skytex.level = RenderSettings.reflectionIntensity;

						var skybox = new UnityBabylonMesh();
						skybox.name = "sceneSkyboxMesh";
						skybox.id = Guid.NewGuid().ToString();
						skybox.indices = new[] { 0, 1, 2, 0, 2, 3, 4, 5, 6, 4, 6, 7, 8, 9, 10, 8, 10, 11, 12, 13, 14, 12, 14, 15, 16, 17, 18, 16, 18, 19, 20, 21, 22, 20, 22, 23 };
						skybox.positions = new[] { 50.0f, -50.0f, 50.0f, -50.0f, -50.0f, 50.0f, -50.0f, 50.0f, 50.0f, 50.0f, 50.0f, 50.0f, 50.0f, 50.0f, -50.0f, -50.0f, 50.0f, -50.0f, -50.0f, -50.0f, -50.0f, 50.0f, -50.0f, -50.0f, 50.0f, 50.0f, -50.0f, 50.0f, -50.0f, -50.0f, 50.0f, -50.0f, 50.0f, 50.0f, 50.0f, 50.0f, -50.0f, 50.0f, 50.0f, -50.0f, -50.0f, 50.0f, -50.0f, -50.0f, -50.0f, -50.0f, 50.0f, -50.0f, -50.0f, 50.0f, 50.0f, -50.0f, 50.0f, -50.0f, 50.0f, 50.0f, -50.0f, 50.0f, 50.0f, 50.0f, 50.0f, -50.0f, 50.0f, 50.0f, -50.0f, -50.0f, -50.0f, -50.0f, -50.0f, -50.0f, -50.0f, 50.0f };
						skybox.uvs = new[] { 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f };
						skybox.normals = new[] { 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 0.0f, 0.0f, -1.0f, 0, 0f };

						/*
						var skyboxMaterial = new UnityPBRMaterial() {
							name = "sceneSkyboxMaterial",
							id = Guid.NewGuid().ToString(),
							albedo = new[] { 1.0f, 1.0f, 1.0f, 1.0f },
							reflectivity = new[] { 1.0f, 1.0f, 1.0f },
							microSurface = 1.0f,
							directIntensity = 0.0f,
							specularIntensity = 0.0f,
							environmentIntensity = 1.0f
						};
						*/

						var skyboxMaterial = new UnityStandardMaterial() {
							name = "sceneSkyboxMaterial",
							id = Guid.NewGuid().ToString(),
							diffuse = new[] { 1.0f, 1.0f, 1.0f, 1.0f },
							specular = new[] { 1.0f, 1.0f, 1.0f },
						};

						skyboxMaterial.reflectionTexture = skytex;
						skyboxMaterial.backFaceCulling = false;
						skyboxMaterial.disableLighting = true;
						skybox.materialId = skyboxMaterial.id;
						skybox.infiniteDistance = true;
						skybox.renderingGroupId = 0;

						babylonScene.MeshesList.Add(skybox);
						babylonScene.MaterialsList.Add(skyboxMaterial);
						babylonScene.AddTextureCube("sceneSkyboxMaterial");
					}
                }
            }
        }


I added 6 side cube map support (Although this skis is used Shader/Cubemap)

Attach is the babylon file it produced

[Untitled.babylon.txt](https://github.com/BabylonJS/Babylon.js/files/560282/Untitled.babylon.txt)

**Comment by MackeyK24** [comment]
Attached whole scene folder to check out in sandbox
[Archive.zip](https://github.com/BabylonJS/Babylon.js/files/560283/Archive.zip)

**Comment by deltakosh** [comment]
Ok found the issue! thank you so much
I'll fix it

**Pull request closed without merging**
