### PR TITLE
zoom with estimated radius to avoid zooming to far

### PR DESCRIPTION
**Pull request by TrevorDev**
https://github.com/BabylonJS/Babylon.js/issues/6215

testPG: #DQ29UL

### CODE REVIEW

**Comment by deltakosh** [comment]
Pinging @MiiBond for validation

**Comment by MiiBond** [comment]
I just tested this out. It's much easier to use now!
However, now zooming in requires a lot more turns of the wheel than zooming out does. From our usability perspective, this is much better but it still feels like zooming in and out should ideally require the same amount of effort.

**Comment by MiiBond** [comment]
@deltakosh @TrevorDev 
I'm definitely seeing issues with this change when zooming in very quickly. The camera bounces back instead of forward.

https://www.babylonjs-playground.com/ts.html#WFAW5A#2

The problem seems to be that `estimatedTargetRadius` is allowed to go negative. A simple clamp might fix it.

**Comment by TrevorDev** [comment]
Sure, Ill try clamping it, see PR and let me know if it fixes it for you. (I cant seem to repro with my mouse)

**Comment by MiiBond** [comment]
@TrevorDev that solves it for me. Thanks!

**Pull request merged**
