### PR TITLE
Fix shader compile issue with non-float vertex buffers for native

### PR DESCRIPTION
**Pull request by bghgary**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15217/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15217/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15217/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15217/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15217/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15217/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15217/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15217/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15217/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15217/merge/testResults/webgpuplaywright/index.html

**Comment by bghgary** [comment]
> With these changes, replacing a non-float vertex buffer by another one won't work. So, this PG will fail:
> 
> https://playground.babylonjs.com/?webgpu#U1CZV3#46
> 
> It's probably not a common use case, but it's theoritically possible to do it (and it works in WebGL)...



> With these changes, replacing a non-float vertex buffer by another one won't work. So, this PG will fail:
> 
> https://playground.babylonjs.com/?webgpu#U1CZV3#46
> 
> It's probably not a common use case, but it's theoritically possible to do it (and it works in WebGL)...

@sebavan and I thought this might be the case, but we thought it wouldn't work with WebGPU either. How does it work with WebGPU?

**Comment by Popov72** [comment]
It's what `vertexBufferKindToType` is used for in the current code. It keeps track of the types of the vertex buffers created last for the pipeline context, and if the type of the current vertex buffer is different, it will trigger a re-creation.

You can check that https://playground.babylonjs.com/?webgpu#U1CZV3#46 currently works in WebGPU (as well as in WebGL).

**Comment by bghgary** [comment]
Hmm, @sebavan and I couldn't see how `vertexBufferKindToType` is being used in the current code and thus I removed the usage. Maybe we missed something. I will double check.

**Comment by bghgary** [comment]
I ran the PG with the current code and `checkNonFloatVertexBuffers` is only called once.

**Comment by Popov72** [comment]
`checkNonFloatVertexBuffers` is called two times in my testing:
image

(
I added a console.log at the start of `checkNonFloatVertexBuffers` in my local repo:
image
)

The first time right at start, because the default vertex buffer is created as float and we set a BYTE vertex buffer line 46. The second time, two seconds later, because we set an UNSIGNED_BYTE vbuffer (line 50). `checkNonFloatVertexBuffers` is not called a third time (when we set back the BYTE vbuffer) because there is some caching in WebGPU, and the pipeline created the first time is reused the third time.

**Comment by bghgary** [comment]
Weird, I don't know what I was testing before, but it was only hitting it once. Now, I see it getting hit twice.

**Comment by bghgary** [comment]
It appears this PG is not deterministic. If I stay on a breakpoint too long, it will only call `checkNonFloatVertexBuffers` once.

**Comment by Popov72** [comment]
Probably because the PG is driven by some `setTimeout`, and if you stay on a breakpoint longer than the timeout delay, the breakpoint won't trigger. But the current existing code works as expected and can handle the change of vbuffer type.

**Comment by bghgary** [comment]
I have console.logs also and they don't happen either when I stay on a breakpoint. Anyways, I'll just only use console.logs for now.

**Comment by bghgary** [comment]
After discussing with @sebavan, we decided to limit the scope of this change to native only for now. We will discuss what the proper fix is later.

**Comment by sebavan** [comment]
Yup as this will require a deeper change let s be sure the case happens before investing too much in and it unlocks the major mismatch case with gltf today

**Review by sebavan — APPROVED** [review]

**Pull request merged**
