### PR TITLE
Use getAbsolutePosition to ensure world matrix is up-to-date

### PR DESCRIPTION
**Pull request by bghgary**
https://forum.babylonjs.com/t/how-intersectsmesh-works

### CODE REVIEW

**Comment by BabylonJSGuide** [comment]
How big a breaking change might this cause?

**Comment by bghgary** [comment]
> How big a breaking change might this cause?

Hmm, fair question. I would hope no one is depending on these functions to use an incorrect world matrix. That seems very unlikely. @sebavan what do you think?

**Comment by sebavan** [comment]
I think none at all as well here, just fixing things :-)

**Comment by BabylonJSGuide** [comment]
OK just wanted to be sure :)

**Comment by sebavan** [comment]
I totally agree it is better to be safe here, you did well to check.

**Pull request merged**
