### PR TITLE
Adding callback on CubeTexture and a CubeTexture Loader Task

### PR DESCRIPTION
**Pull request by AGallouin**
Adding a CubeTexture loader task following the logic of the texture loader task

### CODE REVIEW

**Comment by deltakosh** [comment]
Seems great so far. But can you please just merge *.ts files?

**Comment by AGallouin** [comment]
The merge isn't automatic when I have no conflicts ?

**Comment by deltakosh** [comment]
Merges are not automatic :) I need to bless them (me or someone from the core team)

My ask was: Please update yoru PR to not merge .js files :)

**Comment by deltakosh** [comment]
Hum something went wrong as your PR contains no file now :)

**Comment by AGallouin** [comment]
That should be good now. Didn't knew if i needed to comit the d.ts file, cause it's a generated one, but still a ts. We will see.

**Comment by deltakosh** [comment]
That's fine:)
Just last ask: please credit yourself in the readme: https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/what's%20new.md

**Comment by AGallouin** [comment]
Thanks !

**Pull request merged**
