### PR TITLE
Create new EdgesRenderer for LineMeshes.

### PR DESCRIPTION
**Pull request by barteq100**
Normal EdgesRenderer was buggy because of unnecessary triangulation of lines. 

Easy way to see difference is to run this code on playground:
````
var createScene = function () {

    // This creates a basic Babylon Scene object (non-mesh)
    var scene = new BABYLON.Scene(engine);

    // This creates and positions a free camera (non-mesh)
    var camera = new BABYLON.FreeCamera("camera1", new BABYLON.Vector3(0, 5, -10), scene);

    // This targets the camera to scene origin
    camera.setTarget(BABYLON.Vector3.Zero());

    // This attaches the camera to the canvas
    camera.attachControl(canvas, true);

    // This creates a light, aiming 0,1,0 - to the sky (non-mesh)
    var light = new BABYLON.HemisphericLight("light1", new BABYLON.Vector3(0, 1, 0), scene);

    // Default intensity is 1. Let's dim the light a small amount
    light.intensity = 0.7;

     var line = new BABYLON.MeshBuilder.CreateLines('line', {points: [
        new BABYLON.Vector3(1,0,7),
        new BABYLON.Vector3(2, 0 ,7),
        new BABYLON.Vector3(4,0,3)
    ]}, scene);

    line.enableEdgesRendering();

    return scene;

};
```

### CODE REVIEW

**Comment by sebavan** [comment]
Hello, and thanks for the pull request. 

It seems like a few javadoc documentation are missing on the new API:
[10:53:44] Missing text for parameter generateEdgesLines (id: 32765) of constructor (id: 32760) babylon.d.ts:28757
[10:53:44] Missing text for Class : LineEdgesRenderer (id: 32812) babylon.d.ts:28895

**Comment by barteq100** [comment]
should I just make javaDoc comments in .ts files?

**Comment by sebavan** [comment]
yup but I am sorry I said Javadoc... :-( , my bad.

We are using Typedoc to generate our api doc so that our documentation should follow the following standards:

http://doc.babylonjs.com/how_to/contribute_to_api

Do you mind adapting it ?

A second question is the work you are adding on line mesh is great. I am still wondering wether it is an issue with the default edge renderer and what in line mesh is creating the issue ?

**Comment by barteq100** [comment]
Sure I will adapt. 

And yes it was a problem with a standard edges renderer. It basicaly tried to go through 3 vertices for a line while there were 3 so it iterated past the array getting Vector Zero as a last vertex per triangle.

**Comment by barteq100** [comment]
When you will have some time please look at the docs I mad and tell me what should I change.

**Comment by sebavan** [comment]
looks good, I ll try to merge it in the afternoon ! 

Thanks a lot.

**Comment by sebavan** [comment]
Oh no, just noticed, could you remove the dist/preview release/babylon.d.ts from the PR ?

I promise it is the last comment I have, thx

**Comment by sebavan** [comment]
Also the EdgesRenderer is missing a constructor Comment which fails the build.

I ll merge as soon as the d.ts is removed from the PR and the comment has been put in the constructor.

**Comment by sebavan** [comment]
I took the liberty of fixing the left over issues and merged on master in https://github.com/BabylonJS/Babylon.js/pull/4920

Thanks for your contribution !

**Comment by barteq100** [comment]
Thank you for merging and fixing issues. I had to urgently leave so I didn't see your last request

**Comment by sebavan** [comment]
np

**Pull request merged**
