### PR TITLE
FreeCameraMouseInput: Reset Active pointerId when detaching controls

### PR DESCRIPTION
**Pull request by PolygonalSun**
A user in the forum found an issue where the camera controls stopped working after an animation started.  It was determined the issue was caused by the controls being detached before the `pointerup` event was handled.  A line was added to make sure the the tracked active pointerid was being reset when the controls were no longer active so that input could begin to be received again.

A test has also been added to check for this scenario

Forum Link: https://forum.babylonjs.com/t/mesh-actionmanager-camera-control-bug/42292

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by RaananW — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14065/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14065/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14065/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14065/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14065/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14065/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14065/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14065/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Comment by sebavan** [comment]
This is strange that it does not break any tests, should we add one ?

**Comment by PolygonalSun** [comment]
> This is strange that it does not break any tests, should we add one ?

Probably a good idea, at least to be safe.

**Pull request merged**
