### PR TITLE
Fix memory leak in MeshoptCompression

### PR DESCRIPTION
**Pull request by OrigamiDev-Pete**
As discussed in https://forum.babylonjs.com/t/meshoptdecoder-memory-leak/49696

By using web workers to decode the buffer we can terminate the web worker which releases the wasm heap. In the future, `memory.discard` may be a better way of solving this, but this API is not available yet.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14995/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14995/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14995/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14995/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14995/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14995/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14995/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14995/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14995/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14995/merge/testResults/webgpuplaywright/index.html

**Review by RaananW — APPROVED** [review]
Waiting for @bghgary for a final approval

**Review by bghgary — APPROVED** [review]
LGTM

**Comment by zeux** [comment]
I really would not recommend doing this for every call... this results in inefficient resource utilization as the workers are continuously created and destroyed, and doesn't improve peak memory consumption. The correct pattern should include calling useWorkers(0) at some point *after* all scenes have been loaded (in a streaming scenario you probably never want to do this as you are constantly going to decode buffers anyway.

My understanding fwiw is that KTX2 decoding runs into the exact same problem, and a more centralized solution might be valuable in context of Babylon.JS (e.g. a single app-level hook that can be called when the loading is finished, or at least "temporarily finished", and resources can be relinquished)

**Comment by RaananW** [comment]
KTX2 is using our own implementation or a workerpool, that maintains a worker in memory for a certain amount of time. if a worker is idle after the predefined idle time it deconstructs.
If you have a nice way of solving the issue here, we will be very happy to review it!

**Comment by bghgary** [comment]
For reference, this is the code @RaananW is referring to:
https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Misc/workerPool.ts#L89-L156

This is being used by Draco and KTX2 already. We can probably also use it for Meshopt?

**Pull request merged**
