### PR TITLE
Try fix build

### PR DESCRIPTION
**Pull request by sebavan**
Let s see if it builds, it should as the dependency is even not used anymore.

### CODE REVIEW

**Comment by sebavan** [comment]
Looks like it might be alive.... ALIVE :-) !!!!

**Comment by sebavan** [comment]
@deltakosh this is ready to go :-) This will unlock latest npm versions to install locally

**Comment by deltakosh** [comment]
Too soon my dear :)

**Comment by sebavan** [comment]
This should be the last !!!! Cross your fingers for me :-)

**Comment by sebavan** [comment]
@deltakosh this is ready to go :-) This will unlock latest npm versions to install locally

IT IS ALL GREEN

**Pull request merged**
