### PR TITLE
Scene Manager: V5.0.0-A60.1X9

### PR DESCRIPTION
**Pull request by MackeyK24**
Babylon Toolkit Updates And Fixes

### CODE REVIEW

**Comment by sebavan** [comment]
@MackeyK24 it seems there is a conflict

**Comment by MackeyK24** [comment]
Crap, how do i resolve this... I tried just updating the latest babylon.manager.js (A48.6X9)

I had a bit of regression with some shader stuff and the new BABYLON.RegisterClass stuff

**Comment by sebavan** [comment]
Fixed it for you nw

**Comment by MackeyK24** [comment]
Thank you Sebastian :)

**Pull request merged**
