### PR TITLE
Convention patch by adding RotationAlphaBetaGamma to RotationYawPitchRol...

### PR DESCRIPTION
**Pull request by MavenRain**
Per request of David Catuhe, RotationAlphaBetaGamma added to solve convention fix, instead of replacing RotationYawPitchRoll

### CODE REVIEW

**Comment by deltakosh** [comment]
I'll merge manually

**Comment by MavenRain** [comment]
I forgot to change from RotationYawPitchRoll to RotationAlphaBetaGamma in computerWorldMatrix.  Did you catch that?






Sent from Windows Mail





From: David Catuhe
Sent: ‎Wednesday‎, ‎February‎ ‎11‎, ‎2015 ‎5‎:‎16‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





I'll merge manually

**Comment by deltakosh** [comment]
Yes I'm currently testing it:)

**Comment by deltakosh** [comment]
This does not work for scene "Heart" for instance

**Comment by MavenRain** [comment]
What happens in “Heart”?






Sent from Windows Mail





From: David Catuhe
Sent: ‎Wednesday‎, ‎February‎ ‎11‎, ‎2015 ‎7‎:‎00‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





This does not work for scene "Heart" for instance

**Comment by deltakosh** [comment]
Wrong rotation :(

**Comment by MavenRain** [comment]
I’ll look at Heart after hackathon.






Sent from Windows Mail





From: David Catuhe
Sent: ‎Wednesday‎, ‎February‎ ‎11‎, ‎2015 ‎7‎:‎35‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





Wrong rotation :(

**Pull request closed without merging**
