### PR TITLE
setSnapshotRenderingMode should have no effect on WebGL engine

### PR DESCRIPTION
**Pull request by carolhmj**
Playground example: https://playground.babylonjs.com/?#SYQW69#951

### CODE REVIEW

**Comment by Popov72** [comment]
The problem is not in Babylon but in the PG, line 76. It should be:

```javascript
if (engine.snapshotRendering && engine.snapshotRenderingMode === BABYLON.Constants.SNAPSHOTRENDERING_FAST) {
```

Your fix would not fix the PG if `SNAPSHOTRENDERING_STANDARD` was tested instead of `SNAPSHOTRENDERING_FAST`.

**Comment by sebavan** [comment]
@Popov72 amazing catch !!! :-) should we still do the noop as well then ?

**Comment by Popov72** [comment]
No, I think we should still udpate the property as not doing anything is not a no-op: the value is still `SNAPSHOTRENDERING_STANDARD` which is a valid mode (we don't have a `SNAPSHOTRENDERING_NOSNAPSHOT` value).

**Comment by carolhmj** [comment]
Shall we close the PR then?

**Comment by sebavan** [comment]
I think you could force it to always be standard independently of the mode if I understand @Popov72 correctly ?

**Comment by Popov72** [comment]
Yes you could do that but I'm not sure it's better than doing nothing :)

**Comment by sebavan** [comment]
ok so let s close the PR then @Popov72 ???

**Pull request closed without merging**
