### PR TITLE
FrameGraph: add glow layer block and task

### PR DESCRIPTION
**Pull request by Popov72**
I'm not really happy with the way I've tried to factorize the effect layer code so that it can be used for both the frame graph and the existing code path, so here's a bit of context on how I've implemented it (and I'm open to feedback on how to improve things!).

I've created a `ThinEffectLayer` and a `ThinGlowLayer`, moving all the code from `EffectLayer` and `GlowLayer` that doesn't deal with texture management. The texture management code remains in the latter classes, and in the case of the frame graph, is managed by the framework + the `FrameGraphGlowLayerTask` class.

The `GlowLayer` class is implemented through the `ThinGlowLayer` class (by composition, not inheritance, since it already inherits from the `EffectLayer` class). This means that `EffectLayer` now takes a `ThinEffectLayer` pointer in its constructor, and if it's not provided (as in the case of the highlight layer, which I haven't yet moved to the new architecture, or from existing user code), creates a `ThinEffectLayer` internally.

When a `ThinEffectLayer` pointer is not passed to the `EffectLayer` constructor, this means that part of the code (all the “abstract” methods) is implemented by the class that inherits from `EffectLayer`: this is why the `EffectLayer` constructor binds these methods to the corresponding methods of the `ThinEffectLayer` it has created. When a pointer is passed to the constructor, this means that the methods are implemented in `ThinXXXLayer` (`ThinGlowLayer` for the glow layer), and the implementation of `EffectLayer`'s abstract methods in `XXXLayer` is simply transferred to `ThinXXXLayer` (see `ThinGlowLayer` implementation).

In this way, there is no duplication of code: everything (except the texture management code) is implemented in `ThinEffectLayer` and `ThinGlowLayer` and reused in `EffectLayer`, `GlowLayer` and `FrameGraphGlowLayerTask` (the latter class uses `ThinGlowLayer` directly).

Other changes in this PR:
* I've moved the management of the "dependencies" input to the `NodeRenderGraphBlock`, to centralize the code.
* I've added a `dependencies` property to `FrameGraphTask` and removed `useTexture` from `FrameGraphRenderPass`. It makes more sense this way, and is easier to manage.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
You have made possible changes to one or more graph tools. To test the snapshots:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/TOOLS/refs/pull/16026/merge/nodeEditor/
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/TOOLS/refs/pull/16026/merge/nodeGeometryEditor/
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/TOOLS/refs/pull/16026/merge/nodeRenderGraphEditor/
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/TOOLS/refs/pull/16026/merge/guiEditor/

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/16026/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/16026/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/16026/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/16026/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/16026/merge
https://gui.babylonjs.com/?snapshot=refs/pull/16026/merge
https://nme.babylonjs.com/?snapshot=refs/pull/16026/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/16026/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/16026/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/16026/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
