### PR TITLE
-fix for Bone.getDirection when mesh is scaled -fix for scaling a bon…

### PR DESCRIPTION
**Pull request by abow**
…e before a bone is rotated and while animation is playing

### CODE REVIEW

**Comment by abow** [comment]
I might have a better fix for the second issue.  It looks like it only happens with Bone.setRotationWithMatrix.  I'm going to do some more testing.

**Comment by deltakosh** [comment]
sounds good

**Comment by abow** [comment]
I was able to replicate the issue with the other rotation functions.  The current commit is the only way I could fix the issue.

**Comment by abow** [comment]
I think I figured out a better fix.  I'll commit it tonight.

**Comment by deltakosh** [comment]
lol ok!

**Pull request merged**
