### PR TITLE
Variable Bone Influencers

### PR DESCRIPTION
**Pull request by Palmer-JC**
Fully implemented on BJS side.  Limited testing done, but this is alpha.
Not tested:
- Any shader other than default
- CPU fallback (added message though)
- FileLoader.  Probably better way to expand, but not standard TS not
understood.

### CODE REVIEW

**Comment by Palmer-JC** [comment]
One of the reasons I committed was I thought it was getting too long to check out 19 files.  Guess not quick enough.

**Comment by deltakosh** [comment]
Hello I'm not able to merge this one (Conflicts)

**Comment by Palmer-JC** [comment]
Ok.  I already committed to repository.  So I throw this repo away.  Go back to my Friday EOD repo.  Put these 19 files to one side & do a pull, then put them back.

But which files do I need to edit back?  GitHub just says conflicts, but not which files.

**Comment by Palmer-JC** [comment]
Let Eclispe figure out what is out of date for me.
checkout conflicts _122

**Pull request closed without merging**
