### PR TITLE
add samplingmode option to effectlayer

### PR DESCRIPTION
**Pull request by Hypnosss**
Related: https://forum.babylonjs.com/t/how-to-change-sampling-mode-when-generating-down-scaled-glowlayers-blurtexture/32096/7
Not really familiar with ts so please for give me if it not a gental code.

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by deltakosh** [comment]
Just an issue with formatting and we are good to go :) (you can run npm run format:fix to auto fix it :))

btw @RaananW : could we simply run it on each PR? Is that a bad idea?

**Review by Popov72 — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Comment by RaananW** [comment]
> Just an issue with formatting and we are good to go :) (you can run npm run format:fix to auto fix it :))
> 
> btw @RaananW : could we simply run it on each PR? Is that a bad idea?

There are a few catches when discussing commiting to someone else's  PR. I would rather not do that.
I think that, in general, it will be better to only do it on master after merging a pull request. So allow merging unformatted, and format after merge. This has its downsides as well.
In any case - we can gladly discuss this :-)

**Review by sebavan — COMMENTED** [review]
Are we sure we want to change the sampling mode for blur ??? it seems it won t achieve anything useful ? I am wondering if this is indeed necessary ?

**Comment by Hypnosss** [comment]
> @Hypnosss what do you think ? as reading the forum thread it looks like this is not necessary as well ?

It is useful when anyone wants to do the same thing. However, I'm not sure if it is a request that common enough to put into the source code, and if it is a good way to archive the request.

**Comment by sebavan** [comment]
so let me close it for now, and we ll reopen if anyone asks for it a second time :-)

**Pull request closed without merging**
