### PR TITLE
Fix #15786

### LINKED ISSUE #15786: HTMLMesh not working if there's a VolumetricLightScatteringPostProcess on the scene?
I've tried to add a volumetric light to my scene, and it seems to break htmlmeshes.

Basically, if I add this line of code, the html meshes stop displaying any content:
var godrays = new VolumetricLightScatteringPostProcess('godrays', 1.0, this.camera, undefined, 100, Texture.BILINEAR_SAMPLINGMODE, this.engine, false);

If I remove this line, everything works as expected. Any ideas what might be the cause?

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15787/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15787/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15787/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15787/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15787/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15787/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15787/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15787/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15787/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15787/merge/testResults/webgl2playwright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
