### PR TITLE
Fix TargetCamera rotation issue

### PR DESCRIPTION
**Pull request by BlakeOne**
This patches fixes an issue demonstrated in the below playground where the camera's rotation is misbehaving.

Playground: https://playground.babylonjs.com/#F68Z6N#4
Forum: https://forum.babylonjs.com/t/weird-behavior-with-universalcamera-and-rotation-property/25116/25

### CODE REVIEW

**Comment by BlakeOne** [comment]
Previously _rotateUpVectorWithCameraRotationMatrix was called only when the z property of the camera's rotation vector changed, but with this patch it's called if any property of the rotation vector changed (when quaternion isn't set).

**Comment by deltakosh** [comment]
Yep this fix was suspicious :) Thanks for your appreciated help :)

**Comment by BlakeOne** [comment]
Happy to help. :) This one has me vexed because it seems that theoretically, if it works when the user converts the euler vector to quaternion manually  then it should be able to also work when BJS does that conversion for us, so I'll keep at it. :)

PS I updated the fix and got one of the validation fails corrected, the only one that seems different to me on visual inspection. :)

**Comment by deltakosh** [comment]
Good job! Thanks a lot

**Review by deltakosh — APPROVED** [review]

**Comment by 0x53A** [comment]
Thank you for fixing this!

I can see that it was merged 8 days ago, and ``5.0.0-alpha.61`` was released 4 days ago, should this already be deployed to the playground?

I'm asking because on my system (Windows 10 x64 + Edge-Chrome v95.0.1020.53), it's still wrong:

babylon-5-a61

**Comment by sebavan** [comment]
It was addressing only one part and Blake on the forum is sill looking into the others with @PolygonalSun

**Pull request merged**
