### PR TITLE
Improve buffer

### PR DESCRIPTION
**Pull request by ottoville**
This is my second proposal for buffer creation and updating. It uses the "getMappedRange" method for chunks, avoiding of waiting any promise caused by buffer mapping.

### CODE REVIEW

**Comment by sebavan** [comment]
Does not this result in exactly the same behaviour ? I am wondering what it improves in the end ?

Write buffer is probably doing the same internally natively so as long as we do not do the full rewrite by reusing a single large buffer with async up and down I would prefer to not change it to this except if there is any advantages.

It actually seems more heavy by relying on intermediate buffers and so on. 

The only annoying part we still have is the loop to upload due to a left over bug in chrome windows. Actually, there is no max size defined in the spec.

**Comment by deltakosh** [comment]
Up?

**Comment by sebavan** [comment]
@ottoville ?

**Comment by deltakosh** [comment]
Closing for now. Please reopen at will :)

**Comment by ottoville** [comment]
You are right. One way to make it more performt would be to create a constant staging buffer and feed modified data throug the staging buffer. The constant staging buffer is suitable for uniform buffers that are always same size and do change every frame, such as the scene ubo.

**Pull request closed without merging**
