### PR TITLE
Fix non deterministic test

### PR DESCRIPTION
**Pull request by noname0310**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15493/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15493/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15493/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15493/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15493/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15493/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15493/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15493/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15493/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15493/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by sebavan** [comment]
the last one seems to have failed @noname0310 as you can see in the link above

**Comment by noname0310** [comment]
I'm outside right now, so it'll take some time to check

**Comment by noname0310** [comment]
I can't reproduce the webgl1 test failure on my machine. Can you take a look? @sebavan 

here is the pg #1LF9GK#3

**Pull request merged**
