### PR TITLE
Profiles motion controller and the input repository

### PR DESCRIPTION
**Pull request by RaananW**
This PR integrates the motion controller library available at https://github.com/immersive-web/webxr-input-profiles/

if enabled (default is true), profiles will be loaded from the repository and will be used when a user enters XR and has a supported controller. It includes meshes and movement definitions of the elements of the controller (buttons, triggers, etc').

Also including a small extension of LoadFileAsync so that returned values can be string instead of ArrayBuffer.

### CODE REVIEW

**Comment by deltakosh** [comment]
You are on fire ;D

**Comment by deltakosh** [comment]
Still draft?

**Comment by RaananW** [comment]
issue(s) resolved, ready for review

**Comment by deltakosh** [comment]
Do you  mind creating a tiny demo we could share on twitter?

**Comment by RaananW** [comment]
This will work with any XR demo. Every time you load a controller. I have updated my goal keeper trainer to work with it:

https://playground.babylonjs.com/#PPM311#44

**Comment by RaananW** [comment]
But it is not yet available in the playground

**Pull request merged**
