### PR TITLE
Fixed the display of material on the water

### PR DESCRIPTION
**Pull request by dad72**
Fixed the display of material on the water in the case of the use of multiple camera.
I just add in the signature of the constructor the possibility to choose the camera to use.

I guess that's enough.

### CODE REVIEW

**Comment by deltakosh** [comment]
ping @julien-moreau

**Comment by julien-moreau** [comment]
Thanks for PR !
My question is : when it's time to render for a given camera, how do I get the current camera and check if I'm rendering with multiple camera ?
This would allow us to bypass the camera in constructor and prevent scene.activeCamera when it's null

**Comment by dad72** [comment]
Would you do it?
I'll close my PR because it is not appropriate and I do not see how to do it otherwise.
I'm too null to PR here. I will no longer do.

**Comment by dad72** [comment]
Oh and what I had was not working, so it was probably not enough. I just test what I had done.

I guess I should not have tried to do, I do not master the subject. like what, everyone can not contribute.

**Pull request closed without merging**
