### PR TITLE
KTXDecoder: Update and add new universal transcoders

### LINKED ISSUE #12002: Upgrade to v0.2.0 of Basis-Universal-Transcoders to decode KTX
See https://github.com/KhronosGroup/Basis-Universal-Transcoders/pull/19. Note the breaking changes. Doing this will make it easier to upgrade in the future when we can replace msc_transcoders completely.

### PR DESCRIPTION
**Pull request by Popov72**
Fixes #12002

### CODE REVIEW

**Review by sebavan — APPROVED** [review]
LGTM but I know nothing regarding this area so lets wait on @bghgary review :-)

**Review by RaananW — APPROVED** [review]
My approval - Just for the changes for the public server :-)

The rest if for @bghgary

**Comment by bghgary** [comment]
Are the new WASM files compatible with old code? Do we need to host a second version like [we did for the MSC transcoders](https://github.com/BabylonJS/Babylon.js/pull/12662)?

**Comment by Popov72** [comment]
No, the new WASM files (at least the RGBA transcoders) are not compatible with the old code. I'm going to rename them.

**Review by bghgary — APPROVED** [review]

**Pull request merged**
