### PR TITLE
Allow testing file-size step with chunks

### PR DESCRIPTION
**Pull request by RaananW**
The current implementation of the file-size test doesn't take chunks into account.

This PR adds the ability to generate a main file (the initial references) and an async part (all async-loaded dependencies). The main file is the one that will be tested. the async-size can grow with time, and it is expected that the main size will decrease with time the more async will grow.

This PR also adds the ability to define the flags for testing these packages as part of the repository. For example, to increase the error threshold, edit the file `flags.json` in `./.build/` (which is empty at the momoent) as set it to:

```javascript
{
    "errorThreshold": 1.2
}
```

This will allow a threshold of 20% instead of the default 10%.

To add another test case, simply add a new .ts file in the ./src/ folder of /packages/tools/tests
The initial fileSize will be set but not inspected.

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15589/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15589/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15589/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15589/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15589/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15589/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15589/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15589/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15589/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15589/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
required for https://github.com/BabylonJS/Babylon.js/pull/15579

**Pull request merged**
