### PR TITLE
Fix IBL Shadows async issue during effect creation

### PR DESCRIPTION
**Pull request by MiiBond**
We were hitting this in macOS only but it looks like it could potentially happen anywhere. The effects were potentially being created and applied before the importance sampling pipeline was ready.

I also changed the default shadow opacity to 0.75 to help with the over-darkening issue of the shadows. This is what we use by default in our Substance 3D apps.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by Popov72 — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15535/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15535/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15535/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15535/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15535/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15535/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15535/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15535/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15535/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Comment by sebavan** [comment]
@MiiBond looks like you might need to update the reference image for this one.

**Pull request merged**
