### PR TITLE
Feature.options parameter on create xxx methods

### PR DESCRIPTION
**Pull request by jbousquie**
CreateCylinder : 
fixed the topDiameter valued to zero case
fixed the lazy evaluation on sideOrientation
re-made the _subdivisions_ parameter optional

### CODE REVIEW

**Comment by jbousquie** [comment]
sorry for this chaotic PR but only 2 files were updated actually

**Comment by RaananW** [comment]
Hi Jerome,
The pr has conflicts, please first resolve them

**Comment by jbousquie** [comment]
no idea how to do this...
there aren't any conflicts on my local repo :-(

**Comment by deltakosh** [comment]
I confirm I cannot merge due to conflicts

**Comment by RaananW** [comment]
You will need to merge the remote master branch into your local branch, resolve the conflicts and commit the updates. Pm me if you need any help.

**Comment by jbousquie** [comment]
Pm ... on the forum
since I don't even know if we can PM in github

**Comment by RaananW** [comment]
Wrote you back. The problem is probably pr number 706, which is the same as the last commit in this pr.

**Comment by deltakosh** [comment]
No worry I merged it manually

**Comment by jbousquie** [comment]
Thank you guys

I don't know how I went to the point to get twice the same PR...
Git mysteries ...to me

2015-09-28 18:18 GMT+02:00 David Catuhe <notifications@github.com>:

**Pull request closed without merging**
