### PR TITLE
Fix effect dispose memory leak

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Review by RaananW — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by AmoebaChant — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15294/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15294/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15294/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15294/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15294/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15294/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15294/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15294/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15294/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15294/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
CI run for this PR - https://dev.azure.com/babylonjs/ContinousIntegration/_build/results?buildId=32478&view=results

**Pull request merged**
