### PR TITLE
created Ray.attachToMesh, Ray.detachFromMesh, Ray.dispose, and fixed …

### PR DESCRIPTION
**Pull request by abow**
…issue with Ray.show when ray doesn't have a length

http://www.babylonjs-playground.com/#ZHDBJ#21

### CODE REVIEW

**Comment by abow** [comment]
http://www.babylonjs-playground.com/#ZHDBJ#22

**Comment by RaananW** [comment]
Just an opinion, but:

Ray is a mathematical concept (at least until now), that was used for culling (hence the place where it is stored). I don't think a render function, dispose, mesh attachment, belongs in the Ray class (maybe a new RayMesh class in the mesh directory).  I haven't followed all changes, so I am not sure when the ray received the render function, but before extending this stand-alone class (that had no dependencies apart from math until now) I think we should consider if it is the right place.

**Comment by abow** [comment]
How about I move the show functionality to a RayViewer class and the attachToMesh to Mesh.attachRay?

**Comment by abow** [comment]
or instead of AbstractMesh.attachRay, a RayHelper class with attachRayToMesh function?

**Comment by RaananW** [comment]
I think the AbstractMesh class is large enough :)

Why not add an attachToMesh function to the ray(viewer) class? Keep the dependencies (of AbstractMesh) in control?

I like the idea of a RayViewer, I think it is better than adding it to the ray class. For me it is the same difference of Plane (Mesh) and Plane (Math). 
But I would wait for other to comment, maybe there is a much better idea I am missing :smile:

**Comment by abow** [comment]
Did you see my comment about RayHelper?  I'm liking that idea.

**Comment by RaananW** [comment]
Yeah, I like the idea, I just think that a general user won't find this helper class, so they will never know it exists. 
Or, did you mean there is no RayViewer, there is only a RayHelper class? then it is all the same. Just a different name.

**Comment by abow** [comment]
> then it is all the same. Just a different name.

Right

**Comment by abow** [comment]
http://www.babylonjs-playground.com/#ZHDBJ#26

**Pull request merged**
