### PR TITLE
Allow Draco in NullEngine on node

### PR DESCRIPTION
**Pull request by RaananW**
After these changes it will be possible to use Draco in Node environment using the following code:

```javascript
const Draco = require("./draco_decoder_gltf.js");
const wasm = fs.readFileSync("./draco_decoder_gltf.wasm");

BABYLON.DracoCompression.Configuration.decoder.wasmBinary = wasm;
BABYLON.DracoCompression.Configuration.decoder.jsModule = Draco;
```

Dependencies are not included in the UMD version, and node doesn't fully support ESM, so it will still be required to download the resources once from our CDN and keep them locally on the project directory. A different approach could be to install @babylonjs/core and just require the module and wasm from the assets directory.

This PR also makes it possible to easily override the worker pool configuration option, to allow a more streamlined way of using the decompressor. Setting the static workerPool will avoid creating your own instance of the DracoCompression class:

```javascript
// index.js

import wasm from "@babylonjs/dependencies/draco/draco_decoder_gltf.wasm?arraybuffer"; // also works from "draco3dgltf" package
import { AutoReleaseWorkerPool } from "@babylonjs/core/Misc/workerPool.js";
import { DracoCompression } from "@babylonjs/core/Meshes/Compression/dracoCompression.js";
import { initializeWebWorker } from "@babylonjs/core/Meshes/Compression/dracoCompressionWorker.js";
import { Tools } from "@babylonjs/core/Misc/tools.js";
import { VertexBuffer } from "@babylonjs/core/Meshes/buffer.js";

const workerPool = new AutoReleaseWorkerPool(4, () => {
  const worker = new Worker(new URL("./worker.js", import.meta.url), {
    type: "module",
  });
  return initializeWebWorker(worker, wasm);
});

DracoCompression.Configuration.decoder.workerPool = workerPool;

// worker.js
import { workerFunction } from "@babylonjs/core/Meshes/Compression/dracoCompressionWorker.js";
import "@babylonjs/dependencies/draco/draco_decoder_gltf.js";

workerFunction();
```

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14887/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14887/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14887/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14887/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14887/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14887/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14887/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14887/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14887/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14887/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — COMMENTED** [review]
LGTM, can we add a unit test to validate the node integration ?

**Comment by RaananW** [comment]
> LGTM, can we add a unit test to validate the node integration ?

Will be a bit more than a unit test, as there are two components needed (core and loaders). let me think of something

**Comment by sebavan** [comment]
Np feel free to merge this one first

**Review by sebavan — APPROVED** [review]

**Pull request merged**
