### PR TITLE
Framebuffer re-use WIP

### PR DESCRIPTION
**Pull request by grimdeathr**
https://github.com/BitReelCo/BJS-PR-Bounty-Pool/issues/4

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13492/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by grimdeathr** [comment]
I don't get why my builds are failing. Seem to work earlier. Job description on CI is unclear..

**Comment by sebavan** [comment]
Every imports should be relative and complete (I mean to the file itself) like import { Engine } from "core/Engines/engine"; should be import { Engine } from "../Engines/engine"; maybe with more ../ depending on the hierarchy.

The formatting / linting should be according the rules in the repo (there are npm tasks to help fixing them)

Comments (in ts doc style) should be added.

**Comment by Popov72** [comment]
Let us know when you have validated all your code and the PR is ready for review.

General comments:
* `onBeforeTransparentRendering` already exists in the `RenderingGroup` class. Be sure to call the existing callback in your own callback, in case `onBeforeTransparentRendering` is not undefined.
* The standard and PBR materials must be updated to the default refraction texture of the scene (as is done for the env texture).
* The purpose of the PR is to copy the existing data from the framebuffer to the RTT, not to render the scene in the RTT.
* We don't want to recreate a new render target texture every time, this should be a parameter we pass instead.
* there is also WebGPU support to add
* As @sebavan said, you need to format and document the code according to our rules and you also need to fix the imports.

**Comment by sebavan** [comment]
@grimdeathr , you also need to add a test, you can use the code you are using to validate your PR as I wonder how it could work in the current state.

I will actually move it to draft as it is not ready to be reviewed.

**Comment by grimdeathr** [comment]
Thanks @sebavan @Popov72 for the feedback. Appreciate it.

This is supposed to be a draft yes, I originally intended to PR to my own fork but ended up here. I will move to review when ready fully.

**Comment by sebavan** [comment]
@grimdeathr  I will close the PR for now to prevent other ppl to spend time on early review. I let you reopen it once ready.

This commit https://github.com/BabylonJS/Babylon.js/pull/13492/commits/85e212cbf4504747f7a1100abee2fb37129aa7f9 is not the right approach, you need to copy the GPU content of the texture not the CPU references to it.

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13492/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13492/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by grimdeathr** [comment]
So using engine._currentFramebuffer; is wrong? @Popov72 

Theres no early review but I will be asking a bunch of questions..

**Comment by sebavan** [comment]
_currentFramebuffer is a cached value of the currently bound frameBuffer and can not be assigned as you do to a texture. You cast it to assign it to a texture (not making a copy but swapping it) by passing important type checking which was probably letting you know of the error.

As @Popov72 mentioned, the purpose of the PR is to copy the existing data from the framebuffer to the RTT, not to render the scene in the RTT.

Basically, copy the **GPU content** of the current frame buffer inside of the RTT **GPU content**. readPixels won t be better as it is highly inefficient and will need to copy the data from GPU to CPU and then back to GPU. You want to do the copy GPU side. 

The bounty is not necessarily an easy one if you never developed with Babylon or WebGL in the past. It would be great if you can show us a working Draft we would grow from.

**Comment by grimdeathr** [comment]
Thanks for the detailed response.

I will continue with this in my fork. I've developed extensively with BabylonJS and WebGL, albeit mostly working on games and experiences.

I will update the story on the original bounty issue.

**Pull request closed without merging**
