### PR TITLE
Fix #15397

### LINKED ISSUE #15397: Enable forcing a size on svg conversion to texture in DOM
When we load an svg as a texture we send it to the DOM to generate the rasterized pixel array. It is created at screen resolution at the size of the original svg file. Ideally, since it is an svg, we would be able to force a size to be rasterized at to take advantage of the vector graphic format. In the example below, I created the Babylon logo as a 1cm file and saved as an svg. I then imported as a texture and assigned it to a 2m box as the diffuse texture. Obviously, the resolution is too low to render without pixelation. 

I can see two options that would be great to cover. 
- Forcing a size as a flag on load of the svg
- Allowing the user to manually re-sample the svg at a new size at some point. I don't think this should be automatic or dynamic, just allowing the user to resample without needing to reload the svg again.

I don't know if this means a different way of loading the file. For example, I use text file tasks to load json files with asset container and then parse to json before parsing to NME, NGE, particles, etc. Maybe instead of loading like a texture, we load it as text and then use a method that does the sample at the DOM level as a given size. This would allow the user to keep the svg text in memory and resample at a new size and replace textures as needed. I can see this being useful for graphics such as logos which may need to be present at various sizes at different parts of a scene. Having the svg code in memory and being able to generate textures at multiple resolutions would benefit both in download size as well as size in memory as you can always dispose of the texture if not needed, but retain the svg code to regenerate at any time. 

This may not be the right solution, but something which allows control over rasterization size and regeneration would be great. If it's a new method, it preserves back compat since they can still be loaded as textures as they are now. 

- repro: https://playground.babylonjs.com/#DKMEZK

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Comment by deltakosh** [comment]
@PatrickRyanMS To test it: #DKMEZK#1

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15463/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15463/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15463/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15463/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15463/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15463/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15463/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15463/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15463/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15463/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15463/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15463/merge/testResults/webgpuplaywright/index.html

**Comment by deltakosh** [comment]
Forcefully merged as the error is not related and was already fixed on master

**Pull request merged**
