### PR TITLE
Bbox update for ribbon based shape updates

### PR DESCRIPTION
**Pull request by jbousquie**
The Bbox of a ribbon based shape (ribbon, tubes, extrusions, etc) is now updated when the shape is dynamically morphed.
Note : for performance reasons, the min and max computations are done in the same loop than the position computations. So no call to refreshBoundingInfo and no extra iteration.

### CODE REVIEW

**Comment by RaananW** [comment]
Hi Jerome,
Quick question - why are there so many file changes?

**Comment by jbousquie** [comment]
WTF... I just commited **one** ts file in VS Code (new version) and those compiled js files came along with... I did not even noticed them, tsssss

**Comment by jbousquie** [comment]
do I need to redo everything ?

**Comment by RaananW** [comment]
It seems like js file were added to the texture library. Need to check if their names are correct. On mobile, give me an hour.

**Comment by jbousquie** [comment]
well, I modified just MeshBuilder, so the rest comes from the repo, is compiled here and goes back (not intentionally) to the repo. Nothing is added or removed by me (I hope)

**Comment by jbousquie** [comment]
not sure to understand
let me recap :
I close my branch
I open new one
I modify the ts only,
I commit first
then I compile and test
If ok, then PR

right ?

**Comment by RaananW** [comment]
Sounds like a great plan! 
Thanks. I'll see how to solve this case problem with those files. A git rename will probably do the trick.

**Comment by RaananW** [comment]
Ohh, and of course, don't commit again after building.

**Pull request closed without merging**
