### PR TITLE
Add NME MeshAttributeExistsBlock

### PR DESCRIPTION
**Pull request by MiikaH**
This pull request combines feature requests of two forum threads from last year:

- https://forum.babylonjs.com/t/node-pbr-material-renders-black-if-mesh-doesnt-have-normals/29011
- https://forum.babylonjs.com/t/default-nodematerial-vertex-color-input-to-white-if-attribute-doesnt-exist-on-mesh/29461

I recently refactored a project where I used custom blocks to work around those issues above, and ended up with a single `MeshAttributeFallbackBlock` that I think might be flexible enough to be added to Babylon.js itself.

The nodeblock itself is pretty simple. It allows connecting to an attribute input (or morph target block) and has another falback input to provide value if mesh doesn't have the said attribute.

Here is a test NME url (only works with these PR changes in place): `/#W3ZANW` and a Playground test url: `/#5LCPMS`

The above example demonstrates three use cases where such node is useful / necessary:

### Vertex color fallback

This allows using same NodeMaterial with meshes or mesh primitives that contain and don't contain vertex colors. Currently if vertex color is used, it defaults to black color when attribute is present and there is no way to distinguish between actually intented black color and missing attribute.

Vertex Color Fallback

### Normal fallback

It is possible to generate flat normal in fragment shader if attribute isn't present. This matches gltf spec where a flat normal is used for meshes that don't contain normals.

Normal Fallback

### UV fallback

And kind of as additional possibility that my original normal and vertex color specific nodes didn't allow, is generating UV fallback with a generated UV if attribute isn't present.

UV Fallback

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13727/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13727/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13727/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13727/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13727/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13727/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13727/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13727/merge#BCU1XR#0

**Comment by carolhmj** [comment]
This looks pretty useful! I agree auto detect is probably nicer to use, but we probably should use the `VERTEX` define to avoid adding more defines, @Popov72 knows more about the NME shader code so he can see what's going on 😃

**Comment by Popov72** [comment]
This seems like a good addition to me!

I have a few comments though:
* Why handle the `MorphTargets` block case? Using the new block to get a fallback `normal` and plugging it into the `normal` input of `MorphTargets` should work? Also, conceptually, the `MorphTargets` output is not a mesh attribute, so including it in the `MeshAttributeFallbackBlock` is a bit odd. Finally, the user can rename the outputs, so you can't rely on the block's output connection names (this is not true for the output of the `InputBlock`, which is read-only).
* `VERTEXCOLOR_NME` should be `VERTEXCOLOR`, and its value should be set with the same code we use for standard/PBR materials, i.e. :
```typescript
const hasVertexColors = mesh.useVertexColors && mesh.isVerticesDataPresent(VertexBuffer.ColorKind) ;
defines["VERTEXCOLOR"] = hasVertexColors ;
defines["VERTEXALPHA"] = mesh.hasVertexAlpha && hasVertexColors ;
if (mesh.isVerticesDataPresent(VertexBuffer.ColorInstanceKind) && (mesh.hasInstances || mesh.hasThinInstances)) {
    defines["INSTANCESCOLOR"] = true ;
}
```
As you can see, you also need to add `VERTEXALPHA` and `INSTANCESCOLOR` in the list of defines.

If using `VERTEXCOLOR` doesn't work, we need to find out why.

**Comment by MiikaH** [comment]
Hey,

> * Why handle the `MorphTargets` block case?

Unfortunately including MorphTargetBlock seems like the only way to normal generation working with morph targets.

If you take the fallback from normal attribute and then pass to `MorphTargetBlock` will not work because `MorphTargetBlock` only transforms the normal if it is present (also geometry wouldn't include morph target normal transformation data if it doesn't include the normal itself).

In such case the "normal generation" has to take "morph target applied position" as input or generated normals won't reflect the morph target transformation.

> * `VERTEXCOLOR_NME` should be `VERTEXCOLOR`

I mentioned this without too much detail in my comment above.

If using the usual `VERTEXCOLOR` define then it triggers unexpected conditions in shader files, such as: https://github.com/BabylonJS/Babylon.js/blob/7a6e1f21b2fcd67d8859ad7df5fe9202e9745e5e/packages/dev/core/src/Shaders/ShadersInclude/pbrBlockAlbedoOpacity.fx#L49-L51

This throws error `Error: FRAGMENT SHADER ERROR: 0:515: 'vColor' : undeclared identifier` in my Playground test case above.

But more importantly it triggers a define condition that should *NOT* happen in a NME shader. We don't want albedo color to be automatically multiplied by vertex color. As that not only alters existing NME materials but also takes away the customization.

When searching the codebase for "defined(VERTEXCOLOR)" I can see how many shader files have such condition so like said I'm not familiar enough with Babylonjs internals to determine what is the best solution to that. A `replaceStrings` option for all such included shaders? I don't have enough experience of that to make such call.

A separate define for NodeMaterial was one solution as it avoids any conflicts with no risk of breaking existing models.

**Comment by MiikaH** [comment]
Regarding `INSTANCESCOLOR`. I have to say I don't have experience with this particular feature.

I assume it is a replacement for `VERTEXCOLOR`, but instead of using per vertex color it will color mesh instances as a whole with different colors?

I'm not sure if that applies to the fallback node? If NME materials currently don't use `INSTANCESCOLOR` at all, then fallback block also shouldn't react to it? Or is `INSTANCESCOLOR` already included in a `InputBlock` of `color` attribute?

**Comment by MiikaH** [comment]
And finally... Regarding `VERTEXALPHA`.

Would that apply to MeshAttributeFallbackBlock in any way? To me it looks like alpha is already embedded into the `color` input attribute. Therefore alpha define isn't relevant here. You trigger the fallback if vertex colors don't exist on model, otherwise you pass the Color4 attribute through unchanged.

**Comment by Popov72** [comment]
Yes, you are right that these additional definitions (VERTEXCOLOR, VERTEXALPHA, INSTANCESCOLOR) could cause a problem with the existing code, let's forget about them. So VERTEXCOLOR_NME is fine.

I understand the problem with `MorphTargets`, but there is still the problem with output names that can be renamed. So, why not have a drop-down list for the `MeshAttributeFallbackBlock` to select the attribute, but have "Auto-Detect" as the first option (which would be the default)? That way, if you connect an input block, it could find the correct attribute automatically, and for `MorphTarget` (or in any other case), the user will have to select the correct attribute from the list.

**Comment by MiikaH** [comment]
Btw, I created a test GLTF model with VEC3 type color attribute. It seems to work fine with current NME implementation too: https://playground.babylonjs.com/?snapshot=refs/pull/13727/merge#5LCPMS#1

I was worried that alpha would be zero in such case.

**Comment by MiikaH** [comment]
> but there is still the problem with output names that can be renamed. So, why not have a drop-down list for the `MeshAttributeFallbackBlock` to select the attribute

I don't have enough experience with NME to say how that would work. What would happen if it is already connected to a Vector3 input and you change it to "color" type which is Vector4? Will it throw error? Eject all connected outputs? Current implementation is nice that it doesn't allow you to connect other types to it if you have already connected it to specific type input.

**Comment by MiikaH** [comment]
> Might be a stupid question so be ready :-) Why not using a property of the input block to define the default value in place of a new block ? Should the default be a runtime computed value, some added verifications might need to happen to be sure that it runs in the right part (vertex/fragment) ?

Main reason is that sometimes the fallback needs to be a Fragment shader node. As in the test case linked above the generated vertex normal has to come from fragment shader because of derivatives. On top of that, the morph target case wouldn't work with fallback directly on the InputBlock.

**Comment by sebavan** [comment]
Do not mind me I discussed with @Popov72 and better understand, he might have a couple more changes :-)

**Comment by MiikaH** [comment]
> Note that I still think you should change how `VERTEXCOLOR_NME` is set

I pushed a commit to change that.

**Comment by Popov72** [comment]
So we discussed the issue with @sebavan and came up with this solution:

Instead of having `MeshAttributeFallbackBlock`, let's rename it something like `CheckDefineBlock`, because that's what it really does: check whether a define is set or not and set an output based on the result. This will allow a broader use than just attributes.

Instead of having a drop-down list, we could simply have an edit box where the user would type in the name of the definition: that way we are not limited by a list, we can check any definition. In the first iteration, the user would have to type the definition name because I don't think we're able to detect that something has been connected to the input of the block to get the attribute name automatically (in case it's an input block that's connected)... cc @deltakosh who should know if this is possible. Alternatively, we could have a predefined list and a "Custom..." option at the end, which would allow you to type in the name of the definition.

So, the changes in the existing PR would be to:
* rename the class
* rename the `attribute` input to `input`
* remove the code related to `MorphTargets`.
* add the possibility to type the name of the define

What do you think? Does this still meet your needs?

**Comment by MiikaH** [comment]
Hmm... I have couple of thoughts about that proposal:

- It sounds like this would make it very difficult to use, as users would have to look into the source code to discover what they want to do?
- Also it would make backwards/forwards compatibility a nightmare? Lets say in couple of years with WebGPU defines are removed from shaders as WebGPU shaders don't have preprocessor.
  - `MeshAttributeFallbackBlock`. No problem, the node can be adjusted in the future and will remain useful as long as meshes have different attribute types.
  - The proposed implementation: All existing NodeMaterials using this block will silently fail
- Above point also applies to internal Babylon.js code refactors. What if define names are at some point changed?

My current implementation at least is fairly generalized. New attributes can be added in the future. New auto detected node blocks or rules to handle the auto detection can be improved in the future if needed.

**Comment by Popov72** [comment]
> It sounds like this would make it very difficult to use, as users would have to look into the source code to discover "define names" for what they want to do? I thought the whole concept of NME is to let users create things without any understanding of underlying code.

Yes, that's why a predefined list (with names corresponding to the attributes to begin with) + the "Custom" option would be a must.

Regarding your last two points, this is more of a theoretical problem, as I don't think standard definitions such as NORMAL, TANGENT, etc, which simply indicate whether the corresponding feature is present or not, will be removed anytime soon. However, in theory, it could happen. Note that we use our own preprocessor code, so the fact that WGSL does not have a preprocessor is not a problem.

cc @deltakosh and @sebavan for their opinions.

**Comment by Popov72** [comment]
I think one thing that is misleading is the name of the `attribute` input: it looks like we should connect an attribute, but we can connect anything in fact (as the case of `MorphTargets` shows). I think it should be renamed `input` for better understanding.

**Comment by MiikaH** [comment]
> Note that we use our own preprocessor code, so the fact that WGSL does not have a preprocessor is not a problem.

Oh, I know that. The point was that tying a node type to a lower level concept such as "defines" that may not be relevant in future platforms sounds very problematic to me. When whole point of node based editors is to be higher level abstraction layer tha can be compiled to various platforms if wanted.

Also additional problem with the proposed solution:

- Define conflicts that alter shaders in the future. As we saw with the `VERTEXCOLOR` vs `VERTEXCOLOR_NME` define discussion above, a define can easily introduce conflicts that cause errors or unintentionally alter behavior of the NodeMaterial.
 - If someone is using the proposed `CheckDefineBlock` with a define name like `INSTANCESCOLOR` and at any point in the future someone tweaks the shader source codes, it could all of a sudden throw errors in that shader. Or introduce unintended behaviors that weren't originally there.
  - This would effectively make any change in Babylon.js shaders in the future potentially break NodeMaterials where users use the node.

**Comment by MiikaH** [comment]
> I think one thing that is misleading is the name of the `attribute` input: it looks like we should connect an attribute, but we can connect anything in fact (as the case of `MorphTargets` shows). I think it should be renamed `input` for better understanding.

Yes, it can be connected to a `MorphTargetBlock` but it is still a fallback for the related mesh attribute. Morph targets are under the hood dealing directly with mesh attributes after all so I personally don't see that too problematic.

**Comment by MiikaH** [comment]
Perhaps best solution would be to implement that attribute selection drop menu that @Popov72 suggested originally, but use something like `@editableInPropertyPage` -> notifiers -> `onValidation` to prevent users from selecting incompatible attribute types if the node block is already connected to other type? Another option would be to dynamically limit the options to connected type, if the block is already connected. But I don't think that such functionality exists in NME?

The drop menu could behave like this:
- When not connected to anything it always says "(None)"
- When connected to known block (InputBlock, MorphTargetBlock) it will auto switch to the detected attribute name, such as "Normal"
- When connected to unknown block it will stay as "(None)" until user makes a selection
- When block is disconnected it will auto switch back to "(None)"

I don't know if all that is possible in the current system, but that sounds like a pretty flexible solution. It would be clearest if there was a way to dynamically show only options of the connected input type. (Eg. Vector3 input would only show "position", "normal" and "tangent"), but I don't think that is possible at the moment.

**Comment by MiikaH** [comment]
Hmm... Or actually. Why does it matter if types don't match?

Maybe just allow connecting for example "Color3" inputs / outpust, yet have the attribute condition be "Tangent". In such case you could for example create a NodeMaterial that shows different color for mesh primitives that don't have tangents.

**Comment by MiikaH** [comment]
I now also added the selected attribute in parentheses to the node header so it is easier to follow which one is used without having to manually rename the nodes:

nme-attribute-exists-header

**Comment by MiikaH** [comment]
Hmm... Weird. Now the node no longer appears in NME snapshot list, and headers of existing nodes don't have the parentheses: https://nme.babylonjs.com/?snapshot=refs/pull/13727/merge#W3ZANW#4

But the snapshot playground NME accessed via inspector works as expected: https://playground.babylonjs.com/?snapshot=refs/pull/13727/merge#5LCPMS#2

On local dev setup both work fine. Did I miss something in my commit or is it the snapshot build system glitching out?

**Review by Popov72 — APPROVED** [review]
Looks great to me!

**Review by sebavan — APPROVED** [review]
Nice one thanks for the changes !!!

**Comment by MiikaH** [comment]
Well, there is actually one more todo that I just noticed. Need to rename the `AttributeFallbackBlockTypes` enum to `MeshAttributeExistsBlockTypes`, as that is used to manually define desired attribute type when not using the visual editor.

I'll change that tomorrow morning.

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
