### PR TITLE
fix: gltf metadata data is lost

### PR DESCRIPTION
**Pull request by Spencer17x**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14004/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14004/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14004/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14004/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14004/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14004/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14004/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14004/merge#BCU1XR#0

**Comment by Popov72** [comment]
This is a bug fix, actually, see https://github.com/BabylonJS/Babylon.js/pull/13365

If you really need to access the internal data, you should access them through `_internalMetdata`.

So, I'm closing this PR.

**Pull request closed without merging**
