### PR TITLE
Enhancements and fixes

### PR DESCRIPTION
**Pull request by RolandCsibrei**
GRL can be used for creating image walls displayed in 1 draw call. This requires to add some code for dealing with UVs.

- [x] get/set UVs
- [ ] support appending UVs when in instance mode
- [ ] fix instance support in ribbon mode

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14663/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14663/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14663/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14663/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14663/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14663/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14663/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14663/merge#BCU1XR#0

**Comment by sebavan** [comment]
Happy new year @RolandCsibrei !!!

There is no need to start a draft PR when you start working on the improvements. Let me close it, and you can reopen when almost ready?

This way, it helps the team to focus on the PRs that are closer to go in and discuss the final details when necessary.

**Comment by RolandCsibrei** [comment]
Hello and happy new year!!

I needed a snapshot. Is there any other way to create one?

Thanks!

**Comment by sebavan** [comment]
That is a pretty good reason then :-) feel free to reopen as draft whenever.

**Comment by Popov72** [comment]
> I needed a snapshot. Is there any other way to create one?

Why not testing in your local Playground?

**Comment by RolandCsibrei** [comment]
I always test in my local PG ofcourse. I wanted to make a publicly available PG with the proprosed PR.

**Comment by sebavan** [comment]
Feel free to reopen whenever :-) my bad for closing it yesterday, I was just doing new years cleanup lol

**Comment by RolandCsibrei** [comment]
Sorry guys, I forgot about this one. I will close it now and open a new one when it will be ready.

**Pull request closed without merging**
