### PR TITLE
Geometry buffer renderer: Fix normals not transformed by the world matrix when using normal maps

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/world-normals-dont-account-for-right-handed-coord-system/54625

### CODE REVIEW

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15805/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15805/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15805/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15805/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15805/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15805/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15805/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15805/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15805/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15805/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]
Crazy we never saw it

**Comment by Popov72** [comment]
> Crazy we never saw it

The problem occurred only when bump textures were used, that may be the reason why we didn't spot it earlier.

**Pull request merged**
