### PR TITLE
The STL loader flips the faces

### PR DESCRIPTION
**Pull request by YusakuNo1**
The current code loads STL files with faces flipped for the following combinations (RH for `useRightHandedSystem`, NO_ALTER for `DO_NOT_ALTER_FILE_COORDINATES`):
|&nbsp;|NO_ALTER-true | NO_ALTER-false |
|---|---|---|
| RH-true | good | bad |
| RH-false | bad | good |

The correct combination for whether flip the face indices is like the following table, which means, we should only detect `DO_NOT_ALTER_FILE_COORDINATES` but not `useRightHandedSystem`:
|&nbsp;|NO_ALTER-true | NO_ALTER-false |
|---|---|---|
| RH-true | flip | no-flip |
| RH-false | flip | no-flip |

### CODE REVIEW

**Review by sebavan — CHANGES_REQUESTED** [review]
I do not understand how this will flip the faces in right handed mode after this PR which is needed ?

Not the space I am the most familiar with but I guess rightHanded should be used somewhere ?

@bghgary any thoughts ?

**Comment by bghgary** [comment]
I have the same thought. We have to take `rightHanded` into account somewhere?

**Comment by YusakuNo1** [comment]
+1  I'm wondering as well, the result came from my experiments, but I don't fully understand. Let me dive deeper and update back to this thread.

**Comment by sebavan** [comment]
Moving to draft in the mean time

**Comment by sebavan** [comment]
Makes kinda sense :-)

@bghgary, you can try
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13317/merge/index.html#1DY3CF#4
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13317/merge/index.html#1DY3CF#5
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13317/merge/index.html#1DY3CF#6
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13317/merge/index.html#1DY3CF#7

For all the combinations DO_NOT_ALTER_FILE_COORDINATES and useRightHandedSystem with the stl loader.

**Comment by sebavan** [comment]
And this is still OK https://github.com/BabylonJS/Babylon.js/pull/12957 Thanks a lot for the fix !!!

**Review by sebavan — APPROVED** [review]

**Review by bghgary — APPROVED** [review]
I see. The STL loader doesn't need to check `useRightHandedSystem` because STL uses the default material which already accounts for it. I think we should probably add some tests for these cases, but it doesn't have to be part of this PR.

**Pull request merged**
