### PR TITLE
Small Playground changes

### PR DESCRIPTION
**Pull request by RaananW**
1) Reinstated the definition worker (until a better solution will be found)
2) It is possible to use query strings instead of hash queries. So this - `?pg=3VMTI9&revision=1` is the same as this `#3VMTI9#1` but indexable.
3) Added meta description and keywords that are being updated when a playground is loaded. we will need to start updating playgrounds with better description, title, and tags
4) Moved ALL javascript files to the body (avoiding render-blocking).

This is the version that is hosted here https://playgroundcdn1.azureedge.net/ and https://playgroundcdn2.azureedge.net/ (different CDN providers). **Please check it as well.**

### CODE REVIEW

**Comment by RaananW** [comment]
I will also be running deployment tests from a local branch during the weekend before moving to the new host.

**Comment by deltakosh** [comment]
Getting a 404 for css on the cdn1:
image

**Comment by RaananW** [comment]
I just purged the entire CDN (deployed a new version), did a reload fix it?

**Comment by RaananW** [comment]
image

(Desktop - already much better

**Comment by deltakosh** [comment]
I had to force reload it 3 times but it works now

**Pull request merged**
