### PR TITLE
How do we make scene graphs?

### PR DESCRIPTION
**Pull request by trusktr**
Something similar to Three.js' [Object3D](http://threejs.org/docs/#Reference/Core/Object3D)?

### CODE REVIEW

**Comment by deltakosh** [comment]
Can you please use the forum for questions?

**Comment by trusktr** [comment]
@deltakosh Will do. Hope it' a strong hint to add it to the docs if not there already. I looked through the docs, but if it's already documented, it's not very obvious.

**Comment by deltakosh** [comment]
I do not understand the ask as by default all entities belong to a scene graph. All meshes, cameras and lights are part of the scene graph. They all inherit from BABYLON.Node: http://doc.babylonjs.com/classes/2.2-alpha/Node

**Comment by deltakosh** [comment]
I do not understand the ask as by default all entities belong to a scene graph. All meshes, cameras and lights are part of the scene graph. They all inherit from BABYLON.Node: http://doc.babylonjs.com/classes/2.2-alpha/Node

**Comment by deltakosh** [comment]
I do not understand the ask as by default all entities belong to a scene graph. All meshes, cameras and lights are part of the scene graph. They all inherit from BABYLON.Node: http://doc.babylonjs.com/classes/2.2-alpha/Node

**Comment by deltakosh** [comment]
I do not understand the ask as by default all entities belong to a scene graph. All meshes, cameras and lights are part of the scene graph. They all inherit from BABYLON.Node: http://doc.babylonjs.com/classes/2.2-alpha/Node

**Comment by deltakosh** [comment]
I do not understand the ask as by default all entities belong to a scene graph. All meshes, cameras and lights are part of the scene graph. They all inherit from BABYLON.Node: http://doc.babylonjs.com/classes/2.2-alpha/Node

**Comment by trusktr** [comment]
Why is that not so apparent in the basic examples?

**Comment by trusktr** [comment]
I don't want to investigate API docs to figure out how I'm supposed to do stuff properly, I want to see examples and tutorial, then go to API docs for *reference*.

**Comment by deltakosh** [comment]
I would love to keep discussing with you on your forum post:) for instance what kind of improvements could we do for the samples to make them better

**Pull request closed without merging**
