### PR TITLE
CustomMaterial: Don't prevent support for uniform arrays

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/how-to-sampler-texturearray-with-a-index-from-attribute/38049

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by RaananW — APPROVED** [review]
If I understand this correctly, it removes any array reference (`[123]`) from the string passed?

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13519/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13519/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13519/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13519/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13519/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13519/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13519/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13519/merge#BCU1XR#0

**Comment by Popov72** [comment]
Yes indeed. That part of the code only needs the name of the uniform, not the whole declaration.

**Pull request merged**
