### PR TITLE
WebGPU: Add support for the predeclared alias in WGSL

### PR DESCRIPTION
**Pull request by Popov72**
This will fix the "clear quad" issue in https://playground.babylonjs.com/#W7E7CF#12.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by deltakosh — APPROVED** [review]
Thanks!! It's great we can support all of the types!

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14944/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14944/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
