### PR TITLE
Fix debugging and watch mode for viewer-alpha test app

### PR DESCRIPTION
**Pull request by ryantrem**
This change is mostly about finishing getting debugging and hmr (hot module reload) working for code under core and loaders.

- Make the repo root the web root and reference files from that context (fixes debugging)
- Make the `Viewer (Alpha - Web)` task depend on `Watch all (Dev)` (starts watch mode on dev code which fixes HMR, since it now will compile any changes and HRM will pick up the associated JS changes)

I also tacked on a couple other small fixes in the viewer-alpha code:

- If a new model or env is begins loading before a previous one finished, just log it (not as an error, no need for scary red console logs)
- In the test app, wait until we know the viewer module has finished asynchronously loading before trying to set properties on the viewer element

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15290/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15290/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15290/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15290/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15290/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15290/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15290/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15290/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15290/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15290/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
