### PR TITLE
Hook monaco completion provider to filter members starting with underscores

### PR DESCRIPTION
**Pull request by sailro**
_Given a non filtered babylon.d.ts_

Before:
before

After:
after

### CODE REVIEW

**Comment by sailro** [comment]
@deltakosh, after merging you need to update the babylon.d.ts with the regular one, and remove any auto-post-processing-step if needed.

**Comment by deltakosh** [comment]
yep yep it is done:)

**Comment by sebavan** [comment]
So thankful to @sailro as it helps removing some build steps :-)

**Comment by sailro** [comment]
Do we still need this ?

https://github.com/BabylonJS/Babylon.js/blob/master/Tools/Gulp/tasks/gulpTasks-intellisense.js#L15

**Comment by deltakosh** [comment]
Nope, it is removed in my branch

**Pull request merged**
