### PR TITLE
UnIndexed picking fix

### PR DESCRIPTION
**Pull request by aWeirdo**
Support picking for instance of unIndexed mesh,

### CODE REVIEW

**Comment by aWeirdo** [comment]
Need to check some things, something isn't right :)

**Comment by aWeirdo** [comment]
Ok, found my mistake, instanceMesh already had _unIndexed property from AbstractMesh class, it simply wasn't updated

**Comment by deltakosh** [comment]
some tests are failing?

**Comment by aWeirdo** [comment]
seems unrelated, not sure why they failed

**Comment by deltakosh** [comment]
@sebavan is on it:)

**Pull request merged**
