### PR TITLE
audio negative startOffset bug

### PR DESCRIPTION
**Pull request by wyklion**
it seems right now.

### CODE REVIEW

**Comment by deltakosh** [comment]
@davrous will soon review this but you know this is holidays season.. :)

**Comment by wyklion** [comment]
ok，haha.

**Comment by wyklion** [comment]
the particle color lerp is very bored, i can't stand.

**Comment by wyklion** [comment]
what's the problem?

**Comment by davrous** [comment]
There's no problem. I was just busy on other tasks. Sorry for being late. I'm going to have a look today or tomorrow and will merge quickly if everything is fine on my unit tests.

**Comment by davrous** [comment]
hi @wyklion. Thanks for the bug on this._startTime instead of startTime. But for the _startOffset, I can't see cases where it could be negative. Can you please elaborate on cases you've found?

**Comment by davrous** [comment]
@wyklion , you've also included unrelated modification to audio in your PR. Can you please submit individual and separated PR to the modifications you'd like to do to math.ts & so on?

Thanks!

**Comment by wyklion** [comment]
@davrous 
1. play(10)
2. after 5 second pause() // offset = -5
3. play() error...

i wrote it in early closed pr...
and what do you think about random lerp. if no use. i'll remove the change.
and another miss onError bug has been fixed by someone i can remove that also.

BUT! the audio definitely has the bug!...

**Pull request closed without merging**
