### PR TITLE
Physics Velocity Limits

### LINKED ISSUE #14965: Missing Havok Physics World Speed Limit Set/Get Functions
### Issue 

The `havok.HP_World_SetSpeedLimit` function is undefined in Havok Physics version 1.3.2, despite a type being defined for it. 
Additionally, there is no getter to retrieve the current world speed limit.

### Expected
Expected result: The `havok.HP_World_SetSpeedLimit` function should be properly exported and available for use. There should also be a corresponding getter function to retrieve the current world speed limit value.

### Current 
Current result: The `havok.HP_World_SetSpeedLimit` function is undefined and unavailable for use. There is no built-in way to get the current world speed limit.

### Additional context

This issue was originally brought up and discussed on the Babylon.js forum:
https://forum.babylonjs.com/t/how-to-enable-faster-moving-rigidbodies-in-havok/40631/13?u=nyan-left

The missing bindings for setting and getting the Havok world speed limit were noticed after an update to version 1.3.2. In previous versions, workarounds using direct memory access were provided, but a proper API for this functionality is desired.

It would be greatly appreciated if the function could be properly exported, and a corresponding getter function added as well. This will allow developers to adjust the world speed limit in a supported manner, without resorting to memory hacks.

Thank you for looking into this!

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes #14965

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15158/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15158/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15158/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15158/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15158/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15158/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15158/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15158/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15158/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15158/merge/testResults/webgpuplaywright/index.html

**Review by RaananW — APPROVED** [review]
Can you update the havok wasm here as well?

**Comment by CedricGuillemet** [comment]
> Can you update the havok wasm here as well?

It's was already udpated with these functions exposed.

**Pull request merged**
