### PR TITLE
Split interleaved buffers reference images

### PR DESCRIPTION
**Pull request by bghgary**
This isn't strictly required, but in native, this was a problem. This is here just to make it consistent with native.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14865/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14865/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14865/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14865/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14865/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14865/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14865/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14865/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14865/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14865/merge/testResults/webgpuplaywright/index.html

**Comment by sebavan** [comment]
> Just a heads up @Popov72 , webgpu test fails here, with this error:
> 
> image Stacktrace here - https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14865/merge/testResults/webgpuplaywright/trace/index.html?trace=https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14865/merge/testResults/webgpuplaywright/data/2a28c5657602d8c458ce0d78f07fb3073e8aadba.zip

shoot did not see it before merging... :-(

**Pull request merged**
