### PR TITLE
WebGPU: Simplify error handling during engine creation/initialization

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/webgpu-cannot-allocate-wasm-memory-for-new-instance/48321/5

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14815/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14815/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14815/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14815/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14815/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14815/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14815/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14815/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14815/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14815/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14815/merge/testResults/webgl2playwright/index.html

**Review by RaananW — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14815/merge/testResults/webgpuplaywright/index.html

**Comment by Popov72** [comment]
@RaananW I'm not sure what this error is:

```md
Setting AZURE_CONFIG_DIR env variable to: /home/vsts/work/_temp/.azclitask
##[error]Script failed with error: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at Function.<anonymous> (/home/vsts/work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.230.0/azureclitask.js:118:28)
    at Generator.next (<anonymous>)
    at /home/vsts/work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.230.0/azureclitask.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/vsts/work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.230.0/azureclitask.js:4:12)
    at Function.loginAzureRM (/home/vsts/work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.230.0/azureclitask.js:115:16)
    at Function.<anonymous> (/home/vsts/work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.230.0/azureclitask.js:43:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/_tasks/AzureCLI_46e4be58-730b-4389-8a2f-ea10b3e5e815/2.230.0/azureclitask.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
I already tried to restart the CI with no luck.

**Pull request merged**
