### PR TITLE
Fix #15518

### LINKED ISSUE #15518: Add .exr to the available file types for import to a Texture block in NME/NGE
Now that Babylon.js supports .exr files, we need to add that file type to the available file types that can be loaded into a Texture block when embedding a texture. Right now, these are the only available file formats:

image

For NGE, the only supported file formats are .png and .jpg, so it seems as though we would want the potential of higher precision data for NGE as well. We should probably add .exr here as well, but also .tga and .dds? 

image

Should we additionally add .hdr support for both tools? It would be similar to offering .exr/.dds/.tga to get higher precision, but with just an additional format option.

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15522/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15522/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15522/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15522/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15522/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15522/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15522/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15522/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15522/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15522/merge/testResults/webgl2playwright/index.html

**Pull request merged**
