### PR TITLE
Fix.create xxx with options

### PR DESCRIPTION
**Pull request by jbousquie**

### CODE REVIEW

**Comment by jbousquie** [comment]
@RaananW : could you please tell me if this PR is right before I go on coding on this branch ?

**Comment by RaananW** [comment]
Hola,

what do you mean with "right"? if the code is correct, or if it can be merged?

**Comment by RaananW** [comment]
I would anyhow always recommend a new branch for each feature. Don'T continue on this branch. Without merging and updating you will have conflicts like you had before. close the branch, start a new one, try also avoiding those "mandatory commits" (not sure what they actually mean :-) )

**Comment by jbousquie** [comment]
I meant : 'mergeable'

Actually, I modify only one (or two) same file all day long, changing 
call signatures of many mesh CreateXXX methods. That's why I've been 
keeping a single branch. I'm not sure making a new branch per change on 
the same file would be easily mergeable at the end

"madatory commits" are just ... mandatory commit : when I want to 
fetch/merge upstream to master the next day, git forces me to commit 
some files before be able to merge, then to go on

**Comment by RaananW** [comment]
you can usually avoid that by creating new branches and closing old ones, or by discarding the changes (those are js files) and then regenerating them using gulp. You can also try rebasing (https://www.git-scm.com/book/en/v2/Git-Branching-Rebasing) those commits so you wouldn't see so many "mandatory commits". 
But, as long as everything works, it is all fine.
And yes, it is mergable :-)  You should be able to see a text stating that.

**Comment by jbousquie** [comment]
aarff
I saw the text of course :-)
but I meant : would you merge this before I go on with this branch then 
(I already started but I can copy/paste to another one if needed) ?

**Comment by RaananW** [comment]
So just ask :-)
I didn't go through the code. Try commiting a single commit with the changes, those unneeded commits make the history unreadable.

**Pull request merged**
