### PR TITLE
Fix flacky test

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Comment by deltakosh** [comment]
Webgpu and webgl have a different way of representing fragCoord.y. This change make it simple to compare both

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15379/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15379/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15379/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15379/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15379/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15379/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15379/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15379/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15379/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15379/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — COMMENTED** [review]
This changes the visual to 
image
 from 
image
 I am not sure it is intended

**Comment by deltakosh** [comment]
It is:) I forgot to change the screenshot

**Pull request merged**
