### PR TITLE
Nme webgpu 14 - The long awaited PBR block :)

### PR DESCRIPTION
**Pull request by deltakosh**
Bear with me, it will be long and painful

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15302/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15302/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15302/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15302/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15302/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15302/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15302/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15302/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15302/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15302/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15302/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by deltakosh** [comment]
To keep the size under control this is only the first step. More blocks needs porting and I will do it later

**Comment by Popov72** [comment]
For my understanding, why did you have to update the way we return the outputs from the PBR blocks (`return XXX` instead of through an `out` parameter)? It seems `out` parameters are supported in WGSL: https://stackoverflow.com/questions/72967362/whats-the-idiomatic-replacement-for-glsl-output-parameters-in-wgsl

**Comment by deltakosh** [comment]
It was mostly to clean it up. I had several issues to make it work so so decided to remove it.

Do you see any problem and why did we use it in the first place?

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15302/merge/testResults/webgl2playwright/index.html

**Comment by Popov72** [comment]
> It was mostly to clean it up. I had several issues to make it work so I decided to remove it.
> 
> Do you see any problem and why did we use it in the first place?

I don't really remember... One thing which is possible with an "out" parameter is that we can declare the out structure once and pass it to several different functions if we want, and each function can read/update the structure, something not possible when the structure is returned by the function. But I don't know if it's something we will need in the future.

One drawback of the change I can see, though, is that the diff is even bigger! :)

**Comment by deltakosh** [comment]
Yeah diff is big but honestly this change helped me a lot as the pointer crap of webgpu was simply not reliable.

**Comment by deltakosh** [comment]
I ran all our test PGs:
- in pure webgpu(not working completely as not all the nodes are ported yet)
- in tint for webgpu: all worked
- in glsl: all worked

**Pull request merged**
