### PR TITLE
Missing coma in gulpfile

### PR DESCRIPTION
**Pull request by raananw**
Wrong gulp file was commited, coma was missing.

### CODE REVIEW

**Comment by raananw** [comment]
For some reason I am getting quite a lot of compilation errors in VS stating that the AudioContext is missing.  Any fix for that (except ignoring the audio directory while building)?

**Comment by deltakosh** [comment]
Are some files missing?

**Comment by raananw** [comment]
It just can't seem to find AudioContext, AudioNode, GainNode in the audio ts files. 31 errors all in all. My fork is completely up to date.

**Comment by raananw** [comment]
poly2tri is also missing from polygonmesh.ts

**Comment by TriBlade9** [comment]
I think it's a good thing if none of the files are in comas. On the other hand, if you mean *commas*.

(Sorry, pet peeve)

**Comment by raananw** [comment]
Hmmm... I actually thought you were referring to the missing files (dunno, thought one might say they are in coma) until I noticed my wonderful wonderful mistake. Sum times Spell cheque does nut help, huh?
Yes, I did mean comma, in case you were wondering :-)

**Comment by raananw** [comment]
Just an update regarding the missing classes - I found the missing files in the Reference directory. They are not included in the BuildYourOwn project. This was the cause of the problem. All works now.

**Pull request merged**
