### PR TITLE
Exposing internal texture type argument for proceduralTextures

### PR DESCRIPTION
**Pull request by Pryme8**
did not add it for cubes

### CODE REVIEW

**Comment by deltakosh** [comment]
Why not cube?

**Review by deltakosh — APPROVED** [review]

**Comment by deltakosh** [comment]
Thanks a lot!

**Comment by Pryme8** [comment]
hmmm, Im not sure what to do about the webGL2 fails.

**Comment by deltakosh** [comment]
BEcause the default type should be TEXTURETYPE_UNSIGNED_INT

**Comment by Pryme8** [comment]
"TEXTURETYPE_INT" hahah whoops wrong one.

**Pull request merged**
