### PR TITLE
Fix missing internal sized formats for MSAA render targets

### PR DESCRIPTION
**Pull request by rapid-images-tore-levenstam**
Original issue described here: https://forum.babylonjs.com/t/using-msaa-causes-opengl-errors-with-certain-color-renderable-formats/45994

Fixed by removing `thinEngine._getRGBAMultiSampleBufferFormat` as when creating an MSAA render target, I think you always want the same format in your resolved render target, as in your MSAA render target.

Does not validate the formats are color-renderable. But it didn't do that before either, and the function for creating normal render targets doesn't do that either, as far as I can see.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by rapid-images-tore-levenstam** [comment]
First time here, so let me know if any changes are needed :)
Couldn't find anything about PR titles, etc.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14580/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14580/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14580/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14580/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14580/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14580/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14580/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14580/merge#BCU1XR#0

**Review by Popov72 — APPROVED** [review]

**Comment by sebavan** [comment]
ohhh nice one !!! thanks a lot @rapid-images-tore-levenstam

**Pull request merged**
