### PR TITLE
Fix #15588

### LINKED ISSUE #15588: Babylon's `HTMLCanvasElement.requestPointerLock()` conflicts with new TS `lib.d.ts`
The return type of Babylon's `HTMLCanvasElement.requestPointerLock()`, which is `void`, conflicts with the return type of TypeScript's version on `lib.d.ts`, which is `Promise<void>`.

In Babylon: https://github.com/BabylonJS/Babylon.js/blob/05e9f47bae970f5ff219628779263072fde86a18/packages/dev/core/src/LibDeclarations/browser.d.ts#L32

In TypeScript: https://github.com/microsoft/TypeScript/blob/8230bc66a7eb4b88cfb6cdaa4ea8324808b39a07/src/lib/dom.generated.d.ts#L7873

### PR DESCRIPTION
**Pull request by sebavan**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15595/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15595/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15595/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15595/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15595/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15595/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15595/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15595/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15595/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15595/merge/testResults/webgl2playwright/index.html

**Pull request merged**
