### PR TITLE
CUstom Material

### PR DESCRIPTION
**Pull request by NasimiAsl**
hi @deltakosh  i have small change for standard material 
after you accept that i begin write documents thanks i wait your response

### CODE REVIEW

**Comment by sebavan** [comment]
Hello Nasimi,

Is it not possible to reuse customShaderNameResolve even if the signature changes to be located in one place ?

Thx,

**Comment by NasimiAsl** [comment]
it is possible but after use customMaterial that make new shaderName actually this method  created  for customMaterial ( this is crated after i make first customMaterial PR )
any way if you see any benefit for make that i can write new version about this

**Comment by sebavan** [comment]
yep, I would like to see all the custom part in one method if possible. maybe just after the MaterialHelper.PrepareUniformsAndSamplersList so that you could pass name, uniforms, samplers, uniformbuffers, and all the oher required information before calling setEffect ???

**Comment by sebavan** [comment]
Btw, I like the custom part and plan to use it for another project :-) hence why I am asking

**Comment by NasimiAsl** [comment]
i make a new method in this PR
reviewBufferBeforeEffectCreation
i just need make uniform and sampler so make that

**Comment by dad72** [comment]
Hi Nasimi,
Your readme file has the .rd extension. .md is you wanted write I guess. 
I do not include the file docHelper.min not minimize.
Why StandardMaterial2 with the code CustomMaterial in the same file?

**Comment by NasimiAsl** [comment]
hi i wanna make a sample in PG so need make some file before that commited
so :) i need md thanks for your notic

**Comment by sebavan** [comment]
@NasimiAsl I ll merge it as soon as the custom functions have been merged together in one callback.

**Comment by NasimiAsl** [comment]
we can wait deltakosh

**Comment by dad72** [comment]
Deltakosh is on vacation, I think it's Sebavan who should do Nasimi

**Comment by NasimiAsl** [comment]
ok :)

**Comment by dad72** [comment]
@NasimiAsl . Have you merged custom functions in a single reminder for your PR can be validated?

**Comment by NasimiAsl** [comment]
yes that is finished for this time ( i need make shader builder changes too )

**Comment by sebavan** [comment]
Thay do not look merged together, there is still reviewBuffersBeforeEffectCreation and customShaderNameResolve

**Comment by NasimiAsl** [comment]
customShaderNameResolve this method is available before this is not for me actually
what is problem about "reviewBuffersBeforeEffectCreation"?

**Comment by sebavan** [comment]
No problem but as it basically addresses the same need of customizing shader inputs this would be great to merge them (do not hesitate to change the signature customShaderNameResolve if you need).

**Comment by NasimiAsl** [comment]
so any  in-progress  task about changing standard material ( in customization stuff ) is available now
because i need that functions ( this is necessary )
and if standard material structure wanna be changed i most wait for that 
but if this changes take long time or not started yet so we can make customMaterial with this version and change it in next time( after customized standard material) too?

about customShaderNameResolve what need i changed i don't understand correctly 
? am i need change standard material  or change custom material?

**Comment by sebavan** [comment]
Sorry for explaining badly, I can do the changes in standard material if you want and you ll simply have to adapt custom (one callback instead of two separates). would that work for you ?

**Comment by NasimiAsl** [comment]
yes  i just need something let me manage uniform and sampler array

**Comment by sebavan** [comment]
Cool, you ll have it in 2 hours.

**Comment by sebavan** [comment]
You have got the changes in https://github.com/BabylonJS/Babylon.js/commit/0b38dad3e8910ae326dd79512614d82bcdedc4a6

you can now do every custom operations from one callback. I let you adapt the customMaterial.

**Comment by NasimiAsl** [comment]
that is nice :)

**Pull request closed without merging**
