### PR TITLE
Master

### PR DESCRIPTION
**Pull request by MackeyK24**
Add support for access the clone’s source mesh. Allows much easier
access for additional cloning. Example: clone.skeleton =
clone.source.skeleton.clone()

### CODE REVIEW

**Comment by deltakosh** [comment]
you have to update the abstractmesh.dispose to nullify the source properties of all clone when source is disposed

**Comment by MackeyK24** [comment]
I dont get what you are saying... Sorry... 
so what and where would you add to the abstract mesh .dispose:

public dispose(doNotRecurse?: boolean): void {
            var index: number;

            // Action manager
            if (this.actionManager) {
                this.actionManager.dispose();
                this.actionManager = null;
            }

            // Skeleton
            this.skeleton = null;

            // Animations
            this.getScene().stopAnimation(this);

            // Physics
            if (this.physicsImpostor) {
                this.physicsImpostor.dispose(/*!doNotRecurse*/);
            }

            // Intersections in progress
            for (index = 0; index < this._intersectionsInProgress.length; index++) {
                var other = this._intersectionsInProgress[index];

                var pos = other._intersectionsInProgress.indexOf(this);
                other._intersectionsInProgress.splice(pos, 1);
            }

            this._intersectionsInProgress = [];

            // Lights
            var lights = this.getScene().lights;

            lights.forEach((light: Light) => {
                var meshIndex = light.includedOnlyMeshes.indexOf(this);

                if (meshIndex !== -1) {
                    light.includedOnlyMeshes.splice(meshIndex, 1);
                }

                meshIndex = light.excludedMeshes.indexOf(this);

                if (meshIndex !== -1) {
                    light.excludedMeshes.splice(meshIndex, 1);
                }

                // Shadow generators
                var generator = light.getShadowGenerator();
                if (generator) {
                    meshIndex = generator.getShadowMap().renderList.indexOf(this);

                    if (meshIndex !== -1) {
                        generator.getShadowMap().renderList.splice(meshIndex, 1);
                    }
                }
            });

            // Edges
            if (this._edgesRenderer) {
                this._edgesRenderer.dispose();
                this._edgesRenderer = null;
            }

            // SubMeshes
            this.releaseSubMeshes();

            // Engine
            this.getScene().getEngine().unbindAllAttributes();
            this.getScene().getEngine().wipeCaches();

            // Remove from scene
            this.getScene().removeMesh(this);

            if (!doNotRecurse) {
                // Particles
                for (index = 0; index < this.getScene().particleSystems.length; index++) {
                    if (this.getScene().particleSystems[index].emitter === this) {
                        this.getScene().particleSystems[index].dispose();
                        index--;
                    }
                }

                // Children
                var objects = this.getDescendants(true);
                for (index = 0; index < objects.length; index++) {
                    objects[index].dispose();
                }
            } else {
                var childMeshes = this.getChildMeshes(true);
                for (index = 0; index < childMeshes.length; index++) {
                    var child = childMeshes[index];
                    child.parent = null;
                    child.computeWorldMatrix(true);
                }
            }

            this.onAfterWorldMatrixUpdateObservable.clear();
            this.onCollideObservable.clear();
            this.onCollisionPositionChangeObservable.clear();

            this._isDisposed = true;

            super.dispose();
        }

**Comment by deltakosh** [comment]
you have to go through all meshes and find all meshes where source==this and set source =null

**Comment by MackeyK24** [comment]
But i dont have source in abstract mesh... Its in mesh.source... So should i check to null all other in mesh.dispose ???

**Comment by deltakosh** [comment]
you can still test if it is a mesh with typeof

**Comment by MackeyK24** [comment]
??? ... But mesh._source is private.

if you are talking about doing something like this in mesh.dispose (i follow.. if not i dont know)

         var meshes = this.getScene().meshes;
            meshes.forEach((mesh: Mesh) => {
                if (mesh._source && mesh._source === this) {
                    mesh._source = null;
                }
            });


But you are saying i should be doing this abstract mesh... 

Should i just move 'private _source' to abstract mesh and use some kind of abstractMesh setSource and clearSource functions... Im sorry, just not getting what you want me to do and WHERE

Can you just make out the snippet you are talking about

**Pull request merged**
