### PR TITLE
Fix #15279

### LINKED ISSUE #15279: Teleport node on matrix and world pos/nor/tan blocks connected to PBR nodes causing compile error
When using teleport nodes to prevent long wires connecting nodes like world matrix or world pos/nor/tan to blocks in the vertex output and blocks like the PBRRoughnessMetallic bock in the fragment output, compile errors are thrown and the mesh does not render. In looking at the scene, the node material builds and can be opened in the editor. It will also successfully add textures loaded in code to any targeted texture node in the graph even though the compilation of the shader errors. There are no textures in the repro below just to make it a simpler repro, but I can confirm that attaching textures to texture nodes does work even if the compilation fails. 

It is inconsistent when it fails, and fixing it is also inconsistent. It seems as though some teleport nodes are ok and work in the graph but at some point using teleport out nodes will cause compilation to fail. The repro below is in such a state where the compilation has failed. Rewiring from the original nodes and bypassing the teleport nodes will make the graph work again, but I can't determine a specific and consistent workaround that will make it work other than not using teleport nodes all together. 

**Repro**
- https://playground.babylonjs.com/#I9QT5W

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15281/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15281/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15281/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15281/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15281/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15281/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15281/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15281/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15281/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15281/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
