### PR TITLE
P8 skeleton viewer try2

### PR DESCRIPTION
**Pull request by Pryme8**
DONE - Attach Gizmos to Bones through Inspector
DONE - Expose Sphere/Spur Sizing Parameters in Debug Menu

*IMPORTANT*
Also Id like to note a bug with the gizmo attachments.  If you do a build of this branch and drop into any scene with a skeleton with mesh is not at Zero the gizmo does not go into the correct place.  Don't think its anything that I would have done and is behavior that will need to be fixed on the gizmo manager level?
TODO - Solve noticeable fps drop when constructing or swapping to sphere/spheres & spur mode.

### CODE REVIEW

**Comment by deltakosh** [comment]
There is one file in conflict

**Comment by Pryme8** [comment]
Checking it out now.

Im trying to figure out how to get this in, and then merged with Popovs PR.

**Comment by deltakosh** [comment]
you can cancel it, merge from master when I'll merge popov's one and do a new PR

**Comment by Pryme8** [comment]
Sounds good

**Pull request closed without merging**
