### PR TITLE
Added UI tests sandbox and graph-based tool

### PR DESCRIPTION
**Pull request by RaananW**
User interaction tests for the sandbox, including drag and drop a file (texture) and loading an asset. Also testing that the inspector opens correctly.

I also made a slight change to the playground tests to be sure they are also using the .env file and taking HTTPS settings into account for local testing.

This also adds tests to all 4 graph-based editors. The tests are simple and straight-forward - check it renders, check we can add a node and check we can move a node. Further tests can (and should) be added in the future.

### CODE REVIEW

**Comment by bjsplat** [comment]
You have changed file(s) that make changes to the playground.
You can test the snapshot here:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/PLAYGROUND/refs/pull/15908/merge/

The snapshot playground with the CDN snapshot (only when available):

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/PLAYGROUND/refs/pull/15908/merge/?snapshot=refs/pull/15908/merge

Note that neither Babylon scenes nor textures are uploaded to the snapshot directory, so some playgrounds won't work correctly.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15908/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15908/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15908/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15908/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15908/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15908/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15908/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15908/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15908/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
You have changed file(s) that make changes to the playground.
You can test the snapshot here:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/PLAYGROUND/refs/pull/15908/merge/

The snapshot playground with the CDN snapshot (only when available):

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/PLAYGROUND/refs/pull/15908/merge/?snapshot=refs/pull/15908/merge

Note that neither Babylon scenes nor textures are uploaded to the snapshot directory, so some playgrounds won't work correctly.

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15908/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
You have changed file(s) that make changes to the playground.
You can test the snapshot here:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/PLAYGROUND/refs/pull/15908/merge/

The snapshot playground with the CDN snapshot (only when available):

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/PLAYGROUND/refs/pull/15908/merge/?snapshot=refs/pull/15908/merge

Note that neither Babylon scenes nor textures are uploaded to the snapshot directory, so some playgrounds won't work correctly.

**Pull request merged**
