### PR TITLE
fix(Runtime Animation): Reset future runtime animation events on goToFrame

### PR DESCRIPTION
**Pull request by zakhenry**

### CODE REVIEW

**Comment by deltakosh** [comment]
You may need to fix the code :) (see CI test all failing)

**Comment by zakhenry** [comment]
Damn, thought it was a simple enough fix to use the github ui, I suppose not. Will fix up tomorrow

**Comment by zakhenry** [comment]
Not sure what is wrong with the tests, retrying by rebasing on latest master

**Comment by zakhenry** [comment]
@deltakosh please re-review :)

**Pull request merged**
