### PR TITLE
Added subdivisions handling for CreateCylinder

### PR DESCRIPTION
**Pull request by jahow**
Better now: http://www.babylonjs-playground.com/#1S6POH#2

### CODE REVIEW

**Comment by deltakosh** [comment]
Please leave the mesh.CreaeCylinder unchanged and update VertexData.CreaeCylinder instead. This way the geometry class will be updated as well

**Comment by jahow** [comment]
That was my intention, but the issue is that CreateTube only exists on the Mesh class.

The only parametric shape VertexData does is CreateRibbon. whereas the Mesh class has:
- CreateRibbon
- CreateTube
- CreateCylinder
(+ extrusion methods)

I think it's consistent to transfer the actual logic of CreateTube and CreateCylinder to the VertexData class, I'll add it to the PR (closed in the meantime)

**Comment by deltakosh** [comment]
Completely agree

**Comment by jbousquie** [comment]
Beware of the fact that a tube mesh can be updated... this means that an instance of tube (mesh object)  can be passed to the the _CreateTube()_ method and in this case the mesh (so the VertexData) isn't re-created but just updated (actually the underlying ribbon). The geometry only changes : in fine a call to _updateVerticesData(Position.Kind)_ 

It may not be that easy to transfer the current _CreateTube()_ code as is to the VertexData class.
Have fun :-D

**Comment by deltakosh** [comment]
At least the createCylinder update has to be transferred.

**Comment by jahow** [comment]
Will do, will do! I just hope I won't have to refactor too much...

**Pull request closed without merging**
