### PR TITLE
Add an ugly flag to glTF draco loader extension

### PR DESCRIPTION
**Pull request by bghgary**
There appears to be lots of files out there with invalid Draco data where the `normalized` flag in the data is marked `false` when it should be `true`. The glTF accessor info is correct. Draco data is supposed to be self-contained, so this is troubling. For now, adding this flag to read from the glTF accessor instead and log a warning when there is a mismatch.

### CODE REVIEW

**Comment by bghgary** [comment]
I need to figure out how to create files like this. Once that happens, I'll add a visual test in a separate PR.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14325/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14325/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14325/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14325/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14325/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14325/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14325/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14325/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14325/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14325/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
