### PR TITLE
Fix planeRotationGizmo's behavior when updateGizmoRotationToMatchAttachedMesh is set to false.

### PR DESCRIPTION
**Pull request by AN-DCL**
Hello dear Babylon maintainers,

This PR fixes seemingly incorrect behavior of plane rotation gizmos' when it is not set to be aligned with mesh's rotation.

To see an issue please run this code in Playground 6.6.1:

```ts
var createScene = function () {
    var scene = new BABYLON.Scene(engine);

    var camera = new BABYLON.FreeCamera("camera1", new BABYLON.Vector3(0, 5, -10), scene);
    camera.setTarget(BABYLON.Vector3.Zero());
    camera.attachControl(canvas, true);

    var light = new BABYLON.HemisphericLight("light", new BABYLON.Vector3(0, 1, 0), scene);
    light.intensity = 0.7;

    var box = BABYLON.MeshBuilder.CreateBox("box", {size: 1, height: 5}, scene);
    box.position.y = 1;
    box.rotation = new BABYLON.Vector3(0, 0, Math.PI / 6)

    const utilLayer = new BABYLON.UtilityLayerRenderer(scene);
    const gizmo = new BABYLON.PlaneRotationGizmo(new BABYLON.Vector3(0, 1, 0), BABYLON.Color3.FromHexString("#00b894"), utilLayer);
    gizmo.updateGizmoRotationToMatchAttachedMesh = false;
    gizmo.attachedMesh = box;

    return scene;
};
```

While gizmo is set to not align with mesh rotation's, it rotates a mesh as if it was aligned, i.e. rotation happens about mesh's local axes instead of gizmo's axes.

The fix boils down to simply changing an order of matrix multiplication in one place.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13939/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13939/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13939/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13939/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13939/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13939/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13939/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13939/merge#BCU1XR#0

**Comment by carolhmj** [comment]
Hmm this behavior changed from 4 to 5, just checking with @CedricGuillemet if it wasn't an intentional change?

**Comment by CedricGuillemet** [comment]
Names are not explicit and no one in in the industry is using concept like `updateGizmoRotationToMatchAttachedMesh`. The standard is to use the gizmo as local or global/world coordinate system.
`updateGizmoRotationToMatchAttachedMesh=true` means local
`updateGizmoRotationToMatchAttachedMesh=false` means global
So, in your PG, it uses respectively: local mesh Y axis and world Y axis.
Which was not the case before your PR.
I think we should make these flags (updateGizmoRotationToMatchAttachedMesh) less visible or document them to not use them. And add a new coordinate system flag (world/local) that would actually change updateGizmoRotationToMatchAttachedMesh value. And add a combobox/radiobutton in the inspector.
What do you think @PatrickRyanMS ?

**Comment by carolhmj** [comment]
> And add a new coordinate system flag (world/local)

I like that idea very much it makes things much clearer 😄

**Comment by sebavan** [comment]
The main question now is should we adapt this PR or close it and create a new one ?

**Comment by CedricGuillemet** [comment]
I prefer to have everything in 1PR so it's easier to test. The change is not big so it can be easily ported to a new PR. I'm in favor of closing this 1.

**Comment by sebavan** [comment]
Ok so closing for now at least.

**Pull request closed without merging**
