### PR TITLE
Unity Playground Missing Library Fix

### PR DESCRIPTION
**Pull request by MackeyK24**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14770/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14770/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14770/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14770/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14770/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14770/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14770/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14770/merge#BCU1XR#0

**Comment by bjsplat** [comment]
(Experimental) visualisation test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14770/merge/testResults/webgl2playwright/index.html

**Comment by RaananW** [comment]
There are no changes in this PR. What am I missing?

**Comment by MackeyK24** [comment]
Your not missing anything, i made a line change but forgot i moved that line. So i reverted that change. Sorry for the confusion

**Comment by MackeyK24** [comment]
Yo @RaananW ... FYI... the 6.41.2 version of the playground, which i thought had the updates from this PR. Its not working, by detecting the InitializePlayground code snippet.

Please try this simple playground that just loads the toolkit environment with pyhsics

https://playground.babylonjs.com/#ENYHSQ

**Comment by RaananW** [comment]
> Yo @RaananW ... FYI... the 6.41.2 version of the playground, which i thought had the updates from this PR. Its not working, by detecting the InitializePlayground code snippet.
> 
> Please try this simple playground that just loads the toolkit environment with physics
> 
> https://playground.babylonjs.com/#ENYHSQ
> 
> But the query string method does work
> 
> https://playground.babylonjs.com/?UnityToolkit#ENYHSQ

This happens because of typescript and the failed compilation attempt. The issue here is that declarations are first loaded after the code compiles the first time. This works:

https://playground.babylonjs.com/#ENYHSQ#1

I will see how we can deal with this better

**Comment by MackeyK24** [comment]
Ok... Thanks... I am still kool with ?UnityToolkit if we can prefix the SAVED playground url with '?UnityToolkit'.

That way if the 'using_unity_toolkit' flag is true when you save a playground, prefix the '?UnityToolkit' if it does not currently exist on the url.

Or whatever else you come up with us the SM.InitializePlayground... Im kool wit dat too

**Comment by MackeyK24** [comment]
This demo unity playground has a bit more meat and potatoes (Still working on a character controller, so it does not move yet... Just playing is idle animation for now)

https://playground.babylonjs.com/?UnityToolkit#VS103G

**Comment by RaananW** [comment]
> Ok... Thanks... I am still kool with ?UnityToolkit if we can prefix the SAVED playground url with '?UnityToolkit'.

Not sure hat you mean here. We won't change the PG snippet structure for this.

The error is quite specific for - "typescript + not assigned in the URL". I'll see what we can do to accommodate this option as well, but i'll be honest and say - I think the (window as any) is a good solution. You could also declare the UNITY namespace before the playground.

I believe I have a nice solution for this, but it will have to wait a bit. till then - window as any :-)

**Comment by RaananW** [comment]
> This demo unity playground has a bit more meat and potatoes (Still working on a character controller, so it does not move yet... Just playing is idle animation for now)
> 
> https://playground.babylonjs.com/?UnityToolkit#VS103G

Love the demo :-)
Is there a character control planned?

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14770/merge/testResults/webgpu/index.html

Note - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14770/merge/testResults/webgl2playwright/index.html

**Comment by MackeyK24** [comment]
Yo @RaananW ... Did you fix something with the typescript compile issue ?

I think is working now **without** the ?UnityToolkit query string or checking the 'Load Unity Toolkit' setting

https://playground.babylonjs.com/#ENYHSQ

and

https://playground.babylonjs.com/#VS103G

Can you please try on your end

**Comment by MackeyK24** [comment]
Well, ill wait to see if you can come up with a better way. Cause will so many references to the UNITY.SceneManager class and having to do a  (window as any) or declaring a UNITY var at the top will kind of defeat the purpose of the two declaration files (babylon.toolkit.d.ts and unity.playground.d.ts) that the UnityToolkit options is supposed to enable.

Anyways, let me know what you come up with, for now i guess i can just manually mod the saved playground url with **?UnityToolkit**

Like this:

https://playground.babylonjs.com/?UnityToolkit#VS103G


BTW... I am working on a Character Controller. I was using Ammo.js/Bullet to do my physics before, so I was using versions I modified of the **btKinematicCharacterController** and **btRaycastVehicle** classes. Havok only has the Rigidbody module, no vehicle or character controller support. So for vehicles i am working on a PORT, of a PORT that Raggar made of the Cannon Raycast Vehicle which is a PORT Bullet's btRaycastVehicle... So i made a port of all that for the Babylon Toolkit... Long story short there... I can a HavokRaycastVehicle class i made in typescript that does the same thing Ammo.js btRaycastVehicle does plus all my changes i put in the original Bullet C++ class for btRaycastVehicle

I am doing the same thing to create a character controller. Should be done soon... I hope :)

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14770/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
I am closing this for now, will keep you updated when I find a solution for the typescript issue. In JS there shouldnt be any problem.

**Pull request closed without merging**
