### PR TITLE
Adds: keysRotateUp/keysRotateDown (Free Camera)

### PR DESCRIPTION
**Pull request by Nawarius**
Possibility to rotate Free Camera up and down using the keyboard. 

https://forum.babylonjs.com/t/free-camera-rotation-keys-cameras-feature-reques/38891

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13628/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13628/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13628/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13628/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13628/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13628/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13628/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13628/merge#BCU1XR#0

**Review by sebavan — COMMENTED** [review]
LGTM letting it to the rest of the team to check :-) thanks @Nawarius

**Comment by RaananW** [comment]
Please merge from master, we had a small issue with one of the tests.

**Review by RaananW — APPROVED** [review]

**Review by PolygonalSun — APPROVED** [review]
LGTM

**Pull request merged**
