### PR TITLE
Perf regression Workaround

### PR DESCRIPTION
**Pull request by sebavan**
Repro playground: https://playground.babylonjs.com/#9YB6SB 

Runs at about 15 fps on first run, plays back at 60 fps when playing a second time

The current "workaround" makes it run at 60 fps on the first run as well. Duplicating the class Vector4 with another name worked as well as using another Temporary Vector4 🤯

This might be a wrong deopt code ???

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15817/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15817/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15817/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15817/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15817/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15817/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15817/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15817/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15817/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15817/merge/testResults/webgl2playwright/index.html

**Comment by sebavan** [comment]
closed as a workaround is in place and a min repro has been shared here https://issues.chromium.org/issues/380433753

**Pull request closed without merging**
