### PR TITLE
Erroneous morph target manager ids

### PR DESCRIPTION
**Pull request by HoferMarkus**
Fixes Bug #15668 
[Forum Post](https://forum.babylonjs.com/t/erroneous-morph-target-manager-ids/53848)
[PG example](https://playground.babylonjs.com/#M9S259#3)

While testing the models in my PG example I stumbled on another bug in the `importMesh` function.
Checking for unused transform nodes only considered the direct parent, therefore meshes couldn't be loaded if they are located in a deeply nested transform node structure.
I tried to fix that right away, works fine in my PG example.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15669/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15669/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15669/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15669/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15669/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15669/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15669/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15669/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15669/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15669/merge/testResults/webgl2playwright/index.html

**Review by deltakosh — APPROVED** [review]
Looks great!

**Pull request merged**
