### PR TITLE
NME: Fix the shadow output of the light blocks

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/nme-shadow-output-of-lights-node-doesnt-work-with-multiple-lights/43573

I tagged it as a bug, as I think it does not behave as expected when there are multiple lights: depending on the position of the light that casts shadows in the light array, it will or will not generate the right value for the "shadow" output. Also, the current code does not work when multiple lights cast shadow.

In the case of a single light casting shadows, the code from the PR gives the same output than the current code, so it's not a breaking change in this regard.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14207/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14207/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14207/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14207/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14207/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14207/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14207/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14207/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Review by deltakosh — APPROVED** [review]

**Comment by sebavan** [comment]
I wonder if the bug is still build related @Popov72 ? as the build as been fixed and I re run the tests

**Comment by Popov72** [comment]
> I wonder if the bug is still build related @Popov72 ? as the build as been fixed and I re run the tests

Indeed, there was a problem with the background material, I fixed it!

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14207/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
