### PR TITLE
SPS particle parenting feature

### PR DESCRIPTION
**Pull request by jbousquie**
New SPS simple but powerful (hope so) feature: particle parenting.

Simple to use : 
```javascript
sps.updateParticle = function(particle) {
  particle.parentId = particle.idx - 1;   // defines the previous particle in the pool as the current one parent
  // now the particle position, rotation, pivot are expressed in the parent space
}
```
example : http://jerome.bousquie.fr/BJS/test/spsParenting.html

Powerful : 600 boxes parented per stem of 10 particles each http://jerome.bousquie.fr/BJS/test/spsParenting2.html

### CODE REVIEW

**Comment by deltakosh** [comment]
You need to update the what's new for the PR to validate

**Comment by jbousquie** [comment]
arg, no idea how to add the whatsup.md file online to edit it.
I will do it tomorrow from my local repo with git.

**Comment by jbousquie** [comment]
what's new updated

**Comment by jbousquie** [comment]
oops wait a minute before merging, I'll add a tiny optimizer

**Comment by jbousquie** [comment]
done. Mergeable now from my point of view.

**Pull request merged**
