### PR TITLE
ArcRotateCamera: Modify mapPanning to account for upVector

### PR DESCRIPTION
**Pull request by PolygonalSun**
This PR contains a change to the logic for `mapPanning` so that the X/Z panning will happen with respect to whatever the current upVector is, rather than against the absolute X/Z axes.

Related forum link: https://forum.babylonjs.com/t/arcrotatecamera-mappanning-does-not-take-upvector-into-account/43820/3

Example PR to test in future: https://playground.babylonjs.com/#YSVLLN#1

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14352/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14352/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14352/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14352/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14352/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14352/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14352/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14352/merge#BCU1XR#0

**Comment by PolygonalSun** [comment]
Hey @bghgary, @deltakosh, @Popov72, and @RaananW,

Originally, `mapPanning` didn't take the `upVector` into account and would only eliminate movement on the Y-axis in World space with panning.  I talked the math over with @bghgary to verify the approach but we had determined that this change should be considered a bug fix; however, it would also technically be a breaking change.  This is because the `ArcRotateCamera` will now treat whatever vector `upVector` is as the Y-axis and if anyone enables `mapPanning` but also happens to change the `upVector` to something that isn't (0,1,0), it wouldn't work the same.  While I feel like this is a reasonable change, I wanted to talk this over with you guys to see what your thoughts were on the subject.

**Comment by sebavan** [comment]
Looks like a bug fix to me as well.

**Review by sebavan — APPROVED** [review]

**Review by RaananW — APPROVED** [review]

**Pull request merged**
