### PR TITLE
Import fix for UMD modules typing

### PR DESCRIPTION
**Pull request by RaananW**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13624/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13624/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13624/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13624/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13624/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13624/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13624/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13624/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]
@RaananW  anything possible to prevent it to happen ?

**Comment by RaananW** [comment]
> @RaananW anything possible to prevent it to happen ?

This was an error in import type and not import.
imports will fail, import type are harder to solve. But I am on it.

**Comment by slang123** [comment]
I am still getting an error when importing.

**Comment by sebavan** [comment]
@slang123 the PR will fix this one

@RaananW There was 2 import types issues reported today :-) so the investment will be worth it.

**Comment by RaananW** [comment]
> @slang123 the PR will fix this one
> 
> @RaananW There was 2 import types issues reported today :-) so the investment will be worth it.

I'll have that working soon. Will probably require compiling the director TS devhost, but, as you say, it's worth the effort. Or better yet - we must do it.

**Pull request merged**
