### PR TITLE
rotate3dBlock

### PR DESCRIPTION
**Pull request by Pryme8**
Can we have this please?

Its really useful and I tested it on my local seems to work well!

### CODE REVIEW

**Comment by Pryme8** [comment]
I added blocks for  x*0.5+0.5 and x*2.0-1.0 as well... cause it was getting annoying making frames for those.

**Comment by deltakosh** [comment]
I'm not convinced honestly. 

Some questions: 
- What is the difference between ROtate3D and Transform (existing block?)
- zeroOneblock can be done with normalize
-zeroOneInverseBlock cane be done with remap

**Comment by Pryme8** [comment]
How would I make the matrix to rotate the vector by with the transform block?

Normalize only accepts vectors and I just found remap, so the inverse is not necessary.

**Comment by deltakosh** [comment]
No problem buddy!

**Pull request closed without merging**
