### PR TITLE
Fix default render pipeline image processing

### PR DESCRIPTION
**Pull request by Popov72**
For discussion, see https://forum.babylonjs.com/t/whats-happening-in-imageprocessing-fragment-fx/11742/9

Note: don't pay attention to the change to the .obj loader, it's in another PR

### CODE REVIEW

**Comment by sebavan** [comment]
I would prefer to not change it as it will create a bit of overhead if the post pro is not used and should not necessarily impact the rendering itself ?

**Comment by Popov72** [comment]
Ok done!

**Comment by sebavan** [comment]
Actually might be changing my mind again, explanation in the forum thread, let s discuss it there for a bit more :-)

**Comment by sebavan** [comment]
I love it !!!

**Comment by Popov72** [comment]
In the `onUpdateParameters` observer:
```typescript
        this._imageProcessingConfigurationObserver = this._scene.imageProcessingConfiguration.onUpdateParameters.add(() => {
            this.bloom._downscale._exposure = this._scene.imageProcessingConfiguration.exposure;

            if (this.imageProcessingEnabled !== this._scene.imageProcessingConfiguration.isEnabled) {
                this._imageProcessingEnabled = this._scene.imageProcessingConfiguration.isEnabled;
                this._buildPipeline();
            }
        });
```
This will be called when doing `this._scene.imageProcessingConfiguration.isEnabled = enabled;` in the `imageProcessingEnabled` setter.

**Comment by sebavan** [comment]
Cooool All good for me !!!

**Pull request merged**
