### PR TITLE
Add speed and delay to camera auto orbit config/props

### PR DESCRIPTION
**Pull request by ryantrem**
This PR adds the ability to set the camera auto orbit delay and speed (as discussed here: https://forum.babylonjs.com/t/babylon-viewer-v2/54317/33).

After some discussion with @sebavan we're trying out grouping related properties together at the JS layer to reduce API surface area explosion, so I applied this pattern to tone mapping + contrast + exposure as well.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15789/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15789/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15789/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15789/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15789/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15789/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15789/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15789/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15789/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15789/merge/testResults/webgl2playwright/index.html

**Comment by RaananW** [comment]
> Putting this PR in draft

Did you mean to enable auto-merge?

**Comment by ryantrem** [comment]
> > Putting this PR in draft
> 
> Did you mean to enable auto-merge?

Yes I just forgot to update the description. The changes here are based on some feedback from @sebavan.

**Pull request merged**
