### PR TITLE
WebXR camera API

### PR DESCRIPTION
**Pull request by RaananW**
Closing #7239 

This removes the container element in the webxr experience helper and adds support to setting and getting the camera's position and rotation (and view / world matrix)

Changes:

- experienceHelper.camera is the head position / base position of the user
- camera.position can be changed and re-set
- camera.rotationQuaternion can be changed and re-set
- The rest of the TargetCamera API works as expected
- the camera's position will be set when entering XR - the x and z position and the Y-Axis rotation will be taken from the non-xr camera 
- Rig camera do not have the camera as their parent, as they receive the full transformation and not relative to the head position.
- a new observable - `onInitialXRPoseSetObservable` will allow you to alter the position and rotationQuaternion on your own (for example when setting a height other than 0 as ground level)

### CODE REVIEW

**Comment by deltakosh** [comment]
Some tests are failing :(

**Comment by RaananW** [comment]
The two validation tests. are we running webxr visualisation tests?

**Comment by RaananW** [comment]
@deltakosh - before merging - old playgrounds using the container will probably throw some errors in the console. The container is usually used when entering XR (async), so the playground will probably work correctly.

**Comment by deltakosh** [comment]
Seems not a big deal

**Pull request merged**
