### PR TITLE
Fixed #3689

### LINKED ISSUE #3689: Fix fontSize percentage support

### PR DESCRIPTION
**Pull request by JeanPhilippeKernel**

### CODE REVIEW

**Comment by JeanPhilippeKernel** [comment]
To convert px ---> % we always calculate any pixels size with 16.
So 8px --> 50 %
    125% ---> 20px
and so on..

**Comment by deltakosh** [comment]
we cannot change the way percentage are compiled as this is used everywhere
We need to fix it at fontsize level

**Comment by JeanPhilippeKernel** [comment]
Oh :(  you right !! so I move it in control with some parsing stuff

**Comment by deltakosh** [comment]
Here is a repro case: https://www.babylonjs-playground.com/#XCPP9Y#421
The text should be really large

**Comment by deltakosh** [comment]
Closing for now ;)

**Pull request closed without merging**
