### PR TITLE
Fix Right Handed light and shadow orientation regression.

### PR DESCRIPTION
**Pull request by Drigax**
This PR reverts commit c97a6e5e43f3d4727cead22972fdb8215c1d05f8 (created via PR #6712) , which inverted directional light and shadow matrices based on scene handedness. 

This PR also adds a Right handed coordinate system variant of the Soft Shadows test, with associated baseline image, and updated GLTF Serializer with Negative World Matrix to point to playgrounds with proper directional light direction initialization.

Created as part of investigation of #7377.

### CODE REVIEW

**Comment by Popov72** [comment]
In the cascaded shadow generator code there is:
```typescript
if (this._scene.useRightHandedSystem) {
    Matrix.OrthoOffCenterRHToRef(this._cascadeMinExtents[cascadeIndex].x, this._cascadeMaxExtents[cascadeIndex].x, this._cascadeMinExtents[cascadeIndex].y, this._cascadeMaxExtents[cascadeIndex].y, minZ, maxZ, this._projectionMatrices[cascadeIndex]);
} else {
    Matrix.OrthoOffCenterLHToRef(this._cascadeMinExtents[cascadeIndex].x, this._cascadeMaxExtents[cascadeIndex].x, this._cascadeMinExtents[cascadeIndex].y, this._cascadeMaxExtents[cascadeIndex].y, minZ, maxZ, this._projectionMatrices[cascadeIndex]);
}
```
to create the orthographic projection matrix of each cascade.

As I understand it (I wrote the code, but I copied what @lockphase did in the first place in this regard, as I don't master all those left/right handedness shenanigans), it was modeled after the same code found in the `DirectionalLight` class, but because this code is now removed, I think we should also update the `CascadedShadowGenerator` code?

**Comment by Drigax** [comment]
Ah @Popov72, I agree that we should update the CascadedShadowGenerator code as well. Do we have a testing scene that I can check? Most likely the CSG would fail right now for our right handed case.

**Comment by Popov72** [comment]
There is the PG linked in the doc: https://www.babylonjs-playground.com/#IIZ9UU#40

I have tried locally to set `scene.useRightHandedSystem = true;` but there are artifacts with both code (current and when only using `OrthoOffCenterLHToRef`)...

**Comment by Drigax** [comment]
Ok, this seems kind of wrong. I reverted to before the lighting change, the shadows look properly rendered:

Left hand:
image
Right hand:
image

And on the latest:
Left hand:
image
Right hand:
image

With the odd long shadow artifact visible depending on the disc location?
Left hand:
image

Right hand:
image

**Comment by Drigax** [comment]
Hmm...as you say changing the shadow matrix calculation to only use the left handed calculation results in some upside down shadow calculations?:

image

**Comment by Drigax** [comment]
Created an issue to discuss this issue specifically. Unfortunately I haven't made much headway other than changing random calculations to not much avail.

**Pull request merged**
