### PR TITLE
When the obj file contains line data, use the line fill mode material.

### PR DESCRIPTION
**Pull request by 2315137135**
https://forum.babylonjs.com/t/import-obj-model-to-scene/50911/20

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15156/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15156/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15156/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15156/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15156/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15156/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15156/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15156/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15156/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15156/merge/testResults/webgpuplaywright/index.html

**Comment by Popov72** [comment]
I think you should also handle the case when a .mtl file is provided.

So, instead of creating a material during mesh parsing/creation, you could do something like this:
* flag meshes that should have a line material (with something like `mesh._internalMetadata = true`)
* in `OBJFileLoader._parseSolid`:
  * if mtl file provided:
    * turn the material to "line" if `mesh._internalMetadata == true` for that mesh (be careful that a material could be used for a line mesh and a non-line mesh at the same time - clone the material if necessary).
    * reset `mesh._internalMetadata` to `undefined`.
  * loop over all meshes and create a line material for that mesh if `mesh._internalMetadata == true` (and reset it to `undefined`)

**Comment by 2315137135** [comment]
Now there are two questions, though not directly related to this topic .

1. The obj loader seems to use the material declared in the previous mesh for mesh with undefined material. Is this expected?

2. Blender doesn't seem to take into account the material on the curve when exporting the obj.

**Comment by 2315137135** [comment]
[test file.](https://github.com/user-attachments/files/15525889/test.zip)
Since blender does not specify materials for curves, I edited the materials in this file manually.

**Pull request merged**
