### PR TITLE
Improved typing for PostProcess constructor

### PR DESCRIPTION
**Pull request by Kesshi**
This PR improves the typing for "ratio" parameter of the PostProcess constructor.
I also modified most of the derived classes because they defined the ration as "number" only and not "number | { width: number, height: number }".

### CODE REVIEW

**Comment by deltakosh** [comment]
This seems wrong to me. Ratio should be number | PostProcessRatio

**Comment by Kesshi** [comment]
Ok i can change that if you want but PostProcessRatio should be renamed then in my opinion because its not a "ratio" anymore. Maybe PostProcessSize? Or a general PostProcessOptions for future additions?

**Comment by deltakosh** [comment]
options is cool

**Comment by Kesshi** [comment]
done

**Pull request merged**
