### PR TITLE
Fix ClearCoat Refraction V direction

### PR DESCRIPTION
**Pull request by sebavan**
https://forum.babylonjs.com/t/clear-coat-shader-compute-question/30440/4

### CODE REVIEW

**Comment by RaananW** [comment]
The failed tests were happening because of this:

https://github.com/BabylonJS/Babylon.js/pull/12540

**Comment by sebavan** [comment]
I ll wait for the other one to go in and I ll update accordingly

**Comment by RaananW** [comment]
Oh, you can merge. It was an issue with netlify (www.babylonjs.com). I now removed all references to this domain in the framework.

**Comment by sebavan** [comment]
I prefer to check back the tests results :-)

**Comment by sebavan** [comment]
You are awesome !!!

**Comment by sebavan** [comment]
I ll do a couple tests on the snapshot and merge after :-)

**Pull request merged**
