### PR TITLE
Camera: Modify Camera Movement to work off of time, instead of frame rate, revisited

### PR DESCRIPTION
**Pull request by PolygonalSun**
This PR contains modified changes from these PRs:
- https://github.com/BabylonJS/Babylon.js/pull/14482
- https://github.com/BabylonJS/Babylon.js/pull/14508

The big difference is that there were new variables added to each of the camera's movement values (eg. `pendingCameraDirection` for `cameraDirection`) that will take a user's desired movement value, calculate what value is needed to move for the initial value to match the previous movement, and decay the inertial movement over time.  It should be noted that the "pending" variables will only hold their values until consumed by the `_checkInputs` function is called by its corresponding camera.  All of the inertial values will *only* be populated with the new values *inside* of the `_checkInputs` function.

The expected behavior is that the 60 FPS behavior should be the same.  Any initial values added to a "pending" variable will move with respect to the same time frame as 60 FPS (eg. A pending movement value at 60 FPS will take one frame and 120 FPS will take around two frames)

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14809/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14809/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14809/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14809/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14809/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14809/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14809/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14809/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14809/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14809/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14809/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by sebavan** [comment]
Would be great to understand what impacted the particles changes as much ?

**Comment by PolygonalSun** [comment]
> Would be great to understand what impacted the particles changes as much ?

I think that it's because I changed the constant frame time value from 16 to 1000 / 60

**Comment by PolygonalSun** [comment]
I just want to reiterate that this PR will introduce a new variable for each of the inertial types (eg. `pendingCameraDirection` or `pendingAlphaOffset`).  While the original used values will move the camera and decrease as before, the "pending" values will take the user/input provided values, scale them to the current frame rate, and add them to the inertial value (ie. `old inertial value` = `(new pending value * scale factor) + new inertial value`)

**Comment by PolygonalSun** [comment]
> I just want to reiterate that this PR will introduce a new variable for each of the inertial types (eg. `pendingCameraDirection` or `pendingAlphaOffset`). While the original used values will move the camera and decrease as before, the "pending" values will take the user/input provided values, scale them to the current frame rate, and add them to the inertial value (ie. `old inertial value` = `(new pending value * scale factor) + new inertial value`)

Posting as reference to @sebavan, @bghgary, @RaananW, and @Popov72

**Review by RaananW — COMMENTED** [review]
LGTM

A question about the breaking change - is it the way the inertia is being taken into account? i.e. - the camera movement will be subtler now?

**Pull request closed without merging**
