### PR TITLE
recast.d.ts

### PR DESCRIPTION
**Pull request by CedricGuillemet**
follow up https://forum.babylonjs.com/t/recast-detour-in-typescript/16235/5

### CODE REVIEW

**Review by sebavan — APPROVED** [review]

**Comment by CedricGuillemet** [comment]
Let's wait for forum user feedback before merging this PR in.

**Comment by deltakosh** [comment]
good?

**Comment by CedricGuillemet** [comment]
@deltakosh waiting for feedback. I'll ping you when ready. I can switch the PR to draft if you prefer.

**Comment by deltakosh** [comment]
both are fine ;D

**Comment by CedricGuillemet** [comment]
@deltakosh All good!

**Pull request merged**
