### PR TITLE
Revert debug-classification

### PR DESCRIPTION
**Pull request by RaananW**
Debug was reduced from module to class with static members to:
1) support es6 submodules
2) reduce the amount of submodules babylon has.

As we are delaying submodules, it is safe to revert this change, yet making it still es6-safe. Debug will be a variable in ES6 but its internal variables might not be accessible. Opening the debug layer will wrok in ES6, but its internal components cannot be imported individually.

Tested locally in es6 environment and using typescript compilation

Fixing - https://github.com/BabylonJS/Babylon.js/issues/3507

### CODE REVIEW

**Comment by RaananW** [comment]
I will fix the typedoc error

**Comment by RaananW** [comment]
I am not sure I understand the error:
`Module is not Upper Case Debug (id: 11976) babylon.d.ts:5524`
Debug is upper case. should it be fully upper-case?

**Comment by deltakosh** [comment]
It should not:)
Pinging @sevan

**Comment by RaananW** [comment]
I actually put it with ignoreNaming now, let's see

**Comment by sebavan** [comment]
What convention do you want for namespace module ? I ll adapt the rule.

**Comment by deltakosh** [comment]
Namespace / Module should be fine (like class names)

**Comment by sebavan** [comment]
ok i ll add pascal case in the list of conventions for module/namespace.

**Comment by RaananW** [comment]
Let me know when the rule updates, I will merge it here and remove the ignoreNaming

**Comment by sebavan** [comment]
np, should be done in 20 minutes (in the bus atm)

**Comment by RaananW** [comment]
no wifi in buses? pfff.....

**Comment by sebavan** [comment]
:-) Should be all good.

**Pull request merged**
