### PR TITLE
Add globalThis definitions to Draco modules

### PR DESCRIPTION
**Pull request by RaananW**
The UMD definition of some of the modules didn't populate the global namespace if no loader is available. This solves it.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15127/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15127/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15127/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15127/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15127/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15127/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15127/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15127/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]
Is there a way to automate the addition to be sure we are not losing the changes on next update ? (assuming we did not change the sources)

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15127/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15127/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
> Is there a way to automate the addition to be sure we are not losing the changes on next update ? (assuming we did not change the sources)

not really, as some files are minified, some are not, syntax is different. We will need it next time we update the dependency. it took us a few years last time :-)

**Pull request merged**
