### PR TITLE
Change the URL for the snapshots server

### PR DESCRIPTION
**Pull request by RaananW**
Old URL will soon be inaccessible

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15295/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15295/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15295/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15295/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15295/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15295/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15295/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15295/merge#BCU1XR#0

**Comment by RaananW** [comment]
CI run for this PR - https://dev.azure.com/babylonjs/ContinousIntegration/_build/results?buildId=32479&view=results

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15295/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
