### PR TITLE
Fixes and performance improvement for linked GUI

### PR DESCRIPTION
**Pull request by carolhmj**
* Removing linked controls without moving the camera was causing glitching effects, this has been fixed.

linked-meshes-master

* Instead of running the _checkControls function every time a mesh is added or removed, do it before rendering, so adding multiple linked controls on the same frame performs better.

* When moving a control, only update and mark as dirty if the calculated new values have changed relative to the old ones.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13430/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13430/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13430/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13430/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13430/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13430/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13430/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13430/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13430/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Review by sebavan — COMMENTED** [review]
Wondering if more comments could be added for contributors to really well differentiate the use of isDirty vs controlListChanged about what should or should not happen ?

**Comment by carolhmj** [comment]
@sebavan added the comments!

**Review by sebavan — APPROVED** [review]

**Pull request merged**
