### PR TITLE
Update doc for CreateScreenshotWithResizeAsync

### PR DESCRIPTION
**Pull request by alexchuber**
Nit for clarity. (https://forum.babylonjs.com/t/how-should-i-use-screenshottools-create-screenshot-with-resize-async/55363)

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15996/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15996/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15996/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15996/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15996/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15996/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15996/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15996/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15996/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15996/merge/testResults/webgl2playwright/index.html

**Review by RaananW — APPROVED** [review]
LGTM!

I wonder (unrelated to this PR) - shouldn't we return the image in the promise? And allow disabling the automatic download process?

**Pull request merged**
