### PR TITLE
Added SPS visibility helpers / bbox, frustum, toussa

### PR DESCRIPTION
**Pull request by jbousquie**
Added : 
* _SPS.refreshVisibleSize()_ : just refreshes the SPS underlying mesh bounding info
* _SPS.forceVisibility()_ : sets the SPS underlying mesh as always selectable as active

As the SPS may have a variable mesh size, its bounding box may not be updated when needed so the full SPS can disappear from screen because its BBox is no longer in the frustum.
These two helpers will allow the user to update the SPS BBox on demand.

This will be documented

### CODE REVIEW

**Comment by jbousquie** [comment]
Please don't merge now, I will change some little things tomorrow

**Comment by jbousquie** [comment]
changes done

documented

**Comment by Temechon** [comment]
Can I merge ?

**Comment by jbousquie** [comment]
yes, you can !

**Comment by jbousquie** [comment]
last important commit coming !
travis is sick again ...

**Comment by jbousquie** [comment]
you can really merge now ;-)

**Pull request merged**
