### PR TITLE
STL ASCII

### PR DESCRIPTION
**Pull request by Pryme8**
STL Ascii Export Support.

I need to still add array iteration to this but in the state its in it should work to at least test my first TS script ^_^.

### CODE REVIEW

**Comment by deltakosh** [comment]
Can you revert all the file from dist?

**Comment by Pryme8** [comment]
how do I do that?

checkout the dist folder from the remote?

**Comment by Pryme8** [comment]
I ended up copying all the files from the public repository to overwrite my local dist.

Hope that was what you were meaning!

**Comment by deltakosh** [comment]
not exactly, I would like to not see the file at all in the PR (you need to git revert them before updating the PR)

**Comment by Pryme8** [comment]
Ok I will do that now!

**Pull request closed without merging**
