### PR TITLE
update package-lock.json version to match package.json

### PR DESCRIPTION
**Pull request by egnor**
I don't know if something is supposed to do this automatically in your spiffy CI setup, but the file keeps popping up in my "git status" after I run "npm install", and... normally I think it's supposed to match...?

### CODE REVIEW

**Comment by deltakosh** [comment]
Adding @RaananW  to have a look (I do not know why we have this in the lock in first place)

**Comment by RaananW** [comment]
Someone merged it once, and even since then we update it from time to time :-)


As the project is not defined by the `package.json` in the main directory (out of historical reasons), this file doesn't matter too much. Merging, as it will be good to keep it updated.

**Review by RaananW — APPROVED** [review]

**Comment by deltakosh** [comment]
How can we make it updated automatically? Or do we need it at all?

**Comment by RaananW** [comment]
npm officially recommends comitting this file, but we are using package.json a little differently.

There is no issue in removing this file. As part of the overhaul that we want to do to the build system in 5.0, it will probably be addressed as well.

**Comment by deltakosh** [comment]
Sorry I did not mean the file but the babylonjs entry. This looks weird to me

**Comment by egnor** [comment]
(I am excited to hear about a build system overhaul :-))

**Comment by RaananW** [comment]
> Sorry I did not mean the file but the babylonjs entry. This looks weird to me

We can discuss this offline if you want :-) In general, the package-lock is bound to the `package.json` in the same directory, meaning it is bound to this - https://github.com/BabylonJS/Babylon.js/blob/master/package.json, and this one lists the project as 5-alpha19.

**Comment by deltakosh** [comment]
ok but why it does not contains the same version? because we missed to merge it when it changed?

**Comment by RaananW** [comment]
It only updates if you run npm update or npm install. So to keep this updated you need to push to npm (which updates our package.json) and run npm install, and commit both.

**Comment by deltakosh** [comment]
Gotcha!

**Pull request merged**
