### PR TITLE
Make delay a local variable to improve readability

### PR DESCRIPTION
**Pull request by ericwood73**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by sebavan** [comment]
Yup nw, we discussed it with @RaananW and all good, we already asked you way more changes than required in the PR only ;-)

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13412/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13412/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request closed without merging**
