### PR TITLE
Tweaking and fixing SSAO2

### PR DESCRIPTION
**Pull request by CraigFeldspar**
+ Using Hammersley low-discrepancy sequence for better repartition of samples above 16 taps.
+ Adding `textureSamples` param for enabling native MSAA on postprocesses
+ Reducing randomtexture size for lower GPU memory usage
+ Tweaking SSAO2 shader for better visual quality (specifically avoid banding artifacts and numerical precision issues)

### CODE REVIEW

**Comment by sebavan** [comment]
LGTM :-)

A couple of questions:
* How much more expensive it is ?
* Could you remove the dist files from the commit ?
* Could you add a quick not in the What s new ?

Thanks a ton.

**Comment by sebavan** [comment]
Nope, targetting master is the way to go, preview is our deploy branch, It should only receive content from the bbabylonjs/master branch

**Comment by sebavan** [comment]
@CraigFeldspar would be pretty cool if you could also add a line in the What s new file in dist/preview relaease/ then I ll merge the PR

**Comment by CraigFeldspar** [comment]
done :)

**Comment by sebavan** [comment]
Perfect, I ll merge just after the build.

**Pull request merged**
