### PR TITLE
Add visual test for two position vertex buffers pointing to same buffer

### PR DESCRIPTION
**Pull request by bghgary**
This test is currently failing in native. Adding to JS to make sure we have the same coverage on both sides.

https://github.com/BabylonJS/BabylonNative/pull/1376 is a potential fix for native, but it causes the buffer to be retained on the CPU. The right thing to do is to fix it like we did for WebGPU.

I will be adding this test to native also.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15074/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15074/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15074/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15074/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15074/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15074/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15074/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15074/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15074/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15074/merge/testResults/webgl2playwright/index.html

**Comment by RaananW** [comment]
set to auto-merge, i prefer waiting for @Popov72 to approve :-)

**Review by sebavan — APPROVED** [review]

**Pull request merged**
