### PR TITLE
Fixes and enhancement on Havok & volumes

### PR DESCRIPTION
**Pull request by CedricGuillemet**
Follow up :
- https://forum.babylonjs.com/t/physicsshape-getboundingbox-returns-empty-object/49133/5
- https://forum.babylonjs.com/t/incorrect-size-of-physics-body/50677/5
- https://forum.babylonjs.com/t/is-there-an-easy-more-efficient-way-to-set-a-havok-physics-body-box-shape-meshs-bounding-box/48512/20

Expose Shape aabb from Havok and use absoluteScaling for aggregate volume computation instead of local scaling.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15130/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15130/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15130/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15130/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15130/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15130/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15130/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15130/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15130/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15130/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — COMMENTED** [review]
Is there a way to make it Garbage Collection free ? 

Or is it not intended to be use in the render loop ?

**Comment by CedricGuillemet** [comment]
> Is there a way to make it Garbage Collection free ?
> 
> Or is it not intended to be use in the render loop ?

I think it's mostly for debugging purpose. So it should not be called every frame and should not end up being used in production.

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
