### PR TITLE
Always pass default KTX2 decoder options

### PR DESCRIPTION
**Pull request by jure**
There is more discussion about this in the topic on the forum: https://forum.babylonjs.com/t/banding-when-viewing-uastc-ktx2-in-babylon-js-sandbox/38540

The long story short is that on second invocation of the worker, the default options are no longer being set, as the `isDirty` on the main thread that is being relied on for setting those options, is no longer `true`, due to the first time those options are sent over in: https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Misc/khronosTextureContainer2.ts#L408

The worker, however, no longer contains these options on second invocation, since, if I'm reading this correctly, it gets created anew for each job: https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Misc/khronosTextureContainer2.ts#L309

This results in a wrongly transcoded texture the second time, for example this is how it should look:
image
But this is how it looks (notice the extreme banding, flipped Y too?):
image

If there are no workers, i.e. `numWorkers = 0`, the same issue appears, since in the second `if` branch, we never set the default options of the decoder: https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Misc/khronosTextureContainer2.ts#L421

This PR fixes both of those situations.

The issue was reproduced only on macOS running either Chrome, Firefox or Edge, but not on Safari or other platforms, namely Windows. The reason for this is that by default, the capabilities of e.g. Safari include ASTC, so the ASTC transcoder is selected even without the default options, e.g.:
```js
> console.log(gl.getExtension('WEBGL_compressed_texture_astc'))
[Log] WebGLCompressedTextureASTC {getSupportedProfiles: function, COMPRESSED_RGBA_ASTC_4x4_KHR: 37808, COMPRESSED_RGBA_ASTC_5x4_KHR: 37809, COMPRESSED_RGBA_ASTC_5x5_KHR: 37810, COMPRESSED_RGBA_ASTC_6x5_KHR: 37811, …}
```
But in Chrome, for example, this extension does not exist (that's weird, no?), so the caps of the engine do not have `astc` set:
```js
console.log(gl.getExtension('WEBGL_compressed_texture_astc'));
null
```

This resolves my issue, but I'm not familiar with the inner workings of this subsystem and the potential other implications of these changes, so I would like to ask for comments & feedback. Thank you!

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13568/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13568/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13568/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13568/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13568/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13568/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13568/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13568/merge#BCU1XR#0

**Review by Popov72 — CHANGES_REQUESTED** [review]
Great catch!

I noticed there's another potential bug, so could you also perform these changes:
* line 86: change the line to `private _useRGBAIfOnlyBC1BC3AvailableWhenUASTC?: boolean = true;`
* line 96: change the line to `public set useRGBAIfOnlyBC1BC3AvailableWhenUASTC(value: boolean | undefined) {`

Thanks!

**Comment by jure** [comment]
Happy to add those two lines, @Popov72! Could you please explain just a bit about how they are source of a bug?

**Comment by Popov72** [comment]
This is because the default global options take precedence over local options passed to the `decode` function:
``javavascript
 const finalOptions = { ...options, ...KTX2Decoder.DefaultDecoderOptions } ;
```
If a parameter in the default global option can only be `true` or `false` (as was the case for `useRGBAIfOnlyBC1BC3AvailableWhenUASTC`), then it will always overwrite the value of local options. However, if a value is `undefined` in the global options, it will not overwrite the corresponding local options.

**Review by sebavan — APPROVED** [review]

**Pull request merged**
