### PR TITLE
Animation: weighted tangent key

### PR DESCRIPTION
**Pull request by noname0310**
**The `AnimationKey` can contain a \*normalized cubic bezier tangent**
- the tangent is not affected by the distance between keyframes

Example Animation creation using Bezier curve interpolation:
```typescript
const animation = new Animation("animation", "position", 30, Animation.ANIMATIONTYPE_VECTOR3, Animation.ANIMATIONLOOPMODE_CYCLE);

const keys: IAnimationKey[] = [];

keys.push({
    frame: 0,
    value: new Vector3(positions[i * 3], positions[i * 3 + 1], positions[i * 3 + 2]),
    inTangent: [
        new Vector2(0.8, 0.8),
        new Vector2(0.8, 0.8),
        new Vector2(0.8, 0.8)
    ],
    outTangent: [
        new Vector2(0.2, 0.2),
        new Vector2(0.2, 0.2),
        new Vector2(0.2, 0.2)
    ],
    interpolation: AnimationKeyInterpolation.BEZIER,
    lockedTangent: false
});
//... more keys

animation.setKeys(keys);
```

- I need to add some tests
- I'd like to get some feedback on this type of implementation
- I can always change the direction of the implementation. I have the time and passion to do so

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14410/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14410/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14410/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14410/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14410/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14410/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14410/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14410/merge#BCU1XR#0

**Comment by Popov72** [comment]
I'm not an expert in this field, so I'd really appreciate any pointers to documentations / articles / ... for cubic Bézier interpolation in the context of an animation system, in order to better judge the PR.

As explained in this [forum thread](https://forum.babylonjs.com/t/any-plans-to-support-animation-interpolation-with-cubic-bezier/43485), we don't support any file format for exporting animation data suitable for Bézier interpolation, so we won't be able to test your PR with concrete examples. This means that we need to be 100% sure that the implementation conforms to what can be expected from a Bézier curve implementation, in case we support new file formats (or extensions to existing formats) that require Bézier interpolation in the future.

For example, I see that you are linearly interpolating the x/y/z/w components of a quaternion, after applying the Bézier calculation to each component separately. This is not how Bézier interpolation is described in [this document](https://www.researchgate.net/publication/281068244_Spherical_Linear_Interpolation_and_Bezier_Curves) (or http://graphics.cs.cmu.edu/nsp/course/15-464/Fall05/homeworks/HW1.pdf). For ease of reading, here's the relevant excerpt:

image
image

Maybe what you're doing amounts to the same thing when tangents are given (or maybe the above document is irrelevant!), but as I said, I don't understand the subject enough to know. But maybe others will!

**Comment by RaananW** [comment]
The idea behind the inTangent and outTangent should be to compute the weight between 0 to 100%. After calculating the weight at a specific time point (0-100%) you can LERP/SLERP between the two values. It is especially apparent in quaternion. Animating the 4 quaternion axes is incorrect, as quaternion doesn't interpolate like a vector3 does.

Providing three inTangent(s) and 3 outs is an overkill. If someone wants to animate every axis individually they could simple animate x,y, and z instead of the vector.

So, unless I am missing something - your float computation is correct - compute the bezier curve interpolation weight based on the tangent and the gradient, Otherwise, you can use the same method to pass amount to Lerp/Slerp of the corresponding objects. Would that work for what the PR is trying to achieve?

**Comment by noname0310** [comment]
@Popov72 @RaananW 
> For example, I see that you are linearly interpolating the x/y/z/w components of a quaternion, after applying the Bézier calculation to each component separately.

This is intended implementation. Already in Babylon.js' animation system, Hermite spline interpolation was also implemented to interpolate x y z w components separately:
https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Maths/math.vector.ts#L4921-L4951

This implementation seemed strange, but I assumed that it implemented some of GLTF's animation specifications? so i decided to follow it.

And here's an exception: [blender's animation system interpolates the x y z w components of a quaternion separately](https://devtalk.blender.org/t/quaternion-interpolation/15883).
image

To apply an interpolation to a quaternion, a expression of the form *Slerp(Interpolate(x))* is probably the intended behavior in most cases.

I personally think it's useless to interpolate the four components of a quaternion separately, so if you agree with me, I could just modify this to interpolate using Slerp.

Alternatively, we could provide both a Slerp-based interpolation and a way to interpolate each component separately. This is something I've already implemented and you can check out the code here:
https://github.com/noname0310/babylon-mmd/blob/main/src/Runtime/Animation/bezierAnimation.ts#L225-L256

In fact, I was thinking of splitting the interpolation implementation using Slerp into another PR, because it doesn't seem to be related to weighted tangents per se

---

> As explained in this [forum thread](https://forum.babylonjs.com/t/any-plans-to-support-animation-interpolation-with-cubic-bezier/43485), we don't support any file format for exporting animation data suitable for Bézier interpolation, so we won't be able to test your PR with concrete examples. This means that we need to be 100% sure that the implementation conforms to what can be expected from a Bézier curve implementation, in case we support new file formats (or extensions to existing formats) that require Bézier interpolation in the future.

I think it's very important that this code is fully functional, and I've already [implemented it once](https://github.com/noname0310/babylon-mmd/blob/main/src/Runtime/Animation/bezierAnimation.ts) to more or less confirm the correct behavior, and I'll be generating test data to carefully verify the implementation.

**Comment by sebavan** [comment]
Let s first all agree if it is needed or not as the conversation on the forum ended up highlighting it might not be useful as it seems redundant with Hermite from my poor understanding of the thread :-)

Let me add @bghgary to this issue as well.

**Comment by bghgary** [comment]
> Already in Babylon.js' animation system, Hermite spline interpolation was also implemented to interpolate x y z w components separately:
> https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Maths/math.vector.ts#L4921-L4951

This is indeed not an accurate way to interpolate quaternions, but it is a fast way for an approximation and is what [the glTF spec indicates](url). Doing it with Slerp is more expensive.

> [forum thread](https://forum.babylonjs.com/t/any-plans-to-support-animation-interpolation-with-cubic-bezier/43485)

The forum thread didn't resolve. Hermite form of a cubic spline is cheaper to compute at runtime. Converting the Bezier to Hermite form would be more performant than computing the cubic spline using control points directly. Will this work for your scenario?

**Comment by noname0310** [comment]
@bghgary 
Does the Hermite implementation now in Babylon.js have the same degrees of freedom as Bezier?
If so, what parameters can express the weight of tangent?
If not, I can change the implementation to Hermite interpolation, where weight can be expressed.

**Comment by bghgary** [comment]
Sorry @noname0310, I somehow missed your message last week. We were having this discussion on the thread. It might be good to continue that discussion instead of here.

> Does the Hermite implementation now in Babylon.js have the same degrees of freedom as Bezier?

I believe so. I don't know why you think otherwise.

> I just took a fresh look at the hermite spline expression. It seems impossible to use hermite spline for animation runtime because the function is not defined in the form of a relation of y to x in hermite spline, where each control point is defined in two dimensions.
>
> This implementation will help you understand what I mean:

I think this function exactly matches your example? https://github.com/BabylonJS/Babylon.js/blob/master/packages/dev/core/src/Maths/math.vector.ts#L599-L627

**Comment by sebavan** [comment]
Any progress on this one or should we close the draft at the moment and continue on the forum until we can reopen ?

**Comment by noname0310** [comment]
> Any progress on this one or should we close the draft at the moment and continue on the forum until we can reopen ?

Okay. I'm working on it personally right now.

**Pull request closed without merging**
