### PR TITLE
U3D - BabylonJS Editor Toolkit

### PR DESCRIPTION
**Pull request by MackeyK24**
U3D - BabylonJS Editor Toolkit - Initial Release

### CODE REVIEW

**Comment by MackeyK24** [comment]
Hey Delta... Please do not change any folder or filenames. I have an update system built into the toolkit. Filenames are hardcoded in Unity C# Toolkit.

Thanks :)

**Comment by deltakosh** [comment]
as an open source project you need to provide all tools required to build the unity package

**Comment by deltakosh** [comment]
I mean as a contributor, if I change a .cs file, what should I do to update the package?

**Comment by MackeyK24** [comment]
Nothing... the .cs files are RAW unity source script files... they are compiled in unity ... Just like the original unity exporter.

**Comment by MackeyK24** [comment]
Thats why is under the main Unity 'Assets/Babylon' folder

**Comment by deltakosh** [comment]
but do tou have a script or a gulp taks to build the package?

**Comment by deltakosh** [comment]
how to build the package in redist folder?

**Comment by MackeyK24** [comment]
There is nothing to build outside of unity itself. The package in the reset folder a standard unity package. You dont 'BUILD' it... The files in the Assets/Babylon folder are standard unity assets as well... You dont build anything outside of unity.

This is the same thing as the current Unity3D2Babylon exporter... I just added ALOT of code to the existing unity scripts (plus added a few new ones). But its all pretty standard unity stuff.

**Comment by MackeyK24** [comment]
Just to clarify... You dont build unity script files outside of the unity editor. The Assets folder contains the raw project files... You would manually COPY that folder to your unity project (Just like you would with the original exporter). The preferred unity way is to use unity packages (basically the assets foles in a zip file... Then unity will proper install all the packge assets... Either by Import Package command or by store in your asset store folder and you CHOOSE BabylonJS Edit Toolkit as a packe to inlcude in creating a new project... It all prety standard unity stuff)

**Comment by deltakosh** [comment]
yep I get that but I was wondering how yo build the unitypackage. so if I want to update the one in redist, I just need to zip the assets folder correct?

**Comment by MackeyK24** [comment]
Inside unity... to build ANY package your just RIGHT-CLICK Any content your want... scripts, models, textures, materials... ANYTHING... And you say "Export Package"... 
This is way ALL packages on the asset store are created... from a source project.

Its really kool.. because WE can now use the packaging feature to package up AND ENTIRE babylonJS game... With all the assets and scripts and textures and EVERYTHING... and simple pass that package to our dev team members... the just open unity and do a "Import Package" and they will have the whole project... OR WHATEVER PARTS you select to export.

**Comment by deltakosh** [comment]
huge... I'll merge tomorrow

**Comment by MackeyK24** [comment]
K

**Comment by MackeyK24** [comment]
Yeah... It does ALOT now... Complete U3D Style BabylonJS Game Development is wrapped in there :)

**Comment by deltakosh** [comment]
Now the next step is documentation. We have a separate repo for it:
https://github.com/BabylonJS/Documentation

and more precisely: https://github.com/BabylonJS/Documentation/blob/master/content/exporters/Unity/Unity.md

You can edit it in the website or using this guide:http://www.html5gamedevs.com/topic/16365-contributing-to-documentation-101/

**Pull request merged**
