### PR TITLE
DeviceInputSystem: Update Device Input folder structure

### PR DESCRIPTION
**Pull request by PolygonalSun**
The purpose of this PR is to consolidate all of the DeviceInputSystem specific files into the DeviceInput folder.  All of the import references should also be updated.

### CODE REVIEW

**Comment by deltakosh** [comment]
Is the breaking change only about the folder structure? And why do we need that folder structure change?

**Comment by PolygonalSun** [comment]
Closing to address with team on Monday

**Comment by sebavan** [comment]
is inputInterfaces not exposed or mainly used publicly ? 

If not LTGM.

**Comment by PolygonalSun** [comment]
> is inputInterfaces not exposed or mainly used publicly ?
> 
> If not LTGM.

inputInterfaces is only used internally for the DeviceInputSystem implementations so we should be good.

**Review by sebavan — APPROVED** [review]

**Pull request merged**
