### PR TITLE
added option forceDisposeChildren to multiMaterial.dispose

### PR DESCRIPTION
**Pull request by danjpar**
Return an array of multi-materials that a single material is used in.

### CODE REVIEW

**Comment by danjpar** [comment]
Sorry, that was my first ever pull request on a major repo.
Yes. Ultimately, I just want to know when I'm disposing of a multi material
I can iterate over its submaterials to check if they're used elsewhere and
dispose of them and their textures accordingly. Disposing of multi material
itself leaves all materials and textures referenced within the scene.

**Comment by deltakosh** [comment]
No need to apologise:)
So you may prefer having an option on the multi-material.dispose to make sure to dispose its children as well?

**Comment by danjpar** [comment]
only if they are absolutely unused in other multi materials and meshes. thank you !

**Comment by deltakosh** [comment]
Far better :) 
I'm not sure we need the getBindedMaterials to be fair as this is easy to do with current API

Also please remove all the dist/ files from the PR

**Comment by deltakosh** [comment]
This is perfect. Just waiting for the build to finish and I will merge

**Comment by deltakosh** [comment]
Gonna merge manually

**Pull request closed without merging**
