### PR TITLE
world vs finalWorld fix in shader material

### PR DESCRIPTION
**Pull request by RolandCsibrei**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14469/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14469/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14469/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14469/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14469/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14469/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14469/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14469/merge#BCU1XR#0

**Review by Popov72 — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Comment by RaananW** [comment]
should this still stay in draft? or ready to merge?

**Comment by Popov72** [comment]
I'm not sure why it is in draft mode: maybe @RolandCsibrei has more changes to commit?

**Comment by RolandCsibrei** [comment]
I was not sure wheter the visualization tests will pass so I put it to draft. All went ok, you can merge, Thank you!

**Pull request merged**
