### PR TITLE
Added @babylonjs/ktx2decoder public package

### PR DESCRIPTION
**Pull request by RaananW**
This PR adds a new publich package - @babylonjs/ktx2decoder, which can be used instead of our ktx2decoder on the CDN.

This package will include the compiled wasm files, created by the khronos group. License file(s) and a notice file was added to the package, including the Khronos group and all licenses that were used to create the wasm directory.

Note - the wasm directory will be populated during build.

This PR is directly related to #14773, but both can be merged independently.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14811/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14811/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14811/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14811/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14811/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14811/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14811/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14811/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14811/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14811/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
Updated notice file

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Pull request merged**
