### PR TITLE
ArcRotateCamera pinch zoom debug

### PR DESCRIPTION
**Pull request by vousk**
ArcRotateCamera. Touch event system has been redone :

added Tools > SmartCollection
debug pinch zooming (now works on any case)
touch listeners removed (all events now rely on hand.js lib to avoid useless numerous listeners)
system ready for further more complex multitouch fantasies

To avoid some calls and objects reads during camera rotation, the last pointer object is cached (no perceptible gain however, I also let the "not cached" code version, commented, just in case - lines 137/143)

(I don't understand why the following commits list also show my local merges of bjs/bjs master branch and my previous PR on a totally different branch... Hope it won't be a mess to integrate)

### CODE REVIEW

**Comment by deltakosh** [comment]
Why a SmartCollection object? We already have the SmartArray

**Comment by vousk** [comment]
SmartArray is not applicable for the need. SmartCollection is more than an array, it's a hashtable. 
This is a "smart" version because we can access an item by its key and also by index (sometimes "for each key" is not enough or require additionnal tests to be used). With this SmartCollection we have an object that benefit of both Arrays and Literals capabilities. 
It was usefull for the pointers management, and I thought that would be usefull for further needs, but I can be wrong, what do you think ?

**Comment by deltakosh** [comment]
That's ok, you're right :) Can you just add it in the same file as SmartArray?

**Comment by vousk** [comment]
Hmm, I don't understand, should'nt we have only one class per file ?

**Comment by deltakosh** [comment]
If you prefer:)

**Comment by deltakosh** [comment]
In this case can you update all the files listed at the bottom of this doc: http://doc.babylonjs.com/page.php?p=22671

**Comment by vousk** [comment]
OK. gulpfile is already updated
I will update babylonjs.xml, and also 2.0 class list (http://doc.babylonjs.com/page.php?p=24845)
(and add this one to contributors todo list)

**Comment by deltakosh** [comment]
sounds good!

**Comment by vousk** [comment]
Can't update v2.0 classes hotlist for now because I have no doc links to put (since the class is not in the doc yet).
BTW, how is the API doc generated ? I can see some var or method description in the docs (for SmartArray class for instance), but I don't see any "JSDoc comments" in the corresponding TS source file for this class...

**Comment by deltakosh** [comment]
Do not worry for the doc. It will be auto generated:)

**Comment by vousk** [comment]
Ok I add the cell in hotlist now, and I will update with link when doc will be updated with the new class.

I'm still asking myself how "complex" method descs can be auto generated. For instance desc for push method of SmartArray is "Push method. If the length of the smart array is reached, the length of this array is doubled.". Nowhere in the code I can see that. Are you using a super smart AI based doc generator ?

**Comment by vousk** [comment]
Hmm... I cannot push my local/patch_pinchZoom changes (babylonJS.xml updated) to remote (vousk/bjs fork) patch_pinchZoom  branch, it says that my local branch is behind the remote...

What I've just done is :
. fetch and pull bjs/master branch to my local master
. switched to local/patch_pinchZoom and rebase on local/master (to simplify your integration)
. commited the xml file update to local/patch_pinchZoom 
. trying to push to remote/patch_pinchZoom (remote is vousk/bjs fork)

How can my local branch be in late compared to remote one ?

**Comment by vousk** [comment]
If I force push, will that create problem for the PR ?

**Comment by deltakosh** [comment]
I have no idea :D

**Comment by jbousquie** [comment]
@Vousk : Will you provide a doc for SmartCollection object ?
sounds very versatile

**Comment by vousk** [comment]
I'd like to, but as I said earlier in this PR, I wonder how descs are generated. For instance desc for push method of SmartArray is "Push method. If the length of the smart array is reached, the length of this array is doubled". But nowhere in the SmartArray source code I can see that comment. Is everything filled by hand in the wiki/doc ?

**Comment by jbousquie** [comment]
no idea...
for Curve3 and Path3D objects, I just wrote the doc directly in the doc site so I don't depend upon in-code doc generation.
But I guess it's better to have the doc in the code.

**Comment by vousk** [comment]
@DK: I've just noticed that VirtualJoystickCameras has a Collection inner class. I've had a quick look into it, it can be updated to use SmartCollection so we can remove inner Collection class and avoid useless code redondancy. I'll take care of that, probably next week (I'll be pretty busy in the next couple of days).

**Comment by dk** [comment]
Hi guys could you possibly avoid using "@dk" , that spams me. Thanks!

**Comment by vousk** [comment]
:-)
sorry!
I didn't even know that using "@..." sends special message to people.

**Comment by deltakosh** [comment]
Sorry Dmitry:(
For SmartCollectiin doc, please provide an article like Jerome did for Curve3.

I love your idea for virtualJoystivks, this is great:)

**Comment by vousk** [comment]
Ok I'll write an article in the doc.

**Pull request merged**
