### PR TITLE
Fix #13391 instanceof Dom Elements

### LINKED ISSUE #13391: `instanceof` will return false if element is created from a different window object than the global one
We are running into an issue where the videotexture we upload ended up drawn upside down on the canvas. After investigation, we found that the cause is this line failing.

https://github.com/BabylonJS/Babylon.js/blob/ff920e81b6b2f24d90aa64fb32f319a0727edf64/packages/dev/core/src/Materials/Textures/htmlElementTexture.ts#L101

I wonder if babylonjs has the ability to pass in the window/host object? In our case, since the element is created from a window object from another window, the global HTMLVideoElement actually refers to the one in the global window object. This causes `this._isVideo = element instanceof HTMLVideoElement;` to fail. I was able to verify this by

1. Checking the element in dev tool where `instanceof` does return false on the global HTMLVideoElement
2. Try calling `instanceof host.HTMLVideoElement` instead and it returns true
3. Patch the videotexture's `_isVideo` to be `instanceof host.HTMLVideoElement` and the code worked as expected.

This also means other `instanceof` can fail too in similar cases.

### PR DESCRIPTION
**Pull request by sebavan**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by RaananW — COMMENTED** [review]
Didn't you mean to check if it is a HTMLVideoElement and not a canvas?

**Comment by sebavan** [comment]
Fixed as discussed together

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by RaananW — APPROVED** [review]

**Pull request merged**
