### PR TITLE
adding material alphaMode description

### PR DESCRIPTION
**Pull request by Vinc3r**

### CODE REVIEW

**Comment by deltakosh** [comment]
Does it work with the new doc site?
Can't remember where you added those already

**Comment by Vinc3r** [comment]
Yep, I check that before trying this patch :)
http://doc.babylonjs.com/classes/classes/babylon.basetexture.html#coordinatesmode from 
https://github.com/BabylonJS/Babylon.js/blob/master/src/Materials/Textures/babylon.baseTexture.ts#L35

(by the way I notice that anchor links doesn't works on Firefox when accessing through http://doc.babylonjs.com/api.html?basetexture urls - works in Chrome - for coordinatesMode anchor link above, I've made right-click > copy link to get it)

**Comment by deltakosh** [comment]
Ok I'll check:)

**Comment by deltakosh** [comment]
It works for me on firefox
do you have any error in the console?

**Comment by Vinc3r** [comment]
last version of firefox (59.0.1 64b) & windows 10, newly created profile (so without addons), still the issue, and no console error (here a [video screen capture](https://i.imgur.com/vDGvDG8.mp4))

**Comment by deltakosh** [comment]
Looks like a bug to me :) but in Firefox

**Pull request merged**
