### PR TITLE
Added terrain material with bump mapping support to materials library

### PR DESCRIPTION
**Pull request by julien-moreau**
- Based on a mixmap (RGB)
- Support of bump mapping
- Documentation is coming

### CODE REVIEW

**Comment by deltakosh** [comment]
This is excellent!

**Comment by deltakosh** [comment]
Doc is required as you mentioned :)

**Comment by julien-moreau** [comment]
I'd like to add some textures to the playground and create a better Mixmap to create an awesome playground example in the documentation

**Comment by deltakosh** [comment]
Feel free to send me those textures

**Pull request merged**
