### PR TITLE
createRibbon method refactored

### PR DESCRIPTION
**Pull request by jbousquie**
added strong typing on every variable, improved scope 

sorry, I guess the whole BJS is commited with this PR

### CODE REVIEW

**Comment by raananw** [comment]
Quite an amount of file changes :-)

**Comment by jbousquie** [comment]
yep
sorry... commit/update inversion I guess :-(

**Comment by deltakosh** [comment]
OMG it will take ages to check this one :)

**Comment by jbousquie** [comment]
actually, they are only genuine BJS files
sorry again :-(

**Comment by raananw** [comment]
Maybe revert/close this one and commit from a new branch?

**Comment by jbousquie** [comment]
I closed the branch actually.
Let me know if I need to re-do everything a better way as RaananW suggests.

**Comment by deltakosh** [comment]
No that's good I cleaned it for you:)

**Pull request merged**
