### PR TITLE
Fix styling for viewer toolbar select options (Windows only)

### PR DESCRIPTION
**Pull request by ryantrem**
I recently added the default toolbar for animation controls in the alpha Viewer. I tested it on Chrome/Edge/Safari/Firefox on MacOS as well as Safari on iOS and Chrome on Android. However it turns out that only on Windows, the popup for a `select` is stylable, and so it did not render correctly since the default Viewer styling first removes all default styling for `select`s and then adds back custom styling. This change adds additional custom styling to the `option`s of the `select`s.

image

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15488/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15488/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15488/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15488/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15488/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15488/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15488/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15488/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15488/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15488/merge/testResults/webgl2playwright/index.html

**Review by PatrickRyanMS — COMMENTED** [review]
Looks good to me!

**Pull request merged**
