### PR TITLE
fix for freeCamera pointer lock and fullscreen

### PR DESCRIPTION
**Pull request by abow**
http://www.html5gamedevs.com/topic/25108-problems-with-unlocking-pointer/

http://babylonjs-playground.azurewebsites.net/#15ECGN#13

### CODE REVIEW

**Comment by abow** [comment]
You can easily see the current issue with the freeCamera controls by going to the playground and then pressing the fullscreen button.  The freeCamera controls won't work in fullscreen.

**Comment by RaananW** [comment]
Top answer your second question - yes, that would be the best way to go. Try creating a new branch per pull request, otherwise every commit will be shown here.

Regarding the code - we'll review it and let you know. Without testing - it looks fine.

**Comment by deltakosh** [comment]
@abow: I have a pending question in your code

**Comment by abow** [comment]
What's the question?

**Comment by deltakosh** [comment]
Check the code. I started a review

**Comment by abow** [comment]
Where do I find the review?  I'm not seeing it here:

https://github.com/BabylonJS/Babylon.js/pull/1352/files

**Comment by deltakosh** [comment]
image

**Comment by abow** [comment]
I'm not sure why I can't view that question on my page.

Anyway, we need to use mousemove, because the following doesn't work with pointermove:

var offsetX = evt.movementX || evt.mozMovementX || evt.webkitMovementX || evt.msMovementX || 0;
var offsetY = evt.movementY || evt.mozMovementY || evt.webkitMovementY || evt.msMovementY || 0;

**Comment by deltakosh** [comment]
Ok makes completely sense.
I will merge your PR but you need first to fix the conflict :)

**Comment by deltakosh** [comment]
(and please credit yourself here:https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/what's%20new.md)

**Comment by deltakosh** [comment]
Something went wrong with your commit. 39 files updated and you are reversing a lot of recent changes

**Comment by abow** [comment]
I'm having trouble with git.  :(

I didn't mean to commit those js files.

**Comment by RaananW** [comment]
Hi, conflicts seems to be gone, but you are still commiting a lot of files (39) for now reason. Can you try fixing that?

**Comment by abow** [comment]
I think I finally got it.

**Comment by abow** [comment]
I have one more commit I'd like to make later today that would fix the issue with going from pointer locked to pointer unlocked.  Right now, you have to click to stop the camera from moving on mouse move.

**Pull request merged**
