### PR TITLE
Fixing an issue with touch camera initialization

### PR DESCRIPTION
**Pull request by RaananW**
The code section make an incorrect assumption - 

If mouse exists, disable touch on the mouse, and the same on the touch input, However, it doesn't take into account whether or not touch (or mouse) input is enabled on the camera.

The change here will enable touch on the mouse input if touch is not enabled, and will enable mouse on the touch if mouse module is not available.

Not sure if we should consider this as a bug or a breaking change. I think it is a bug, looking for feedback.

See issue here - https://forum.babylonjs.com/t/the-free-camera-serialization-cannot-save-the-touch-screen-swipe-perspective-information/50715?u=raananw . The serialized camer haas only mouse enabled, so touch is disabled.

Playground ID to test (using touch input or emulated touch device) - #D4DKWL#2

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15141/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15141/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15141/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15141/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15141/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15141/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15141/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15141/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15141/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15141/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
