### PR TITLE
refactor: optimize getForwardRayToRef

### PR DESCRIPTION
**Pull request by GuoBinyong**
optimize getForwardRayToRef

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14531/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14531/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14531/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14531/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14531/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14531/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14531/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14531/merge#BCU1XR#0

**Comment by Popov72** [comment]
Can you provide us with benchmark data showing that the new code is faster than the existing code? We want to avoid modifying the code base if there is no justification for doing so.
Javascript optimization has nothing to do with native optimizations, and it's usually hard to tell how the code will behave in one case or another just by looking at it. Storing something like `a.b` in a variable instead of using `a.b` twice is not guaranteed to be faster, it depends on what the JVM is going to do.

**Comment by sebavan** [comment]
Completely agree with @Popov72 on this one. For any PR doing perf related changes, we need data.

**Comment by Popov72** [comment]
The PG to check performance is not that complicated: https://playground.babylonjs.com/#C9HDN5#1

I get 1.54s with the PR and 1.91s with the existing code, for 100,000,000 iterations.

I don't think it will make a difference in real code where we're not making tens of thousands of `getForwardRay` calls to each frame, but I'm ok with the PR because it makes the code more readable.

**Review by Popov72 — APPROVED** [review]

**Comment by GuoBinyong** [comment]
Yes, I used to use threeJS and CESIUM, but I'm planning to use babylonjs as my main engine recently, so I really want babylonjs to get better and better!

I'm an INTP type person, I pursue perfection, I usually write code, and I also pay a lot of attention to sentence-level optimization, so when I was researching babylonjs recently, if I found that the code needed to be optimized, even if it was a small optimization, I couldn't help but optimize it; So recently, a lot of optimization PR has been proposed, the essence is to hope that babylonjs is getting better and better, and I hope to understand!

Next, I'm going to save up as much optimized code as possible and then raise the PR to ease your work

**Comment by GuoBinyong** [comment]
Yes, I used to use threeJS and CESIUM, but I'm planning to use babylonjs as my main engine recently, so I really want babylonjs to get better and better!

I'm an INTP type person, I pursue perfection, I usually write code, and I also pay a lot of attention to sentence-level optimization, so when I was researching babylonjs recently, if I found that the code needed to be optimized, even if it was a small optimization, I couldn't help but optimize it; So recently, a lot of optimization PR has been proposed, the essence is to hope that babylonjs is getting better and better, and I hope to understand!

Next, I'm going to save up as much optimized code as possible and then raise the PR to ease your work

**Pull request merged**
