### PR TITLE
Update axes viewer

### PR DESCRIPTION
**Pull request by bghgary**
- Support setting the renderingGroupId parameter in the constructor
- Add new createInstance function
- Update names of axes properties to better represent what they are

### CODE REVIEW

**Comment by sebavan** [comment]
Is the constructor change not a problem regarding back compat ?

**Comment by bghgary** [comment]
The constructor should behave the same as before if you don't pass additional arguments. There is a breaking change on the axis properties.

**Comment by sebavan** [comment]
It should be ok as I do not think they are in use directly outside of our code (PG is returning 0 results) We ll rename back if it creates too many forum issues.

Could you log them in the readme in the breaking change section ?

**Comment by bghgary** [comment]
@sebavan This is ready to go.

**Pull request merged**
