### PR TITLE
Added ability to pass callback as key trigger parameter.

### PR DESCRIPTION
**Pull request by reimund**
This PR makes it possible to add key up/down triggers with more control than using just lowercase letters, by allowing the use of a callback function as 'parameter' value.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13538/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13538/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13538/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13538/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13538/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13538/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13538/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13538/merge#BCU1XR#0

**Comment by reimund** [comment]
This should be labeled with `new feature` but I do not think I have the rights to add labels.

**Comment by reimund** [comment]
Here's an example how this PR makes it possible to create a trigger that only triggers on uppercase R:

```javascript
scene.actionManager.registerAction(
    new BABYLON.ExecuteCodeAction(
        {
            trigger: BABYLON.ActionManager.OnKeyUpTrigger,
            parameter: function(actionEvent) { return actionEvent.sourceEvent.key === 'R'; }
        },
        function () { console.log('R button was pressed'); }
    )
);
```

**Review by RaananW — APPROVED** [review]
that's a great addition!

**Comment by RaananW** [comment]
After this is merged - it would be great to expand this section of the docs:

https://doc.babylonjs.com/features/featuresDeepDive/events/actions#triggers

**Pull request merged**
