### PR TITLE
NME: fix wrong perturbed normals when using pre-existing tangents

### LINKED ISSUE #13182: NME: wrong perturbed normal when using pre-existing tangents
The perturbed normal is not ok when the mesh has existing vertex tangents.

See:
https://playground.babylonjs.com/#LVRYCC#2

image

The cube should be identical (left: PBRMaterial, right: Node material).

### PR DESCRIPTION
**Pull request by Popov72**
Fix #13182 

Note that regarding tangents in the bump context we don't take into account the w component of the vector.

In the regular bump code, we use this component as a factor to negate the bitangent (the w component is normally either 1 or -1):

From `bumpVertex.fx`:

```typescript
#if defined(BUMP) || defined(PARALLAX) || defined(CLEARCOAT_BUMP) || defined(ANISOTROPIC)
	#if defined(TANGENT) && defined(NORMAL)
		vec3 tbnNormal = normalize(normalUpdated);
		vec3 tbnTangent = normalize(tangentUpdated.xyz);
		vec3 tbnBitangent = cross(tbnNormal, tbnTangent) * tangentUpdated.w;
		vTBN = mat3(finalWorld) * mat3(tbnTangent, tbnBitangent, tbnNormal);
	#endif
#endif
```

We don't do it in the NME: should we? If yes, we need to discuss it, I don't see a way to do it without a breaking change...

### CODE REVIEW

**Comment by sebavan** [comment]
Should this not also apply to anisotropy and clear coat block ???

**Comment by sebavan** [comment]
Cool thanks a lot, I am not sure to understand the impact of the breaking change you are mentioning ?

Isnt it more like a bug fix as the materials won t be broken, just lit properly ?

**Comment by Popov72** [comment]
It's not a bug fix if `tangent.w=+1` for all vertices, so for a number of people what we currently do is ok: I don't know if `tangent.w=-1` is used a lot or not in models...

The breaking change I'm speaking about is in the implementation on our side: the existing node materials using perturbed normals + pre-existing tangents would break if we implement the change. The users will have to fix their node materials to account for the change. At least it's what I think would happen but I didn't think about it too thoroughly, so maybe we should discuss about that issue.

**Comment by sebavan** [comment]
Makes sense !!! Let s chat on wednesday

**Review by sebavan — APPROVED** [review]

**Pull request merged**
