### PR TITLE
Ammo.JS Update

### PR DESCRIPTION
**Pull request by MackeyK24**
BtSmoothTriangleMesh Support - Smooth Mesh Collider Content Using Barry Normal Interoperation

### CODE REVIEW

**Comment by sebavan** [comment]
Did you use all the flags as @CedricGuillemet was doing on the previous builds ?

**Comment by MackeyK24** [comment]
I didnt know @CedricGuillemet was doing the C++ builds for Ammo.js (I thought he was handling Recast/Detour)

Anyways... I made the first custom build of Ammo.js and the main thing was to get the Ammo.addFunction support with a 128MB stack (instead of default 64MB). This was how the last Ammo.js builds i submitted a while ago.

Kripen has changed the Ammo.js build system and now uses CMAKE to build. There are now only couple switches and i am using the default switches kripen uses to build the main ammo.js (Except 128MB stack)

and that is:
```
$ cmake -B builds -DCLOSURE=1 -DTOTAL_MEMORY=134217728
$ cmake --build builds

```

But that should be the release build switches. I am not sure how or what switches @CedricGuillemet might have used to build a Ammo.js

**Comment by sebavan** [comment]
Perfect I ll merge it and if it misses anything, @CedricGuillemet can spot it when he is back :-) is the BtSmoothTriangleMesh Support planned to be merged upstream or are you on a custom fork to expose it ?

(trying to ensure that next build would not remove it)

**Comment by MackeyK24** [comment]
BtSmoothTriangleMesh was a Babylon Feature i added to smooth out mesh collider contacts. According to this document

[Vehicle_Simulation_With_Bullet.pdf](https://github.com/BabylonJS/Babylon.js/files/5721384/Vehicle_Simulation_With_Bullet.pdf)

This is how i am doing all that fancy Need For Speed Driving using Ammo.js and btRaycastVehicle (and BtSmoothTriangleMesh)

**Comment by MackeyK24** [comment]
Should we start a Babylon Fork of the kripen/ammojs project ???

**Comment by sebavan** [comment]
Nah, I would definitely prefer not to and @MackeyK24, your new release is breaking some previously working code :-( I have to revert this PR. The ammo.js generated file seems to be the culprit, I am not sure what change and if intented. I will revert your latest push for the time being. Feel free to make another PR once you have it fully ok. It looks like the js generation is not the same anymore.

**Comment by sebavan** [comment]
It looks like the module generation might be different: 
image

and creating the issue. In this case, I guess the plugin should be updated to reflect the changes, but please double check it is all ok.

**Comment by sebavan** [comment]
Revert is following this thread: https://forum.babylonjs.com/t/ammo-typeerror-on-reloading-playground-need-to-click-play-button-to-bypass-error/16891/4

**Pull request merged**
