### PR TITLE
Blender tag: export tags

### PR DESCRIPTION
**Pull request by kpgbrink**
I added an option to add tags to meshes in blender. Right now this only works for meshes.

### CODE REVIEW

**Comment by deltakosh** [comment]
ping @jcpalmer

**Comment by deltakosh** [comment]
ping @palmer-jc

**Comment by Palmer-JC** [comment]
Well, if BJS will read this, seems ok.  The __init__.py version should be updated to 5.2.  The zip file "Blender2Babylon-5.2.zip" also needs to be generated.  I can do this if reqd, but would not get to till tomorrow, probably.

**Comment by binki** [comment]
Should the bumping and zip-generation be part of the PR? I assumed it made more sense for the repo maintainers to do that because if there are multiple PRs for the blender exporter and they all regenerate the zip and touch the version, merging one would make the others unmergeable.

**Comment by Palmer-JC** [comment]
For the main Typescript stuff transpiled to Javascript, yes.  Blender exporter a little sleepy part of repo.  I am not doing anything right now.  I can do it, or you might.

**Comment by Palmer-JC** [comment]
Please accept.  I'll zip / update version

**Pull request merged**
