### PR TITLE
Feature.update other mesh positions

### PR DESCRIPTION
**Pull request by jbousquie**
Added two final user features : Lines mesh and Tube mesh update.
This works on the model of ribbon update with the original _CreateXXX()_ method to which the existing mesh to be updated is passed as last parameter : the parameters changing vertices positions can be passed and will update the mesh, the others are ignored.

Lines : 
```javascript
var points1 = [v1, v2, ..., vN];  // vector3 array
var lines = BABYLON.Mesh.CreateLines("lines", points1, scene, true);
var points2 = [u1, u2, ..., uN];  // another vector3 array
lines = BABYLON.Mesh.CreateLines(null, points1, null, null, null, lines);
```
Tube : 
```javascript
var path1 = [v1, ..., vN];  //vector3 array : tube axis1
var radius1 = 5;
var path2 = [u1, ..., uN]; // another vector3 array : tube axis2
var radius2 = 8;
var tube = BABYLON.Mesh.CreateTube("tube", path1, radius1, 12, null, scene, true);
tube = BABYLON.Mesh.CreateTube(null, path2, radius2, null, null, null, null, tube);
```
Of course, it also works with the _radiusFunction_ parameter : 
```javascript
var radiusFunction1 = function(i, distance) { ... };
var radiusFunction2 = function(i, distance) { ... };
var tube = BABYLON.Mesh.CreateTube("tube", path1, null, 12, radiusFunction1, scene, true);
tube = BABYLON.Mesh.CreateTube(null, path2, null, null, radiusFunction2, null, null, tube);
```

Under the hood, a new class (and file) was created : TubularMesh.
It just embbeds some final user parameter usually lost in the underlying ribbon creation (tessellation) and keeps pointers on some intermediate tube objects used while its construction in order to re-use them when updating the tube instead of re-creating them.

Both tube and lines can be now updated this way in the render loop.

### CODE REVIEW

**Comment by deltakosh** [comment]
Adding a new file is not straight forward unfortunately. Check the final part of this doc: http://doc.babylonjs.com/page.php?p=22671

**Comment by RaananW** [comment]
Is the new class really needed in that case? If it is just a placeholder for data you can simply cast to any or use mesh["property']. 
Then you don't have to update the other files as well.

**Comment by jbousquie** [comment]
Ok, I will then follow Raanan's advices and remove the new class file... tomorrow.

**Comment by jbousquie** [comment]
The tubularMesh class file was deleted.
The same mesh update feature is added to _ExtrudeShape()_ and _ExtrudeShapeCustom()_ : just pass the existing instance as last parameter to the same _CreateXXX()_ method.
```javascript
var shape1 = [s1, s2, ...sN];  // Vector3 array
var shape2 = [t1, t2, ...tN];    // another Vector3 array
var path1 = [p1, p2, ...pN]; // Vector3 array
var path2 = [q1, q2, ...qN]; //  another Vector3 array
var scale1 = 1;
var scale2 = 3;
var rotation1 = 0;
var rotation2 = 0.2;
// extrusion
var extruded = BABYLON.Mesh.ExtrudeShape("ext", shape1, path1, scale1, rotation1, scene, true);
// mesh update
extruded = BABYLON.Mesh.ExtrudeShape(null, shape2, path2, scale2, rotation2, null, null, null, extruded);
```
Idem for _ExtrudeShapeCustom()_ accepting _scaleFunction_ and _rotateFunction_ parameters : 
```javascript
// path and shape var declared before ...
var myScale1 = function(i, distance) { ... };
var myScale2 = function(i, distance) { ... };
var myRotation1 = function(i, distance) { ... };
var myRotation2 = function(i, distance) { ... };
// extrusion
var ext = BABYLON.Mesh.ExtrudeShapeCustom("ext", shape1, path1, myScale1, myRotation1, false, false, scene, true);
// mesh update
ext = BABYLON.Mesh.ExtrudeShapeCustom(null, shape2, path2,  myScale2, myRotation2, null, null, null, null, null, ext);
```
Both new functions can be used in the render loop.

The funny part is, as _ExtrudeShape()_ and _ExtrudedShapeCustom()_ build the same mesh (only parameters change), you can create a simple extruded shape with _ExtrudeShape()_ and then morph it with _ExtrudeShapeCustom()_ if you need more complexity.
```javascript
var ext = BABYLON.Mesh.ExtrudeShape("ext", shape1, path1, scale1, rotation1, scene, true);
// mesh update
ext = BABYLON.Mesh.ExtrudeShapeCustom(null, shape2, path2,  myScale2, myRotation2, null, null, null, null, null, ext);
```

**Pull request merged**
