### PR TITLE
Oimo parameter updated.

### PR DESCRIPTION
**Pull request by Temechon**

### CODE REVIEW

**Comment by Temechon** [comment]
It worked with the very first version of Oimo committed in the repo, but never after as the method prototype changed.

**Comment by RaananW** [comment]
So the version in the repo should also be updated? The last commit in oimo was 8 months ago, is that the newest version?
Just want to make sure it won't harm shady existing implementations

**Comment by Temechon** [comment]
Oimo in the repo is the last version (Oimo hasn't been updated for 8 months). 

On the first Oimo commit, setPosition took 3 parameter, so the Babylon plugin worked. Then Oimo was updated, and Babylon repo was updated as well: Oimo.setPosition (and Oimo.setRotation) prototype has been updated, but not the Babylon plugin. My fix make the last Oimo version work with Babylon (as it didn't work before that)

**Comment by RaananW** [comment]
Prefect, thank you :-)

**Comment by Temechon** [comment]
You're welcome ! Hooooo you can merge PR now ! xD Awesome !

**Comment by deltakosh** [comment]
Are you interested?

**Comment by Temechon** [comment]
Ha wai grave ! What do you need from me ?

**Pull request merged**
