### PR TITLE
fixed leaking observables in Rendering

### PR DESCRIPTION
**Pull request by ricardovg4**

### CODE REVIEW

**Review by RaananW — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15860/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15860/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15860/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15860/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15860/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15860/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15860/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15860/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15860/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Comment by ricardovg4** [comment]
@RaananW Hi, I wonder why some visualization checks in WebGPU timed out? I think it was on either: https://playground.babylonjs.com/?version=7.34.4#N55Q2M#8   OR https://playground.babylonjs.com/?version=7.34.4#Y6W087#71   

I checked those manually with the playground and local version with changes and all seems good.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15860/merge/testResults/webgpuplaywright/index.html

**Comment by Popov72** [comment]
Just so I understand, why doesn't clear the observable in the “dispose” function cause a (memory) leak? I would have thought that when the instance of a class is no longer accessible, the memory used by the observable (and by all the other resources inside the class for that matter) will be reclaimed by the browser at some point, and the same goes for observers inside the observable?

**Comment by deltakosh** [comment]
Because the observable is retained by its clients through the capture that happens when we add a function to the observable. I'm looking at using weakref so this may not be necessary anymore

**Pull request merged**
