### PR TITLE
Fixes Bounty #Basic USD/Z export -Draft

### PR DESCRIPTION
**Pull request by Pryme8**
Just looking for some code review and some direction on where to go next with this.

Probably need a list of GLB/GLTFs we want to run this on and get the script validated that its working on more than just the DamagedHelmet model.

### CODE REVIEW

**Comment by Pryme8** [comment]
I'm not sure why this has such a long list of commits?

Its like every single commit anyone has done between now and the last time I did a PR.

Any suggestions on how to clean this up?

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by Pryme8** [comment]
> Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s). To prevent this PR from going to the changelog marked it with the "skip changelog" label.

I do not have the option to add or edit labels it seems.

**Comment by Popov72** [comment]
cc @RaananW regarding the long list of commits.

**Review by RaananW — CHANGES_REQUESTED** [review]
Merging this PR as is will cause the repo history to be incorrect. The best solution would be to re-fork babylon and applying the changes to an updated branch. but we can't merge it as is.

**Pull request closed without merging**
