### PR TITLE
Added Generics to the tasks.

### PR DESCRIPTION
**Pull request by RaananW**
This way, the tasks' onError and onSuccess will deliver the right type and no casting will be needed. The add?????Task of the AssetsManager will also deliver the right type, which can be very helpful :smile:

```javascript
let task = assetsManager.addTextureTask("download texture", "/textures/");
task.onError = (task, message, exception) => { console.log(task.texture);}; // was not valid until now
```

Continuing this -https://github.com/BabylonJS/Babylon.js/pull/3111 .

### CODE REVIEW

**Comment by Kesshi** [comment]
This PR introduces a compile error again if the strictFunctionTypes option is enabled:

babylon.d.ts(15717,20): error TS2420: Class 'AbstractAssetTask' incorrectly implements interface 'IAssetTask<AbstractAssetTask>'.
  Types of property 'onSuccess' are incompatible.
    Type '(task: this) => void' is not assignable to type '(task: AbstractAssetTask) => void'.
      Types of parameters 'task' and 'task' are incompatible.
        Type 'AbstractAssetTask' is not assignable to type 'this'.

15717     abstract class AbstractAssetTask implements IAssetTask<AbstractAssetTask> {
                         ~~~~~~~~~~~~~~~~~

**Comment by RaananW** [comment]
Not sure how you try to compile this, but this was, of course, fully tested (otherwise we wouldn't have been able to update the dist js files).
Care to share a bit mroe information? Are you trying to use this in code? are you using the Abstract class as a type?
I have updated the documentation, maybe this will help - http://doc.babylonjs.com/how_to/how_to_use_assetsmanager

**Comment by Kesshi** [comment]
I'm not using any AssetTasks. My project is referencing the babylon.d.ts
I compile my project with typescript 2.6.1 and all strict options enabled.
(BabylonJs itself still uses typescript 2.5.3 which does not support strictFunctionTypes)

**Comment by RaananW** [comment]
Gotcha.
Our gulp script is still using 2.5.3 . We actually dont have strictFunctionTypes enabled. Let me see if I can fix this. and the rest of the (ca. 100) errors :)

**Comment by RaananW** [comment]
Just an update - strictFunctions check was enabled and is available as version 3.1.0-beta6 on NPM

**Pull request merged**
