### PR TITLE
First version of module-testing

### PR DESCRIPTION
**Pull request by RaananW**
There are curently two tests that are running one after the other - 
1) vanilla-typescript that loads the dependencies and calling the runTests function wit the global namespace
2) webpack-typescript that bundles the dependencies and loading them using es6 imports.

the source is being compiled and bundled (when using a bundler).

There are two iunternal tests running - checking that the dependencies actually loaded, and loading a GLTF model.

Further tests will be added shortly.

At the moment this is not part of the "tests" task. to trigger this test, call gulp tests-modules.

### CODE REVIEW

**Comment by deltakosh** [comment]
OK to merge?

**Comment by RaananW** [comment]
This and the gulp 4 branch will conflict. Both are ok to merge, I just need to know which one is being merged first :smile:

**Comment by deltakosh** [comment]
merge in the order you want:)

**Comment by RaananW** [comment]
I will merge this branch to the gulp 4, fix conflicts and merge to master

**Comment by RaananW** [comment]
Closing this PR

**Pull request closed without merging**
