### PR TITLE
Update VSCode settings to include Prettier

### PR DESCRIPTION
**Pull request by dr-vortex**
Updates VSCode workspace settings so that the prettier extension will format correctly.

### CODE REVIEW

**Comment by RaananW** [comment]
image

This is from the vscode extension. Again, I am not sure why it is needed

**Comment by BabylonJSGuide** [comment]
> This is from the vscode extension. Again, I am not sure why it is needed
> 
> If it doesn't work as expected it is a different issue, but duplicating the configuration is redundant and should not be the accepted solution

Agree.

 I once found Prettier didn't work for me, all because I didn't do npm install, since then I have used it very successfully with VSCode.

**Comment by dr-vortex** [comment]
[prettier.webm](https://user-images.githubusercontent.com/75621402/192045561-ea49eac7-efc1-4a8e-b3e8-68833cb48a7f.webm)
This video clearly shows that it is an issue, and does not work. Also, this is on vscode.dev/github.dev so npm is not an option. If anything, the setting would work as a compatibility measure.

**Comment by BabylonJSGuide** [comment]
> so npm is not an option

I am not a developer just a hobbiest but what I do know is how much more straightforward @RaananW has made contributing to Babylon.js over time. I also know that when I follow the steps from [contribute](https://doc.babylonjs.com/contribute/toBabylon), i.e

1. Use VSCode
2. Install Prettier as default formatter in VSCode
3. Clone Babylon.js to local folder
4. Do npm install in local Babylon.js folder
5. Use VSCode to make code changes
6. Ctrl + Shift + P Format Document
7. Terminal Run Build Task

I have no failures when submitting a PR. 

Recently I did a new clone and fogot about step 4, so Prettier didn't work.

I trust @RaananW if he says this PR is not necessary.

**Pull request closed without merging**
