### PR TITLE
Physics Bug Fixing

### PR DESCRIPTION
**Pull request by RaananW**
Delta rotation should be conjugated, otherwise the body will keep on
constantly flipping (if deltaRotation is set).
cannonJS collision of joined objects improved.
Added Conjugate function to the quaternion class.

### CODE REVIEW

**Comment by nockawa** [comment]
#1000 milestone reached! yey champagne!

**Comment by deltakosh** [comment]
That's a lot!

**Comment by RaananW** [comment]
1000 ftw!
Should have commited more than a bug fix :smile:

**Comment by rsarieddine** [comment]
That's pretty awesome!

**Pull request merged**
