### PR TITLE
Fix #13536

### LINKED ISSUE #13536: Add up/down arrow control to NME search results
When using the new "spacebar to search" functionality, with each key press the results query updates to any nodes that match the input term. A user may see the node they want in a position other than the first. For example, typing "col" will return `Color3` first and `Color4` second. If the user wants a `Color4`, they need to continue typing the rest of "color4" to get `Color4` return first to press enter and place the node. The other way is to grab the mouse and hover `Color4` and click. This feature would speed up the process. Consider the following flow:

image

1. The user presses spacebar and types "col"
2. The results show `Color3` first, highlighted the same as if it were hovered with the mouse. It shows `Color4` as the second return.
3. Since the `Color3` is highlighted, pressing enter will place the `Color3` node.
4. If the user wants to place a `Color4` instead, pressing the down arrow once will move the highlight down one space in the returned list to highlight the `Color4` node. 
5. With the `Color4` node highlighted, pressing enter will place the `Color4` node
6. If the user had the `Color4` node highlighted, but decided instead to place a `Color3` node, pressing the up arrow once will move the highlight up one space in the returned list to highlight the `Color3` node. 
7. Repeated presses of the up or down arrow will move the highlight up or down by one item with each press.

For this to work as we have the initial feature working, we always need to highlight the first node in the returned list so that the user knows that pressing enter without using the mouse will return the first node. Currently we don't highlight anything until the mouse hovers a returned node in the list. Using the arrow keys to modify what is selected by moving the highlight on arrow press will often result in fewer key presses and no lost time reaching for the mouse.

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13899/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13899/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13899/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13899/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13899/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13899/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13899/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13899/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Comment by carolhmj** [comment]
This is soooo good to use! gg!

**Pull request merged**
