### PR TITLE
font inheritance changes

### LINKED ISSUE #13130: [GE] Control font style inheritance
Related forum discussion: https://forum.babylonjs.com/t/gui-editor-inputtext-is-now-missing-font-selection/33370/12

> We can express the idea of default even more simply by just adding a new possible value for font family, “inherit”. If a control has control.fontFamily = "inherit" set, then we adopt the inheritance rules. I initially had thought about assuming that if fontFamily was not set then adopt inheritance, but this would be a different behavior from the current one so there is back compat to take into account.

> As an additional bit of UI, if the control has fontFamily set to inherit and we’re on the GUI Editor, we could display what family it’s currently inheriting from on the font parameters section.

The inheritance rules should be: if a control is set to "inherit", then adopt the style of its first parent that has a style other than "inherit". If no parents have a style other than that, then use the system default.

Inheritance rules could also be implemented for more properties, like the CSS "inherit": https://forum.babylonjs.com/t/null-style-properties-shouldnt-override-set-properties-on-applied-controls/32253

### PR DESCRIPTION
**Pull request by carolhmj**
Fix #13130

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by RaananW — COMMENTED** [review]
where is the inheritance? Am I missing some function that hasn't changed?

**Comment by Popov72** [comment]
I'm not sure the visualization test can detect a problem, since it's based on a difference between the snapshot and the generated images. I think you should enlarge the text or add a lot more text to increase the chances of the visualization test detecting a problem.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14431/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14431/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
