### PR TITLE
Canvas2D: dispose SceneNode of a WorldSpaceCanvas 

### PR DESCRIPTION
**Pull request by nockawa**
when this is created automatically and when the Canvas is disposed.

https://trello.com/c/y4U62vn4

### CODE REVIEW

**Comment by nockawa** [comment]
[WSC Dispose should dispose the Scene Mesh if it's the one that were automatically created](https://trello.com/c/y4U62vn4/65-wsc-dispose-should-dispose-the-scene-mesh-if-it-s-the-one-that-were-automatically-created)

**Comment by KingMaks** [comment]
Hello, I decided to try preview release version of babylon and get error
"Uncaught TypeError: BABYLON.Sprite2D is not a constructor(…)", but in the version babylon 2.4 all works.
I use a typescript version of babylon and canvas2d. In the version babylon 2.4 babylon.d.ts and convas 2d it was one file, but now it is two files a babylon.d.ts and a babylon.canvas2d.d.ts.

**Comment by nockawa** [comment]
@KingMaks my bad, I think the releases are unsync. I was supposed to update them but forgot, I do it right away.

**Comment by nockawa** [comment]
@KingMaks  done, please retry with the new version, and let me know, sorry for the inconvenience.

**Comment by KingMaks** [comment]
@nockawa nothing changed, maybe I am doing somthing wrong?

**Comment by nockawa** [comment]
you now need to reference two js files in order for canvas2D to work, something like this:

```javascript
    <script src="babylon.max.js"></script>
    <script src="babylon.canvas2d.max.js"></script>
```

All the code related to Canvas2D was moved from the babylon.js file to a independent file that you need to include.

**Comment by KingMaks** [comment]
@nockawa yes, I am doing exactly.
///<reference path="libs/babylon.d.ts"/>
///<reference path="libs/babylon.canvas2d.d.ts"/>

and if write let's say console.log(BABYLON.Sprite2D) we get undefined

**Comment by nockawa** [comment]
are you using the max.js or the minified version? in the .max.js of canvas2d I can find many reference to Sprite2D as well as its constructor, so I don't really understand...
Sorry, but JS is not my specialty... maybe @deltakosh or @RaananW  can help on this, I'm getting clueless...

**Comment by KingMaks** [comment]
@nockawa  I am using 
http://s8.hostingkartinok.com/uploads/images/2016/11/1d1e64eed34ebe28b70c06d58048af63.png

**Comment by nockawa** [comment]
these are the definition files that let you code in typescript using babylon as typescript classes.
it works fine at compile time, but at runtime you need to include the actual .js files of both babylon.js and babylon.canvas2d.js.
Do you reference the .max.js or just the .js files?

**Comment by KingMaks** [comment]
@nockawa Oh really, just the .js files

**Comment by KingMaks** [comment]
@nockawa Oh really, just the .js files

**Comment by nockawa** [comment]
I've just tried locally and the exact same repo I used locally to update the main repo is working fine when I reference the .js files of both bjs and c2d. I have the Sprite2D unit test working correctly on screen, just by loading the two .js files.
There might be something you miss.

**Comment by KingMaks** [comment]
@nockawa It is probably, I am doing something wrong. Thank for quick answer and for help. I will be find what I am doing wrong.

**Pull request merged**
