### PR TITLE
PBR NME: Support of ClearCoat

### PR DESCRIPTION
**Pull request by Popov72**
There are also a number of small changes to the PBRMetallicRoughness block.

### CODE REVIEW

**Comment by sebavan** [comment]
Looks like the tests are failing, but it was looking good :-)

**Comment by Popov72** [comment]
Tests should be fixed with the latest commit.

**Comment by Popov72** [comment]
Don't merge yet please, there's a problem with clear coat direct lighting.

**Comment by Popov72** [comment]
Fixed now.

**Pull request merged**
