### PR TITLE
NME: Add a CSS class to all graph nodes

### LINKED ISSUE #13329: Light information block output names rendering incorrectly
Output names on the `LightInformationBlock` are colliding with the sockets and rendering outside the block. This is visible in NME by dragging the Light Information block onto the workspace.

image

### PR DESCRIPTION
**Pull request by Popov72**
Use this new feature to widen the `LightInformationBlock`.

Closes #13329

### CODE REVIEW

**Review by sebavan — APPROVED** [review]
Pretty Smart !!!

**Comment by sebavan** [comment]
Just a quick question, does that not conflict on any of the current nodes ? (I guess not cause in the worst case, it might double the className I believe)

**Comment by Popov72** [comment]
> Just a quick question, does that not conflict on any of the current nodes ? (I guess not cause in the worst case, it might double the className I believe)

As I could see it, there is only a single CSS class added to graph node elements, and this class seems to be auto-generated as it is not readable at all:

image

The PR is adding a second class on the main `div` element of the node at creation time, so I don't think it's possible to have this class doubled(?)

**Comment by sebavan** [comment]
I added @RaananW and @carolhmj for review :-)

**Review by RaananW — APPROVED** [review]

**Pull request merged**
