### PR TITLE
Add a new camera : VRDeviceOrientationArcRotateCamera

### PR DESCRIPTION
**Pull request by Temechon**
Also fixed some bugs on VR mode for ArcRotateCamera

### CODE REVIEW

**Comment by deltakosh** [comment]
Do you mind adding the new camera in the existing file(where the freecamera version belongs) ?

**Comment by Temechon** [comment]
in babylon.vrDeviceOrientationCamera ?

**Comment by deltakosh** [comment]
correct :)

**Comment by deltakosh** [comment]
And welcome back :D

**Comment by Temechon** [comment]
Ask and you shall receive :D

**Comment by deltakosh** [comment]
Lovely!

**Pull request merged**
