### PR TITLE
Update meshSimplification.ts

### PR DESCRIPTION
**Pull request by aWeirdo**
Would it be ok to add a check if setting.distance exists?

I'd like to use the function without LOD :)

### CODE REVIEW

**Review by sebavan — CHANGES_REQUESTED** [review]
could you change `void 0` to the usual checks we do in the rest of the code ??? Some typescript ppl might be less confortable with this notation

**Comment by aWeirdo** [comment]
problem is it can be 0, 
then it'll have to be typeof() === 'undefined' check to avoid false negative

**Comment by sebavan** [comment]
Why not simply settings.distance !== undefined ?

**Comment by aWeirdo** [comment]
you're right :)
done

**Review by sebavan — APPROVED** [review]

**Pull request merged**
