### PR TITLE
Add support for cannon-es in plugin

### LINKED ISSUE #9810: Cannon-es support
Using the maintained [Cannon-es](https://github.com/pmndrs/cannon-es) version of Cannon, with Babylon.js results in the following error.

```javascript
import * as Cannon from 'cannon-es';
window.CANNON = Cannon;
```

```javascript
TypeError: this.world.add is not a function. (In 'this.world.add(impostor.physicsBody)', 'this.world.add' is undefined)

135 | this.world.addEventListener("preStep", impostor.beforeStep);
136 | this.world.addEventListener("postStep", impostor.afterStep);
137 | impostor.physicsBody.addShape(shape);
> 138 | this.world.add(impostor.physicsBody);
^  139 |
140 | //try to keep the body moving in the right direction by taking old properties.
141 | //Should be tested!
```

This is also discussed on the Babylon.js forum and on the Cannon-es github:
- https://forum.babylonjs.com/t/how-does-react-use-the-cannon-js-physics-engine/10275/9?u=tim-montague
- https://github.com/pmndrs/cannon-es/issues/68

### PR DESCRIPTION
**Pull request by frankieali**
closes #9810

Check for cannon-es method `addBody` for generating a physics body. Fallback to cannonjs method `add`.

### CODE REVIEW

**Review by CedricGuillemet — APPROVED** [review]
LGTM !

**Comment by deltakosh** [comment]
Just a lint issue and we can merge :)

**Comment by frankieali** [comment]
Missing whitespace! Oh boy, I'm going to have to install your lint rules to make sure I catch all the lint errors.

**Comment by frankieali** [comment]
For some reason `npm install` failed on the Build and Unit Tests step, but Linting passed. Any idea why the other step failed?

**Comment by deltakosh** [comment]
Hey, do you mind trying to sync with master ? Just to make sure you have all the latest

**Comment by frankieali** [comment]
I see I have to add to the `what's new.md` file for this to pass CI. Would this ticket be filed under "Bugs" or under a new entry for "Physics" or perhaps "Plugins"?

**Comment by deltakosh** [comment]
As you wish:) It is your baby :)

**Pull request merged**
