### PR TITLE
Managed Scene Component API

### PR DESCRIPTION
**Pull request by MackeyK24**
Managed Scene Component Life Cycle

### CODE REVIEW

**Comment by MackeyK24** [comment]
What the heck is this compiler's problem with my typescript code ???

**Comment by deltakosh** [comment]
This is really cool. Only one ask: can you move it under exporters/unity3d?

**Comment by MackeyK24** [comment]
This is the new PURE BabylonJS Managed Scene Component API. Can now use all the Scene Manager And Scene Component API from runtime using just code and NO UNITY

There will be the actual 'U3D - BabylonJS Toolkit' which i will put in exporters/unity3d... That new toolkit will use the new pure BabylonJS Scene Manager on the preview index page... Other than that the Unity Exporter is now JUST A GAME IDE... All the Managed Scene Component API is now pure BabylonJS :)

**Comment by deltakosh** [comment]
Ok so it is not clear to me what this extension is doing. Fancy creating a doc to explain usage and goal of the extension?

**Comment by deltakosh** [comment]
From what I've seen so far I think you should send the PR to this repo actually: https://github.com/BabylonJS/Extensions

**Comment by deltakosh** [comment]
The main repo is only for core components

**Comment by MackeyK24** [comment]
OK... Just delete all that stuff... The only way i know how to cleanly do it again... is to refork a clean copy and do it again.

**Comment by MackeyK24** [comment]
I just looked at that extension folder... There is no config.json... I only know how to setup automatic compile from what @sebavanmicrosoft  told me... Can i just email you the files and you put em where ever you want

**Comment by deltakosh** [comment]
Sure

**Pull request closed without merging**
