### PR TITLE
BoneWeightShader, SkeletonMapShader

### PR DESCRIPTION
**Pull request by Pryme8**
Is it alright that I have the shaders inline like this or should I pull them through and include?

### CODE REVIEW

**Comment by deltakosh** [comment]
First please remove dist :)

**Comment by deltakosh** [comment]
And yep it is ok for the shader to be like that (that was what I expected :))

**Comment by deltakosh** [comment]
Also please make sure to use the heat map approach mentioned by Patrick (from red to blue to get a heat map approach)

**Comment by Pryme8** [comment]
That's already included in that and I thought I dropped the dist directory dang it git!

https://playground.babylonjs.com/#35XDRU#13 <- Bone Weight Example
https://playground.babylonjs.com/#35XDRU#23 <- SkeletonMap Example

**Comment by Pryme8** [comment]
Whats the best way now to drop the dist stuff? I guess that was from a the merge, I thought I dropped the dist folder but it seems that did not happen.

**Comment by Pryme8** [comment]
I think I got that dist stuff sorted.

**Comment by deltakosh** [comment]
lol not really 1278 files now

**Comment by deltakosh** [comment]
btw the rendering are perfect
It would super cool to be able to have that rendering per skeleton but also being able to enable it per bone!

**Comment by Pryme8** [comment]
XD dang it I suck at git I guess.  What would be the way to fix this?

And yeah per bone that sounds interesting, can you show me an example or explain that more id be happy to include it!

**Comment by deltakosh** [comment]
Probably cancel it and start again ;D

**Comment by Pryme8** [comment]
Im getting some weird stuff happening with the spriteManager and I never touched it.

**Comment by Pryme8** [comment]
I need help with this git stuff, I have been going in circles trying to revert and merge and commit.

Have literally done nothing but make this more complicated.  There has to be a better way to ensure that the dist does not go on a commit because I literally told VS code to discard it and now am stuck here in a constant git nonsense circle.

**Comment by deltakosh** [comment]
YOu should be able to find gazillion of git doc on the web. The idea is simply to revert the dist folder (I'm using Tortoise git on my side, and this is like right click on the dist folder/revert)

**Pull request closed without merging**
