### PR TITLE
Missing type definitions for older versions of typescript

### LINKED ISSUE #14976: Cannot build. Missing ImageEncodeOptions, VideoFrame, etc.
Cannot build on Angular 14 + TypeScript 4.7 with Babylon 7 or 6. Workaround: Use version 5 of Babylon.

Missing types:

- ImageEncodeOptions
- OffscreenRenderingContextId
- OffscreenRenderingContext
- VideoFrame

https://doc.babylonjs.com/setup/frameworkPackages/es6Support

Upgrading Angular and/or Typescript is currently impossible. It's not just a hello world project. ^^

Is there a compatibility info? What version is depending on what dependencies. And how to handle it? Not sure, but I also could just define the missing types as any-type. Or babylon could support these type fallbacks/polyfill. It's great that babylon comes with types. But it's sad that TypeScript (indirect) types are blocking the use. Since types have no effect on runtime. It's just the d.ts behind in node_modules of babylon. At least we could provide some docs and how to handle this. I just wondering how to avoid that.

### PR DESCRIPTION
**Pull request by RaananW**
Fixes #14976

VideoFrame was already added in #14426

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by Popov72 — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15129/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15129/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15129/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15129/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15129/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15129/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15129/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15129/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15129/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15129/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
