### PR TITLE
Split angularSensibiliy into X and Y for additional functionality

### PR DESCRIPTION
**Pull request by Remwrath**
redid change in type script to allow flipping of rotation for individual or both axis and ability to have different rotation speeds for the different axis.

### CODE REVIEW

**Comment by deltakosh** [comment]
Before validating this PR, we need to keep angularSensibility as well. It could just be a set/get that updates your values. We cannot remove it because of backward compatibility

**Comment by Remwrath** [comment]
so angularSensibility should be private with get and set so on set it will use setter to set angularSensibilityX and angularSensibilityY but on get im not  sure what should happen for example if you get angularSensibility when angularSensibilityX and angularSensibilityY are different values then which do you return or should you set them the same as angularSensibility and then return that, which will work but may seem confusing to a deveoper?

**Comment by Remwrath** [comment]
Also is there a way to mark angularSensibility as depreciated to it can be removed at a later stage?

**Comment by deltakosh** [comment]
get (as property get in typescript) should return the biggest for instance and should log an warning as deprecated.
set should affect both to same value

**Comment by Remwrath** [comment]
sorry for all the back and forth, hope ive covered your requests now

**Comment by deltakosh** [comment]
Good to go :)

**Pull request merged**
