### PR TITLE
Fix for LinkWithMesh causes some flickering on button creation

### PR DESCRIPTION
**Pull request by msDestiny14**
Since currentMeasure isn't calculated until the render and the update is happening before the render I call the computeLayout which will calculate the currentMeasures.

https://github.com/BabylonJS/Babylon.js/issues/11014

### CODE REVIEW

**Review by sebavan — COMMENTED** [review]
Is this not really expensive on update ??? why was it working on the second frame ? we might be able to warm up the missing data earlier only when needed ?

**Comment by msDestiny14** [comment]
The problem is these two lines: 

        var newLeft = ((projectedPosition.x + this._linkOffsetX.getValue(this._host)) - this._currentMeasure.width / 2);
        var newTop = ((projectedPosition.y + this._linkOffsetY.getValue(this._host)) - this._currentMeasure.height / 2);

_currentMeasure.width/height are not calculated until the first render frame. But the function that calls this is called before this. So the values are 0;

**Comment by msDestiny14** [comment]
Another solution I thought about was just using w/h flat out without the _currentMeasure. But that might have other consequences.

**Comment by deltakosh** [comment]
Yeah this is a very slow solution. We cannot render a text per update per mesh to get a measure

**Comment by msDestiny14** [comment]
> Yeah this is a very slow solution. We cannot render a text per update per mesh to get a measure

What do you think of the second solution I wrote above?

**Review by sebavan — COMMENTED** [review]
I do not think this will work :-( I guess we might have less precision than _currentMeasure.

This probably needs to be dealt with in another way

**Comment by msDestiny14** [comment]
I'm gonna think more about it for now then.

**Pull request closed without merging**
