### PR TITLE
internal radius retry

### PR DESCRIPTION
**Pull request by Pryme8**
Fixing some of the purposed changes, after input from others.

### CODE REVIEW

**Comment by Pryme8** [comment]
http://www.html5gamedevs.com/topic/38508-bounding-sphere-radius-and-point-intersection/?do=findComment&comment=219771

based off of.

**Comment by Pryme8** [comment]
but then again, I am torn between this and doing a:
max.subtract(min).scale(0.5) and having it be something you can check the radius per axis.  

Not sure which one will be of more use, but this seems to be a common request to find a "true" mesh bounding sphere.

**Comment by deltakosh** [comment]
Well still this is just for spherical mesh so I don't think it should be in the framework

**Comment by Pryme8** [comment]
then what about a vector3 from bb.max.subtract(bb.min).scale(0.5);

Then we could add a method like mesh.isSphere() or something where if all the axes are the same it returns true, and then have another one that is like mesh.getBoundingRadius() that checks the mesh.isSphere and returns a vector3 if its not and if it is returns a float.

I feel like this is a re-occurring request so a solution should be found.

**Comment by Pryme8** [comment]
Feel free to close this one then as well, Ill re-think this and come back with a more thought out approach.
Maybe exclude it completely like you are saying and just write up a snippet page explaining how to get internal mesh radii

**Comment by deltakosh** [comment]
I'm more on the snippet side:)

**Comment by Pryme8** [comment]
Same, now that I kinda thought about it more.

**Pull request closed without merging**
