### PR TITLE
Comments for Materials

### PR DESCRIPTION
**Pull request by kcoley**

### CODE REVIEW

**Comment by deltakosh** [comment]
The build has issue with some unrecognized tags :(

**Comment by kcoley** [comment]
Hmm, I'll check it out.

**Comment by kcoley** [comment]
Hmm, I'm not able to reproduce this locally for some reason.  When running the gulp command, it seems to indicate that typedoc has passed:

`[16:59:40] Starting 'typedoc-all'...
[16:59:40] Starting 'typedoc-generate'...
[16:59:46] Finished 'typedoc-generate' after 5.87 s
[16:59:46] Starting 'typedoc-validate'...
[16:59:47] All formatting check passed successfully during the validation !
[16:59:47] Finished 'typedoc-validate' after 1.04 s
`
Is there a different command I should be using?

**Comment by deltakosh** [comment]
Agree this is weird.. Will merge and check locally

**Pull request merged**
