### PR TITLE
Revert "BoundingBox helper: add batch methods"

### PR DESCRIPTION
**Pull request by deltakosh**
Reverts BabylonJS/Babylon.js#15225

### CODE REVIEW

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by deltakosh** [comment]
#B8B8Z2#9: this is the one to test
correct:
 
image

incorrect:
image

**Comment by deltakosh** [comment]
Please do not merge for now. We are not sure yet if we can repro

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15230/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15230/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15230/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15230/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15230/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15230/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15230/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15230/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15230/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15230/merge/testResults/webgpuplaywright/index.html

**Pull request closed without merging**
