### PR TITLE
Bye bye Poly2Tri, welcome Earcut

### PR DESCRIPTION
**Pull request by nockawa**
PolygonMeshBuilder updated

I don't know what the commit of May25th is doing here! But you also have it in the other PR that is pending (Canvas2D), so I hope you won't mind.

### CODE REVIEW

**Comment by deltakosh** [comment]
hey cannot merge this one. There are conflicts

**Comment by nockawa** [comment]
not by the time I did the PR... :(
ok, I'm checking...

**Comment by nockawa** [comment]
ok I know what's going on, it's will be fixed in few mins

**Comment by nockawa** [comment]
ok, build in progress, should be better now

**Pull request merged**
