### PR TITLE
Add Scene Metadata Support

### PR DESCRIPTION
**Pull request by MackeyK24**
Add scene level metadata support

### CODE REVIEW

**Comment by deltakosh** [comment]
can you also update the sceneSerializer?

**Comment by MackeyK24** [comment]
Ok... I added:
// Metadata
            if (scene.metadata) {
                serializationObject.metadata = scene.metadata;
            }

to sceneSerializer... But i never did this for node.metadata.

Because node.metadata has @serialize, does it also need to be handled in sceneSerialize or is that automatic... What about mesh.metedata... I had to manually "Parse" mesh.metadata... So do i need to do anything with node.metadata in sceneSerilizer ?

**Comment by deltakosh** [comment]
Correct
We need to do it for the mesh serialization (only) 
Other nodes are already handled

**Comment by MackeyK24** [comment]
Done.

**Pull request merged**
