### PR TITLE
Gizmos: add additional transform property

### PR DESCRIPTION
**Pull request by Popov72**
This PR adds a new `additionalTransformNode` property to the `Gizmo` class. The name can be changed! I had first thought of `rootTransformNode`, but there's already a `_rootMesh` in the `Gizmo` class...

It is used primarily when a gizmo is attached to a bone. Currently, the gizmo is not displayed at the right location/orientation because it does not take into account the mesh on which the skeleton is attached (the gizmo is relative to the root of the skeleton). By setting `additionalTransformNode` to the mesh, the gizmo will be correctly displayed because we will multiply the final transform with the mesh transform.

I also updated the inspector to use the new feature.

Test PG (the gizmos should be at the location of the upper bone): https://playground.babylonjs.com/#HFWCMJ#26

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14795/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14795/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14795/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14795/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14795/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14795/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14795/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14795/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14795/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14795/merge/testResults/webgpuplaywright/index.html

**Comment by CedricGuillemet** [comment]
is it worth making the mesh optional if the transformNode is a bone? Is it possible to detect if the transformNode is a bone, and use its attached mesh automatically? idk if it possible to do it here : https://github.com/BabylonJS/Babylon.js/blob/d016da08cb27fe2169ed16019d8bcaf2c193cda9/packages/dev/core/src/Gizmos/gizmo.ts#L516

**Review by CedricGuillemet — APPROVED** [review]

**Pull request merged**
