### PR TITLE
Occlusion query fix

### PR DESCRIPTION
**Pull request by IbraheemOsama**
fixing issue #3552

### CODE REVIEW

**Comment by IbraheemOsama** [comment]
@deltakosh ping :)

**Comment by sebavan** [comment]
Nice :-) but is it also fixing the occlusion issue or just the bounding box renderer ?

**Comment by sebavan** [comment]
Ok, stupid me ... all good for me.

**Comment by deltakosh** [comment]
Wonderful! Thanks a lot @ibraheemosama

**Pull request merged**
