### PR TITLE
NME: Add a RealTime input

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/node-material-animation-runs-slower-than-unity-shader-graph/37067/8

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13418/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13418/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13418/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13418/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13418/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13418/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13418/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13418/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]
Pressed the wrong button in the review... my bad and can not seem to find a way to delete...

**Comment by sebavan** [comment]
@Popov72 sorry, I meant this one https://github.com/sebavan/Babylon.js/blob/master/packages/dev/core/src/Misc/precisionDate.ts#L10 :-)

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13418/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Review by sebavan — APPROVED** [review]

**Pull request merged**
