### PR TITLE
Add viewer load options

### PR DESCRIPTION
**Pull request by ryantrem**
Now that we have loader options, I'm allowing these options to be passed through the new viewer. It also exposes the createViewerFromCanvas helper function. These are needed for a product integration of the new viewer.

I'm also tacking onto this PR a quick fix for a regression in environmentTextureTools where rgbdPostProcess!.getEffect() returns null because the effect hasn't been created yet.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15413/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15413/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15413/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15413/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15413/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15413/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15413/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15413/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15413/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15413/merge/testResults/webgl2playwright/index.html

**Comment by ryantrem** [comment]
@deltakosh this change causes one WebGPU test to fail. You may be able to id the issue quickly, otherwise I can take a look.

**Comment by deltakosh** [comment]
@ryantrem : Please merge from master it should be fixed

**Pull request merged**
