### PR TITLE
Refactor ArcRotateCameraPointersInput to use BaseCameraPointersInput.

### PR DESCRIPTION
**Pull request by mrdunk**
NOTE: **This change is not intended for merging as it is.**
It is intended to demonstrate the `ArcRotateCameraPointersInputExperimental` class is functionally the same as `ArcRotateCameraPointersInput`.
Providing reviewers agree, we should replace `ArcRotateCameraPointersInput` with `ArcRotateCameraPointersInputExperimental` in a separate PR.

To run the tests, instantiate `Test_ArcRotateCameraPointersInput`.
eg: `var test = BABYLON.Test_ArcRotateCameraPointersInput()` in the console.

The test cases are all methods in the `Test_ArcRotateCameraPointersInput` class 
and have the name format: "test_something".

Note that the tests uncover 2 slight differences between `ArcRotateCameraPointersInputExperimental` and the original `ArcRotateCameraPointersInput`
in the following test cases:
`test_MutiTouchPinchZoomPercentage` and `test_MutiTouchPinchZoomLinear`.
These differences are caused by `ArcRotateCameraPointersInput` using 2 different methods to determine the distance traveled for multi-touch-drag type events.
`ArcRotateCameraPointersInputExperimental` obviously uses the Base class method which is the same in both cases.

### CODE REVIEW

**Comment by deltakosh** [comment]
This looks good to me!
You can update the arcrotateinput to this one on the other PR ;)

**Comment by mrdunk** [comment]
> This looks good to me!
> You can update the arcrotateinput to this one on the other PR ;)

done! (finally!!)

Question: The tests i wrote here could fairly easily be converted into UnitTests to protect ArcRotateCameraPointersInput. Is that something you are interested in?

**Comment by deltakosh** [comment]
OH YEAH :)

**Comment by mrdunk** [comment]
Never intended for submission.

**Pull request closed without merging**
