### PR TITLE
Unity Toolkit Playground Content

### PR DESCRIPTION
**Pull request by MackeyK24**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14751/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14751/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14751/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14751/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14751/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14751/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14751/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14751/merge#BCU1XR#0

**Comment by sebavan** [comment]
There seem to be lots of art content here and I do not think they should be in this repo. Could you either move them in the assets repo or another CDN ?

**Comment by MackeyK24** [comment]
it was intended to playground demo assets like XBOT.GLB

I sample prototype scene and a player character. But i can look at hosting them somewhere else if you really dont want them there.

**Comment by MackeyK24** [comment]
Yo @sebavan what is the url you would use when saving content to the Assets repo ?

**Comment by MackeyK24** [comment]
Yo @sebavan ... I removed the demo playground content

**Review by sebavan — APPROVED** [review]

**Pull request merged**
