### PR TITLE
Compile from git hub 

### PR DESCRIPTION
**Pull request by NasimiAsl**
Please don't close this pull let me fix all errors

### CODE REVIEW

**Comment by deltakosh** [comment]
Sure! 
let me know when you're good.
Please add a folder to contain all your files (at least this one and a readme.md)

**Comment by NasimiAsl** [comment]
i wanna make a sample folder in extensions  r u agree @deltakosh

**Comment by deltakosh** [comment]
Sure please create a /ShaderBuilder and then do whatever you want inside ;)

**Comment by NasimiAsl** [comment]
ok ShaderBuilder Ts is complete
but how can i test it in PG ?
i start write readme.md  all about shader :)

**Comment by deltakosh** [comment]
add the .js here as well and I reference it in the playground :)

**Comment by NasimiAsl** [comment]
ok dear DK what i do for for last i complete ShaderBuilder in that folder
it is ready now

**Comment by deltakosh** [comment]
Ok I moved everything to extensions: https://github.com/BabylonJS/Extensions/tree/master/ShaderBuilder

**Comment by NasimiAsl** [comment]
thanks
i wann make sample in pg
 how can use js?

**Comment by deltakosh** [comment]
here is an example: http://www.babylonjs-playground.com/#17GGFI#7

**Pull request merged**
