### PR TITLE
SIMD fixes

### PR DESCRIPTION
**Pull request by benaadams**
Just fixes for SIMD with asm.js removed

See also: https://github.com/BabylonJS/Babylon.js/pull/1180

### CODE REVIEW

**Comment by RaananW** [comment]
Hi Ben,

1. what's the difference between the last PR and this one?
2. The SIMD file is a d.ts file. Let me think where it fits the best.
3. Was the change of Vector3 needed?

**Comment by benaadams** [comment]
@RaananW 

1. Last one the SIMD functions are written to be asm.js AST pre-compiled with the parameters going to the functions via a shared heap (between asm.js and js). I wasn't convinced it added any perf, so I tried this one where just fixed the current implementation - not convinced by its performance either :see_no_evil: (using the SIMD demo to test)

2. Sure

3. The previous SIMD implementation when activated mutated each Vector object to add the `Float32Array` `_data` backing field in the `x` setter and indirected `x`,`y`,`z` on the prototype to via property getters and setters, so I changed it to happen in the constructor for a monomorphic type cache rather than having a polymorphic type cache on all the functions taking `Vector3`s (e.g. https://blogs.msdn.microsoft.com/ie/2014/10/09/announcing-key-advances-to-javascript-performance-in-windows-10-technical-preview/). I've reverted most of the changes to go back to using `x`,`y`,`z` however.

**Comment by benaadams** [comment]
e.g. I'm not sure if  #1180 or #1181 is better as I don't seem to getting a great benefit from either in Firefox Nightly or Edge (with experiment js on)

**Comment by RaananW** [comment]
@benaadams - I totally forget we are currently in code freeze, bug fixing only. This will be a great feature for 2.5, but we will need to test all together and see how much benefit it brings. 
I am commenting here, but it is, of course, referring to https://github.com/BabylonJS/Babylon.js/pull/1180 as well.

**Comment by deltakosh** [comment]
Which on (between this one an #1180) do you want to keep?

**Comment by benaadams** [comment]
Closing this as making good progress on other

**Comment by benaadams** [comment]
@arunetm this is the pure simdjs change, however it currently performs worse that the asmjs with the double copy step

image

**Comment by arunetm** [comment]
Thanks. Edge currently wont optimize the non-asm version of SIMD, and this explains the degraded performance here. The new typespecialization optimization for simd should address this case and we plan to use this update to evaluate the same. Thank you for the PR.

**Comment by arunetm** [comment]
@benaadams. The time spent in "SIMDMatrix.prototype.multilyToArraySIMD" drops from 60% to 14%, in Edge with new simd optimizations running the simd enabled version of the demo. I could see that the "SIMDMatrix.prototype.multilyToArraySIMD" shows speedups compared to the non-simd counterpart, but this didnt translate to an increase in number of dancers in the actual demo. The demo is spending most of the time outside the simd math library and the libraries are not stressed enough to see the benefits of simd speedup. 
Did you notice anything similar in your trials? Are you seeing any increase in dancers with asmjs changes? 

edge-simd

**Comment by benaadams** [comment]
Do you have the call stacks for the other areas? (or better the `.diagsession` file) can improve them.

The asm.js approach with the copy-to and copy-from steps is too slow for the general js case; whereas if the simd is recognised in general js then the entire maths functions can be switched when SIMD is enabled.

**Comment by deltakosh** [comment]
Hey Ben,
I plan to close your 2 PRs unless you want to merge one of them?

**Comment by benaadams** [comment]
I think this one is better as it does fix the SIMD not working.

While the other one seems to be more SIMD accelerated; too much speed is lost copying the data back and forth between asm and regular.

**Pull request merged**
