### PR TITLE
Scroll Viewer: Add specific methods to change the horizontal/vertical bar pictures

### PR DESCRIPTION
**Pull request by Popov72**
I did not modify the what's new file as there is already:

- Scroll Viewer extended to include the use of images in the scroll bars([JohnK](https://github.com/BabylonJSGuide/))

### CODE REVIEW

**Comment by lockphase** [comment]
Heyas @Popov72 : Thanks for the PR, I just tested a little and it seems that verticalBarImage and verticalThumbImage are rotated by default (see attached pic). I'm not using the horizontal ones. Is it possible to simple switch off the rotation when using the individual hori/vert bar/thumb images ?

sv_bug1

**Comment by Popov72** [comment]
Hi @lockphase,

Indeed, the rotation is automatically performed by `ImageScrollBar` when `isVertical = true`.

Going to see if I can add a property on `ImageScrollBar` to disable the rotation in this case.

**Comment by Popov72** [comment]
I made this PR: https://github.com/BabylonJS/Babylon.js/pull/7578

**Comment by Popov72** [comment]
#7578 is live

**Pull request merged**
