### PR TITLE
added Ray.intersectsMesh and Ray.render

### PR DESCRIPTION
**Pull request by abow**
http://www.babylonjs-playground.com/#ZHDBJ#10

### CODE REVIEW

**Comment by abow** [comment]
Maybe it should only render for 1-2 seconds?  The user could change the render time through an optional param.

**Comment by abow** [comment]
or maybe just a show and hide function?

**Comment by deltakosh** [comment]
Yep I'm more for a show/hide version

**Comment by abow** [comment]
http://www.babylonjs-playground.com/#ZHDBJ#13

**Pull request merged**
