### PR TITLE
added second drawText function with textAlign argument

### PR DESCRIPTION
**Pull request by mwpowellhtx**
Keep me posted how this works. Thank you...

### CODE REVIEW

**Comment by deltakosh** [comment]
actually this could be added directly on drawText itself as an optional parameter.

**Comment by mwpowellhtx** [comment]
That wouldn't be a breaking change for some?

**Comment by deltakosh** [comment]
nope if we just add a if (textAlign){}

**Comment by mwpowellhtx** [comment]
We aren't communicating. Yes, I understand we can test for whether the argument exists.

Breaking changes are in terms of the caller, not the implementation.

**Comment by RaananW** [comment]
The caller won't notice the function had changed of it's optional. If he checks the signature he will understand he can set it, but it's not a must. So an extra optional parameter is not a breaking change.

**Pull request closed without merging**
