### PR TITLE
3D Commerce Certification Test

### PR DESCRIPTION
**Pull request by bghgary**
Copy the 3D commerce certification models into `test/certification/models` for the test to work. This is a WIP, but it's good enough to create the zip for certification.

https://user-images.githubusercontent.com/19158740/120871868-c8fd5300-c551-11eb-8eae-b17977293548.mp4

### CODE REVIEW

**Comment by bghgary** [comment]
This is ready for review. I've added some instructions to the folder to explain how to run it.

**Comment by RaananW** [comment]
Do we want to run it in our CI?

**Review by Popov72 — APPROVED** [review]
LGTM!

**Comment by bghgary** [comment]
> Do we want to run it in our CI?

Not yet. This test doesn't currently pass given the same threshold as the validation tests. We are waiting for Khronos to come up with the correct criteria for the tests. We have already submitted something and will wait to see what they say.

**Pull request merged**
