### PR TITLE
Fixe alpha of button

### PR DESCRIPTION
**Pull request by dad72**
I just made that alpha does not degrade increments at each hovers of mouse but still leave with its initial value. (If the "hover out" event does not trigger)

### CODE REVIEW

**Comment by deltakosh** [comment]
This does not work if I change alpha afterwards

**Comment by dad72** [comment]
I think the ideal will be a new event when pert focus. In my case, the pointerOut event is not run, because the click on the button I have a new window that opens and prevents the pointerOut event to run. And I find myself gradually to an alpha of 0.

I do not know how.

**Comment by deltakosh** [comment]
I'll do something to fix it

**Comment by deltakosh** [comment]
Can you provide a repo in pg?

**Comment by dad72** [comment]
I would have joined to this, a library jQuery and CSS the bug on PG.

**Comment by dad72** [comment]
I try to do it later, there I have to go pick up my daughter at school

**Comment by dad72** [comment]
I can not do it in the playground, he refuses my link to the jquery lib.

https://www.babylonjs-playground.com/#U9AC0N#10

**Comment by deltakosh** [comment]
jquery is in the repo I think by default

**Comment by dad72** [comment]
This is jquery.modal.min.js

**Comment by deltakosh** [comment]
then you just need to reference it over https

**Comment by dad72** [comment]
My server is not with https

**Comment by dad72** [comment]
If I put https I: Failed to load resource: net::ERR_INSECURE_RESPONSE

**Pull request closed without merging**
