### PR TITLE
Update babylon.sceneSerializer.ts

### PR DESCRIPTION
**Pull request by dad72**
added collisionsEnabled and workerCollisions for serialization

### CODE REVIEW

**Comment by dad72** [comment]
Il y a un probleme avec ce PR Deltakosh ? Pourquoi n’est il pas valider avec les autres qui l'ont été ? j'ai fait des erreurs sur l'une de ses deux ligne ?

serializationObject.collisionsEnabled = scene.collisionsEnabled;
serializationObject.workerCollisions = scene.workerCollisions;

**Comment by Temechon** [comment]
Raanan is the collision master, I think it's up to him to validate your PR. For me it seems ok (only two lines), but maybe there are some edge effects. 
Just wait his feedback :)

**Comment by RaananW** [comment]
Hi, sorry, I just waved to wait with it until I finish the scene loader as well. Merging won't matter, as it's not read yet.
I'll merge now and hopefully commit my changes in a few hours

**Comment by RaananW** [comment]
(*just wanted)

**Comment by dad72** [comment]
Ok.

**Comment by deltakosh** [comment]
And please do not forget to update this as well: http://doc.babylonjs.com/generals/File_Format_Map_(.babylon)

**Comment by RaananW** [comment]
working on it now, I just added a few more properties.

**Pull request merged**
