### PR TITLE
Early return from InstancedMesh.getLOD if there are no LODs

### PR DESCRIPTION
**Pull request by jure**
`Mesh.getLOD` has this nice thing where it returns early in case there are no LODs. `InstancedMesh.getLOD` uses `Mesh.getLOD` underneath, but not before it calls off to a `AbstractMesh.getBoundingInfo`: https://github.com/BabylonJS/Babylon.js/blob/087deb584b40fc5fe8543d54b3e3eed60d1cc121/src/Meshes/instancedMesh.ts#L390

So even if there are no LODs, a whole lot happens to figure out which one would be the right one:
Screenshot 2022-02-23 at 01 05 02

I assume LODs are not used very often, especially in combination with `InstancedMesh`es, so this PR includes a significant early return optimisation for that common case.

### CODE REVIEW

**Review by sebavan — APPROVED** [review]

**Comment by sebavan** [comment]
I wonder if you could change the code from 

```
        const sourceMeshLODLevels = this.sourceMesh.getLODLevels();
        if(!sourceMeshLODLevels || sourceMeshLODLevels.length === 0) {
            this._currentLOD = this.sourceMesh;
            return this.sourceMesh;
        }

        let boundingInfo = this.getBoundingInfo();

        this._currentLOD = <Mesh>this.sourceMesh.getLOD(camera, boundingInfo.boundingSphere);
        if (this._currentLOD === this.sourceMesh) {
            return this.sourceMesh;
        }
        return this._currentLOD;
```

to 

```
        const sourceMeshLODLevels = this.sourceMesh.getLODLevels();
        if(!sourceMeshLODLevels || sourceMeshLODLevels.length === 0) {
            this._currentLOD = this.sourceMesh;
        } else {
            let boundingInfo = this.getBoundingInfo();
            this._currentLOD = <Mesh>this.sourceMesh.getLOD(camera, boundingInfo.boundingSphere);
        }
        
        return this._currentLOD;
```

**Comment by sebavan** [comment]
if not, nw I ll do it after the pr

**Comment by jure** [comment]
> I wonder if you could change the code from

Yes, cleaner this way. Thank you!

**Comment by RaananW** [comment]
Ready to be merged! just waiting for the linting issues (formatting, in that case)

**Review by sebavan — APPROVED** [review]
Thanks a lot !!!

**Pull request merged**
