### PR TITLE
Feature.create box.face colors

### PR DESCRIPTION
**Pull request by jbousquie**
We can set different colors per face of the box.
Example : red top face and green front face 
```javascript
var faceColors = new Array(6);
faceColors[4] = new BABYLON.Color4(1,0,0,0.3);
faceColors[1] = new BABYLON.Color4(0,1,0,0.3);
var options = { width: 10, height: 3, depth: 5, faceColors : faceColors };

var box = BABYLON.Mesh.CreateBox('box', options, scene);
box.hasVertexAlpha = true; // for transparency, if needed
```

For now, if the mesh is double sided, each internal and external pair of sides have still the same UVs and color. There is no implementation of different internal color/UV from external ones, for instance, although it is doable but more complex.

### CODE REVIEW

**Comment by deltakosh** [comment]
I validate it but I'll need to update it as I do not want to generate colors if this is not asked

**Comment by jbousquie** [comment]
okay

I just forgot this case, tsssss

**Comment by deltakosh** [comment]
no worry it is already fixed :)

**Comment by jbousquie** [comment]
tinkiou :-D

**Pull request merged**
