### PR TITLE
SkyMatrial: fix cameraOffset serialize

### PR DESCRIPTION
**Pull request by happyPaner**
SkyMatrial: fix cameraOffset serialize

### CODE REVIEW

**Comment by julien-moreau** [comment]
LGTM! @happyPaner anyway can you test that when you parse a sky material serialized with the old decorator then parsing with the new decorator still works? 
Else, we’ll have to create the vector 3 manually in the .Parse function to keep the backward compatibility
Thanks ! :)

**Comment by happyPaner** [comment]
Hi! @julien-moreau, yes. I has tested. it's a bug. When i parse a sky material serialized with the old decorator get a wrong result. Use new decorator, get right result.

**Comment by deltakosh** [comment]
Any update?

**Comment by julien-moreau** [comment]
@deltakosh it's ok for me, and it looks like Chibi Rex and Yeti valitation tests are not using the Sky Material. I don't understand why this pipeline is failing

**Comment by deltakosh** [comment]
Let me run that again :)

**Comment by julien-moreau** [comment]
CI looks good now @deltakosh :)

**Pull request merged**
