### PR TITLE
Update comments in ibl shadows

### PR DESCRIPTION
**Pull request by MiiBond**
While working on [documentation for the IBL Shadow Pipeline](https://github.com/BabylonJS/Documentation/pull/1233), I've been updating comments in the code to align.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15802/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15802/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15802/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15802/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15802/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15802/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15802/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15802/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15802/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15802/merge/testResults/webgpuplaywright/index.html

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
