### PR TITLE
Add function Animation.ParseFromACEFileAsync

### PR DESCRIPTION
**Pull request by BlakeOne**
PR to add the new function ParseFromACEFileAsync to the Animation class to let users load files that were saved from ACE.
Forum: https://forum.babylonjs.com/t/animation-from-json-loading/26421/8

### CODE REVIEW

**Review by sebavan — APPROVED** [review]
GG !!!

**Review by sebavan — CHANGES_REQUESTED** [review]
Wait, I spoke too soon :-) Is there a way you can factorize with the code from ParseFromFileAsync as it is awfully similar but the .animations ???

**Review by deltakosh — CHANGES_REQUESTED** [review]
Same comment as seb :)

**Comment by sebavan** [comment]
maybe after parsing just check if animations exists and is an array, so we only have one function?

**Comment by BlakeOne** [comment]
Just finished doing it by passing an optional parameter to the existing function and then saw your comment. I think would be better to check and handle it automatically like you suggested instead of using param, I'll make another commit for it that way. :)

**Comment by BlakeOne** [comment]
Okay got it working with auto-detection of ACE-saved files by just checking for the animations array. Haha much simpler fix this way. :)

**Review by sebavan — APPROVED** [review]

**Review by deltakosh — APPROVED** [review]

**Pull request merged**
