### PR TITLE
Make `CompatibilityOptions` an object, not a class

### PR DESCRIPTION
**Pull request by james-pre**
This PR migrates `CompatibilityOptions` from a class with static properties into a plain Javascript object. This is from https://github.com/BabylonJS/Babylon.js/issues/14805. Continued from #15376.

### CODE REVIEW

**Comment by james-pre** [comment]
Reopening with the addition of 075363d because of @sebavan's comment:

> If the class with static sounds too much, you could simply replace with an object but keep the same structure.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by james-pre** [comment]
Oops I didn't update the references. I'll do that tomorrow morning.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15380/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15380/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15380/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15380/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15380/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15380/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15380/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15380/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15380/merge/testResults/webgl2playwright/index.html

**Comment by RaananW** [comment]
I am fine with this change. Just want to be sure the vis-tests pass

**Review by RaananW — APPROVED** [review]

**Comment by james-pre** [comment]
@RaananW,

This is kind of last minute, but could we still use a variable, and then export the object with getters and setters?
```
export let useOpenGLOrientationForUV = false;

export const CompatibilityOptions = {
	get UseOpenGLOrientationForUV() {
		return useOpenGLOrientationForUV;
	},
	set UseOpenGLOrientationForUV(value) {
		useOpenGLOrientationForUV = value;
	}
}
```

**Comment by RaananW** [comment]
> @RaananW,
> 
> This is kind of last minute, but could we still use a variable, and then export the object with getters and setters?
> 
> ```ts
> export let useOpenGLOrientationForUV = false;
> 
> export const CompatibilityOptions = {
> 	get UseOpenGLOrientationForUV() {
> 		return useOpenGLOrientationForUV;
> 	},
> 	set UseOpenGLOrientationForUV(value) {
> 		useOpenGLOrientationForUV = value;
> 	}
> }
> ```

sure, but is there reasoning behind this? seems like the getter/setter are not really needed here

**Comment by james-pre** [comment]
This just reduces bundle size and improves performance since all of the references aren't one on object:

- Accessing `useOpenGLOrientationForUV ` is faster than `CompatibilityOptions.UseOpenGLOrientationForUV`
- It removes `CompatibilityOptions.` from every access, which is 21 bytes, with 45 references that is ~1 KB (not very much, but still something).
- It's cleaner syntax
- Tree-shaking if more compatibility options are added in the future.

I haven't made the change yet, though I will if you give the green light.

**Comment by RaananW** [comment]
> This just reduces bundle size and improves performance since all of the references aren't one on object:
> 
> * Accessing `useOpenGLOrientationForUV` is faster than `CompatibilityOptions.UseOpenGLOrientationForUV`
> * It removes `CompatibilityOptions.` from every access, which is 21 bytes, with 45 references that is ~1 KB (not very much, but still something).
> * It's cleaner syntax
> * Tree-shaking if more compatibility options are added in the future.
> 
> I haven't made the change yet, though I will if you give the green light.

On the other hand, legacy users (i.e. users who use `CompatibilityOptions` already) will have a slower access to the variable :-) There is always a trade-off.

I am fine with the change, as long as UMD doesn't export the variable. It should be an es6 feature only.

**Comment by james-pre** [comment]
Okay.

I included a `setOpenGLOrientationForUV`, because with ES6 when you `import` something, you import the *binding* not the *value*, and the binding is read-only (though it's live). Because of that, we need a separate function for updating the value.

Given that it is a new function, and the naming convention of `useOpenGLOrientationForUV` is camel case, I opted to use camel case for the function's name. Please let me know if pascal case would be preferred for the variable and setter instead.

**Comment by RaananW** [comment]
> I included a `setOpenGLOrientationForUV` function because ES6 imports are read-only live bindings to symbols. Because of that, we need a separate function for updating the value.
> 
> Given that it is a new function, and the naming convention of `useOpenGLOrientationForUV` is camel case, I opted to use camel case for the function's name. Please let me know if pascal case would be preferred for the variable and setter instead.

This is fine as is right now. I'll merge this when CI is done

**Pull request merged**
