### PR TITLE
WebGPU: ubos and storage buffers optimizations

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/i-am-writing-webgpu-ray-tracer-is-anyone-interested-in-this-topic/42188/25

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14611/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14611/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14611/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14611/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14611/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14611/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14611/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14611/merge#BCU1XR#0

**Review by RaananW — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Comment by RaananW** [comment]
> image
> 
> Problem is that when I run prettier in VSCode on this file (or when running `npm run format:check` / `npm run format:fix`), there's no error in this file. My prettier extension is up to date, not sure what I should do?
> 
> image
> 
> Maybe the extension is not up to date on the CI?

can't be - it is using the package-lock to install the dependencies. It uses a fixed version. What version are you running locally?

**Comment by RaananW** [comment]
Ran the formatter locally - there is a difference:

image

This is from a newer version of prettier. Make sure your local dependency is updated . locally it should be 3.1.0

**Comment by Popov72** [comment]
image

It is version 10.1.0... Are we using the same extension?

**Comment by RaananW** [comment]
> image
> 
> It is version 10.1.0... Are we using the same extension?

The important version is the one you have installing using npm install. run `npm install` to make sure your dependencies are up to date and then run format:fix

**Comment by Popov72** [comment]
> locally it should be 3.1.0

It is 3.0.3 in package.json:

https://github.com/BabylonJS/Babylon.js/blob/master/package.json#L43

I set 3.1.0 locally, did a npm install then `npm run format:check` and still no errors...

**Comment by RaananW** [comment]
It should be ^3.0.3, which is the latest minor in the 3 major branch. npm format:fix does nothing? 

Let's go over this tomorrow. You can add those two tabs like I pasted to fix it for now

**Comment by Popov72** [comment]
My bad, I can't read:

image

**Pull request merged**
