### PR TITLE
Fix `additionalTransformNode` type

### PR DESCRIPTION
**Pull request by alecmev**
Same as https://github.com/BabylonJS/Babylon.js/pull/14306, so that `skipLibCheck: false` and `exactOptionalPropertyTypes: true` pass.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14848/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14848/merge/testResults/webgl2playwright/index.html

**Review by RaananW — APPROVED** [review]

**Review by Popov72 — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Comment by alecmev** [comment]
Thanks!

**Pull request merged**
