### PR TITLE
Add flag for inverting target camera pan direction and speed multiplier

### PR DESCRIPTION
**Pull request by Exolun**
This change adds a flag and a separate speed multiplier for enabling inverted panning controls on target camera.

Per the feature request #7663  I created targeting 4.2

### CODE REVIEW

**Comment by Exolun** [comment]
@deltakosh  Should I go ahead and add a placeholder `what's new.md` file with the same sections as the 4.1.0 one and a description of my change in a Camera section?

**Comment by deltakosh** [comment]
Yes here: https://github.com/BabylonJS/Babylon.js/blob/master/dist/preview%20release/what's%20new.md

**Comment by deltakosh** [comment]
Wrong file ;) (check my link)

**Comment by Exolun** [comment]
> Wrong file ;) (check my link)

Whoops - thanks!

**Pull request merged**
