### PR TITLE
Fit crop viewport around selected controls

### PR DESCRIPTION
**Pull request by carolhmj**

### CODE REVIEW

**Review by sebavan — APPROVED** [review]

**Review by darraghjburke — CHANGES_REQUESTED** [review]
This does not seem to work as expected if the control is not positioned at 0, 0.
fit to window

**Comment by carolhmj** [comment]
Thanks for catching that @darraghjburke ! I tried a fix with non-centralized positions

**Comment by carolhmj** [comment]
@darraghjburke branch algorithm updated to work on rotated controls (finally got the matrices!) and for the new build system :D

**Review by darraghjburke — APPROVED** [review]
excellent!

**Pull request merged**
