### PR TITLE
TransmissionHelper: Add generateMipmaps option

### PR DESCRIPTION
**Pull request by Popov72**
See https://forum.babylonjs.com/t/transmission-helper-optimisation/21037/3

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by Popov72** [comment]
The test failing is "GUI Near Menu" but there's no relationship between this test and the changes from this PR. Also, the test does work in WebGL1, so I guess we can suppose it's a transient error...

**Comment by deltakosh** [comment]
Adding @RaananW who should know what this test is about

**Comment by deltakosh** [comment]
@CraigFeldspar can you check why the GUI near menu test is sometimes failing?

**Comment by CraigFeldspar** [comment]
> @CraigFeldspar can you check why the GUI near menu test is sometimes failing?

@deltakosh I think this is because of the XHR for the pin icon that sometimes arrives late.
I will remove the test from auto testing and only keep it local

**Comment by CraigFeldspar** [comment]
@deltakosh #10415

**Pull request merged**
