### PR TITLE
Fix resuming animation after pause

### PR DESCRIPTION
**Pull request by sebavan**
This playground should display diamonds during the animation: https://playground.babylonjs.com/#9CLJEF

[This fix](https://github.com/BabylonJS/Babylon.js/pull/15267) introduced a regression as when the animatable counts changes (e.g.) one anim is done but not all of them, we simply resume, but when new target animations have been added, we end up in a similar situation.

Adding a dirty mecanism prevents the misdetection of simply running animation groups.

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15318/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15318/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15318/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15318/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15318/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15318/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15318/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15318/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15318/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15318/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
