### PR TITLE
Flycamera element fix

### PR DESCRIPTION
**Pull request by RolandCsibrei**
https://forum.babylonjs.com/t/procedural-galaxy-and-streaming/51468/22

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by RolandCsibrei** [comment]
`private _element: HTMLElement` was never set and it is not used anywhere else. I believe it was safe to remove it completely.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15240/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15240/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15240/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15240/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15240/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15240/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15240/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15240/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15240/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15240/merge/testResults/webgpuplaywright/index.html

**Review by RaananW — APPROVED** [review]
I wonder why typescript hasn't reported this. Anyhow - good catch :-)

**Pull request merged**
