### PR TITLE
Babylonjk1

### PR DESCRIPTION
**Pull request by Cubees**
Fur material submitted for consideration

### CODE REVIEW

**Comment by deltakosh** [comment]
Why the renames of normalXxxx files?

**Comment by Cubees** [comment]
Sorry deltakosh as far as I know I didn't rename any files. Must be in my inexperience with Github and Visual Studio Code I did something without realising. As far as I knew I had only added the fur folder into the material folder and added two new images into the texture folder. Anything else is an error on my part. Also I just hit the green Pull Request button should I have just done a pull request on the folder I had added?

**Comment by Cubees** [comment]
Let me know if there is something I should do to put things right. JohnK

**Comment by Temechon** [comment]
Hi John, 

With git, a PR is a sum of all files that are different between your repo (babylonjk1) and the upstream repo (babylonjs). It appears that the folder 'materialLibrary/test/refs' is not exactly like the one in Babylonjs master (a folder 'normal' is on your branch). It should be exactly the same.
Could you please  delete the folder 'materialLibrary/test/refs/normal', commit and push ? 

You don't have to delete this PR, as it will be automatically updated.
Cheers !

**Comment by Cubees** [comment]
Hopefully I have now correctly placed everything. My new laptop has a smooth touchpad whereas the old one had separate buttons and I find that I am selecting and dragging accidently. Will remember to keep only one finger at a time on the pad eventually.

**Pull request closed without merging**
