### PR TITLE
Support dynamic focal of gaussian splatting

### PR DESCRIPTION
**Pull request by xiasun**
Currently, the GaussianSplatting implementation uses a fixed focal length in the shader. However, if the rendering parameters such as the fov, aspect, or render size are changed, the resulting rendering may appear too 'sparse' or 'dense'.

To address this issue, I have added a public function `updateFocal()`. This function is called during construction and can also be called by the user whenever needed, such as when changing the fov or other relevant parameters.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14713/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14713/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14713/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14713/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14713/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14713/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14713/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14713/merge#BCU1XR#0

**Comment by Popov72** [comment]
Thanks for the fix!

As there is already an open PR for Gaussian Splatting (#14711), your code has been added to it.

**Comment by xiasun** [comment]
glad to see that

**Pull request closed without merging**
