### PR TITLE
Loading screen interface and implementation

### PR DESCRIPTION
**Pull request by RaananW**
It is now possible to create a new implementation of the loading screen and set it in the engine.
The engine now includes a loadingScreen variable that is per default the native loading screen but can be set with a new loading screen in accordance to the ILoadingScreen interface.

*Breaking changes*
the engine's set loading text and set background color were removed as they are no longer conform with the new interface!

### CODE REVIEW

**Comment by deltakosh** [comment]
Hello I think this is great but I would like to keep the set loading text and background color on the engine. This then will be sent to the interface. If someone wants to have a loader which does not take this in account that's fine but I think this is a good first level of customization without having to completely rewrite a loader

**Comment by RaananW** [comment]
Will make the changes and commit soon

**Comment by RaananW** [comment]
Interface and engine updated (including a small and silly bug fix).

**Comment by deltakosh** [comment]
Another small ask :) can you update the file list here:https://github.com/BabylonJS/Documentation/blob/master/content/generals/General/Creating_the_Mini-fied_Version.md

**Comment by RaananW** [comment]
updating the documentation now.

**Comment by deltakosh** [comment]
Lol this is fast:) thank you!

**Comment by RaananW** [comment]
I'm only fast when I am sitting in front of my computer :smile:

**Comment by deltakosh** [comment]
I hope so :D

**Pull request merged**
