### PR TITLE
Typo in VertexData

### PR DESCRIPTION
**Pull request by jahow**
sorry about that

### CODE REVIEW

**Comment by RaananW** [comment]
I wonder how this passed the CI's inspection... :-)

**Comment by jahow** [comment]
Yeah... especially since I noticed it because of an error in the CI log.

BTW this time the CI log is full of errors. :fearful:

**Comment by RaananW** [comment]
That looks like a typescript version problem. Will look into that later.
And I will look into the reason why travis shows success when errors are present.
Thanks!

**Comment by jahow** [comment]
Always glad when my f***-ups are useful ;D

**Comment by RaananW** [comment]
:smile: always look on the bright side of coding!

**Comment by deltakosh** [comment]
Is it because we moved to TS 1.5?

**Comment by RaananW** [comment]
yep, the 1.5 libs contains more properties than 1.4, including properties that are already defined in BJS mixins. need to see how this can be solved nicely. I thought of adding or removing the mixins file, depending on the compiler version. i'll try fixing it later today.

**Comment by deltakosh** [comment]
Actually this should not be a problem (I can compile the current version with 1.5 with no issue as interface overwriting is allowed)

**Comment by RaananW** [comment]
I'll check what's up with travis then. I haven't tried locally yet, was just an assumption.

**Comment by deltakosh** [comment]
Ok I checked in everything :) Let me know!

**Comment by RaananW** [comment]
Travis compiles correctly now, I will notify the community that they must use 1.5 from now on :-)

**Pull request merged**
