### PR TITLE
Input management for cameras

### PR DESCRIPTION
**Pull request by gleborgne**

### CODE REVIEW

**Comment by deltakosh** [comment]
181 files...is a bit too much :)

**Comment by gleborgne** [comment]
It's because of Typescript, almost all JavaScript files got changes (I guess we don't use the same version)

**Comment by gleborgne** [comment]
rebuilt using Babylon's gulp tasks but it adds 10 more JavaScript file differences :-(

**Comment by deltakosh** [comment]
can't validate unfortunately :(

**Comment by gleborgne** [comment]
which version of Typescript do you have ?

**Comment by nockawa** [comment]
@gleborgne at each compilation all Javascript files are regenerated, even if you didn't touch the corresponding .ts. You have to commit only the .js files corresponding to the .ts file you changed.
You should start from a clean branch, merge the .ts file you changed manually, compile, commit the .ts/.js files that you changed, and resubmit your PR.

**Pull request closed without merging**
