### PR TITLE
typedoc comment analyzer

### PR DESCRIPTION
**Pull request by carolhmj**
This script is intended to run Typedoc on the code, and use the output JSON to check for any public methods or attributes that don't have a comment.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14693/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14693/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14693/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14693/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14693/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14693/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14693/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14693/merge#BCU1XR#0

**Review by sebavan — COMMENTED** [review]
Thanks a log @carolhmj I missed this a lot :-)

Why not reusing the one we had in the old infra ? it was also doing some quick and dirty naming convention sanity checks ?

**Comment by RaananW** [comment]
> Thanks a log @carolhmj I missed this a lot :-)
> 
> Why not reusing the one we had in the old infra ? it was also doing some quick and dirty naming convention sanity checks ?

If this one is working, let's stay with it. Let's let it run for a few days and see how well it works.

**Pull request merged**
