### PR TITLE
Update Draco compression to use web workers

### PR DESCRIPTION
**Pull request by bghgary**
@deltakosh Please review and see if you like the way I'm using web workers and how the external Draco script location is determined.

### CODE REVIEW

**Comment by deltakosh** [comment]
Please just update the waht's new

**Comment by bghgary** [comment]
I wasn't thinking I needed to update what's new since I already added the Draco support part. Did you want me to add web worker specifically to it?

**Comment by deltakosh** [comment]
This is more for the WorkerPool object actually
This is a great feature and it will also require a tiny page in the doc to explain how to use it

**Comment by bghgary** [comment]
Ahh, okay. Sure, I'll update the what's new and docs.

**Comment by deltakosh** [comment]
Much appreciated :)

**Pull request merged**
