### PR TITLE
Oculus go vr fixes

### PR DESCRIPTION
**Pull request by TrevorDev**
https://github.com/BabylonJS/Babylon.js/issues/4891

### CODE REVIEW

**Comment by pgbladeqcode** [comment]
I tried it out, but same issue :(

**Comment by deltakosh** [comment]
I merged it. Can you try again?

**Comment by pgbladeqcode** [comment]
Sorry.. not working :-( Same as before..

**Comment by deltakosh** [comment]
@trevordev cab you have a look?

**Comment by TrevorDev** [comment]
Yep, I tried yesterday morning and it looked to be fixed, tested with Oculus go on the website. @pgbladeqcode if you are still seeing issues let me know.

**Pull request merged**
