### PR TITLE
Added prototype of InputTextArea

### PR DESCRIPTION
**Pull request by fneitzel**
As per request I send this proposal of an InputTextArea. So one can have a multiple line InputTextField. Here is a link to the forum discussion: https://forum.babylonjs.com/t/gui-textinput-with-multiple-lines/9927

The are a quite a few things left and since I got no time in the moment, maybe others can push this forward.

What's missing:

    include margin
    text highlighting (copy/paste/delete)
    backspace deletion

I don't know how to reolve this issue:
```
 [at-loader] ../../gui/src/2D/controls/inputTextArea.ts:906:55 
    TS2339: Property 'text' does not exist on type 'object'.
```

### CODE REVIEW

**Comment by deltakosh** [comment]
Hello and thanks a ton! Before going in depth I think we should consider having the textarea inheriting from textinput as they share a lot of code (to avoid duplications and maintenance hurdles)

**Comment by sebavan** [comment]
Related to #5630

**Comment by sebavan** [comment]
It is getting there nicely, text highlighting and the rest would be kickass :-)

**Comment by sebavan** [comment]
@fneitzel do you think you will address the PR ?

**Comment by deltakosh** [comment]
Closing for being stalled for too long

Please feel free to reopen when possible

**Pull request closed without merging**
