### PR TITLE
Support Model Change

### PR DESCRIPTION
**Pull request by nockawa**

### CODE REVIEW

**Comment by wyklion** [comment]
I update and try. 
There's more sprite2d problem...
Not display.
Same texture two sprite2d only display last one.

**Comment by nockawa** [comment]
@wyklion I'm on it, starting right now

**Comment by nockawa** [comment]
@wyklion this is working fine for me:
```            var texture = new BABYLON.Texture("assets/sprites.png", this.scene, true, false, BABYLON.Texture.NEAREST_SAMPLINGMODE);
            texture.wrapU = BABYLON.Texture.CLAMP_ADDRESSMODE;
            texture.wrapV = BABYLON.Texture.CLAMP_ADDRESSMODE;
            var sprite = new BABYLON.Sprite2D(texture, { parent: canvas, id: "sprite1", x: 100, y: 100, invertY: true, spriteSize: new BABYLON.Size(64, 64), spriteLocation: new BABYLON.Vector2(0, 192 - 64) });

            var sprite2 = new BABYLON.Sprite2D(texture, { parent: canvas, id: "sprite1", x: 200, y: 100, invertY: true, spriteSize: new BABYLON.Size(64, 64), spriteLocation: new BABYLON.Vector2(0, 192 - 64) });```
do you have a PG/Use case?

**Comment by wyklion** [comment]
@nockawa I don't know when PG update neweast with github code.

And i see you remove these codes when textrueReady.
                    _this._parentTransformStep = 0;
                    _this._setFlags(BABYLON.SmartPropertyPrim.flagModelDirty);
                    _this.onPrimitivePropertyDirty(BABYLON.Prim2DBase.actualPositionProperty.flagId);
For me, it they are gone, sprite not display most times.

**Comment by nockawa** [comment]
@wyklion I didn't intent to remove this code, it's a bad merge from GIT... damn that's why things are not working now....It's bad luck all the time with this issue!!! Thanks for letting me know I take a look right now!

**Comment by nockawa** [comment]
@wyklion   just checked what you said, I thought you were talking about this: https://github.com/BabylonJS/Babylon.js/blob/master/src/Canvas2d/babylon.sprite2d.ts#L332 but the code is the same as I expected. Can you be more precise on what you think it should be, because right now, looks like it's worst than before (and I don't understand why).

**Comment by wyklion** [comment]
@nockawa yeah, That's my feel... worse than before... but i dont know why. I dont really understand the code what you modified... 
you can see http://www.html5gamedevs.com/topic/24120-new-primitive-type-in-canvas-has-dispose-problem/ 
i use F12 in chrome to track code and find something not stable...

Even i add three lines code i said before, it's also not right, it's not root problem.
You should find it yourself.... Fighting!!! We all depend on you~~

**Comment by nockawa** [comment]
@wpdildine I've spotted the issue, it's another dev that caused this bug, I'm fixing right now.

**Comment by nockawa** [comment]
you can get the changes of this commit https://github.com/BabylonJS/Babylon.js/pull/1286/commits/cb8dcf8a85c77395c86a0ef7474c5f9945eeeb12 if you want things working back again. I think it's good now.

**Comment by wyklion** [comment]
good new!! it works!!
I'll continue find your bugs...
Now aknown bug 1. WSC/ORTHOGRAPHIC_CAMERA pointevent.  2. position move make draw order wong

**Pull request merged**
