### PR TITLE
Dev Host improvements

### PR DESCRIPTION
**Pull request by RaananW**
The dev host allows you to write code directly related to the typescript files in the dev packages instead of using the UMD pattern.

This allows you to better experiment with es6 modules.

This improves the dev host by doing the following:

1) Module resolution using the module's name (without the @babylon part). 
2) Server is much quicker to reload
3) Full sruppot for all of our modules.
4) A new analyze script that allows you to show a report of the modules loaded with your current code.

To run the analyzer, do the following:

`npm run analyze -w @tools/dev-host`

The HTML page will open automatically and will look roughly like this:

image

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14775/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14775/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14775/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14775/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14775/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14775/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14775/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14775/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14775/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14775/merge/testResults/webgl2playwright/index.html

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
