### PR TITLE
DeviceEventFactory: Modified event factory to provide correct value for buttons property (part deux)

### PR DESCRIPTION
**Pull request by PolygonalSun**
This PR is a fix to https://github.com/BabylonJS/Babylon.js/pull/13927.  It addresses some of the logic changes but also re-adds support for buttons in Native pointer events.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14043/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14043/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14043/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14043/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14043/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14043/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14043/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14043/merge#BCU1XR#0

**Review by RaananW — APPROVED** [review]
LGTM! makes sense (especially setting the buttons value correctly)

**Review by CedricGuillemet — APPROVED** [review]
Tested OK with gizmo PG

**Pull request merged**
