### PR TITLE
Fix GlowLayer resize bug

### PR DESCRIPTION
**Pull request by BlakeOne**
Fix GlowLayer issue where blurKernelSize is reset when canvas is resized. Note: the value passed to the setter is multiplied by 2 because later _createTextureAndPostProcesses() will divide it by 2.

Test Playground: https://playground.babylonjs.com/#RPA5G8
Forum: https://forum.babylonjs.com/t/glowlayers-kernelblursize-is-reset-on-canvas-resize/34495

### CODE REVIEW

**Review by sebavan — COMMENTED** [review]
Adding a comment could be nice :-) as it is not automatically understandable ?

**Review by RaananW — COMMENTED** [review]
Sorry, might be naive, but wouldn't it be a better solution not to change it in the first place?

**Comment by sebavan** [comment]
We should make it a bit differently I agree for maintenance purpose I ll try something out ASAP.

**Comment by sebavan** [comment]
@BlakeOne I am gonna close this one in favor of the other one if you do not mind ?

**Pull request closed without merging**
