### PR TITLE
Don't allow blocks in NME to automatically connect to other blocks in…

### LINKED ISSUE #14225: [NME] - Visual Bug - Texture Node + Mesh.uv inside a collapsed frame
In the following Node Material: https://nme.babylonjs.com/#SRSTKI

If you drag out a texture node, you will see that the editor draws a visual line from the new texture node uv input out into the distance and it connects to nothing.
image

There is a visual bug here. There is already a mesh.uv node inside of the collapsed frame, but the editor doesn't know how to display any new texture node correctly. What SHOULD happen is that if there's already a mesh.uv node inside of a frame, any future node that needs mesh.uv should create a new node rather than try to reuse the existing one.

### PR DESCRIPTION
**Pull request by carolhmj**
…side frames.

Fixes #14225

Thankfully the NGE blocks don't need the same change as they only create new input blocks, never connect to existing blocks 😌

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by deltakosh** [comment]
Nice!

**Review by sebavan — APPROVED** [review]
Just an idea but not sure if we should :-)

instead of `!additionalFilteringInfo || additionalFilteringInfo(b)` everywhere, I wonder if we should have a default empty filter like `() => true` ? so we can not forget at the usage site ?

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14226/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14226/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14226/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14226/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14226/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14226/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14226/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14226/merge#BCU1XR#0

**Comment by carolhmj** [comment]
> Just an idea but not sure if we should :-)
> 
> instead of `!additionalFilteringInfo || additionalFilteringInfo(b)` everywhere, I wonder if we should have a default empty filter like `() => true` ? so we can not forget at the usage site ?

Oh, that would look better! Let me change it 😃

**Review by Popov72 — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14226/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14226/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
