### PR TITLE
NME: multiple-import Custom Block and Custom Frame 

### PR DESCRIPTION
**Pull request by onekit-boss**
allow user to multiple-import Custom Block and Custom Frame in NME

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14409/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14409/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14409/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14409/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14409/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14409/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14409/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14409/merge#BCU1XR#0

**Review by sebavan — CHANGES_REQUESTED** [review]
multiple should be a property of LineWithFileButtonComponent as it is a shared component and we can not assume multiple will be ok everywhere (for instance environment only one at a time)

Then at the usage site, you ll be able to enable it.

**Comment by onekit-boss** [comment]
> multiple should be a property of LineWithFileButtonComponent as it is a shared component and we can not assume multiple will be ok everywhere (for instance environment only one at a time)
> 
> Then at the usage site, you ll be able to enable it.

ok。 I has fixed it

**Review by sebavan — APPROVED** [review]

**Pull request merged**
