### PR TITLE
remove surrounding module start/end

### PR DESCRIPTION
**Pull request by TrevorDev**
**Note:** the script skipped these files as they are part of the DEBUG namespace
SKIPPING: src/Cameras/webvr.ts
SKIPPING: src/Debug/axesViewer.ts
SKIPPING: src/Debug/boneAxesViewer.ts
SKIPPING: src/Debug/physicsViewer.ts
SKIPPING: src/Debug/skeletonViewer.ts
SKIPPING: src/Engine/webgl2.ts
SKIPPING: src/mixins.ts

The diffing in github makes it look like its modifying every line but that is just the removal of indent.

Script:
var fs = require('fs');
var glob = require("glob-promise")

var main = async ()=>{

    var files = await glob("src/**/*.ts")
    // not d.ts files
    files = files.filter((f)=>{return f.indexOf(".d.ts") == -1})
    
    files.forEach((file)=>{
    //file = files[0];
        // read data
        var data = fs.readFileSync(file, 'utf8');

        if(data.indexOf("module BABYLON {") == -1){
            console.log("SKIPPING: "+file)
            return;
        }

        // Remove module
        data = data.replace("module BABYLON {", "")
        
        // remove ending brace
        var lines = data.split("\n")
        if(lines[lines.length - 1].indexOf("}")!= -1){
            lines.splice(lines.length - 1, 1)
        }else if(lines[lines.length - 2].indexOf("}")!= -1){
            lines.splice(lines.length - 2, 1)
        }else{
            console.log("No end found: "+file)
        }
        
        lines.forEach((l, i)=>{
            lines[i] = l.replace(/^    /gi,"")
        })

        data = lines.join("\n")
        // console.log(lines[lines.length - 3])
        // console.log(lines[lines.length - 2])
        // console.log(lines[lines.length - 1])
        //console.log(data)
        var err = fs.writeFileSync(file, data)
        //console.log(err)
    })
}
main();

### CODE REVIEW

**Comment by sebavan** [comment]
LGTM but could you double check by a lot :-) before merging ?

**Comment by TrevorDev** [comment]
Yep, diffing with vscode works much better, checked about 20 random files, all looked good to me.

**Comment by sebavan** [comment]
Did you check files where module BABYLON { was defined several time or not last ? (in case we have some)

**Comment by TrevorDev** [comment]
no cases found of multiple module Babylon {  and no cases where it was last

**Comment by sebavan** [comment]
Sweet I ll merge tomorrow morning for me I am validating the prefix to ensure it does not break any gulp stuff we did not hink about, THX !!!!

**Comment by sebavan** [comment]
@TrevorDev Could you resolve the conflicts on this branch and then I merge it in ???

**Comment by TrevorDev** [comment]
using this pr instead https://github.com/BabylonJS/Babylon.js/pull/5410

**Pull request closed without merging**
