### PR TITLE
Wrong loadMipmaps flag in ddsTextureLoader

### PR DESCRIPTION
**Pull request by Nikys**
https://forum.babylonjs.com/t/wrong-loadmipmaps-flag-in-ddstextureloader/51942

As @RaananW mentioned on forum, there still'll be discussion about presence of `loadMipmaps` parameter at the first place, but here's my temp fix until it is done.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15259/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15259/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15259/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15259/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15259/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15259/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15259/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15259/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15259/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15259/merge/testResults/webgpuplaywright/index.html

**Comment by Nikys** [comment]
Am I correct in assuming that I can't change label to `bug` as I am not a member of Babylon.js project?

**Comment by RaananW** [comment]
Yes, this is more of a note for us

**Pull request merged**
