### PR TITLE
Switch Viewer alpha test app from WebPack to Vite

### PR DESCRIPTION
**Pull request by ryantrem**
Switching the Viewer alpha test app from WebPack to Vite for a couple reasons:
1. I need to use Rollup for some of the size analysis testing as it's very easy to configure Rollup to do what I want, but I've not figured out any way to get WebPack to do the same thing.
2. It is easier to setup a test app with Vite that consumes the source (e.g. index.html just references the Viewer index.ts directly as a module as opposed to WebPack where it has to reference the WebPack output explicitly).
3. It was fairly easy to get working debugging in the test app's index.html inline scripts while I've not figured out how to get that to work with WebPack.
4. Vite is super fast, less waiting. :)

On the other hand, a few things were harder to configure with Vite:
1. Getting my Vite test app to correctly debug other parts of the code required manually configuring the `pathMapping` in launch.json.
2. Getting the VSCode task to recognize that Vite is up and running required manual configuration.

Overall I still prefer moving to Vite as I think the benefits outweigh the costs.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15282/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15282/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15282/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15282/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15282/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15282/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15282/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15282/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15282/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15282/merge/testResults/webgpuplaywright/index.html

**Review by RaananW — APPROVED** [review]

**Pull request merged**
