### PR TITLE
onDrawObservable, raw text size, Watcher

### PR DESCRIPTION
**Pull request by royibernthal**
I found myself needing to listen to draw. I notify the observers in container to avoid doing any rewrites. Hopefully you'll be fine with this addition.

New issue I'd like to discuss (can possibly be part of this PR) -

When I'm creating a TextBlock, in many cases its container's size depends on its size, however since that can't be evaluated at the creation time when resizeToFit is set to true, there's a problem.

1) The solution would be to define the size of the container when textBlock.onDrawObservable is notified (probably consistently and not just on the first render, which would be the default behavior when listening to an observable), however it should be possible to evaluate the raw size of the width and height (sort of reverse idealWidth / idealHeight) in order for it to make sense in controls that are using idealWidth and idealHeight and need to depend on that size.

2) Since a container size can depend on more than 1 TextBlock and/or containers that themselves depend on a TextBlock's size, I was thinking of creating a watcher to aggregate observers. It'd be an all purpose watcher rather than just for this specific case of course, I imagine it something like this:

`new Watcher(controls: Control[], observable: string, callback: (control: Control) => void)`

So for instance:

`new Watcher([textBlock1, textBlock2, someContainer], 'onDrawObservable', (control) => console.log('Control Drawn', control);`

I imagine the Watcher being part of bjs rather than gui.

These solutions will of course be useful in many other cases as they're generic.

What do you think?

### CODE REVIEW

**Comment by deltakosh** [comment]
Should it be onAfterDrawObservable to be coherent with the engine?
Regarding the watcher, I don't hink we will add it to the core for now as we did not use it.

**Comment by royibernthal** [comment]
Sure.
Watcher - I was afraid you might say something like that, no problem.

**Comment by deltakosh** [comment]
I'm working on a kind of watch for you :) stay tuned

**Comment by royibernthal** [comment]
Sounds good :)

**Comment by deltakosh** [comment]
Here we are: http://doc.babylonjs.com/overviews/observables#multiobserver

**Comment by royibernthal** [comment]
Thanks looks good

**Comment by royibernthal** [comment]
Out of curiosity, any reason you don't do something like that?

```
public static Watch<T>(observables: Observable<T>[], callback: (eventData: T, eventState: EventState) => void, mask: number = -1, scope: any = null): MultiObserver<T> {
	let result = new MultiObserver<T>();

	result._observables = observables; 
	result._observers = observables.map(observable => observable.add(callback, mask, false, scope));

	return result;
}
```

**Comment by deltakosh** [comment]
No good reason for one or another:)

**Comment by royibernthal** [comment]
Okay :)

**Comment by royibernthal** [comment]
Hey can you please build it so it's available in preview release?

**Comment by deltakosh** [comment]
I will in a couple of hours

**Comment by royibernthal** [comment]
kk

**Pull request merged**
