### PR TITLE
[XR] Implementation of WebXR Depth Sensing Feature

### PR DESCRIPTION
**Pull request by drumath2237**
Add a WebXR Feature of [Depth Sensing Module](https://www.w3.org/TR/webxr-depth-sensing-1/).

Related issue is #11876 

Related forum page is [here](https://forum.babylonjs.com/t/webar-demo-of-creating-depth-image-of-real-world-using-depth-sensing/34745).

### CODE REVIEW

**Review by RaananW — COMMENTED** [review]
Thank you so much for thie PR! Great work :-)

We try not to provide the dev directly with WebXR objects but abstract the usage as much as we can.

For example - CPU usage, it seems like we can "init" the XRCPUDepthInformation object internally, and then, once available, provide the `getDepthInMeters` directly, or at least abstract that to the dev.

Regarding GPU, we should not provide a WebGL2Texture to the user, but a babylon texture that the user can use. Internally, the user can have access to the internal texture, but the public API should be a babylon object and not a WebXR/WebGL object.

We should provide something extra to the dev, otherwise there is no difference between using the feature and implementing it yourself.

**Comment by drumath2237** [comment]
@RaananW 
Sorry for very late reply.

I've thought about API specification of the WebXRDepthSensing feature and managed to draw a proposal.

image

The parameters of `XRDepthInformation` are exposed directry for example `width`, `height`, and `rawValueToMeters`.
These are acquired from cached `XRDepthInformation` internally.

And specific fields of `XRCPUDepthInformation` and `XRWebGLDepthInformation` are provided as nullable data.

When the Usage is 'cpu-optimized', we can access `data` field as ArrayBuffer.

```ts
interface XRCPUDepthInformation extends XRDepthInformation {
    readonly data: ArrayBuffer;

    getDepthInMeters(x: number, y: number): number;
}
```

This type of array can be changed by depth information data format between `luminance-alpha` and `float32`.

When the usage is 'gpu-optimized', we can access texture field as WebGLTexture.
I assumed that WebGLTexture can be convert to `InternalTexutre` and wraped by `RawTexture`.
(I'm not sure this is correct and best way. So, please fix if I'm wrong.)

Maybe, when the usage is 'cpu-optimized', we can generate RawTexture from ArrayBuffer.

How do you think abou this?

**Comment by RaananW** [comment]
> Maybe, when the usage is 'cpu-optimized', we can generate RawTexture from ArrayBuffer.

Yes to all! :-)

We should use a texture instead of a webgl texture, so that the dev will be able to use it in a babylon material or use it just like any other texture on both gpu and cpu optimized

> This type of array can be changed by depth information data format between `luminance-alpha` and `float32`.

Those will need to be configurable in the options (if it's not already the case).

`getDepthInMeters` should also be exposed from the module itself, and throw if not available (for example in a gpu-optimized scenario, if I understand correctly)

**Comment by sebavan** [comment]
@drumath2237 any update on this PR :-) It looks like a really cool feature.

**Comment by drumath2237** [comment]
@sebavan 
Sorry, I couldn't worked on it these days...
Once, I'll turn this PR to draft PR.

**Comment by RaananW** [comment]
I have to close this PR because of the repo cleanup. Let's open it again from a clean branch

**Pull request closed without merging**
