### PR TITLE
NME support custom Properties with CustomBlock 

### PR DESCRIPTION
**Pull request by onekit-boss**
Allow users to design Properties in CusontBlock JSON file, Like other 3D Engines's Material Blocks, here a demo JSON:
{
  "name": "Math",
  "comments": "Math",
  "target": "VertexAndFragment",
  "inParameters": [
    {
      "name": "x",
      "type": "Float",
      "default": "0.5"
    },
    {
      "name": "y",
      "type": "Float",
      "default": "0.5"
    }
  ],
  "outParameters": [
    {
      "name": "Value",
      "type": "Float"
    }
  ],
  "math_type": 0,
  "titleProperty": 0,
  "x_properties": [
    {
      "propertyName": "math_type",
      "label": "Type",
      "options": [
        { "label": "Add", "value": "Add" },
        { "label": "Subtract", "value": "Subtract" }
      ]
    }
  ],
  "x_layouts": [
    {
      "condition": { "math_type": "Add" },
      "node": {
        "inputNames": ["x", "y"],
        "functionName": "Math_Add",
        "code": [
          "void Math_Add(float x,float y,out float value) {",
          "   value = x + y;",
          "}"
        ]
      }
    },
    {
      "condition": { "math_type": "Subtract" },
      "node": {
        "inputNames": ["x", "y"],
        "functionName": "Math_Subtract",
        "code": [
          "void Math_Subtract(float x,float y,out float value) {",
          "   value = x - y;",
          "}"
        ]
      }
    }
  ]
}

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by onekit-boss** [comment]
Okay......Properties to be  used for allow one block with muilty-modes. so that user can wirte different GLSL in different modes. and some other settings. Plese refer to "Float Block in Babylon NME " and "Math Block in Blender  Shading"

**Comment by onekit-boss** [comment]
> @sebavan Okay......Properties to be used for allow one block with muilty-modes. so that user can wirte different GLSL in different modes. and some other settings. Plese refer to "Float Block in Babylon NME " and "Math Block in Blender Shading"



> @onekit-boss thanks for the PR.
> 
> I am not too sure what this brings compared to creating several blocs. Usually, those features are pretty good for factorization but I am not sure it helps in this regards here.
> 
> Could you help me to understand your use case and why this would be better than creating several blocs ?
> 
> Let me move as draft in the mean time.



> @sebavan Okay......Properties to be used for allow one block with multi-mode. so that user can wirte different GLSL in different modes. and some other settings. Plese refer to "Float Block in Babylon NME " and "Math Block in Blender Shading"



> @onekit-boss thanks for the PR.
> 
> I am not too sure what this brings compared to creating several blocs. Usually, those features are pretty good for factorization but I am not sure it helps in this regards here.
> 
> Could you help me to understand your use case and why this would be better than creating several blocs ?
> 
> Let me move as draft in the mean time.

here a demo Block:
{
  "name": "Demo",
  "comments": "Demo",
  "target": "VertexAndFragment",
  "inParameters": [
    {
      "name": "x",
      "type": "Float",
      "default": "0.5"
    },
    {
      "name": "y",
      "type": "Float",
      "default": "0.5"
    }
  ],
  "outParameters": [
    {
      "name": "Value",
      "type": "Float"
    }
  ],
  "demo_a": 0,
  "demo_b": 0,
  "titleProperty":0,
  "x_properties": [
    {
      "propertyName": "demo_a",
      "label": "Flag A",
      "options": [
        { "label": "A 1", "value": "A1" },
        { "label": "A 2", "value": "A2" }
      ]
    },
    {
      "propertyName": "demo_b",
      "label": "Flag B",
      "options": [
        { "label": "B 1", "value": "B1" },
        { "label": "B 2", "value": "B2" }
      ]
    }
  ],
  "x_layouts": [
    {
      "condition": { "demo_a": "A1","demo_b":"B1" },
      "node": {
        "inputNames": ["x", "y"],
        "functionName": "Demo_A1B1",
        "code": [
          "void Demo_A1B1(float x,float y,out float value) {",
          "   value = x + y;",
          "}"
        ]
      }
    },
    {
      "condition": { "demo_a": "A1","demo_b": "B2"  },
      "node": {
        "inputNames": ["x", "y"],
        "functionName": "Demo_A1B2",
        "code": [
          "void Demo_A1B2(float x,float y,out float value) {",
          "   value = x - y;",
          "}"
        ]
      }
    },
    {
      "condition": { "demo_a": "A2","demo_b": "B1"  },
      "node": {
        "inputNames": ["x", "y"],
        "functionName": "Demo_A2B1",
        "code": [
          "void Demo_A2B1(float x,float y,out float value) {",
          "   value = x * y;",
          "}"
        ]
      }
    }
    ,
    {
      "condition": { "demo_a": "A2","demo_b": "B2"  },
      "node": {
        "inputNames": ["x", "y"],
        "functionName": "Demo_A2B2",
        "code": [
          "void Demo_A2B2(float x,float y,out float value) {",
          "   value = x / y;",
          "}"
        ]
      }
    }
  ]
}

We have lot of CustomBlocks may contains 3 Propertis,and each Property has 10 options.  now we have tow solutions:
Plan A: One Block with 3 Properties.
Plan B: create 1000 CustomBlocks (10x10x10).

We need Plan A

**Comment by onekit-boss** [comment]
> > @sebavan Okay......Properties to be used for allow one block with muilty-modes. so that user can wirte different GLSL in different modes. and some other settings. Plese refer to "Float Block in Babylon NME " and "Math Block in Blender Shading"
> 
> > @onekit-boss thanks for the PR.
> > I am not too sure what this brings compared to creating several blocs. Usually, those features are pretty good for factorization but I am not sure it helps in this regards here.
> > Could you help me to understand your use case and why this would be better than creating several blocs ?
> > Let me move as draft in the mean time.
> 
> > @sebavan Okay......Properties to be used for allow one block with multi-mode. so that user can wirte different GLSL in different modes. Plese refer to "Float Block in Babylon NME " and "Math Block in Blender Shading"
> 
> > @onekit-boss thanks for the PR.
> > I am not too sure what this brings compared to creating several blocs. Usually, those features are pretty good for factorization but I am not sure it helps in this regards here.
> > Could you help me to understand your use case and why this would be better than creating several blocs ?
> > Let me move as draft in the mean time.
> 
> here a demo Block: { "name": "Demo", "comments": "Demo", "target": "VertexAndFragment", "inParameters": [ { "name": "x", "type": "Float", "default": "0.5" }, { "name": "y", "type": "Float", "default": "0.5" } ], "outParameters": [ { "name": "Value", "type": "Float" } ], "demo_a": 0, "demo_b": 0, "titleProperty":0, "x_properties": [ { "propertyName": "demo_a", "label": "Flag A", "options": [ { "label": "A 1", "value": "A1" }, { "label": "A 2", "value": "A2" } ] }, { "propertyName": "demo_b", "label": "Flag B", "options": [ { "label": "B 1", "value": "B1" }, { "label": "B 2", "value": "B2" } ] } ], "x_layouts": [ { "condition": { "demo_a": "A1","demo_b":"B1" }, "node": { "inputNames": ["x", "y"], "functionName": "Demo_A1B1", "code": [ "void Demo_A1B1(float x,float y,out float value) {", " value = x + y;", "}" ] } }, { "condition": { "demo_a": "A1","demo_b": "B2" }, "node": { "inputNames": ["x", "y"], "functionName": "Demo_A1B2", "code": [ "void Demo_A1B2(float x,float y,out float value) {", " value = x - y;", "}" ] } }, { "condition": { "demo_a": "A2","demo_b": "B1" }, "node": { "inputNames": ["x", "y"], "functionName": "Demo_A2B1", "code": [ "void Demo_A2B1(float x,float y,out float value) {", " value = x * y;", "}" ] } } , { "condition": { "demo_a": "A2","demo_b": "B2" }, "node": { "inputNames": ["x", "y"], "functionName": "Demo_A2B2", "code": [ "void Demo_A2B2(float x,float y,out float value) {", " value = x / y;", "}" ] } } ] }
> 
> We have lots of CustomBlocks that may contains 3 Propertis,and each Property has 10 options. now we have two solutions: Plan A: One Block with 3 Properties. Plan B: create 1000 CustomBlocks (10x10x10).
> 
> We need Plan A

**Comment by onekit-boss** [comment]
> Would that not force us to have One block with 1000 functions flavors anyway ?
> 
> (sorry for all my questions just trying to make sure the extra complexity and maintenance is worth it)

as [https://doc.babylonjs.com/toolsAndResources/nme/customBlocks](https://doc.babylonjs.com/toolsAndResources/nme/customBlocks) said:"Starting with v5.0 you can now create custom blocks by wrapping some plain GLSL code. It can come in handy when you have some complicated code that could be difficult to recreate with the existing node material blocks."
I think the best useful of the Custom Block , should be extend the System Block. but we not be able to create  properties in it.
we just need "multi-mode" in One Block, please, and almost all modern 3D engines contained this feature.

**Comment by sebavan** [comment]
I am still troubled to understand what this brings compared to creating several nodes.

It could be error prone as it is simple to forget the implementation of one condition whereas the separate custom blocks would not suffer from this.

In the 10*10*10 example you provided, would the issue be at creation time / import time or at usage time within the editor ? (trying to see if there is another solution like maybe opening the system for ppl to create their nodes by codes and reference them in nme)

**Comment by RaananW** [comment]
missing formatting fix to get the CI green. run `npm run format:fix` to solve these issues.

**Pull request closed without merging**
