### PR TITLE
Dependency update and removing lint:fix

### PR DESCRIPTION
**Pull request by RaananW**
See title :-)

### CODE REVIEW

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14966/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14966/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14966/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14966/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14966/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14966/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14966/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14966/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14966/merge/testResults/webgpuplaywright/index.html

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14966/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
