### PR TITLE
Added notifying onStopped observers in gpu particles

### PR DESCRIPTION
**Pull request by RolandCsibrei**

### CODE REVIEW

**Comment by RolandCsibrei** [comment]
```javascript
    gpuPS.onStoppedObservable.add(() => {
       // do whatever you want
    })
```

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15245/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15245/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15245/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15245/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15245/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15245/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15245/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15245/merge#BCU1XR#0

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15245/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15245/merge/testResults/webgpuplaywright/index.html

**Pull request merged**
