### PR TITLE
Include Draco and Basis in @babylonjs/core

### PR DESCRIPTION
**Pull request by RaananW**
Part of #12783.
KTX2 Decoders package was already released under @babylonjs/ktx2decoder

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Reviewer - this PR has made changes to one or more package.json files.

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14869/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14869/merge/testResults/webgl2playwright/index.html

**Review by Popov72 — APPROVED** [review]

**Pull request merged**
