### PR TITLE
Fix PBRSpecularGlossiness excluded from material export - redo

### LINKED ISSUE #9423: PBRSpecularGlossiness materials are excluded from export
See:
https://forum.babylonjs.com/t/spec-gloss-material-to-gltf-glb/15652/3

Currently we only export PBRMaterial, PBRMetallicRoughnessMaterial, and StandardMaterial.

We should either A) create some material conversion functionality to export PBRSpecularGlossinessMaterial as PBRMaterial, or reimplement the PBRSpecularGlossiness export codepath.

### PR DESCRIPTION
**Pull request by Drigax**
Refactored material export code paths to use PBRBaseMaterial, with relevant fields retreived via fallback OR operations.
Fixes #9423
This reverts commit 8ed097748092d1b8aade78d7ac37ff0d35bc67c4.

### CODE REVIEW

**Comment by sebavan** [comment]
LGTM adding @bghgary to review

**Review by bghgary — APPROVED** [review]
Seems fine.

**Comment by sebavan** [comment]
@Drigax could you update to master to remove the conflict ??? and I ll merge it

**Comment by sebavan** [comment]
Actually I updated it inlined :-)

**Pull request merged**
