### PR TITLE
Use FirefoxHeadless instead of the obsolete PhantomJs in tests.

### PR DESCRIPTION
**Pull request by mrdunk**
One additional thing that could be done here is remove PhantomJS from `npm`'s `package.json` file but i don't know enough about Babylon's build environment to know if that will break anything else...

Advice welcome.

### CODE REVIEW

**Comment by deltakosh** [comment]
Pinging @sebavan  to evaluate the build issues

**Comment by mrdunk** [comment]
likely root cause for the Build step:
https://github.com/webpack/webpack/issues/8768

My other PR in flight at the moment is hitting the same error:
https://github.com/BabylonJS/Babylon.js/pull/5891

**Comment by deltakosh** [comment]
Yes chasing it down. Will force a build here to make sure that is fixed

**Comment by deltakosh** [comment]
Actually can you merge from Master to get the "fix" ?

**Comment by deltakosh** [comment]
Nope all good, I was able to do it
let's wait for the build now

**Comment by sebavan** [comment]
Sounds Perfect to me, could you remove phantomjs from https://github.com/BabylonJS/Babylon.js/blob/master/package.json and indicates in the doc that firefox should be installed on the dev machine ?

Thanks a lot I am glad you did it :-)

**Comment by mrdunk** [comment]
> indicates in the doc that firefox should be installed on the dev machine ?

Firefox is already what he docs recommend.
see here:
https://doc.babylonjs.com/how_to/how_to_start#install-firefox

**Comment by sebavan** [comment]
Oh true even better, you do not even need to add it there :-)

**Comment by sebavan** [comment]
I am noticing some visual tests failures on your branch despite no changes to this. Please hold on before merging, I am looking into it.

**Comment by mrdunk** [comment]
> I am noticing some visual tests failures on your branch despite no changes to this. Please hold on before merging, I am looking into it.

yes, please see my earlier post as to likely root cause.
I believe this is happening in all branches just now.

**Comment by sebavan** [comment]
So I have run your build several times and it still fails on Travis whereas it works locally. The other branches do not look like they have been impacted so far.

Would be amazing if you could figure out the issue or replace with another headless solution ?

**Comment by mrdunk** [comment]
967fecb contains some possible solutions but without any experience in any of the technology used here (Phantom, Travis, etc) or access to full logfiles i'm just guessing.

Let's see, we might get lucky.

**Comment by sebavan** [comment]
Your last change would break our visual tests as they need to run on a none headless version of Firefox to fully support WebGL rendering.

This internally relies on Travis provided virtual drivers.

Nothing looks wrong in your PR, But it looks like the build is impacted by relying on Firefox healess in some ways. 

We do not have access to more than the travis log either :-)

**Comment by mrdunk** [comment]
> Your last change would break our visual tests as they need to run on a none headless version of Firefox to fully support WebGL rendering.

that implies Travis must be able to run the full version of Firefox...
so we can probably run the full version everywhere.

I was working under the assumption that the test environment did not have access to a full GUI environment so needed to be headless.

I also saw a partially formatted error in the log file: `'%c failed (gl error)', 'color: red'`
That implies we are looking at WebGL issues....

It's a little wasteful but we could just swap `FirefoxHeadless` for `Firefox` everywhere.
Out of time right now but i'll try that in a bit.

**Comment by mrdunk** [comment]
Hrm. Making everything use `Firefox` rather than `FirefoxHeadless` makes things worse.
Build failure.
I guess this implies we need a headless browser for the components that use PhantomJS.

Reading a little online it appears FF used to do WebGL on headless but it was disabled at one point.
Reports are ambiguous as to whether it currently works.
Given the results we are seeing here, i think we can confirm it does not (easily) work.

Strangely, PhantomJS does /not/ have WebGL support so there must be another component providing WebGL  support for the PhantomJS tests.

The next thing i intend to try is Chrome (or some derivative).
I've seen reports online that it can do headless WebGL.

stay tuned.

**Comment by deltakosh** [comment]
Yep excellent idea!

**Comment by deltakosh** [comment]
Can you merge with master? I added more logs to get why the visual tests are failing

**Comment by deltakosh** [comment]
Actually this is the one you want :)
https://github.com/BabylonJS/Babylon.js/commit/daa0d7c2f4127edd68451c9744a6c0bfb3aa09c6

**Comment by sebavan** [comment]
Also Could you replace Phantomjs in the viewer/tests/karma.conf.js file ?

And I guess we ll be able to merge :-)

**Comment by mrdunk** [comment]
> daa0d7c

How do i merge this into my branch?
I'm not used to using Git at scale.

**Comment by deltakosh** [comment]
You need to switch to master, git pull then back to your branch and run git merge master

**Comment by mrdunk** [comment]
so i think i have a combination of browsers that work while still avoiding PhantomJS.
Chrome works for `viewer/tests/karma.conf.js` and is already used elsewhere so does not add any dependency.

This works on my laptop... Let's see what happens on the build server...

**Comment by deltakosh** [comment]
Sounds good. if it does not work I think we can revert back to pure firefox + ff headless as I think I fixed the test issues

**Comment by mrdunk** [comment]
> Sounds good. if it does not work I think we can revert back to pure firefox + ff headless as I think I fixed the test issues

Not quite; FF broke `viewer/tests/karma.conf.js`. We'd have to revert to PhantomJS there.

**Comment by deltakosh** [comment]
The overall goal was to avoid phantom..I thought it was working before? (except the visual tests that I may have fixed)

**Comment by mrdunk** [comment]
o right, didn't realise you'd done work on the visual tests.
Let me test that locally again with FF.

**Comment by mrdunk** [comment]
yup,
Firefox works for the Visual tests on my laptop.

Let's leave the current build (Chrome for Visual tests) running to confirm whether it passes or not then we can do the same for Firefox.
It's late here and i've not slept much in a few days so it will be tomorrow before i do anything more.

Glad the end of this one is in sight... it was supposed to be a quick fix....

**Comment by deltakosh** [comment]
Yeah take care!! we have time!

**Comment by mrdunk** [comment]
hrm, something not making sense.
that last build fails the Lint step die to files i didn't change...
All failing steps pass when i run them locally.

Won't get much time for this today.
Probably tonight.

**Comment by sebavan** [comment]
No rush :-) we ve got time for this, really appreciate your work on it.

**Comment by mrdunk** [comment]
Ok, i can reproduce these failures locally.
The same recent change arrived on my system with an `npm update`.
I suspect this will be affecting other PRs too.

Anyway,
i can reproduce this so i can fix it.
Stay tuned.

**Comment by deltakosh** [comment]
thanks a lot

**Comment by mrdunk** [comment]
ok, that's back to where we were.
Everything builds but `'%c failed (gl error)', 'color: red'` error during `tests-validation-virtualscreen`.

I can't reproduce this one on my system so
I'll go back to trying different browsers for this target.

**Comment by deltakosh** [comment]
Did you merge all the changes from master?

**Comment by mrdunk** [comment]
> Did you merge all the changes from master?

yup.

**Comment by deltakosh** [comment]
well i doubt it as I do not see the additional info I added:
https://github.com/BabylonJS/Babylon.js/blob/master/tests/validation/validation.js#L43

**Comment by mrdunk** [comment]
well balls.
let me try to pull those in again.

**Comment by mrdunk** [comment]
o wait, no i do have your changes.
Please confirm you see your changes here: https://github.com/mrdunk/Babylon.js/tree/PhantomJs_to_Firefox

**Comment by mrdunk** [comment]
interestingly, the Browser is not getting correctly set for these failing tests either.
If is using `Firefox` no matter what i configure.

**Comment by deltakosh** [comment]
ok this time I can see the change on your branch!

**Comment by mrdunk** [comment]
Aha. Firefox is set in Tools/Gulp/tasks/gulpTasks-tests.js as well.
Let's try Chrome there.

**Comment by mrdunk** [comment]
o but wait, this has always been set to Firefox.
If it's broken now then this must be related to changing .npm files.

**Comment by mrdunk** [comment]
well that's ...odd...
Using Chrome in `Tools/Gulp/tasks/gulpTasks-tests.js` all the build and test stages pass: https://travis-ci.com/BabylonJS/Babylon.js/builds/100693210

but we get a `Deploy preview failed.` with the following error:
`11:29:12 PM: /usr/local/bin/build: line 32: ./Tools/Gulp/node_modules/.bin/gulp: No such file or directory`

**Comment by mrdunk** [comment]
so this step passed in 967fecb (even though the tests failed)
and failed in d836cf0 and hasn't passed since.

I don't see how anything in d836cf0 could have caused this; that change was partially /reverting/ changes.

I can't reproduce this on my machine.
We don't have proper logs.
All i can think of trying is to scrap this PR and recreate from scratch; Maybe something is screwed in yGit workspace.

Any other ideas anyone?

**Comment by deltakosh** [comment]
I think this could be the best idea. Let's scrap everything and restart from scratch

**Comment by deltakosh** [comment]
I will try on my side as well :)

**Comment by mrdunk** [comment]
ok, this is interesting (and not definitely related)...
When i run the default `gulp` target (ie, `gulp` with no other options) i'm getting a JS stacktrace.
What's happening here? Are we exceeding Nodes stack size?
This /could/ cause the symptom we are seeing.

Here's the tail of my log:

```
<--- Last few GCs --->

[6265:0x3e20660]   479212 ms: Scavenge 1362.1 (1425.6) -> 1358.3 (1434.6) MB, 4.1 / 0.0 ms  (average mu = 0.157, current mu = 0.091) allocation failure 
[6265:0x3e20660]   479976 ms: Mark-sweep 1366.1 (1434.6) -> 1358.4 (1433.1) MB, 744.8 / 0.0 ms  (average mu = 0.102, current mu = 0.038) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x359e16e5be1d]
Security context: 0x3a2d2b61e6e1 <JSObject>
    1: createPrinter [0x13206d8ee401] [/home/duncan/Working/Babylon.js/node_modules/typedoc/node_modules/typescript/lib/typescript.js:~78771] [pc=0x359e1c58b7af](this=0x13206d8cd1c9 <Object map = 0x22d67e136b9>,printerOptions=0x178484309dd1 <Object map = 0x2b3c82af1281>,handlers=0x1f4e87a026f1 <undefined>)
    2: arguments adaptor frame: 1->2
    3: symbolTo...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8daaa0 node::Abort() [gulp]
 2: 0x8daaec  [gulp]
 3: 0xad79ae v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [gulp]
 4: 0xad7be4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [gulp]
 5: 0xece9e2  [gulp]
 6: 0xeceae8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [gulp]
 7: 0xedac12 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [gulp]
 8: 0xedb5d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [gulp]
 9: 0xede241 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [gulp]
10: 0xea7564 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [gulp]
11: 0x114bc12 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
12: 0x359e16e5be1d 
Aborted (core dumped)
```

**Comment by sebavan** [comment]
Yup you can use npm run build instead.

This is related to some of the tooling in place leaking some memory during the build

**Comment by mrdunk** [comment]
OK, it's a known issue.
Just thought maybe the build server was hitting the same issue.

**Comment by deltakosh** [comment]
tests here: https://github.com/BabylonJS/Babylon.js/pull/5917

**Comment by mrdunk** [comment]
ok, let's see how this goes:
https://github.com/BabylonJS/Babylon.js/pull/5916

**Comment by mrdunk** [comment]
Snap!
i'll race you.... first person with passing tests... gets... Passing tests!
(I think that's a good enough prize.)

**Comment by mrdunk** [comment]
AhHa!
I've worked out what's going on:
https://github.com/BabylonJS/Babylon.js/pull/5916/commits/f9f804f0e0a205aedf509b79405883bf7ba6d4dd

Obvious in retrospect.

**Comment by deltakosh** [comment]
Still building...what a suspens!

**Comment by mrdunk** [comment]
yea, but my `Deploy preview` passes.
I've already had everything else pass so i'm pretty confident...

**Comment by mrdunk** [comment]
In summary,
Firefox can't service all the GL tests.
Chrome can but Travis didn't know what the Chrome binary was called and spat a particularly uninformative error message.
Setting the `CHROME_BIN` environment variable in `.travis.yml` lets Travis find Chrome (even though it doesn't need it since the tests are run by Gulp).

**Comment by deltakosh** [comment]
wait did you managed to get a build working with chrome?

**Comment by mrdunk** [comment]
> wait did you managed to get a build working with chrome?

yes.
see the line `- export CHROME_BIN=chromium-browser` in 5f0beb9

looks like my current submission has a few test failures though.
I've switched to Chrome everywhere and i think these might be failures that used to pass with FF...

Wakaomole...

**Comment by sebavan** [comment]
We should not use Chrome here as it falls back to its software rendering rendering version that we know having some slight diffs which will take us a long time to troubleshoot:

image

**Comment by sebavan** [comment]
Closing in favor of #5923 as this succeeded on Travis. Thanks for all the help.

**Comment by mrdunk** [comment]
good work!
Thanks for the rescue!

**Pull request closed without merging**
