### PR TITLE
[WebXR] Tweak teleportation landing zone appearance

### PR DESCRIPTION
**Pull request by yuripourre**
This is a breaking change!

This PR is an attempt to tweak landing zone's appearance. It removes the torus and draws the orientation arrow at the ground mesh.

It also adds an hologram effect with gradient transparency around the ground mesh. The textures still need some tweaks but this is a start.

Playground: https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14643/merge/index.html#B8D5Z6

Any feedback is welcome.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14643/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14643/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14643/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14643/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14643/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14643/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14643/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14643/merge#BCU1XR#0

**Comment by sebavan** [comment]
Thanks for the PR but one of the Babylon main pillar is to introduce breaking changes only when absolutely required (bugs) so I do not think we can introduce the change as it is today.

Maybe you could instead introduce a way to customize it as you want and we could have several versions if that makes sense ? cc @RaananW for this part ? 

Let me close for now so we can reopen once agreed on the direction to take with @RaananW

**Comment by yuripourre** [comment]
Thanks for reviewing it, @sebavan I am cracking my head to tweak it in a way I can customize the way I need without introducing breaking changes. It will be tough but I will try my best in a future PR.

**Comment by yuripourre** [comment]
@RaananW thanks for looking into it, the solution I've found is instead of changing the texture l am replacing the entire target mesh (avoiding torus creation).

This PR is not needed anymore.

**Pull request closed without merging**
