### PR TITLE
NME Custom Blocks

### PR DESCRIPTION
**Pull request by BlakeOne**
Here’s the new patch for NME custom blocks, with the file customBlock.ts fixed to explicitly provide function findInputByName’s return type.

Forum: https://forum.babylonjs.com/t/nme-custom-blocks-take-two/23961

Link to the json test files (and src files): https://github.com/BlakeOne/NMECustomBlockFiles

### CODE REVIEW

**Comment by BlakeOne** [comment]
Forum: https://forum.babylonjs.com/t/nme-custom-blocks-take-two/23961

Link to test files (and src files): https://github.com/BlakeOne/NMECustomBlockFiles

**Comment by Popov72** [comment]
You should also read the Unity doc page I have linked in the other PR, I think it can lighten things a bit.

**Comment by BlakeOne** [comment]
@deltakosh, @Popov72, it looks like the only keeping it from validating now is the missing "What's New Update", should I update that file to say that NME custom blocks were added and redo the patch?

**Comment by deltakosh** [comment]
Please add it to the file..But I think we should merge it when completely done right? (meaning including the great idea from @Popov72 )

**Comment by BlakeOne** [comment]
> Please add it to the file..But I think we should merge it when completely done right? (meaning including the great idea from @Popov72 )

Okay, I'll wait to make the patch until customBlock.ts is more finalized as well then.

And I just posted on the forum about implementing @Popov72's idea, to try to get a better handle on it before I start coding and testing it out:)

https://forum.babylonjs.com/t/nme-custom-blocks-take-two/23961/6

**Pull request closed without merging**
