### PR TITLE
Add support for instanced meshes in STLEXPORT

### PR DESCRIPTION
**Pull request by d-0-s-t**
Related Forum Topic: https://forum.babylonjs.com/t/propose-to-remove-baking-transforms-during-stl-export-support-instanced-meshes/37210

CreateSTL has a new param "supportInstancedMeshes" which when set to true exports Instances without baking transforms on source mesh. Exporting instances with supportInstancedMeshes=false and doNotBakeTransforms=false may cause them to change orientation/positions in the scene.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by d-0-s-t** [comment]
Can't figure out how to add label to this PR. I thought I missed something the first time but can't see an option. Maybe I don't have permission?

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/13439/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13439/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/13439/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/13439/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/13439/merge
https://gui.babylonjs.com/?snapshot=refs/pull/13439/merge
https://nme.babylonjs.com/?snapshot=refs/pull/13439/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/13439/merge#BCU1XR#0

**Review by RaananW — APPROVED** [review]
LGTM.
@sebavan ?

**Review by sebavan — APPROVED** [review]

**Pull request merged**
