### PR TITLE
Add viewerready event and other fixes

### PR DESCRIPTION
**Pull request by ryantrem**
This PR has a number of fixes related to the new viewer, mostly in response to usages of the new viewer in different contexts.

1. The viewer html element previously exposed the underlying viewer object as a property. However, the underlying viewer is created asynchronously depending on various factors (whether or not the element is in the DOM, asynchrony of the Lit update/render sequence, and now also additional asynchrony for Babylon engine instantiation). This makes it quite hard to use, so I've replaced the property with an event (`viewerready`) that fires every time a viewer instantiation has completed.
1. Added events for environment change and error.
1. Made viewer API more consistent for loading/resetting the environment/model.
1. Enabled Lit property "reflection" (e.g. changing the property will "reflect" back to the attribute, which allows for CSS styling based on attribute values).
1. Added an "engine" attribute/property that can be undefined (we make the best choice of engine for you based on implementation details) or "WebGL" or "WebGPU", and updated aspects of the code to be async to account for the fact that WebGPUEngine creation is asynchronous (requires a call to `initAsync`). However, I am leaving out "WebGPU" for now because there are a number of problems due to missing dependencies that come from side effects. Some of these looked easy to fix (e.g. they are already in an async context), and some of them not so easy. @deltakosh not sure if this is the expected state of things for WebGPUEngine.
1. Changed MSFT_audio_emitter to import `audioSceneComponent` (it can't work without this). @bghgary 
1. Fixed a bug in weightedsound where if pause was called when not playing, then play will try to index into the sounds array with an undefined index value. @docEdub

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15560/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15560/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15560/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15560/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15560/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15560/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15560/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15560/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15560/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15560/merge/testResults/webgl2playwright/index.html

**Review by docEdub — COMMENTED** [review]
The weightedsound change looks good to me.

**Review by deltakosh — APPROVED** [review]

**Pull request merged**
