### PR TITLE
fixing scss not found exports

### PR DESCRIPTION
**Pull request by ricardovg4**
Getting about 180 warnings (errors) due to this:

WARNING in ../../dev/sharedUiComponents/src/nodeGraphSystem/graphNode.ts 170:46-72
export 'highlighted' (imported as 'localStyles') was not found in './graphNode.module.scss' (possible exports: default)

This is noticeable specially on the playground where styles won't be applied. I believe this is after commit 26ae13a where "import styles from ..."  is replaced by "import * as styles from ...". Undoing those lines and adding the flag         "allowSyntheticDefaultImports": true to tsconfig on some levels fixes the errors both on playground and the babylon-server.

From: 
image

To:
image

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by ricardovg4** [comment]
This fixes the playground as well, notice the white square on the left:

image

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15875/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15875/merge/testResults/webgl2playwright/index.html

**Comment by ricardovg4** [comment]
> Unfortunately, these changes make the ES6 build fail... We are actively working on a solution.

Yeah, just saw the ES6 build failed. I saw the revert PR which should be better. Closing PR.

**Pull request closed without merging**
