### PR TITLE
Master

### PR DESCRIPTION
**Pull request by MackeyK24**
Non breaking changes for serializable rotation angle (thetay) support

### CODE REVIEW

**Comment by MackeyK24** [comment]
What am i doing wrong when i commit a change using GitHub Desktop Version for Mac... Why does is say sooooo many **Merge remote-tracking branch 'BabylonJS/master'**

All i did was make a small change and hit commit ???

I really dont know how to use all the github features... I just make my changes and hit commit...

Note: I do SYNC my clone quite often to get latest changes ???

**Comment by MackeyK24** [comment]
I am kool with rotationY

**Comment by deltakosh** [comment]
I'll merge asap!

**Comment by RaananW** [comment]
Yo, just wanted to jump in on the "what am I doing wrong" - first you are doing nothing wrong, the app is simply doing things a bit differently.

Try creating a branch per feature, and dont use master as your development branch, and try, instead of pressing the "sync" button (or however it is called now) to use teh git console and merge the remote changes:

`git fetch BabylonJS`
`git merge BabylonJS/master`

**Pull request merged**
