### PR TITLE
Update azure-pipelines-cd.yml for Azure Pipelines

### PR DESCRIPTION
**Pull request by RaananW**
Adding preview CDN update.

### CODE REVIEW

**Comment by RaananW** [comment]
@sebavan - this is the preview CDN update task(s).

**Comment by RaananW** [comment]
What is the 2nd CI step? can't seem to find information about it

**Comment by sebavan** [comment]
The other CI step is the check for PR ensuring they are compiling and running tests.

Yup Continuous Deployment runs from preview so I think the branch has been setup from there. not a big deal, we can merge back in master just after.

**Comment by sebavan** [comment]
I just merged it and merged it back into master. Let s monitor the next nightly to see what happens :-)

**Pull request merged**
