### PR TITLE
Test NewCustomMaterial

### PR DESCRIPTION
**Pull request by NasimiAsl**

### CODE REVIEW

**Comment by RaananW** [comment]
Hi @NasimiAsl ,
any breaking changes involved here? I just noticed you removed a whole class (market with _OldVer).

**Comment by NasimiAsl** [comment]
that is just Used in CustomMaterial 
and in this task we most remove that part

**Comment by NasimiAsl** [comment]
hi when i can test playground with this changes?

**Comment by deltakosh** [comment]
I'll push a nightly in a couple of hours

**Pull request merged**
