### PR TITLE
Use Quaternion and slerp for alpha/beta/gamma arcrotate interpolation

### PR DESCRIPTION
**Pull request by CedricGuillemet**
Using modulo and Euler angles is always a bad idea. Using quaternion and slerp instead.

test PG : #TT1T4C#2

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15254/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15254/merge/testResults/webgpuplaywright/index.html

**Comment by RaananW** [comment]
Is this a breaking change to the camera behavior?

**Comment by CedricGuillemet** [comment]
> Is this a breaking change to the camera behavior?

Nop, it's a math improvement for this feature: https://github.com/BabylonJS/Babylon.js/pull/15248/files

**Pull request merged**
