### PR TITLE
Update babylon.node.ts

### PR DESCRIPTION
**Pull request by RaananW**
Fixing the === null reference

### CODE REVIEW

**Comment by RaananW** [comment]
http://www.html5gamedevs.com/topic/21008-getchildren-broken-in-babylon-playground/
This is caused by the "=== null"

**Comment by nockawa** [comment]
===null was returning false when undefined was passed, which caused the bug?

**Comment by RaananW** [comment]
yes, since the variable was not null but undefined. So !predicate (or (predicate === void 0)) would be the right way to go.

**Comment by nockawa** [comment]
good to know thank  you. the undefined concept is really interesting, but I'm still not used to it.

**Pull request merged**
