### PR TITLE
Physics scaling issue

### PR DESCRIPTION
**Pull request by RaananW**
Fixing #8888 

There is still an issue with oimo under specific conditions.

Playground that will work after merging:

https://playground.babylonjs.com/#492ZK0#120

### CODE REVIEW

**Comment by CedricGuillemet** [comment]
Rotations do not seem to be taken into account. Will this work with compound of oriented objects?

**Comment by RaananW** [comment]
The issue here was scaling, I changed nothing else.

sub-rotation is working well in ammo:

image

It was always an issue with oimo (Would be good to re-write the entire oimo sync procedures).  Looking into cannon now

**Comment by RaananW** [comment]
And now in cannon as well:

image

**Review by CedricGuillemet — APPROVED** [review]
LGTM!

**Comment by RaananW** [comment]
I am closing for now, I want to test every example we have before finalizing it.

**Comment by RaananW** [comment]
Apart from oimo acting up on compound of the mesh itself (due to an issue with the scaling), all demos work as expected.

**Comment by deltakosh** [comment]
Let's merge?

**Pull request merged**
