### PR TITLE
Projective

### PR DESCRIPTION
**Pull request by MavenRain**

### CODE REVIEW

**Comment by Palmer-JC** [comment]
Side stepping the merits of the arg order switch.  Timing of such a change, the day before a release, seems wildly dangerous.  That is the kind of thing, if done, is better that day after a release for the next one.

**Comment by deltakosh** [comment]
Can you explain if there is an impact regarding code that may already call tgis function?

**Comment by MavenRain** [comment]
The arg order switch doesn’t change the number of arguments, and so doesn’t break, and, in fact, fixes the implementation of mesh rotations so that all the various rotation conversions are consistent.  The naming itself re-enforces this consistency (Quaternions, Euler angles, etc. are NOT in Yaw-Pitch-Roll convention, mathematically).


With that said, there is nothing forcing the change to be applied at a certain time.






Sent from Windows Mail





From: Jeff Palmer
Sent: ‎Monday‎, ‎February‎ ‎9‎, ‎2015 ‎9‎:‎40‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





Side stepping the merits of the arg order switch. Timing of such a change, the day before a release, seems wildly dangerous. That is the kind of thing, if done, is better that day after a release for the next one.

**Comment by Palmer-JC** [comment]
It breaks AbstractMesh.calcMovePOV().  Probably others in repository.

**Comment by MavenRain** [comment]
I might need to you clarify what you mean by “break” in that case.






Sent from Windows Mail





From: Jeff Palmer
Sent: ‎Monday‎, ‎February‎ ‎9‎, ‎2015 ‎9‎:‎52‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





It breaks AbstractMesh.calcMovePOV(). Probably others in repository.

**Comment by deltakosh** [comment]
This is what I was thinking about. Could you push a PR with a new function instead of a replace?

**Comment by MavenRain** [comment]
This function is called during mesh rotation when quaternions are not used.  In that code, it essentially aides a transformation from Euler Angles to a quaternion, and then to a matrix.  However, the function is currently in the wrong convention, and so it does not match the rotations done with quaternions.






Sent from Windows Mail





From: David Catuhe
Sent: ‎Monday‎, ‎February‎ ‎9‎, ‎2015 ‎9‎:‎50‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





Can you explain if there is an impact regarding code that may already call tgis function?

**Comment by Palmer-JC** [comment]
Anyone calling code expecting a given order, got it to work that way.  When I made the method above, I just got it to work.  Yaw Pitch & roll not really in my vocabulary.  Now I would be processing the old way still

If this were 2 weeks ago, I would not even commented.  My yelp is about timing.

**Comment by deltakosh** [comment]
So what about renaming this function to whateverAlphaBetaGamma and use this new function for computeWorldMatrix

**Comment by Palmer-JC** [comment]
FYI, Not just me.  Did a search found used in TargetCamera, OculusGamepadCamera.

**Comment by MavenRain** [comment]
Good idea.  OK








Sent from Windows Mail





From: David Catuhe
Sent: ‎Monday‎, ‎February‎ ‎9‎, ‎2015 ‎9‎:‎56‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





This is what I was thinking about. Could you push a PR with a new function instead of a replace?

**Comment by MavenRain** [comment]
Understood






Sent from Windows Mail





From: Jeff Palmer
Sent: ‎Monday‎, ‎February‎ ‎9‎, ‎2015 ‎10‎:‎05‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





Anyone calling code expecting a given order, got it to work that way. When I made the method above, I just got it to work. Yaw Pitch & roll not really in my vocabulary. Now I would be processing the old way still

If this were 2 weeks ago, I would not even commented. My yelp is about timing.

**Comment by MavenRain** [comment]
This will work.






Sent from Windows Mail





From: David Catuhe
Sent: ‎Monday‎, ‎February‎ ‎9‎, ‎2015 ‎10‎:‎07‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





So what about renaming this function to whateverAlphaBetaGamma and use this new function for computeWorldMatrix

**Comment by MavenRain** [comment]
The idea here is that RotationYawPitchRoll is currently incorrect in all of these functions.  In that case, correcting it will “break” it.  David Catuhe has proposed adding a RotationAlphaBetaGamma, instead of subbing the current function.  I will proceed that way, so that either can be used.






Sent from Windows Mail





From: Jeff Palmer
Sent: ‎Monday‎, ‎February‎ ‎9‎, ‎2015 ‎10‎:‎19‎ ‎AM
To: BabylonJS/Babylon.js
Cc: Onyeka Obi





FYI, Not just me. Did a search found used in TargetCamera, OculusGamepadCamera.

**Pull request closed without merging**
