### PR TITLE
Adding new debug tools to the scene Inspector : copyCommandToClipboard & window.debugNode

### PR DESCRIPTION
**Pull request by Tricotou**
Initiated in this topic : [scene.debugLayer : Copy last command to Clipboard](https://forum.babylonjs.com/t/scene-debuglayer-copy-last-command-to-clipboard/49796)
____
**Addind copyCommandToClipboard :**

In the right panel of the inspector, all the main component have now a copy button, which copies to the clipboard the javascript command this component is actually doing. For example : `"AbstractMesh.checkCollisions = true;"`

It is based on the `target` property of the `React.Component` considered (CheckboxLine, SliderLine, ColorLine, etc...)
* `this.props.target` is the node considered (ex : `AbstractMesh`)
* `this.props.propertyName` is the property (ex : `checkCollisions`)
* `this.props.target[this.props.propertyName!]` is the value

In order to access the Class name of the target, `this.props.target.constructor.name` works in dev preview mode, but returns a single (random) letter such as "e" after the build. I suspect this is due to the mangling + minify at build;

That's why I replaced `this.props.target.constructor.name` by the `getInstanceType()` function, which finds a `instanceof` match over BABYLON classes.

Please feel free to propose a neater solution.

([Demo Video](https://global.discourse-cdn.com/business7/uploads/babylonjs/original/3X/3/8/3833bf84f734ef25c7e7503f4f1f490c5dab4357.mp4))
____
**Addind window.debugNode :**

Also, I'm putting the reference of the selected node into `window.debugNode`;
This is soooo usefull, already since it's built on my side, I'm using it multiple times per day !
* You select a mesh and type `let mesh = window.debugNode;`
* You select a material and type `let mat = window.debugNode;`
And then you can work in the console using `mesh` and `mat` ...

([Demo Video](https://global.discourse-cdn.com/business7/uploads/babylonjs/original/3X/0/8/08c73f8152af42976194c326211e9d8cea4d91f6.mp4))

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15050/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15050/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15050/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15050/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15050/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15050/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15050/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15050/merge#BCU1XR#0

**Review by deltakosh — APPROVED** [review]
It kicks ass!!! Love it

**Comment by Tricotou** [comment]
> Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s). To prevent this PR from going to the changelog marked it with the "skip changelog" label.

When I published the PR, I did not see options for labels. Now indeed, I see on the right panel `Labels : None yet` but I cannot find a way to edit or add some. Do I have the necessary rights to do so ?

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15050/merge/testResults/webgpuplaywright/index.html

**Comment by sebavan** [comment]
Only some last changes required about the format and this will be all good 
image

npm run format:fix should do it for you :-)

**Comment by sebavan** [comment]
Last one Linting :-)
image

**Comment by Tricotou** [comment]
* `import * as BABYLON from "core/index"; is not allowed` : :white_check_mark: Solved using new function `GetClassName` along with registered classes from the `core/Misc/typeStore` implementation
* `AbstractXXX` : :white_check_mark: Solved
* Missing some Classes : :white_check_mark: Solved by registering names for `Sound`, `MaterialPluginBase`, `BaseParticleSyste`, `ArcRotateCamera`, `FlyCamera`, `FollowCamera`, `ArcFollowCamera`, `FreeCamer`, `HemisphericLight`, `DirectionalLight`, `PointLight`, `SpotLight`
* Issue with copy buttons on particles (component `floatLine` which is used by component `sliderLine` was inducing a double copy button) : :white_check_mark: Solved by tweeking the `inspector/components/actionTabs/actionTabs.scss`, with a `display:none` inside the class `floatLine` when child of `sliderLine`

**Pull request merged**
