### PR TITLE
180 dome

### PR DESCRIPTION
**Pull request by RaananW**
Addressing #8897 

Cross Eye support added (switching between the eyes), and 180 dome offset was corrected.

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by deltakosh** [comment]
There are conflicts :)

**Comment by RaananW** [comment]
Wow, github conflict resolution made a mess. Let me try vscode.

**Comment by deltakosh** [comment]
Woot I have no idea what are the changes now :(

**Review by deltakosh — APPROVED** [review]

**Comment by RaananW** [comment]
I was just about to redo it, because it bothered me as well. Lesson learned, I won't resolve conflicts on github next time...

**Pull request merged**
