### PR TITLE
fixed scene.pointerUp bug

### PR DESCRIPTION
**Pull request by ssaket**
Addressing issue - http://www.html5gamedevs.com/topic/40469-pointerup-observable-bug/
test playground -> http://playground.babylonjs.com/#9LLJMJ

Since it's  related to pointer events, please guide me in case of any time complexity issue in my code :)

### CODE REVIEW

**Comment by aWeirdo** [comment]
Hi @ssaket 
A lot of odd file changes included, could you try to limit it to the bug-fix only?

**Comment by deltakosh** [comment]
Thanks a lot for pointing out this issue!
I found a smaller fix (that works this time :))
https://github.com/BabylonJS/Babylon.js/commit/b5f7039f12d3f06ec2e9d9ff06b60565f9715dab

**Comment by ssaket** [comment]
image
@deltakosh - I was thinking that all the observables should be get called first after scene.pointerDown() and then scene.pointerUp (screenshot attached). 
Do you think this will affect the sequencing (like someone might want to deal/run with the observables first and then pointerUp() ?

**Comment by deltakosh** [comment]
Well I so not want to change the current sequencing:)

**Comment by ssaket** [comment]
@deltakosh - sorry I forgot to explain this earlier, this is the current sequencing 

The one in my previous comment is generated my patch. 
Anyways your call ! Happy weekend :)

**Comment by ssaket** [comment]
image

**Comment by deltakosh** [comment]
Thanks for your support!!

**Pull request closed without merging**
