### PR TITLE
Test babylon pbrmaterial

### PR DESCRIPTION
**Pull request by Dok11**
Hi!
I made some test cases for PBRMaterial.
One strange point — the getAnimatables don't return all possilbe textures, such metallic reflectance, reflectance, micro surface and refraction texture. So I added a note to the method JSDoc, and comment to the test case.

### CODE REVIEW

**Comment by Popov72** [comment]
> One strange point — the getAnimatables don't return all possilbe textures, such metallic reflectance, reflectance, micro surface and refraction texture

Maybe because they are not animatables? However, I don't know what means to have animations for a texture.

Or we have simply forgotten to add those textures. What do you think @sebavan ?

**Comment by Dok11** [comment]
@Popov72 but all basic textures are animatable

```ts
// packages/dev/core/src/Materials/Textures/baseTexture.ts
export class BaseTexture extends ThinTexture implements IAnimatable {
```

**Review by sebavan — APPROVED** [review]

**Comment by sebavan** [comment]
I am working on something for @Popov72 comment :-) trying to merge getAnimatable and getActiveTextures code in some ways. Will PR soon-ish

**Comment by Dok11** [comment]
> I am working on something for @Popov72 comment :-) trying to merge getAnimatable and getActiveTextures code in some ways. Will PR soon-ish

@sebavan nice! And pay attention to what getAnimatable returns an IAnimatable interface, but in fact these are `BaseTerxture & IAnimatable`.

**Pull request merged**
