### PR TITLE
Use tabs instead of spaces

### PR DESCRIPTION
**Pull request by james-pre**
Spaces vs Tabs is a very common and sometimes passionate argument.

I think Babylon would benefit from using tab for a number of reasons:

1. Accessibility: Tabs are easier to use for many individuals with physical or neurological disabilies.
2. Size: Spaces take up 4 times as much space as a tab in Babylon's case (4 bytes for spaces and 1 byte for tabs in UTF-8)
3. Customizability: Developers working on or with Babylon can configure their editors to render tabs as 2, 4, 8 etc. spaces
4. Tabs are easier to use for new developers. When using spaces, some will actually press space 2/4/8 times instead of using the *tab* key
5. We use the *tab* key, not the *space* key to indent- doesn't it make more sense for the tab key to insert a tab instead of spaces? 

https://github.com/prettier/prettier/issues/7475 has a significant amount of discussion I spent hours going through.

Some concerns:

**How does `printWidth` affect formatting with different tab sizes?** (from the above prettier issue)

The rendered tab size in an editor will not affect how prettier formats code, it uses `tabSize` for the equivalent amount of characters a tab is "worth".

**How can the integrity of the formatting commit be verified?**

As a security conscious programmer, one thought I had is: if this were my project, how could I make sure the commit with formatting didn't include other changes?

You can verify the commit by:
1. `git checkout 8126bbd` (the commit prior to the formatting)
2. `npm run format:fix` (formatting)
3. `git diff 7714262` (diff the formatting commit and HEAD)

This will show that the commit is only the result of running `npm run format:fix` after changing `.prettierrc`.

**What about other contributions?**

For other PRs and commits, they will need to re-format before merging. 

Since this PR changes almost every file in the repository (even though it is only formatting), any and probably *every* change could cause a merge conflict. For this reason, I recommend we expedite merging this PR.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15360/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15360/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15360/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15360/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15360/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15360/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15360/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15360/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15360/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15360/merge/testResults/webgpuplaywright/index.html

**Comment by sebavan** [comment]
Sorry @james-pre, the ROI is not big enough considering we wont review manually and it does not impact runtime.

I love the accessibility concern and looking more into it ppl still use the tab key as you mentioned in point 4.

**Pull request closed without merging**
