### PR TITLE
Improve GS quality with XR Camera

### LINKED ISSUE #15109: Improve GaussianSplatting for VR
Potential improvement for rendering quality and Gaussian Splatting.
See  https://forum.babylonjs.com/t/gaussian-splats-rotate-incorrectly-in-vr/50256/41

Current quality:

image

potential improvement:

image

I believe it's a small fix related to viewport and focal computation. I could find a fix that worked with a VR rig locally but it doesn't work on real device (no idea why).

Check this as a starting point:

https://github.com/BabylonJS/Babylon.js/blob/bf55ce26227a4fb5285e817daeb8848095d996b5/packages/dev/core/src/Materials/GaussianSplatting/gaussianSplattingMaterial.ts#L219

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes #15109 

Extract needed value from projection matrix to compute focal shader uniform

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15193/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15193/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15193/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15193/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15193/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15193/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15193/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15193/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/15193/merge/testResults/webgl2playwright/index.html

**Review by RaananW — APPROVED** [review]
Tested on the quest, works great

**Pull request merged**
