### PR TITLE
Fix #14296

### LINKED ISSUE #14296: Vertex color mesh used for instantiate source not visible if density set to 0
I have a source mesh I am using for instantiate on vertices that is also merged with the output of the instance node. The vertex color of the source mesh is set outside the connection to the instance node and while the density of the instance node is a non-zero value, the vertex color of the source mesh is correct. If the density of the instance node is set to 0.0, the vertex color of the source mesh displays as white (default).

Repro: https://nge.babylonjs.com/#728CBC

Denisty set to non-zero value:

image

Density set to 0.0:

image

### PR DESCRIPTION
**Pull request by deltakosh**

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by deltakosh** [comment]
@RaananW as it seems the build has crashed

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14298/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14298/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14298/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14298/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14298/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14298/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14298/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14298/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for webgl1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14298/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14298/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14298/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14298/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14298/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14298/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14298/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14298/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14298/merge#BCU1XR#0

**Review by RaananW — APPROVED** [review]

**Pull request merged**
