### PR TITLE
Add back architecture specific nx packages to package-lock.json

### PR DESCRIPTION
**Pull request by ryantrem**
Currently in master, `npm install` fails because it can't resolve the optional architecture specific nx packages. This is because the architecture specific packages are missing from the package-lock.json. This change adds those back to package-lock.json to fix the `npm install` error that happens in a clean repo. This was done by regenerating the package-lock.json locally. This resulted in a lot of changes, but it's mostly tiny changes like the LICENSE property being removed for all packages in the lock file. This seems to be due to a difference in how the package-lock.json file gets generated locally vs. the package-lock.json update that happens in the build process (see below), but @RaananW said these small changes are expected and ok from his experience. Unfortunately this means you can't diff the file in GitHub.

This is an example of one of the architecture specific packages that was added back to the package-lock.json:
image

The reason these optional architecture specific packages are missing from the package-lock.json is due to a step in the automated release process where package versions in the package-lock.json are updated. This step regenerates the package-lock.json, but results in any packages not present in node_modules to be removed from the package-lock.json which is then checked back in. This means that if nothing else is done, this will break again next time a release is cut. Fortunately @RaananW already planned to remove part of the step that causes this problem and is no longer needed anyway. He's expecting to make that change on Monday, but this change is also needed and at least fixes master.

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14873/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14873/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14873/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14873/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14873/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14873/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14873/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14873/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14873/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)
Important - these might fail sporadically. This is an optional test.

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14873/merge/testResults/webgpuplaywright/index.html

**Review by RaananW — APPROVED** [review]

**Pull request merged**
