### PR TITLE
Fix sourcemaps compilation in es6 modules

### PR DESCRIPTION
**Pull request by RaananW**
There was an issue with our shader compilation when compiling to es6 and up.

The issue was that some files have \r\n and some have \n, and typescript doesn't deal with that very well (especially if a \r is left without a \n).

This should fix the issue (tested locally).

See https://forum.babylonjs.com/t/es6-sourcemaps-not-lining-up-since-5-27-1/43021

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14134/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14134/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14134/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14134/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14134/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14134/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14134/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14134/merge#BCU1XR#0

**Review by Popov72 — APPROVED** [review]

**Comment by RaananW** [comment]
note - this fails on linux (but works in window). looking into that right now

**Comment by RaananW** [comment]
Another note - I moved all blocks to \n instead of \r\n . This will save a few bytes but won't make any other difference

**Comment by RaananW** [comment]
@Popov72 just making sure you are fine with the new changes

**Review by Popov72 — APPROVED** [review]

**Comment by Popov72** [comment]
I think it's fine to replace the "\r\n" by "\n".

**Pull request merged**
