### PR TITLE
Adding two new parameters to teleportation

### PR DESCRIPTION
**Pull request by RaananW**
* Time to teleport start - if using the mainn component only, it is possible to delay the start of the teleportation ray, so a standard press won't automatically trigger it. 
* blockAllPickableMeshes - If enabled this will allow all pickable meshes in the scene to be teleportation blockers. This is off per default for performance reasons.

Partly from https://forum.babylonjs.com/t/teleportation-activates-when-pinching-a-non-floor-mesh-with-a-hand/48443

### CODE REVIEW

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14840/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14840/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14840/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14840/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14840/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14840/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14840/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14840/merge#BCU1XR#0

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14840/merge/testResults/webgl2playwright/index.html

**Comment by RaananW** [comment]
test playground:

https://playground.babylonjs.com/?snapshot=refs/pull/14840/merge#B8D5Z6#142

**Review by sebavan — APPROVED** [review]

**Comment by sevaseva** [comment]
`timeToTeleportStart` is very useful, I think. I say it needs a lot more explanation of what it does in a comment (maybe a better name, too, but nothing comes to mind just yet, it's late here..) in order for most people who are not already familiar with the intention here to understand. `timeToTeleport` (and many many many other places in BJS code, sadly, but that's another story) can also use more explanation to be clear to most people, I think.

With `blockAllPickableMeshes`, I like the intention, but it looks inflexible. why specifically "pickable"? what if I need a different criteria? e.g. all meshes or all visible meshes or all except some "transparent" meshes or whatever it may be...

What do you think about removing `blockAllPickableMeshes` before it's too late and replacing it with a predicate? so the user can specify any arbitrary condition they'd like. `pickBlockerMeshes` can be deprecated in favor of the new predicate, too.

**Comment by sevaseva** [comment]
jsDoc for the predicate option can quote an example code for a common use like "any mesh that is pickable, visible and enabled" or something like that

**Comment by RaananW** [comment]
> jsDoc for the predicate option can quote an example code for a common use like "any mesh that is pickable, visible and enabled" or something like that

This addresses your comments - https://github.com/BabylonJS/Babylon.js/pull/14850

**Comment by sevaseva** [comment]
> This addresses your comments - #14850

I love that one, thank you! Didn't test that one yet, but I will soon and let you know if something comes up.

**Comment by sevaseva** [comment]
One thing regarding `timeToTeleportStart` after _this_ PR that I noticed and forgot to mention in my earlier comment:

With `timeToTeleportStart: 1000` as in [the testing PG](https://playground.babylonjs.com/?snapshot=refs/pull/14840/merge#B8D5Z6#142), repeatedly quickly pinching a floor makes the teleportation target appearing and disappearing in funny ways, predictably.

Not sure how severe an issue this is, but here you go.

**Pull request merged**
