### PR TITLE
KHR_node_visibility

### PR DESCRIPTION
**Pull request by RaananW**
Adding the implementation of KHR_node_visibilityAs per specs in this PR - https://github.com/KhronosGroup/glTF/pull/2410

Vis test added to make sure we support the current specs.

### CODE REVIEW

**Review by deltakosh — APPROVED** [review]

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15754/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15754/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15754/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15754/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15754/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15754/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15754/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15754/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15754/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15754/merge/testResults/webgl2playwright/index.html

**Comment by ryantrem** [comment]
This new extension should be added to packages/dev/loaders/src/glTF/2.0/Extensions/dynamic.ts as well.

**Review by ryantrem — APPROVED** [review]

**Review by sebavan — APPROVED** [review]

**Pull request merged**
