### PR TITLE
SIMD fixes + asm.js

### PR DESCRIPTION
**Pull request by benaadams**
Issue with minifed

### CODE REVIEW

**Comment by benaadams** [comment]
Disabled multiplyToArraySIMD function as that is one causing issue atm

**Comment by RaananW** [comment]
If you want to revert the vector3 changes you will have to revert them all. You have create an infinite loop : `get x() { return this.x }` will constantly call the getter.

**Comment by benaadams** [comment]
Whoops, fixed

**Comment by deltakosh** [comment]
Regarding perf, we must keep the vector3 as is and instead provide a replacment class when SIMD is active. Accessing filed values through properties is kind of slow for an object like vector3 (which is used everywhere)

**Comment by nockawa** [comment]
a little jsfiddle to proove that we did consider it seriously: https://jsfiddle.net/v6nkbo6b/4/
prop access is 10 times slower...(it depends on the browser, etc, but it's really a big hit)

**Comment by benaadams** [comment]
but then you take the hit by using simd; direct on the Float32Array is petty bad in that jsfiddle, might be better to load directly into the SIMD types from the x,y,z - will look into it...

**Comment by deltakosh** [comment]
Agree. In this case we need a Vector3SIMD which will override the Vector3

**Comment by benaadams** [comment]
@deltakosh question was there a big diff between SIMD vs non-SIMD previously? Not seeing it - might be my gpu hitting limits early though

**Comment by deltakosh** [comment]
No it was definitely not obvious

**Comment by benaadams** [comment]
ah, k might be worth continuing then, SIMDing more things

**Comment by deltakosh** [comment]
yep but we need to stay away from updating pure js code by providing classes to override existing code

**Comment by benaadams** [comment]
Looking much better, still investingating

**Comment by benaadams** [comment]
I'm hitting other perf issues before the SIMD, so i'm going to knock those off along the way

**Comment by benaadams** [comment]
Sorry if this is going to be a noisy PR, just keeping track of the changes

Reduce Observable.notifyObservers allocations
image

**Comment by deltakosh** [comment]
No worry:) regarding observables: If creating them is a problem, we can think about adding a getter to create them on demand

**Comment by benaadams** [comment]
@deltakosh is `EventState` creation, resolved it in last commit https://github.com/BabylonJS/Babylon.js/pull/1180/commits/caa220a55ffb6d5124cb1b294c4c1f62de6f75a1

**Comment by deltakosh** [comment]
Gotcha

**Comment by benaadams** [comment]
Next big ones seem to be `MaterialDefines`

image

**Comment by benaadams** [comment]
define caching isn't working well on frame, and very much not cross frame

**Comment by deltakosh** [comment]
What do you mean by "on frame"?

**Comment by benaadams** [comment]
The simd demo has 50 meshes that all the defines are the same so 3 of the top 3 cpu methods shouldn't be dealing with defines as they are all the same in the same `requestAnimationFrame`; and the same between frames but there may be other objects mixing with that; but could be cached cross-mesh for example.

There is a lot of identical work going on

**Comment by deltakosh** [comment]
Agree. The defines should be cached and reuse as there is only one single material. Something is wrong here

**Comment by deltakosh** [comment]
This is because of the mirror :( It forces meshes to be drawn with a clipplane and then it invalidates the cached define

**Comment by deltakosh** [comment]
For this specific scene you can add "newOne.material.freeze();" to the addDancer function
This will force the material to remain the same between frame (There is no need for clipplane here as no object go through the mirror)

**Comment by deltakosh** [comment]
I updated the scene online with this small update

**Comment by benaadams** [comment]
@deltakosh not seeing this change; is it in Samples?

**Comment by deltakosh** [comment]
Only online so far: www.babylonjs.com/Demos/SIMD/

**Comment by benaadams** [comment]
Hmm different to src, e.g. I can't take the index.html code and apply it locally as material and freeze don't exist...

**Comment by deltakosh** [comment]
Not sure to follow you. Which code are you using?

**Comment by deltakosh** [comment]
https://github.com/BabylonJS/Samples/blob/master/Demos/SIMD/index.html

**Comment by benaadams** [comment]
My fault, had broken something elsewhere

**Comment by benaadams** [comment]
Moved the non-SIMD changes to #1185

**Comment by arunetm** [comment]
@benaadam, We are evaluating some new simdjs optimizations (type specialization for non-asm code) in Msft edge browser. It will be great if we can use the version of simd.js demo based on the changes you have in this PR. The plan is to use the demo on a test version of edge with the new simd optimizations enabled and we might to see more speedup when using the non-asm simd library. 

Is there any copy of the simdjs demo form babylonjs using your changes? 
We tried doing an asmjs version of the simd math library in Babylonjs, but creating and initializing an asmjs module every time when the library is used for computation turned out to be a major bottleneck. Are you able to see any speedup for either versions?

**Comment by benaadams** [comment]
@arunetm the main bottleneck I'm seeing with this simd asmjs version in the is in the copy step to and from the asmjs buffer - the simd portions of the functions themselves are very fast. However I was experiencing other bottlenecks with the non-asmjs versions; which I have now addressed and they have been merged to master.

The asm+simd did seem faster than the pure simd version; however with some of the changes it might be better now and obv if you are looking to improve the pure simdjs code its probably worth pursuing further. I'll remake a pure simdjs PR for you to look at.

**Pull request closed without merging**
