### PR TITLE
Fix #15788

### LINKED ISSUE #15788: HTMLMesh rendering issues
Hey, 

First off, the HTMLMesh extension is amazing and really simple to use. I've been battling two small, but annoying rendering issues with the library:

1) as other people, for example https://github.com/BabylonJS/Extensions/issues/304 have pointed out, when resizing the window, the html meshes do not resize correctly. I ended up using a different workaround to what's mentioned in the linked issue, I basically disabled the resize logic in the extension ( line: (window as Window).addEventListener("resize", boundOnResize);), and I apply my own resizing logic from outside, by calling this.htmlMeshRenderer.setSize(window.innerWidth, window.innerHeight) when the window is resized. The benefit over the solution in 304 is that there's no lag when resizing the window, the html mesh is sized correctly immediately on the next render.

Wouldn't it be helpful if we could provide an option to the HtmlMeshRenderer and allow updating the size from the outside, optionally?

2) there's a rounding error causing a white border around the meshes. 

image

My scene is very dark with a black background, so this becomes very pronounced. I think this might be a rounding issue somewhere during the scaling. I found two hacky ways to solve this if anyone wants to resolve the issue, one option is modifying this line in the html-mesh.ts createMask function:

from

protected createMask() {
        const vertexData = CreatePlaneVertexData({ width: 1, height: 1 }); // BJS 5
to

protected createMask() {
        const vertexData = CreatePlaneVertexData({ width: 0.99, height: 0.99}); // BJS 5

or, alternatively, to change the sizing in fit-strategy.ts:|

from
      sizingElement.style.width = `${width}px`;
      sizingElement.style.height = `${height}px`;

to
      sizingElement.style.width = `${width*1.01}px`;
      sizingElement.style.height = `${height*1.01}px`;

This hack basically crops the iframe a tiny bit so the white lines won't show from the mask. Obviously, this hack is only useful if you're fine with cropping a couple pixels of your website in the iframe. I'm wondering where the rounding issue is coming from, if anyone finds a better solution please let me know!

### LINKED ISSUE #15790: Increase the visibility of InputText._selectAllTexts() public, or provide an public alternative
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to select the content of an `InputText` control programmatically. There is `_selectAllText()`, but it's a protected method, so it's unsuitable for ordinary use cases.

**Describe the solution you'd like**
I want either the `_selectAllText()` method to be a public method or an alternative public API to be provided.

**Discussion**
You must provide a link to the forum post where the initial discussion happened:

https://forum.babylonjs.com/t/is-there-an-alternative-to-inputtext-selectalltext/54636

### LINKED ISSUE #15794: HtmlMeshRenderer issue
https://forum.babylonjs.com/t/htmlmeshrenderer-issue/52603

### PR DESCRIPTION
**Pull request by deltakosh**
Also fix #15794 and #15795

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15796/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15796/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15796/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15796/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15796/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15796/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15796/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15796/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15796/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15796/merge/testResults/webgl2playwright/index.html

**Review by sebavan — APPROVED** [review]

**Pull request merged**
