### PR TITLE
Computing good normals for fur material, as vNormalW is use only for …

### PR DESCRIPTION
**Pull request by julien-moreau**
…lighting computation

### CODE REVIEW

**Comment by julien-moreau** [comment]
Related to https://github.com/BabylonJS/Exporters/pull/96

**Comment by julien-moreau** [comment]
It looks like procedural textures and instances scenes make the tests failing
I thought it was only visual check

**Comment by deltakosh** [comment]
The build is crashing because you did not update the what's new ;)

**Comment by julien-moreau** [comment]
WIll know for the next time ^^

**Pull request merged**
