### PR TITLE
more perfect pixel perfection

### PR DESCRIPTION
**Pull request by RolandCsibrei**
Trying to fix this issue:
https://forum.babylonjs.com/t/sprites-render-pixels-from-cell-next-to-it/53630

### CODE REVIEW

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15610/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15610/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15610/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15610/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15610/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15610/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15610/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15610/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15610/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15610/merge/testResults/webgl2playwright/index.html

**Comment by Popov72** [comment]
My opinion is that what "fixes" the problem is the epsilon applied to the uv coordinates, not the fact we don't use instancing. It happens that in instanced mode, epsilon is not applied, which is why you have to revert to non-instanced mode, but it looks like a bug to me, because it means the output for sprites may be different depending on your computer/browser (if it supports instancing or not). So, I would fix this problem by applying the epsilon in instanced mode too.

It can't be done the same way than in the non-instanced mode (which is probably why it wasn't implemented), but you could do it roughly like this:
* add a uniform to the shader, to pass the epsilon value (feel free to use the names you want for the define/uniform!):
```glsl
#ifdef SPRITE_APPLY_EPSILON_CORRECTION
    uniform float epsilon;
#endif
```
* apply the epsilon:
```glsl
    ...
    vec2 offset = offsets.xy;
    #ifdef SPRITE_APPLY_EPSILON_CORRECTION
        if (offset.x == 0.) offset.x += epsilon;
        if (offset.x == 1.) offset.x -= epsilon;
        if (offset.y == 0.) offset.y += epsilon;
        if (offset.y == 1.) offset.y -= epsilon;
    #endif
    ...
```
* in the JS code, define `SPRITE_APPLY_EPSILON_CORRECTION` when in instanced mode, and pass the value of epsilon to the shader

I think that should do it.

**Comment by RolandCsibrei** [comment]
Created another PR using the solution from @Popov72

**Pull request closed without merging**
