### PR TITLE
fix BB Style anchor alignment

### LINKED ISSUE #15485: boundingBoxGizmo dragging is buggy since v7.21.0
**Repro**
- Bug repro on [playground](https://playground.babylonjs.com/#YIU90M#1204):
- Expected result: Gizmos should follow the dragged direction
- Current result: Gizmo drag axis are twisted (e.g. horizontal rotation gizmos are rotated by moving the mouse vertically)

Also, some of the gizmos have a wrong orientation, see the following screenshot:
image

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Business (10.0.22631 Build 22631)
 - Browser MS Edge 
 - Version 128.0.2739.42 (Official build) (64-bit)

**Additional Context**
The styling of gizmos has changed in https://github.com/BabylonJS/Babylon.js/releases/tag/7.21.0. See https://github.com/BabylonJS/Babylon.js/pull/15415 for reference.

### PR DESCRIPTION
**Pull request by CedricGuillemet**
fixes #15485 
Idk how I missed it :/

### CODE REVIEW

**Comment by bjsplat** [comment]
Please make sure to label your PR with "bug", "new feature" or "breaking change" label(s).
To prevent this PR from going to the changelog marked it with the "skip changelog" label.

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/15487/merge

Test environment: 
https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15487/merge/index.html

To test a playground add it to the URL, for example:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15487/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/15487/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/15487/merge
https://gui.babylonjs.com/?snapshot=refs/pull/15487/merge
https://nme.babylonjs.com/?snapshot=refs/pull/15487/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/15487/merge#BCU1XR#0

**Comment by bjsplat** [comment]
Visualization tests for WebGPU (Experimental)

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15487/merge/testResults/webgpuplaywright/index.html

**Comment by bjsplat** [comment]
WebGL2 visualization test reporter:

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15487/merge/testResults/webgl2playwright/index.html

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15487/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Review by sebavan — APPROVED** [review]

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15487/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15487/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by sebavan** [comment]
@CedricGuillemet looks like smthg might have change in the tests ?

**Comment by sebavan** [comment]
> @CedricGuillemet looks like smthg might have change in the tests ?

It has nothing to do with you, mostly an undeterministic test. @noname0310 could you have a look ? this is the latest tests that have been added for VAT + Volumetric Scatterring

**Comment by noname0310** [comment]
Let me check. Maybe there is a problem with async load and animation playback

**Comment by bjsplat** [comment]
Visualization tests for WebGL 1 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://snapshots-cvgtc2eugrd3cgfd.z01.azurefd.net/refs/pull/15487/merge/testResults/webgl1/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
