### PR TITLE
Add observable for collision finished events/trigger events

### PR DESCRIPTION
**Pull request by carolhmj**
Test PG: #Z8HTUN#613 (collision ended)
#M0C2X5 (triggers)

### CODE REVIEW

**Comment by bjsplat** [comment]
Snapshot stored with reference name:
refs/pull/14109/merge

Test environment: 
https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14109/merge/index.html

To test a playground add it to the URL, for example:

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14109/merge/index.html#WGZLGJ#4600

Links to test babylon tools with this snapshot:

https://playground.babylonjs.com/?snapshot=refs/pull/14109/merge
https://sandbox.babylonjs.com/?snapshot=refs/pull/14109/merge
https://gui.babylonjs.com/?snapshot=refs/pull/14109/merge
https://nme.babylonjs.com/?snapshot=refs/pull/14109/merge

To test the snapshot in the playground with a playground ID add it after the snapshot query string:

https://playground.babylonjs.com/?snapshot=refs/pull/14109/merge#BCU1XR#0

**Review by RaananW — COMMENTED** [review]
does it mean we need to wait with merging this?

**Comment by carolhmj** [comment]
> does it mean we need to wait with merging this?

Can be merged now 😄

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14109/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14109/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Comment by RaananW** [comment]
@CedricGuillemet - any issues merging this?

**Review by CedricGuillemet — APPROVED** [review]

**Comment by CedricGuillemet** [comment]
All good!

**Comment by bjsplat** [comment]
Visualization tests for webgl2 have failed. If some tests failed because the snapshots do not match, the report can be found at

https://babylonsnapshots.z22.web.core.windows.net/refs/pull/14109/merge/testResults/webgl2/index.html

If tests were successful afterwards, this report might not be available anymore.

**Pull request merged**
