### PR TITLE
Canvas2D: WorldSpaceCanvas supporting interaction

### PR DESCRIPTION
**Pull request by nockawa**

### CODE REVIEW

**Comment by NeoHoffa** [comment]
You are a machine!!! :)

**Comment by nockawa** [comment]
@NeoHoffa check this out: http://babylonjs-playground.com/#1BKDEO#9 (don't forget to CTRL-F5 your browser)

**Comment by deltakosh** [comment]
This guy is a robot :D

**Comment by NeoHoffa** [comment]
@nockawa this is so awesome! You are doing an amazing job for this community! On behalf of everyone, thank you for your devotion!

**Comment by NeoHoffa** [comment]
The animation within the Canvas2D gets pretty jittery when you rotate the camera. It doesn't seem to be a performance issue because the FPS remains at 60fps.

**Comment by NeoHoffa** [comment]
Interesting, it becomes jittery even on mouse move.

**Comment by deltakosh** [comment]
Yep..we are on it:) a bug in the picking mechanism of Canvas2D. Will have it fixed soon :)

**Pull request merged**
